### ISSUE TITLE
Change Masterkey on password update

### ISSUE THREAD

**Issue by mustaqimM** [rfjakob/gocryptfs#101]
Obviously the Encrypted key and Salt changes on an update of the password but is it possible to have the masterkey change with it?

**Comment by rfjakob** [comment]
No, the masterkey is immutable. The masterkey is the key that is actually
used to encrypt the files. Changing it would mean you have to re-encrypt
everything.

If you want that, create a new filesystem and copy the files over

**Comment by rfjakob** [comment]
Here is some guidance for how to do that efficiently: https://github.com/rfjakob/gocryptfs/wiki/Upgrading

**Comment by kovica** [comment]
Does this wiki mean that when I want to use version 1.2.2, when it is released, I will have to re-encrypt everything I have now stored in encrypted filesystem?

**Comment by rfjakob** [comment]
No, the on-disk-format has not changed since v0.9 and future versions will support it in the foreseeable future. Check this for details: https://github.com/rfjakob/gocryptfs/wiki/Compatibility

**Comment by kovica** [comment]
OK, thanks for the explanation.

**Comment by mustaqimM** [comment]
@rfjakob I see thanks

**Comment by mustaqimM** [comment]
@rfjakob I see thanks
