### ISSUE TITLE
Allow x-gvfs-hide mount option

### ISSUE THREAD

**Issue by silenc3r** [rfjakob/gocryptfs#103]
When tried to mount volume with ```x-gvfs-hide``` option gocryptfs throws an error:

    $ gocryptfs /my/encrypted/volume ~/my/mountpoint -o x-gvfs-hide
    [...]
    flag provided but not defined: -x-gvfs-hide

Or maybe there's another way to hide gocryptfs volume in Nautilus sidebar I don't know of?

**Comment by rfjakob** [comment]
I have tested this with ext4 and it accepts this mount option, even though I'm not sure how. The option does not show up in the `mount` output afterwards.

It does not work with EncFS:
```
$ encfs -o x-gvfs-hide $PWD/e1 $PWD/e2
EncFS Password: 
fuse: unknown option `x-gvfs-hide'
fuse failed.  Common problems:
 - fuse kernel module not installed (modprobe fuse)
 - invalid options -- see usage message
```

Anyway, reading https://github.com/GNOME/gvfs/blob/master/monitor/udisks2/what-is-shown.txt I found this:
> if any of component directories
> in its directory starts with a dot ("."), the device is not shown

Maybe good enough?

**Comment by silenc3r** [comment]
> Anyway, reading https://github.com/GNOME/gvfs/blob/master/monitor/udisks2/what-is-shown.txt I found this:
>> if any of component directories
in its directory starts with a dot ("."), the device is not shown

> Maybe good enough?

It would be good enough for me, but it doesn't seem to work. I have tried it before opening this issue.

**Comment by silenc3r** [comment]
I also tried writing udev rule but it doesn't work either.  
https://ask.fedoraproject.org/en/question/104585/how-do-i-hide-fuse-partition-from-nautilus-sidebar/

**Comment by rfjakob** [comment]
It looks like the mountpoint (or maybe any parent directory of it) must start with a dot. This works, it is not shown in the sidebar, gocryptfs mounted on `/home/jakob/tmp/.b`
```
$ df -Th | grep fuse.gocryptfs
/home/jakob/tmp/a              fuse.gocryptfs  200G  120G   71G  63% /home/jakob/tmp/.b
```

**Comment by rfjakob** [comment]
I guess this is ok to close?

**Comment by silenc3r** [comment]
OK, I get it now. The *mountpoint* directory and not encrypted volume has to start with a dot. I guess I have to use symlinks to get what I want, i.e.:

    gocryptfs /mnt/encrypted_volume ~/.vol1
    ln -s ~/.vol1 ~/vol1

Not ideal but still better than nothing. Thanks.
