### ISSUE TITLE
cannot use file literal (type *file) as type nodefs.File in return argument

### ISSUE THREAD

**Issue by jerogee** [rfjakob/gocryptfs#104]
Trying to compile the source code under Ubuntu 16.04.2 LTS with go1.6.2 linux/amd64 leads to:
`github.com/rfjakob/gocryptfs/internal/fusefrontend
internal/fusefrontend/file.go:75: cannot use file literal (type *file) as type nodefs.File in return argument:
	*file does not implement nodefs.File (missing Flock method)`

**Comment by rfjakob** [comment]
Oh, this is caused by a recent change in go-fuse. Until I fix it, please go
to the go-fuse folder and "git checkout" something before the flock changes.
