### ISSUE TITLE
Help installing gocryptfs

### ISSUE THREAD

**Issue by schnappijedi** [rfjakob/gocryptfs#106]
EncFS is great. Even with security issues it is only the file name length limit that causes to look elsewhere. CryFS security is excellent but it is slow. So want to give gocryptfs a try. 

Unpackaged gocryptfs_v1.2.1_debian8_amd64.tar.gz to /home/user/bin and /bin too. What else needs to happen to install gocryptfs?

Thanks. Keep up good work.

**Comment by rfjakob** [comment]
/bin works fine, even though I would recommend putting it in /usr/local/bin
.

Optionally, put the man page "gocryptfs.1" into /usr/local/share/man/man1 .

That's all!

**Comment by rfjakob** [comment]
I assume it works for you and I'm closing this?

**Comment by schnappijedi** [comment]
Sorry for delay in response and thanks for your quick response. Finally figured it out. Was running 
"cd /directory"
and then
"gocryptfs"

and gocryptfs (obviously) wasn't working.

Running
"/full-directory/gocryptfs"
or
"cd /directory"
and then
"./gocryptfs"

Solved issue. Thanks.
