### ISSUE TITLE
Full systemd integration

### ISSUE THREAD

**Issue by Nodens-** [rfjakob/gocryptfs#110]
Ability to load user configured encrypted filesystems easily with a systemd unit and handle all stdout/stderr in systemd journal per user.

Suggested systemd unit: gocryptfs@.service
https://pastebin.com/9wgpVprK

Suggested .gocryptfs userconfig format:
`cipherdir1    mountpoint1    option1 option2 option3`
`cipherdir2    mountpoint2    option1`
`cipherdir3    mountpoint3`

gocryptfs would read the file and mount all listed filesystems with their options.
For boot automounts of course password would have to passed in the options.
"systemctl enable gocryptfs@user" enables all filesystems configured by the user.
Per user logging facilities in journal "journalctl -u gocryptfs@user"
Allows automounting by users without touching /etc/fstab or needing elevated permissions in general.

Ability to easily modify or copy and edit the system unit to create custom configurations, systemd after/before controlled mounts etc.

**Comment by rfjakob** [comment]
Hmm, hardcoding the password is pretty much a no-go. Is there a way that gocryptfs can get the password from the user?

**Comment by Nodens-** [comment]
I didn't suggest hardcoding it. If someone wants to init filesystems on boot they would have to do it via supplying it to a file with 700 permissions and passing it to the options of .gocryptfs with -passfile etc for each filesystem in the list. Same way you do it currently when mounting via /etc/fstab etc..

For nonboot operation user will be asked upon "systemctl start gogryptfs@user".

There are ways to get passwords from other secure containers (eg gnone keyring, kde wallet etc) but they're so distro and configuration specific that are not worth to support/implement in my opinion. Perhaps if you have nothing else to work on :)

But the ability to read a userconfig file (which is what needs to be implemented for this enhancement) would allow to package a systemd unit file and simplify setup and logging per user to a great extent.

**Comment by rfjakob** [comment]
I don't understand yet how gocryptfs could prompt for the password. As far as I know, systemd redirects stdout and stderr to the journal. I'm not sure about stdin, but I would be surprised if it was not also redirected.

**Comment by Nodens-** [comment]
There would be no point in redirecting stdin to the journal which provides no input heh. The default for stdin is redirection to /dev/null but "StandardInput" directive can be used in the systemd unit to control stdin.

**Comment by rfjakob** [comment]
Ok. What should I set "StandardInput" to so gocryptfs prompts for the password?

**Comment by Nodens-** [comment]
tty with TTYPath probably set to /dev/tty so it's sent to current terminal instead of /dev/console, which is the default.
Also setting TTYReset to yes is probably a good idea.

See here for more information: http://man7.org/linux/man-pages/man5/systemd.exec.5.html

tty-force may be required instead. This needs testing on how it behaves on a normal tty and under ssh etc

**Comment by rfjakob** [comment]
Oh, maybe that's the solution: [systemd-ask-password](https://www.freedesktop.org/software/systemd/man/systemd-ask-password.html)

Regarding the userconfig, I think this should be done in an external wrapper. Or maybe, even simpler, by having multiple copies of the systemd unit file. I won't implement it myself, but I will accept a script and/or a systemd unit file for inclusion in the `contrib` folder.

**Comment by Nodens-** [comment]
I finally found time to move the mounting of my gocryptfs filesystems to systemd. So if you want to add it to contrib, here it is: https://pastebin.com/K6XGkJ7Q
With this setup you need one unit per mount. I have tested this and it works perfectly with the systemd-ask-password solution under any type of terminal. The solution I originally suggested did not work for some reason (mainly TTYPath=/dev/tty did not work to redirect to active tty as it was supposed to..possibly Fedora or systemd issue but it wasn't working).

**Comment by alexanderadam** [comment]
@Nodens- are you still using this solution?

I'm using it with an `ask-password`-script:

```bash
#!/bin/bash

if [ -n "$1" ]; then
  echo "$1"
elif [[ -n "${GOCRYPTFS_PASSWORD}" ]]; then
  echo "${GOCRYPTFS_PASSWORD}"
else
  {# https://github.com/rfjakob/gocryptfs/issues/110#issuecomment-323565459 #}
  systemd-ask-password "GoCryptFS:"
fi
```

And when I try to restart the service I'm getting an error:

```log
gocryptfs[19285]: Reading password from extpass program "/home/user/.local/bin/gocryptfs-extpass.sh", arguments: []
gocryptfs[19291]: Failed to query password: Permission denied
gocryptfs[19285]: extpass program returned an error: exit status 1
systemd[8198]: gocryptfs.service: Control process exited, code=exited, status=9/n/a
```

**Comment by Nodens-** [comment]
@alexanderadam Unfortunately I no longer use gocryptfs as for my use case (encryption on remote mounted fs via rclone) it caused rate limiting due to reading the diriv file for every file read so on directories with thousands of files it scaled badly. I opted for rclone's built-in encryption scheme instead.
The permission error you're getting though sounds like a selinux denial. Check audit log.
