### ISSUE TITLE
add an option that prints configuration options

### ISSUE THREAD

**Issue by mhogomchungu** [rfjakob/gocryptfs#111]
The command should be able to do what "encfsctl /path/to/volume" does.

I would like to display this info to users of SiriKali through "click opened gocryptfs volume in the main UI->properties".

**Comment by rfjakob** [comment]
Hmm, so this is what we get from encfsctl:
```
$ encfsctl a
Version 6 configuration; created by EncFS 1.9.1 (revision 20100713)
Filesystem cipher: "ssl/aes", version 3:0:0 (using 3:0:2)
Filename encoding: "nameio/block", version 4:0:0 (using 4:0:2)
Key Size: 192 bits
Using PBKDF2, with 274411 iterations
Salt Size: 160 bits
Block Size: 1024 bytes
Each file contains 8 byte header with unique IV data.
Filenames encoded using IV chaining mode.
File holes passed through to ciphertext.
```
And this is gocryptfs.conf:
```
$ cat g/gocryptfs.conf 
{
	"Creator": "gocryptfs v1.3-37-gce4aaf1",
	"EncryptedKey": "TlRJeBN6jvuYj6T5rBfJGehxABZwyrABMdJsD/uxE/X/gDva48uFbcOhqEKIMn3NkBAoUkjF9SbMmmp5yCW2qQ==",
	"ScryptObject": {
		"Salt": "TiJEBl4kMAOidBjcYcVX1fJRF1jpkLdI3h430KRhVd4=",
		"N": 65536,
		"R": 8,
		"P": 1,
		"KeyLen": 32
	},
	"Version": 2,
	"FeatureFlags": [
		"GCMIV128",
		"HKDF",
		"DirIV",
		"EMENames",
		"LongNames",
		"Raw64"
	]
}
```
I think that's pretty good already, do you think there is some merit to adding another pretty-print layer?

**Comment by mhogomchungu** [comment]
In SiriKali just taking those outputs yields the following

![screenshot_20170526_105710](https://cloud.githubusercontent.com/assets/3496115/26486097/6a09b2fc-4202-11e7-9883-140267a92bff.png)

![screenshot_20170526_105734](https://cloud.githubusercontent.com/assets/3496115/26486106/72bd0214-4202-11e7-8242-190a0221d5cb.png)

The gocryptfs config file looks good to look at but its not formatted in a way that can be displayed "as is" by others because of those empty spaces at the beginning of every line.

Some informations are not useful like encrypted key and salt.

Some information lack context like "Version": 2",what is at version 2? The file system?

A "good" output looks like below:

```
[mtz@ink ~]$ gocrypfs info /foo/bar
File System Version: 2
Created By: gocryptfs v1.3-37-gce4aaf1
Feature Flags: "GCMIV128","HKDF","DirIV","EMENames","LongNames","Raw64"
ScryptProperties: "N": 65536,"R": 8,"P": 1,"KeyLen": 32
```

**Comment by rfjakob** [comment]
Maybe left-align the text?

Version 2 is the format of the config file.

**Comment by mhogomchungu** [comment]
An image with left aligned text is below:

![screenshot_20170528_174010](https://cloud.githubusercontent.com/assets/3496115/26529663/e0ef2502-43cc-11e7-9bc4-afd67a6f0216.png)

**Comment by rfjakob** [comment]
Almost usable. Disable word wrap, if possible?

**Comment by mhogomchungu** [comment]
Taking "gocryptfs.conf" file and working on it in one form or another within SiriKali means i have some sort of an idea of its structure and if am to assume of its structure then:

1. I am better off parsing it with a json parser and take only "useful" options and put them it in a UI format that looks best in the GUI.
2. Risk SiriKali breaking everytime anything changes in the config file.

The second reason is why i would like the parsing to be in gocryptfs so that:

1. The output is automatically "properly" formatted(convenient but not very important).
2. The output is independent of the structure of the config file(good because it leads to stable API).

I am supporting too many back ends and stability over a prolonged periods of time is the most important thing i care about.

If the above reasoning is not convincing then please close this as "wont fix".

**Comment by rfjakob** [comment]
Added `-info`. Output looks like this, I tried to stay close to the config:
```
Creator:      gocryptfs v1.3-46-g9a217ce-dirty
FeatureFlags: GCMIV128 HKDF DirIV EMENames LongNames Raw64
EncryptedKey: 64B
ScryptObject: Salt=32B N=65536 R=8 P=1 KeyLen=32
```
What convinced me in the end is that this is also useful when people want to report what configuration they are using, because it strips out the sensitive data.

**Comment by mhogomchungu** [comment]
Now it looks much better 

![screenshot_20170531_133629](https://cloud.githubusercontent.com/assets/3496115/26628613/6e19f628-4607-11e7-861c-a040d9c88af3.png)
