### ISSUE TITLE
ReadDirIVAt: wanted 16 bytes, got 0. Returning EINVAL. OpenDir: invalid argument

### ISSUE THREAD

**Issue by Nodens-** [rfjakob/gocryptfs#112]
Using SyncBack to copy files to samba share gocryptfs mount.
SyncBack error log:
https://pastebin.com/QvGu9i0S

gocryptfs log:
https://pastebin.com/CVDus7hT

Maybe "@" related?

**Comment by Nodens-** [comment]
Also getting these sporadically:

> May 25 13:38:12 wintermute gocryptfs[26962]: go-fuse: can't convert error type: ParseHeader: invalid version: got 0, want 2

**Comment by rfjakob** [comment]
The filesystem stack is

Ext4 | gocryptfs | samba | windows

right?

The diriv error means the gocryptfs.diriv file is empty. The parseheader error means the file is filled with zeros.

**Comment by Nodens-** [comment]
It's ext4 | google-drive-ocamlfuse | gocryptfs | samba | ntfs/windows
By the description of the errors this sounds more like google-drive-ocamlfuse | gocryptfs issue.
I'm running the backup operation again monitoring /var/log/messages via most in tail mode and I'm seeing the parseheader entries regularly and I just saw a:

> May 25 14:27:40 wintermute gocryptfs[26962]: checkAndPadHole: Fstat failed: stat /Drive/.remote/Archive/WZVOmT_oruoOlABLFe9U6g/-zln5cEmoUySV-_uHFRBrw/26CnEpwyhEwBDUfpExuxXQ: no such file or directory

It looks like there's intermittent breakage in accessing the remote cipherdir mount, correct?

**Comment by rfjakob** [comment]
Yes, gocryptfs has problems accessing the backing files in the cipherdir. google-drive-ocamlfuse is throwing errors or returning all-zero data. This one is pretty evil:

    checkAndPadHole: Fstat failed

This means that gocryptfs has opened a file in the cipherdir, obtained a file descriptor, but received a "file not found" error when trying to access it.

Fallocate should not be a problem, gocryptfs disables it the first time it gets an "operation not supported" error.

**Comment by rfjakob** [comment]
This looks similar to https://github.com/rfjakob/gocryptfs/issues/59 . Can you try this on the google drive mount?

    echo 12345678 > file && echo "first read:" && cat file && sleep 1 && echo "second read:" && cat file

**Comment by Nodens-** [comment]
Both your test case and the dd/diff one from #59 pass.
Something else is going on.. I have been testing for the past few hours while using google-drive-ocamlfuse in debug mode. Log output looks absolutely clean I would paste it on pastebin but it's 18mb.
Here it is zipped:https://drive.google.com/file/d/0B878Fd4BOWLnOGJIUFNDc215cGs/view?usp=sharing

Yet I've managed to notice a couple of other things:
a) The parseheader error is logged twice exactly when syncback finishes copying a file. Also syncback things it has lost network connection and tries to reestablish after each file which immediately succeds.
b) Large files end up either being either 0 bytes or corrupted. Smallest tested file showing this is about 60mb. All files <=5mb were written correctly.
c) This was logged in stderr, outside gdfuse.log
> Thread 11838 killed on uncaught exception Failure("Error: Invalid request.  There were 32768000 byte(s) in the request body.  There should have been 81785384 byte(s) (starting at offset 0 and ending at offset 81785383) according to the Content-Range header. (HTTP response code: 400)")

This was not visible anywhere before (gdfuse with -debug stays in foreground so now I could see it) and matches aprox. the size of the test file that resulted in 0 byte size (77.3 MB (81,151,350 bytes))
d) This does not happen at all when I copy the same file with cp via the shell. On this case the gocryptfs to gdfuse pipe works as expected.

At this point I'm starting to believe that it's not a google-drive-ocamlfuse issue but maybe samba to gocryptfs instead. I'm about to test two things:
1) Disable multithreading in google-drive-ocamlfuse
2) Disable samba aio features.

**Comment by Nodens-** [comment]
After extensive testing I finally understood exactly what is going on and I see no bad behavior out of gocryptfs.
This has to do with 2 things:
a) How caching is done in google-drive-ocamlfuse when asynchronous uploads are enabled.
Namely when async is on, subsequent reads of files that have not been written remotely yet (currently in cache) fail. Until upload is done a 0byte file is being read. Ideally when reading files that are currently only in cache (RAM or disk), reading should be pointing in cache instead of reading a stub. This behavior causes any sort of "file written" verification to fail and gocryptfs to throw parseheader errors.
Turning off async uploads, slows down the filesystem but makes write operations from the shell complete properly regardless of file size/bandwidth/network load.
 
b) Caching somewhere in the SMB pipeline that I have yet not found how to disable or even detect if it is Windows side or smbd side. Even with async uploads off, transfers from Windows seem to be cached to some extent. Causing the same behavior for a few seconds at the end of each file transfer.
oplocks = no
csc policy = disable
and disabling samba aio features do not seem to help. This is seems to indicate it's coming from the Windows side, possibly plain windows file cache..

I'm closing this and I'll take it to google-drive-ocamlfuse.

**Comment by rfjakob** [comment]
Great investigation!

I think neither the ParseHeader nor the ReadDirIVAt errors can be caused by caching on top of gocryptfs (i.e. Samba or Windows). The thing is, these are internal data structures that are invisible on the mount point. Unless there is a bug in gocryptfs (which is certainly possible, but I have not seen something like that in my testing) there is no way to corrupt the diriv files or the file header from the mountpoint side.

**Comment by Nodens-** [comment]
Let me explain the on top scenario (I have not seen the ReadDirIVAt error again in all my tests with latest google-drive-ocamlfuse beta).
The moment syncback finishes the write op, the file seen in the plaindir is still a 0byte stub as can be verified with ls -l in the shell. This happens due to on-top cache, Windows thinks the write op is finished but the actual data have not been written entirely to the plaindir, they're still being written from cache. At this point syncback is trying a read operation which results in two parseheader errors in log because simply gocryptfs can not find a header on a 0byte file (which is absolutely normal).

**Comment by Nodens-** [comment]
I just solved the on-top cache issue as well. It's not from samba or Windows in itself. It's from Syncback. It somehow caches the transfer directly or indirectly. Switched to GoodSync and I'm running the operation for half an hour now with no errors reported from gocryptfs. Verification shows that the moment it reports the file written it's actually seen with proper size in plaindir as well.

The entire thing is very slow due to asynchronous uploads being off but it works. If google-drive-ocaml fixes the caching behavior on asynchronous mode it should be fast as well.

**Comment by rfjakob** [comment]
There must be something else going on. Empty files are valid in gocryptfs (they represent an empty plaintext file).

The ParseHeader error you get means:

1) We have read 18 bytes from the file (the file was **not** empty)
2) The first two of these 18 bytes are `0x00 0x00` instead of `0x00 0x02`

**Comment by Nodens-** [comment]
I think this just means that although plaindir shows the file as 0 bytes until the upload is finished, gocryptfs is actually able to read something from the cipherdir. I will report this on google-drive-ocamlfuse in a bit and perhaps the developer can shed some light into what is going on with the caching mechanism exactly.
It is evident though that the gocryptfs errors happen when read ops are done before a write op fully uploads the file to google drive. In all cases of the errors the file is still in transit and 0 bytes is seen in plaindir at the moment of the error. In the cases where the file has managed to finish uploading before it is being read, no error is logged.
