### ISSUE TITLE
pkg doesnt build on centos6

### ISSUE THREAD

**Issue by silv3rr** [rfjakob/gocryptfs#113]
Because CentOS 6 (and older) don't have /etc/os-release so package.bash can't get version info.
Fix in diff below also for rhel and fedora:

```diff
diff --git a/package.bash b/package.bash
index d3b95fd..e629f03 100755
--- a/package.bash
+++ b/package.bash
@@ -4,7 +4,11 @@ set -eu
 cd $(dirname "$0")
 
 source build.bash # Builds binary and sets GITVERSION (example: v0.7-15-gf01f599)
-source /etc/os-release # Sets ID (example: fedora) and VERSION_ID (example: 23)
+source /etc/os-release 2>/dev/null || { # Sets ID (example: fedora) and VERSION_ID (example: 23)
+  ID=$( cat /etc/redhat-release | awk -F release '{ sub(/Red Hat Enterprise Linux/,"rhel"); sub(/Core|Linux/,""); sub(/Server|Workstation|Client|Computenode/,""); sub(/ /,""); print tolower($1) }' ) # For RHEL5, 6 etc
+  VERSION_ID=$( cat /etc/redhat-release | awk -F release '{ printf "%d", $2 }' )
+}
```

**Comment by rfjakob** [comment]
Thanks for the report. I pushed a somewhat simpler version in https://github.com/rfjakob/gocryptfs/commit/c36a55e98599c96f228eb7ea09c1c71a5e114ee5 , do you think that's good enough? My awk powers are not very strong ^_^

**Comment by silv3rr** [comment]
It works.. define good enough ;) Tar is now named:
`gocryptfs_v1.3-34-g9a3f935_CentOS_release_6.9_(Final)_amd64.tar.gz`

**Comment by rfjakob** [comment]
Those "( )" braces suck because the have to be escaped on the shell. How about this https://github.com/rfjakob/gocryptfs/commit/4d2cc551cf6fa71e425fad8f397e96d69f016a6b ?

**Comment by silv3rr** [comment]
Yeah thats better 👍
