### ISSUE TITLE
binaries for Debian 9 stretch

### ISSUE THREAD

**Issue by macmeck** [rfjakob/gocryptfs#115]
Hi, 
since Debian 9 is scheduled for mid June, are there any plans for "official" binaries? Building from source seems to work out fine without issues. Central builds would be great!

**Comment by rfjakob** [comment]
I'll release gocryptfs v1.4 this or next week, and I will switch to
providing a single static binary. This should run equally well on all Linux
distributions.

The static binary does not have openssl support, but you can always compile
from source if you need it. Hint: "openssl -speed" tells you if you do.

**Comment by rfjakob** [comment]
I have released gocryptfs v1.4: https://github.com/rfjakob/gocryptfs/releases
Let me know if any problem on Debian 9.

PS: I meant `gocryptfs -speed` in the post above, not `openssl -speed`
