### ISSUE TITLE
EACCES during ElasticSearch snapshot

### ISSUE THREAD

**Issue by charles-dyfis-net** [rfjakob/gocryptfs#117]
Using gocryptfs as an ElasticSearch snapshot store appears to be unreliable due to EACCES errors being sporadically returned when attempting to open recently-created files to `fsync()` them, per [`org.apache.lucene.util.IOUtils:419`](https://github.com/apache/lucene-solr/blob/releases/lucene-solr/6.2.0/lucene/core/src/java/org/apache/lucene/util/IOUtils.java#L419). This appears to be racy behavior -- backing up a small database with a total of 50 shards, 3-6 may fail.

```
141988 22:17:22.999448866 17 <NA> (52003) < open fd=567(<f>/mnt/crypt/elasticsearch/snapshots/indices/3vDzC48rSvqaHzAnzIxOJA/1/__m
) name=/mnt/crypt/elasticsearch/snapshots/indices/3vDzC48rSvqaHzAnzIxOJA/1/__m flags=38(O_EXCL|O_CREAT|O_WRONLY) mode=0
142035 22:17:22.999956392 17 java (28275) < open fd=-13(EACCES) name=/mnt/crypt/elasticsearch/snapshots/indices/3vDzC48rSvqaHzAnzI
xOJA/4/__f flags=2(O_WRONLY) mode=0
```

TODOs (re: completeness of this ticket):
- [x] Determine whether this happens with a local backing store (as opposed to NFS)
- [ ] Attempt to build a reproducer for the pertinent access pattern

**Comment by rfjakob** [comment]
Nothing from gocryptfs in syslog, I guess? When I post a binary with extra logging for EACCESS, could you retry the test?

**Comment by charles-dyfis-net** [comment]
Nothing particularly enlightening from stdout in debug mode, even. Happy to retest with whatever instrumentation or changes you consider appropriate.

**Comment by charles-dyfis-net** [comment]
Followup:
- Issue *does not* happen when running an ES snapshot direct to the same underlying NFS store where the problem is observed with gocryptfs in front.
- Issue *does* happen when running an ES snapshot to a gocryptfs store backed by a local ext4 filesystem, rather than NFS.

**Comment by charles-dyfis-net** [comment]
I tried to reproduce this against a current build with tracing support, and found that I couldn't. :)

Cannot be reproduced against:
gocryptfs v1.3-62-gd2be22a without_openssl; go-fuse 5404bf0; 2017-06-08 go1.8.3

Reliably reproduces against:
gocryptfs v1.3-51-gcf1ded5; go-fuse 5404bf0; 2017-05-31 go1.8.1

**Comment by rfjakob** [comment]
I looked at what happened between those two versions. Not much, really, so I'm not sure how this disappeared. I see that one version is "without_openssl" and the other is not, maybe this is the significant difference?

**Comment by charles-dyfis-net** [comment]
Strike "can't be reproduced", replace "can't be *reliably* reproduced". It still happens, but with much lower frequency -- running a new snapshot every 5 minutes, I've seen 6 failures out of 218 snapshots.

**Comment by charles-dyfis-net** [comment]
Turning on `-fusedebug`, I think I found the problem here -- it looks like we have a codepath where `-force_owner` isn't taking effect, as the logs indicate that GETATTR is returning the UID of the user running gocryptfs, rather than the user to whom the filesystem is exposed. I'm unclear as to why this is racy (or otherwise not reproducing 100% of the time), but this is probably enough of a clue as to be able to track this one down.

**Comment by rfjakob** [comment]
Looks like it's file.GetAttr: https://github.com/rfjakob/gocryptfs/blob/master/internal/fusefrontend/file.go#L418

**Comment by rfjakob** [comment]
(if go-fuse finds an open FD to the file, it will prefer it over doing get GetAttr by path. That means when the GetAttr lands before the close has completed this path is taken)
