### ISSUE TITLE
Consider PKGBUILD w/ pkgver that includes exact build hash

### ISSUE THREAD

**Issue by charles-dyfis-net** [rfjakob/gocryptfs#119]
Right now, Arch builds of gocryptfs-git have numbers that specify the date of the most recent commit, but nothing more specific.

I'd like to suggest the following as a replacement, which will generate names akin to `1.3.r63.gca998fe`.

```
pkgver() {
  cd "${pkgname%-git}"
  git describe --long --tags | sed -e 's/\([^-]*-g\)/r\1/;s/-/./g' -e 's/^v//'
}
```

**Comment by rfjakob** [comment]
Uhmm, was this ticket supposed to go somewhere else? Or are you suggesting to add pkgver to build.bash ?

**Comment by charles-dyfis-net** [comment]
I was assuming that you also maintain the AUR PKGBUILD for gocryptfs (even though it's out-of-repo). If that's not accurate, my apologies.

**Comment by rfjakob** [comment]
Ah I see, no, I'm a Fedora user. But I know the maintainer. @petres , maybe you want to join the discussion here?

**Comment by petres** [comment]
I am maintaining the [gocryptfs](https://aur.archlinux.org/packages/gocryptfs/) package. The [gocryptfs-git](https://aur.archlinux.org/packages/gocryptfs-git/) package is maintained by atweiden. I would suggest to simply comment on the AUR package page.

**Comment by rfjakob** [comment]
Thanks @petres for clearing this up. I guess this ticket is not useful for talking to https://aur.archlinux.org/packages/gocryptfs-git/ , closing.
