### ISSUE TITLE
Include go-fuse to source

### ISSUE THREAD

**Issue by misery** [rfjakob/gocryptfs#120]
I like to add a package to AlpineLinux of gocryptfs. (https://github.com/alpinelinux/aports/pull/1533)

Since go-fuse is used as a small wrapper. Is it possible to add go-fuse as a copy to the gocryptfs sources? So if go-fuse is not provided on system the included go-fuse will be used. This makes it easier to provide a gocryptfs package.

A lot of software uses the "system or included"-provided approach. See CMake, Qt, Deluge or something like that.

**Comment by charles-dyfis-net** [comment]
Is there a reason you're hesitant to do a "go get" during the build process?

**Comment by misery** [comment]
The reviewer of AlpineLinux says: "it bypasses abuild's source and checksum mechanism."

Seems there is no reproducible state of that dependency.

**Comment by misery** [comment]
by the way... I already try to package go-fuse (https://github.com/hanwen/go-fuse/issues/161). But it is still broken here for me.

**Comment by charles-dyfis-net** [comment]
So, what I'd personally suggest at that point (not speaking for gocryptfs, but speaking as someone who's done a lot of packaging -- building packages was literally my day job for years) is for your package to specify a known commitish of go-fuse and pull that down directly during the gocryptfs build. You can absolutely pull a tarball down from github by commitish, and it'll have a consistent checksum across multiple invocations.

**Comment by charles-dyfis-net** [comment]
My concern with the ticket exactly as requested, by the way, is that the accepted Go way of doing vendoring *isn't* "system-or-included" -- instead, if you have an included version it overrides anything else in the GOPATH. So we'd either be doing something that isn't standard practice / common convention for golang, or we'd *always* be overriding the dependency version.

**Comment by rfjakob** [comment]
I'd like to avoid copying the go-fuse source code into gocryptfs. It's a lot of code, and what go-fuse does is actually quite complex: it handles the inode-to-path translation between the Linux kernel and gocryptfs.

But I see the problem with go-fuse not providing a release, I have also commented at the ticket there and I hope the maintainer will tag a release. Till then I would suggest you to call it "v0-2017-XX-YY".

**Comment by misery** [comment]
Yeah, I like the go-fuse package way, too. Duplicating code is never a good way. Just a try to spread gocryptfs to distributions. Closing this.... :-)
