### ISSUE TITLE
Running gocryptfs on 32-bit system

### ISSUE THREAD

**Issue by schnappijedi** [rfjakob/gocryptfs#122]
Hi there,

Am having trouble running gocryptfs on a 32-bit system. Getting "cannot execute binary file: Exec format error." Using the download under releases called "gocryptfs_v1.4_linux-static_amd64.tar.gz." Since it says "amd64" am not really surprised. Anything can do to make it work?

**Comment by rfjakob** [comment]
You should compile locally - it's easy!

https://github.com/rfjakob/gocryptfs/blob/master/README.md#compile

**Comment by schnappijedi** [comment]
Okay thanks. Have never compiled a program manually but will give it a try.

**Comment by schnappijedi** [comment]
Just compiled this. First time compiled a program manually/ locally. Truly was easy!
