### ISSUE TITLE
load_osxfuse should be run before attempting mount on OSX

### ISSUE THREAD

**Issue by erlandh** [rfjakob/gocryptfs#124]
I've just installed gocryptfs on mac os for the first time. Everything went more or less fine (once I worked out I should `build-without-openssl`) up to the point of mounting the encrypted store I had created. I'm getting the error:

`fuse.NewServer failed: no FUSE devices found`

This looks like [the issue **bailey27** discovered](https://github.com/rfjakob/gocryptfs/issues/15#issuecomment-264253024) in December on the giant generic OSX support ticket, where gocryptfs isn't running **load_osxfuse** before go-fuse tries to open a fuse device file.

I confirmed this by running `/Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse` and then the standard `gocryptfs cipher plain` command worked to mount the encrypted store.

Can we get @bailey27's code patched in for the next release if it works?

**Comment by rfjakob** [comment]
Yeah that's pretty hostile to the user. As an immediate remedy I have added a hint that you need to run load_osxfuse (commit 849ec1008).

The code to call load_osxfuse should probably go here, though - it even has a TODO comment already: https://github.com/hanwen/go-fuse/blob/master/fuse/mount_darwin.go#L23

If I create a patch for this for go-fuse, could you test it? I don't have a Mac to test, unfortunately.

**Comment by erlandh** [comment]
> If I create a patch for this for go-fuse, could you test it? I don't have a Mac to test, unfortunately.

I'd be very happy to test it, but I'm not experienced at patching, so if you can give instructions I'll follow them & report back.

**Comment by pmalhaire** [comment]
I had this bug so :up:

I can fix it in go fuse if as many here I find time for it.

**Comment by alexanderharm** [comment]
I created a pull request for this: https://github.com/hanwen/go-fuse/pull/197 and it works on my machine (macOS Sierra).
All credit goes to @bailey27.

**Comment by alexanderharm** [comment]
@rfjakob: hanwen merged PR https://github.com/hanwen/go-fuse/pull/197. So the upstream issue is fixed. If you could incorporate the change an make a new release I can submit to Homebrew.

**Comment by rfjakob** [comment]
Will do! Hopefully this or next week.

**Comment by rfjakob** [comment]
I have just released v1.4.3: https://github.com/rfjakob/gocryptfs/releases/tag/v1.4.3

Cheers

**Comment by alexanderharm** [comment]
I tested it on my computer and it works flawlessly. Thanks for your good work and I look forward to using your software on a regurlar basis.
I just submitted a PR to https://github.com/Homebrew/homebrew-core/pull/23135.
Is there a release mailing list I can subscribe to in order to keep maintaining this?

**Comment by rfjakob** [comment]
Edit: The first link was supposed to go to https://github.com/isaacs/github/issues/410

**Comment by alexanderharm** [comment]
That'll work for me. Thanks.
