### ISSUE TITLE
DirIV cache is too inefficient in some cases

### ISSUE THREAD

**Issue by lxp** [rfjakob/gocryptfs#127]
The single-entry DirIV cache is too inefficient for general use cases like git commands.
For example `git status` triggers a lot additional DirIV reads, which are not strictly necessary with a better cache strategy.

I implemented an unbound, cache everything forever strategy for testing purposes, you can find it in my [lxp:improve-diriv-cache](https://github.com/lxp/gocryptfs/tree/improve-diriv-cache) branch.

### Test results with a slow underlying filesystem

**Single-entry cache**

Sorry no results, I've given up. It didn't finish after 33 minutes...

**Unbound, cache everything forever**

```
$ time git status
[...]
It took 93.22 seconds to enumerate untracked files. 'status -uno'
may speed it up, but you have to be careful not to forget to add
new files yourself (see 'git help status').
no changes added to commit (use "git add" and/or "git commit -a")

real	10m12.210s
user	0m0.148s
sys	0m0.324s
```

### Test results with a mixed-performance underlying filesystem
Mixed-performance means some directories are accessible slower than others.

**Single-entry cache**

```
$ time git status
[...]
It took 12.21 seconds to enumerate untracked files. 'status -uno'
may speed it up, but you have to be careful not to forget to add
new files yourself (see 'git help status').

real	1m55.994s
user	0m0.120s
sys	0m0.184s
```

**Unbound, cache everything forever**

```
$ time git status
[...]
real	0m0.258s
user	0m0.008s
sys	0m0.040s
```

There are a few questions to consider when implementing another cache strategy:
- Do we need to revalidate DirIVs from time to time?
- Can we just keep DirIVs cached and only revalidate them if some decryption fails?
- Most likely we can't stick with an unbound strategy, because it would consume too much memory on really big filesystems. What's your opinion on that?
- Do we want to introduce a new dependency on a caching library or should we write it on our own?
   e.g. first search result: https://github.com/patrickmn/go-cache
- What replacement strategy should we use? LRU?
- Any other ideas?

**Comment by rfjakob** [comment]
Two more questions:
* What is your underlying filesystem?
* What git tree / how big was the git tree?

**Comment by lxp** [comment]
> What is your underlying filesystem?

The "slow underlying filesystem" is a sshfs mounted over the Internet. The remote host has a latency of around 80ms in this test.
The mixed-performance FS is the same sshfs, the git repo is bind-mounted onto a local ext4 FS.
The git repo is a first-level subdirectory in the gocryptfs root.

> What git tree / how big was the git tree?

It is a private repository, with 51 commits and 11 submodules each having around 20-700 commits.
The git repo incl. submodules has around 17 MB in total.
However, It is similarly slow with other repos. The problem here is mainly the latency of the underlying FS.
Do you need any more specs?

**Comment by rfjakob** [comment]
I used the https://github.com/golang/mock repo for testing, because it is small, but not too small (85 files). The ping time of the sshfs server is about 22ms.

sshfs:
```
$ time git status
real	0m3,289s
```
gocryptfs on sshfs:
```
$ time git status
real	0m7,977s
```
So to me it looks like we are a factor of 2 or 3 slower than plain sshfs. Looking what we can save...

**Comment by lxp** [comment]
Thank you, for testing!

First, sorry for the long text, but I did not described my use-case properly before. I only wrote "mixed-performance" underlying filesystem, but did not describe the reasoning behind it.

Actually, I have a gocryptfs volume that usually only resides on a sshfs mount.
I recently had performance issues with certain applications like git, when the server latency is too high (i.e. the server is accessed over the Internet via VPN). In a Gigabit Ethernet LAN things work reasonably well.
Because of the performance issues, I started to synchronize parts of the gocryptfs volume locally via Syncthing.
It is impossible to sync the whole volume, because it wouldn't fit on the local drive.
So I have the root of the gocryptfs volume still on the slow sshfs and only subfolders bind-mounted onto a fast local ext4 filesystem.

I expected better performance for the synced folders than when working with the sshfs in a Gigabit Ethernet LAN, even when I access the sshfs over the Internet.
However, performance only got slightly better, but was still not very usable.

I started to debug the whole thing and noticed that the current implementation of DirIV-cache fails badly in my scenario, because it doesn't cache the root DirIV for longer times.
However, a lot of file operations access the root folder before accessing the fast synchronized folders, so the root DirIV was constantly read from the slow sshfs again and again.

For testing I hacked together the unbound, cache-everything forever strategy and it performs great for my use-case.
I think to get better support for these scenarios in gocryptfs, we need to keep more than one DirIV cached and avoid re-read of often used DirIVs as much as possible.
Maybe the best solution would be to have a LRU cache of configurable size and only re-validate DirIVs when some decryption operation fails.

**Comment by rfjakob** [comment]
I see, interesting problem. Actually, the root DirIV can be cached indefinitely because it cannot change. This should solve the slowness for your use case.

The "revalidate when decryption fails" is a bit problematic because we don't have strong authentication on the file names. There is a 1/256 chance that random garbage is accepted as a valid file name.

**Comment by lxp** [comment]
It might really solve the problem in this specific case, but I would also like it to work for second or third-level synced directories.

Wouldn't it be a good idea in general to add strong authentication?
I understand that the original idea might have been to save as many bytes as possible for the file name itself, but there is long file name support here anyway, wouldn't it be a good idea to add an authentication tag?

**Comment by rfjakob** [comment]
Should be a lot better now with https://github.com/rfjakob/gocryptfs/commit/e80b5f2049edb794e340da629bce9e44485a4dbb (just merged to master).

**Comment by rfjakob** [comment]
Well, "a lot better" may be an exaggeration. Let's say *somewhat* better.
```
$ gocryptfs -version
gocryptfs v1.4-41-g0c52084; go-fuse v20170619-14-gd8fdcaa; 2017-08-12 go1.8.3
```

sshfs:
```
$ sleep 20 ; time git status
real	0m3,401s
```
gocryptfs on sshfs:
```
$ sleep 20 ; time git status
real	0m5,585s
```

**Comment by rfjakob** [comment]
BTW I noticed that SSHFS caches things for a long time (20 seconds?), which is what the "sleep 20" are for.

**Comment by rfjakob** [comment]
> Wouldn't it be a good idea in general to add strong authentication?

Yes I have though about switching the file name encryption to AES-SIV. We lose a few bytes, but get authentication and a more widely-used algorithm. However, as it's an on-disk format change, and that it will have to be replicated at [cppcryptfs](https://github.com/bailey27/cppcryptfs), I'm hesitant to do it.

So the latest gocryptfs should solve the first-level use case. Does it work OK for you?

For second level and deeper one could think about adding a command-line option for the diriv cache size and lifetime. Is it too much of a burden to move the folder to the top level?
