### ISSUE TITLE
autounmount?

### ISSUE THREAD

**Issue by pepa65** [rfjakob/gocryptfs#128]
Thank you for persisting with this excellent project! I should have switched way earlier. One last feature that I always use on encfs is `-i <minutes>` (autounmount after <minutes> minutes).

Do you think this is an undesirable feature? Of course it's a bit of extra code, and it might fail as well, but I think it does increase security when it does work as intended, not having to remember to unmount manually.

**Comment by duncanka** [comment]
Just dropped in to request this feature and found it was already requested, so adding my +1 in the hopes of raising its priority.

Adding an auto-unmount flag would also allow SiriKali to easily add support for that flag; currently, you can specify a timeout for a gocryptfs stash in SiriKali, but it doesn't actually do anything. (Of course, SiriKali could just disable that option for gocryptfs, but I'd rather see gocryptfs just support it. :smiley:)

**Comment by mhogomchungu** [comment]
An additional ability to specify if the mount point should be deleted or not when the volume is auto unmounted will be appreciated.

**Comment by RevolverOcelotA** [comment]
Try this shell script？usage: ./script cipher plain sleep_time
`#!/bin/sh
gocryptfs $1 $2
sleep ${3}m
fusermount -u -z $2`

**Comment by pepa65** [comment]
Since I already deploy gocryptfs through a wrapper script, I'll just add it this way.

**Comment by mhogomchungu** [comment]
Auto unmount feature does not work the way that script does it.

It auto unmount a volume after a specified period if inactivity is reached. That script unconditionally try to unmount a volume after a specified time has passed since the volume was mounted. The two are completely different.

**Comment by mhogomchungu** [comment]
> Just dropped in to request this feature and found it was already requested, so adding my +1 in the hopes of raising its priority.
> 
> Adding an auto-unmount flag would also allow SiriKali to easily add support for that flag; currently, you can specify a timeout for a gocryptfs stash in SiriKali, but it doesn't actually do anything. (Of course, SiriKali could just disable that option for gocryptfs, but I'd rather see gocryptfs just support it. smiley)

Git version of SiriKali now supports the "idle" option of gocryptfs. Latest released version of SiriKali(1.3.6) supports creating and unlocking of gocryptfs volumes in reverse mode.

**Comment by rfjakob** [comment]
Autoumount support has been merged to master ( 87d3ed9187cb9caccaa8df0769d4cb722cc5bd00 ) and will be in gocryptfs v1.7!
