### ISSUE TITLE
Detached console output

### ISSUE THREAD

**Issue by kofalt** [rfjakob/gocryptfs#13]
After mounting, the filesystem works fine but the console occasionally prints this log message after mounting:

> 2016/01/03 22:24:25 Unimplemented opcode POLL

It would be nice if the process instead logged to a file - maybe `gocryptfs.log` next to `gocryptfs.conf`? Or perhaps not, since log messages might contain sensitive information and/or be trampled by simultaneous edits + remote sync services (Dropbox, etc).

**Comment by rfjakob** [comment]
Yes, this would definitely be useful. I am planning to send log messages to syslog by default, and to the console only if running in the foreground.

**Comment by kofalt** [comment]
That sounds reasonable to me.

**Comment by rfjakob** [comment]
Commit 547ddf426 completed this. Closing the ticket.
