### ISSUE TITLE
Cannot recover files with the -masterkey option if repository created with the -plaintextnames

### ISSUE THREAD

**Issue by 14Elements** [rfjakob/gocryptfs#131]
There seems to be no way to recover files from an ecrypted directory created with the "plaintextnames" option using the master key. 

Steps to recreate:
1. mkdir enc plain
2. gocryptfs -init -plaintextnames enc
3. gocryptfs enc plain
4. cat "test" > plain/test.txt; fusermount -u plain
5. gocryptfs -masterkey <key> enc plain
  --> gocryptfs returns "Filesystem mounted and ready."
6. ls plain
  --> filesystem returns "**ls: cannot open directory plain: No such file or directory**"
       (same error as if incorrect master key used on an encrypted directory created without "plaintextnames"

**Comment by rfjakob** [comment]
With `-masterkey`, gocryptfs does not read the config file, it knows nothing about the used settings. That means you have to pass any non-default options as a command-line argument. This should work:
```
gocryptfs -plaintextnames -masterkey enc plain
```

**Comment by 14Elements** [comment]
Thanks, that makes sense and adding the -plaintextnames as a command-line argument works perfectly. It might be good to mention this in the documentation.
