### ISSUE TITLE
build.bash will break on go1.10

### ISSUE THREAD

**Issue by riking** [rfjakob/gocryptfs#133]
https://github.com/rfjakob/gocryptfs/blob/master/build.bash#L33-L34

The code explicitly selects 3 characters, which will break and read 1.10 as `1.1` .

Does not have any actual impact (failing the build) until `1.30`, but seems like something to fix anyways (e.g. split on dot?)

**Comment by rfjakob** [comment]
Good catch, thanks! I found pure-Go solution that seems good enough: https://github.com/rfjakob/gocryptfs/commit/e4fdb424964599db2e8d0ab273b6be804c6c9c12

The output is a little dirty, but I think users will understand what's wrong:
```
$ /opt/go1.4.3/bin/go build
can't load package: package github.com/rfjakob/gocryptfs: 
go1.4.go:5:1: expected 'package', found 'STRING' "You need Go 1.5 or higher to compile gocryptfs!"
```
