### ISSUE TITLE
encrypted (home)dir at login with gdm and SELinux

### ISSUE THREAD

**Issue by paulas1** [rfjakob/gocryptfs#134]
Thanks for this wonderful project. I almost got this to work perfectly...
I would like to mount encrypted home and shared dirs at login from an kerberized NFS v4 all working on Centos 7.3. For the shared dirs I need different passwords, so pam_mount doesn't seem suitable [1][2]. I now work with pam-script retrieving gocryptfs passwords from IPA vaults and then mounting the dirs with gocryptfs. This works fine in SELinux permissive mode (both sshd and GUI) as well as enforcing mode using sshd. Unfortunately the graphical login does not work. Gocryptfs reports the following error:

Reading password from extpass program
Decrypting master key
Not running on a terminal, suppressing master key display
fuse.NewServer failed: getConnection: recvmsg returned wrong control type: 0_

I cant find any relevant logs causing this (ausearch -i -m AVC)

The only difference i can find is the different SELinux context type that is used:
sshd: system_u:system_r:unconfined_t:s0-s0:c0.c1023
gui:    system_u:system_r:xdm_t:s0-s0:c0.c1023

Do you have any ideas what could cause this error or suggestions to resolve it?

[1]https://github.com/rfjakob/gocryptfs/wiki/Mounting-on-login-using-pam_mount
[2]https://github.com/rfjakob/gocryptfs/issues/34

**Comment by rfjakob** [comment]
I have the feeling that figuring this one out is going to be an adventue. Step one was installing a CentOS VM. Will report progress.

**Comment by paulas1** [comment]
I made some progress. 
1. SElinux does not log everything in default mode. To see all denials you have to use 'semodule --disable_dontaudit --build' [1]
2. My suspicion about the context type seems to be confirmed. If I set only xdm_t in permissive mode by using 'semanage permissive -a xdm_t' and everything works fine.
3. Although this workaround works, there are quite some processes started in the xdm_t context which might be a security risk. I found out i could start gocryptfs in an unconfined context by using 'runcon -u system_u -r unconfined_r -t unconfined_t gocryptfs'. This seems to decrease the area of attack a bit further. But I am not a security expert, so I am not sure what the exact security implications are of using runcon this way.
Hope this helps you a bit in this adventure ;-)

[1] https://wiki.gentoo.org/wiki/SELinux/Tutorials/Where_to_find_SELinux_permission_denial_details

**Comment by rfjakob** [comment]
I have pam_script installed now, and added it as the last line in `/etc/pam.d/sshd`:
```
session optional pam_script.so
```
The first obstacle I am hitting is that SELinux seems to prevent pam_script from running at all:
```
SELinux is preventing /usr/sbin/sshd from entrypoint access on the file /etc/pam_script. For complete SELinux messages. run sealert -l 1160e7cb-d9f6-4bc4-ae64-7e443bcc52fd
SELinux is preventing /usr/sbin/sshd from entrypoint access on the file /etc/pam_script.

*****  Plugin catchall (100. confidence) suggests   **************************

If you believe that sshd should be allowed entrypoint access on the pam_script file by default.
Then you should report this as a bug.
You can generate a local policy module to allow this access.
Do
allow this access for now by executing:
# ausearch -c 'sshd' --raw | audit2allow -M my-sshd
# semodule -i my-sshd.pp
```
I guess you have worked around that using the "semodule" suggestion above?

**Comment by rfjakob** [comment]
After hitting apparently [this redhat bug](https://bugzilla.redhat.com/show_bug.cgi?id=1406328):
```
# ausearch -c 'sshd' --raw | audit2allow -M my-sshd
libsepol.sepol_string_to_security_class: unrecognized class file
```
I worked around the bug using "tr" like htis
```
# ausearch -c 'sshd' --raw | tr -d \\035 | audit2allow -M my-sshd
```
and hit another [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1381112)
```
[Errno 2] No such file or directory: '/etc/selinux/targeted/contexts/files/file_contexts.local'
```
that however seems to be fixed for years (!?). I worked around that one using
```
touch /etc/selinux/targeted/contexts/files/file_contexts.local
```
When did CentOS start to be such a buggy pile of junk?

**Comment by Nodens-** [comment]
It's not..it just has very slow package update rate and patch adoption due to it being server oriented.. and not being RHEL where things move faster because you're paying redhat for exactly this reason :P 

I administer 4 CentOS systems and the best advice I can give is not to update anything if things work, unless it's security oriented or new feature you absolutely must have :P

**Comment by paulas1** [comment]
I used the workarounds as you mentioned. CentOS is a bit on the conservative side with updates, which makes trying new things a hassle, i often try it first in permissive mode. The alternative is Fedora, but i experienced that was often ahead of the crowd, not integrating well with existing older packages.

**Comment by Nodens-** [comment]
I use Fedora as a linux dev system and testbed (I believe rfjakob is also developing gocryptfs on Fedora).
As a server it depends on what you're actually doing with it and if it's exposed to the internet. In the server world, being too cutting edge can be dangerous due to security holes..

**Comment by rfjakob** [comment]
I guess the big thing about RHEL/CentOS is that once you have it running as desired it will keep running and will be supplied with security updates for a long time. That's a good reason to choose it!

So, for pam-script, I made some progress. But I am facing a big problem for debugging this now: The mount works, for ssh and also gdm. But I guess I am doing something differently. I have created the file 
`/etc/pam-script.d/gocryptfs_ses_open`, content is:

```
sudo -u jakob gocryptfs -extpass "echo test" /home/jakob/a /home/jakob/b > /tmp/g.log 2>&1
```

And my `/etc/pam.d/gdm-password`, I guess you are calling pam-script earlier in the stack?

```
auth     [success=done ignore=ignore default=bad] pam_selinux_permit.so
auth        substack      password-auth
auth        optional      pam_gnome_keyring.so
auth        include       postlogin

account     required      pam_nologin.so
account     include       password-auth

password    substack       password-auth
-password   optional       pam_gnome_keyring.so use_authtok

session     required      pam_selinux.so close
session     required      pam_loginuid.so
session     optional      pam_console.so
-session    optional    pam_ck_connector.so
session     required      pam_selinux.so open
session     optional      pam_keyinit.so force revoke
session     required      pam_namespace.so
session     include       password-auth
session     optional      pam_gnome_keyring.so auto_start
session     include       postlogin

session optional pam_script.so
```

**Comment by rfjakob** [comment]
I switched to mounting the whole home directory, gocryptfs_ses_open now looks like [this](
https://gist.github.com/rfjakob/7fb4d7dc780bf5e7823af3eef74edad4/0b19a82a9103250aadea50209aef5013f49a07f0). I'm getting a SELinux alert, but the login seems to proceed nevertheless.

```
SELinux is preventing /usr/libexec/gdm-session-worker from write access on the directory .cache.

*****  Plugin catchall_boolean (89.3 confidence) suggests   ******************

If you want to allow use to fusefs home dirs
Then you must tell SELinux about this by enabling the 'use_fusefs_home_dirs' boolean.
You can read 'None' man page for more details.
Do
setsebool -P use_fusefs_home_dirs 1
```

Running the `setsebool -P use_fusefs_home_dirs 1` command makes the error disappear, as expected.

**Comment by rfjakob** [comment]
What I found surprising is that the `gocryptfs_ses_open` script seems to be run as root. I used sudo to switch to the user, but I may be doing something wrong here.

**Comment by Nodens-** [comment]
By the way what is the output of ls -Z on the gocryptfs binary? And did you try just setting unconfined_t on gocryptfs permanently? 
semanage fcontext -a -t unconfined_t /path/to/gocryptfs
restorecon -v /path/to/gocryptfs

There should not be any security problem from running gocryptfs binary as unconfined_t.

**Comment by paulas1** [comment]
Okay, that is indeed what I already did (as mentioned in my second comment) Just was not sure about the security implications, but they seem to be minimal. Thanks for checking this out and it might help others on this path as well.

**Comment by rfjakob** [comment]
You had it a little different, using `system_u`, but I'm not sure if it makes a difference.

Another objective of digging into this is to find out if we can get a better error message from go-fuse and/or fusermount, because `recvmsg returned wrong control type: 0_` is pretty bad.

I can reproduce the problem now, this is the complete SELinux message: 
```
# sealert -l 8ad8cbe3-daf1-46e2-b0a7-a3acddc82a28
SELinux is preventing /usr/bin/gocryptfs from 'read, write' accesses on the chr_file fuse.

*****  Plugin catchall (100. confidence) suggests   **************************

If you believe that gocryptfs should be allowed read write access on the fuse chr_file by default.
Then you should report this as a bug.
You can generate a local policy module to allow this access.
Do
allow this access for now by executing:
# ausearch -c 'gocryptfs' --raw | audit2allow -M my-gocryptfs
# semodule -i my-gocryptfs.pp


Additional Information:
Source Context                system_u:system_r:xdm_t:s0-s0:c0.c1023
Target Context                system_u:object_r:fuse_device_t:s0
Target Objects                fuse [ chr_file ]
Source                        gocryptfs
Source Path                   /usr/bin/gocryptfs
Port                          <Unknown>
Host                          centos7.localdomain
Source RPM Packages           gvfs-fuse-1.22.4-8.el7.x86_64
Target RPM Packages           
Policy RPM                    selinux-policy-3.13.1-102.el7_3.16.noarch
Selinux Enabled               True
Policy Type                   targeted
Enforcing Mode                Enforcing
Host Name                     centos7.localdomain
Platform                      Linux centos7.localdomain
                              3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4
                              15:04:05 UTC 2017 x86_64 x86_64
Alert Count                   2
First Seen                    2017-08-21 17:56:25 CEST
Last Seen                     2017-08-21 17:56:30 CEST
Local ID                      8ad8cbe3-daf1-46e2-b0a7-a3acddc82a28

Raw Audit Messages
type=AVC msg=audit(1503330990.304:1466): avc:  denied  { read write } for  pid=23301 comm="gvfsd-fuse" name="fuse" dev="devtmpfs" ino=12658 scontext=system_u:system_r:xdm_t:s0-s0:c0.c1023 tcontext=system_u:object_r:fuse_device_t:s0 tclass=chr_file


type=SYSCALL msg=audit(1503330990.304:1466): arch=x86_64 syscall=open success=no exit=EACCES a0=7f90c6428eea a1=2 a2=df50 a3=76 items=0 ppid=1 pid=23301 auid=4294967295 uid=42 gid=42 euid=42 suid=42 fsuid=42 egid=42 sgid=42 fsgid=42 tty=(none) ses=4294967295 comm=gvfsd-fuse exe=/usr/libexec/gvfsd-fuse subj=system_u:system_r:xdm_t:s0-s0:c0.c1023 key=(null)

Hash: gocryptfs,xdm_t,fuse_device_t,chr_file,read,write
```

**Comment by Nodens-** [comment]
Unless I missed something, is there any particular reason to use runcon instead of changing the binary context permanently?
 runcon is prone to failure as the transition of context itself can be blocked by selinux policy. Which means there may be cases where a future update of policy will stop this from working. If this is a production environment, it's not the best idea.

Also can we see the contents of the .te created by audit2allow?

**Comment by rfjakob** [comment]
@Nodens- No, I guess this would work as well. A downside may be that you have to do it again when you replace the binary due to an update. I could not find a *.te file (`find / -name "*.te"` came back empty), sorry!

I'll close this ticket as we seem to have a working solution.
