### ISSUE TITLE
Read password from stdin

### ISSUE THREAD

**Issue by babam86** [rfjakob/gocryptfs#135]
How to read password from standard input?

Sorry for stupid question and bad English.

Thanks.

**Comment by mhogomchungu** [comment]
If you want to send a password to gocryptfs from a script,pipe it in using echo command,example is below where a password of "xxx" is sent to gocryptfs to unlock a folder named "cipher" and mount it to a mount point named "plain"

```
[ink@mtz ~]$ echo "xxx" | gocryptfs cipher plain
Reading password from stdin
Decrypting master key

Your master key is:

    e8d4c38d-1c4bbe53-3aae11d2-06b12bc5-
    3a177a54-0fce7003-340cc842-63ad5970

If the gocryptfs.conf file becomes corrupted or you ever forget your password,
there is only one hope for recovery: The master key. Print it to a piece of
paper and store it in a drawer. Use "-q" to suppress this message.

Filesystem mounted and ready.
[ink@mtz ~]$ 

```

**Comment by babam86** [comment]
@mhogomchungu

Ok, Thanks.

**Comment by rfjakob** [comment]
Thanks for helping out, @mhogomchungu !
