### ISSUE TITLE
full, non-bootable, system backup

### ISSUE THREAD

**Issue by yunesj** [rfjakob/gocryptfs#136]
I'm interested in doing a full, non-bootable, system backup using the reverse option. Usually, when doing a backup I exclude special directories like /run, /proc, etc. on linux, and fseventsd, etc. on a mac. To selectively exclude paths when backing up using gocryptfs, is it necessary to use plaintextnames and exclude in rsync? Or is there a way to exclude paths via gocryptfs configuration?

Do you have any other suggestions or concerns for my use case?

Thanks!

**Comment by charles-dyfis-net** [comment]
I'd suggest creating your gocryptfs mount of a non-recursive bind mount of the root filesystem -- that'll automatically exclude anything that's on a different FS.

**Comment by yunesj** [comment]
Great idea. Thanks!

**Comment by rfjakob** [comment]
The bind mount is a great idea, yes!

The other thing that you could do is to encrypt the paths you want to exclude using [ctlsock-encrypt](https://github.com/rfjakob/gocryptfs/tree/master/contrib) and exclude them in rsync. It's a little tedious, but you only have to do it once.
