### ISSUE TITLE
Suggestion: Lock memory to avoid key/cleartext compromise  

### ISSUE THREAD

**Issue by mcorb** [rfjakob/gocryptfs#137]
When a long-running gocryptfs process is paged out of memory the plain decrypted key stored to disk. With modern SSD drives and wear levelling the key could remain forensically recoverable for months or years.

This can be mitigated using an mlock facility like [memguard](https://github.com/awnumar/memguard) (the go equivalent of libsodium), which manages memory slices that are guaranteed not to page out.

it looks like memguard could be dropped into the `bPool` interface without much work. You'd just need to make sure that the user password and decrypted key are only ever stored in memguard-managed memory.

(For bonus points it might be interesting to use the facility for cleartext content buffers too, ensuring that the gocryptfs process doesn't compromise confidential user data either.)

**Comment by rfjakob** [comment]
Good point, and the memguard library looks pretty good! However, most of the times, we don't store the key, the standard library does, like here: https://github.com/rfjakob/gocryptfs/blob/f59479736bed49411bda3368f419d6605f1faa78/internal/cryptocore/cryptocore.go#L89

In this case there is not much we can do about it.

**Comment by rfjakob** [comment]
But due to your suggestion I have just pushed https://github.com/rfjakob/gocryptfs/commit/0c520845f3623eff28f0277a52e3ccffd928f5c2 to clear the masterkey as soon as we can. We kept an unneccessary copy around.

**Comment by mcorb** [comment]
Thanks @rfjakob. This mitigates a little and at least makes it explicit. If the standard library is using the standard allocator I guess it's inevitable bits of key are going to get swapped - pity.

**Comment by rfjakob** [comment]
The only solution to this, at the moment, is to either disable swap or use an ecrypted partition.
