### ISSUE TITLE
macOS: enable Trash

### ISSUE THREAD

**Issue by eugenesvk** [rfjakob/gocryptfs#141]
I understand it might be exclusively a go-fuse issue (and I've opened an [issue there](https://github.com/hanwen/go-fuse/issues/183) as well), but just wondering if maybe there is something that could be done on the part of gocryptfs as well.
Is it possible to enable Trash on macOS when a gocryptfs volume is mounted?

**Comment by rfjakob** [comment]
Would be nice to have a working trash, yes. I just have no idea how to tell MacOS to enable it. To have a starting point, can you check if trash work with EncFS?

**Comment by eugenesvk** [comment]
Trash doesn't work with EncFS, it offers to permanently remove the files. Guess it's another area to be better than EncFS :) (though I'm also clueless as to how trash is working on macOS)

**Comment by rfjakob** [comment]
Looks like this has escalated all the way to osxfuse, nice :)
Now tracked in https://github.com/osxfuse/osxfuse/issues/424 , I'll close this ticket.

**Comment by eugenesvk** [comment]
Just in case anyone stumbles upon this: you need two things to enable trash 
  1. manually create a `.Trashes` folder in the root of your mounted gocryptfs volume if it doesn't exist
  2. mount your volume with `-ko local` flag

It will let the system auto-create a `$UID` subfolder in the `.Trashes` folder and use it as a trash folder automatically (wish it also automatically created the `.Trashes` folder, but for some reason it doesn't)
(it will also change the "icon" in the Devices tab to be the same as your local hard drive)

However, the osxfuse's docs have the following warning about this `local` flag [src](https://github.com/osxfuse/osxfuse/wiki/Mount-options#local)

> You could run into mysterious problems with Disk Arbitration and other system components. I don't know (and possibly can't know--Mac OS X isn't all open source!) the side effects of using this option. Therefore, treat this as experimental and use with caution. Moreover, please do not file bug reports that involve this option--reproduce your issue without this option and then file a bug report.

Not sure what to make of it, would be nice to know if this is a practical concern or just a theoretical one
