### ISSUE TITLE
[idea] consider AES-OCB

### ISSUE THREAD

**Issue by Vincent43** [rfjakob/gocryptfs#144]
Hi! I wanted to propose an idea of switching to AES-OCB [1][2][3] from currently used AES-GCM.

It's considered as superior encryption mode by cryptographers as it's safer to use and provide better performance [4][5]. The only drawbacks were patent issues but now it's freely available for open source projects [6] and it's included in openssl 1.1 library [7].

It's not widely yet used so it can be interesting feature for gocryptfs users.

[1] https://en.wikipedia.org/wiki/OCB_mode
[2] http://web.cs.ucdavis.edu/~rogaway/ocb/
[3]https://tools.ietf.org/html/rfc7253
[4] https://twitter.com/sweis/status/768911693795631104
[5] https://twitter.com/a_z_e_t/status/657023609022582784
[6]  http://web.cs.ucdavis.edu/~rogaway/ocb/license.htm
[7]https://wiki.openssl.org/index.php/OCB

**Comment by rfjakob** [comment]
Looks interesting, however, the patent thing is problematic given that I want gocryptfs to be useable for whatever you want.

From [6] license 1:

Open Source Software Implementation does not include any Software 
Implementation in which the software implicating the Licensed Patents is 
combined, so as to form a larger program, with software that is not Open Source 
Software.

**Comment by rfjakob** [comment]
The other thing is that aes-gcm has an assembly implementation in Go. While I think i can implement aes-ocb in Go, writing optimized assembly is beyond my capabilities.

But i guess openssl has an optimized implemenatation. Using openssl would also kind of workaround the patent issue. But then a static build of gocryptfs will not be able to work with an ocb filesystem.

It's... Complicated :-)

**Comment by Vincent43** [comment]
The patent will expire in 2020. Maybe better implementations will be available at that time.

There is also AES-PMAC-SIV[1] which has nonce misuse resistance and has available go implementation. It's however slower than AES-GCM and not much tested.

Probably best option is to wait until AES-GCM-SIV[2] is finished.

Anyway, it's probably too early to make any moves. Feel free to close this.

[1] https://github.com/miscreant/miscreant
[2] https://datatracker.ietf.org/doc/draft-irtf-cfrg-gcmsiv/

**Comment by rfjakob** [comment]
Will close this for now.
