### ISSUE TITLE
masterkey decryption

### ISSUE THREAD

**Issue by kochtopf** [rfjakob/gocryptfs#148]
I do something very wrong  - but could not figure out what.
I do..
gocryptfs -extpass "echo -n pwd" /media/webdav/box/Documents /tmp/gocryptfs (reverse mount)
this is working OK (prints out the masterkey). Dirs and files are readable.
Then fusermount -u /tmp/gocryptfs and
gocryptfs -masterkey xxxxxx /media/webdav/box/Documents /tmp/gocrypfs
I'll get...
THE MASTER KEY IS VISIBLE VIA "ps ax" AND MAY BE STORED IN YOUR SHELL HISTORY!
ONLY USE THIS MODE FOR EMERGENCIES.
Filesystem mounted and ready.
ls /tmp/gocrypts shows all the dirs OK but as soon as
cat a data file I get: Input/output error for every file.

I tried to put the masterkey in hyphen without the dashes - no success. 
PS: Mounting this with the extpass and a the .gocryptfs.conf file works - just not with the masterkey.
I'm on Debian gocryptfs v1.4.1-22-g29445c9; go-fuse v20170619-18-g430ccce; 2017-10-19 go1.9.1

**Comment by rfjakob** [comment]
Hi, what do you get in `journalctl -f` when you cat a file?

**Comment by rfjakob** [comment]
Oh, I know what's happening. Reverse mode uses aes-siv mode. With `-masterkey`, all settings are at default, so you need to pass `-aessiv`.

**Comment by rfjakob** [comment]
This was not documentated, so I have just added a paragraph to the man page. Do you think it is clear? Added text below:

> Even if a config file exists, it will not be used. All non-standard settings have to be passed on the command line: -aessiv when you mount a filesystem that was created using reverse mode, or -plaintextnames for a filesystem that was created with that option.

**Comment by kochtopf** [comment]
Yup that was it! Thank you very much. My bad. -aessiv was one of the only options I did not try. With your doc change - it's all clear now. Again thanks for this great product (good bye encfs and hello gocryptfs).
