### ISSUE TITLE
gocryptfs.DirIV keeps chaning

### ISSUE THREAD

**Issue by Lord-Simon** [rfjakob/gocryptfs#149]
To keep it short, I use the master of https://github.com/rpodgorny/unionfs-fuse to bundle the folders in a specific location and then use gocryptfs in reverse mode to encrypt and upload data.

After unmounting and then mounting gocrytfs 1.4 once again, I noticed the following:
```
$ xxd _Ktb0N3EqKPNqszm3UX8AQ/gocryptfs.diriv
0000000: e932 c100 57a5 ccb6 c45e 80fc b79a 9c1a  .2..W....^......
$ xxd _Ktb0N3EqKPNqszm3UX8AQ/gocryptfs.diriv
0000000: 966e 09fc bd20 1ec1 4003 e05b bf26 aa08  .n... ..@..[.&..
$ xxd _Ktb0N3EqKPNqszm3UX8AQ/gocryptfs.diriv
0000000: 7c1e d1ca 1221 19ba 8e5e e51c 3fbe 8284  |....!...^..?...
$ xxd _Ktb0N3EqKPNqszm3UX8AQ/gocryptfs.diriv
0000000: 469c dcbe 5b45 b362 961d ad72 5b9d a4d4  F...[E.b...r[...
```
The content of the presented gocryptfs.diriv keeps changing.
And there are some folders that exist in the reverse view, but can't be read nor accesses. "File does not exist"
I see them in clear text, encrypt the name through ctlsock, yet the folder does not "exist" in gocryptfs view.

To see if it only happens with unionfs folders, I recreated the whole folder structure of the clear path and let gocryptfs encrypt it in reverse mode. Works fine and no changes in the gocryptfs.diriv. Done so on another system. Same result.

After that I unmounted all unionfs folders and mounted only one. Let gocryptfs do it thing. gocryptfs.diriv does not change, I can access all folders. 
umont gocryptfs, mount another unionfs folder and let gocryptfs do it's thing. After this the gocryptfs.diriv starts going wild and I can't access some subfolders in the encrypted view.

It only goes crazy when gocryptfs is encrypting a folder which contains two or more mounted unionfs folders. And only unionfs folders. If I umount a unionfs folder, it's gocryptfs.diriv does not go haywire and stays the same. Strangely, the filename encryption through ctlsock and on the filesystem is the same as before it has gone hywire, execept the folders I can't access.

Doing xxd on multiple unionfs folders, <sup>yaaaaay<sup> :
```
$ find ./reverse -maxdepth 2 -type f -name "gocryptfs.diriv" -exec xxd {} \;
0000000: 966e 09fc bd20 1ec1 4003 e05b bf26 aa08  .n... ..@..[.&..
0000000: 966e 09fc bd20 1ec1 4003 e05b bf26 aa08  .n... ..@..[.&..
0000000: 966e 09fc bd20 1ec1 4003 e05b bf26 aa08  .n... ..@..[.&..
0000000: 966e 09fc bd20 1ec1 4003 e05b bf26 aa08  .n... ..@..[.&..
0000000: 966e 09fc bd20 1ec1 4003 e05b bf26 aa08  .n... ..@..[.&..
0000000: d1a7 c43a eb1c 575d 9848 3727 6fd5 cb27  ...:..W].H7'o..'
0000000: 966e 09fc bd20 1ec1 4003 e05b bf26 aa08  .n... ..@..[.&..
0000000: 966e 09fc bd20 1ec1 4003 e05b bf26 aa08  .n... ..@..[.&..
0000000: 966e 09fc bd20 1ec1 4003 e05b bf26 aa08  .n... ..@..[.&..
0000000: 58a5 0452 871b d61e 2096 b21e a21c 0f42  X..R.... ......B
0000000: c093 03de deab 05bd b4f0 d3a2 c844 8c0b  .............D..
0000000: 7518 5f4f ee8d a958 40bf 46ba fcf6 baa5  u._O...X@.F.....
0000000: 4035 df9d 9018 9100 91ff 742d 0157 3466  @5........t-.W4f
0000000: 14bb d6c7 ebb9 e081 cdc1 0aa9 f98e 61b6  ..............a.
0000000: a8f7 bac4 32dd c1cb 3dc7 4e68 4d6a e48b  ....2...=.NhMj..
```

The debug says the following when reading the gocryptfs.diriv while it keeps changing
```
2017/10/22 02:52:27 Dispatch 6373: GETATTR, NodeId: 1. data: {Fh 0}
2017/10/22 02:52:27 Serialize 6373: GETATTR code: OK value: {A1.000000000 {M040775 SZ=252 L=1 1000:1000 B0*4096 i0:190950 A 1508564115.712375009 M 1503958576.247388636 C 1503958576.247388636}}
2017/10/22 02:52:27 Dispatch 6374: LOOKUP, NodeId: 1. names: [_Ktb0N3EqKPNqszm3UX8AQ] 23 bytes
2017/10/22 02:52:27 Serialize 6374: LOOKUP code: OK value: {NodeId: 14 Generation=0 EntryValid=1.000 AttrValid=1.000 Attr={M040775 SZ=12288 L=1 1000:1000 B24*4096 i0:1 A 1508597309.686034662 M 1506988525.733285732 C 1506988525.733285732}}
2017/10/22 02:52:27 Dispatch 6375: LOOKUP, NodeId: 14. names: [gocryptfs.diriv] 16 bytes
2017/10/22 02:52:27 Serialize 6375: LOOKUP code: OK value: {NodeId: 18 Generation=0 EntryValid=1.000 AttrValid=1.000 Attr={M0100444 SZ=16 L=1 1000:1000 B0*4096 i0:1000000000000000001 A 1488583939.402915449 M 1491251312.157676287 C 1491251312.157676287}}
2017/10/22 02:52:27 Dispatch 6376: OPEN, NodeId: 18. data: {O_RDONLY,0x8000}
2017/10/22 02:52:27 Serialize 6376: OPEN code: OK value: {Fh 2 }
2017/10/22 02:52:27 Dispatch 6377: READ, NodeId: 18. data: {Fh 2 off 0 sz 4096  L 0 RDONLY,0x8000}
2017/10/22 02:52:27 Serialize 6377: READ code: OK value:  16 bytes data

2017/10/22 02:52:27 Dispatch 6378: FLUSH, NodeId: 18. data: {Fh 2}
2017/10/22 02:52:27 Serialize 6378: FLUSH code: OK value:
2017/10/22 02:52:27 Dispatch 6379: RELEASE, NodeId: 18. data: {Fh 2 0x8000  L0}
2017/10/22 02:52:27 Serialize 6379: RELEASE code: OK value:

2017/10/22 02:52:30 Dispatch 6380: GETATTR, NodeId: 1. data: {Fh 0}
2017/10/22 02:52:30 Serialize 6380: GETATTR code: OK value: {A1.000000000 {M040775 SZ=252 L=1 1000:1000 B0*4096 i0:190950 A 1508564115.712375009 M 1503958576.247388636 C 1503958576.247388636}}
2017/10/22 02:52:30 Dispatch 6381: LOOKUP, NodeId: 1. names: [_Ktb0N3EqKPNqszm3UX8AQ] 23 bytes
2017/10/22 02:52:30 Serialize 6381: LOOKUP code: OK value: {NodeId: 14 Generation=0 EntryValid=1.000 AttrValid=1.000 Attr={M040775 SZ=12288 L=1 1000:1000 B24*4096 i0:1 A 1508597309.686034662 M 1506988525.733285732 C 1506988525.733285732}}
2017/10/22 02:52:30 Dispatch 6382: LOOKUP, NodeId: 14. names: [gocryptfs.diriv] 16 bytes
2017/10/22 02:52:30 Serialize 6382: LOOKUP code: OK value: {NodeId: 18 Generation=0 EntryValid=1.000 AttrValid=1.000 Attr={M0100444 SZ=16 L=1 1000:1000 B0*4096 i0:1000000000000000001 A 1488583939.402915449 M 1491251312.157676287 C 1491251312.157676287}}
2017/10/22 02:52:30 Dispatch 6383: OPEN, NodeId: 18. data: {O_RDONLY,0x8000}
2017/10/22 02:52:30 Serialize 6383: OPEN code: OK value: {Fh 2 }
2017/10/22 02:52:30 Dispatch 6384: READ, NodeId: 18. data: {Fh 2 off 0 sz 4096  L 0 RDONLY,0x8000}
2017/10/22 02:52:30 Serialize 6384: READ code: OK value:  16 bytes data

2017/10/22 02:52:30 Dispatch 6385: FLUSH, NodeId: 18. data: {Fh 2}
2017/10/22 02:52:30 Serialize 6385: FLUSH code: OK value:
2017/10/22 02:52:30 Dispatch 6386: RELEASE, NodeId: 18. data: {Fh 2 0x8000  L0}
2017/10/22 02:52:30 Serialize 6386: RELEASE code: OK value:
```

The system has been running for a few month, there were no updates and no new software was added.
So there were no changes except unmounting, mounting gocryptfs and adding data to the folders that unionfs is linking,

**Comment by Lord-Simon** [comment]
Forgot. Tried it with 1.4.1, too. Same result.
Didn't try it with 1.3.9, yet.

**Comment by rfjakob** [comment]
Oh dear, duplicate inode numbers due to the unionfs mount?

**Comment by Lord-Simon** [comment]
...aye, it's inode. Glad that it's not gocryptfs, but unionfs.
Thanks for the quick reply. Gonna see how to fix that problem, since it didn't happen before.

**Comment by rfjakob** [comment]
I think unionfs should add the device number to the inode number to prevent collisions, but I'll also change gocryptfs reverse mode a bit to be more robust against duplicates

**Comment by danim7** [comment]
Hi rfjakob,

Would your changes be backwards compatible? I mean: I'm currently using
reverse mode to backup data remotely. If the current version exposes a
given file as 'aaa', would your evolution expose it as 'bbb' ? Thanks !

**Comment by rfjakob** [comment]
@Lord-Simon I just pushed commit 8c1b363f74f4db4e413fe17e327a82bd6ef66837 which should fix your problem - could you verify?

@danim7 Fully compatible, unless you have duplicate inode numbers you will see no changes in the ciphertext.

**Comment by danim7** [comment]
Great, thanks for your work and quick reply!

**Comment by Lord-Simon** [comment]
@rfjakob Just compiled and tested it. The problem has been fixed by 8c1b363.
The DirIV does not change anymore and I can access the folders that were previously inaccessible.

Thank you for the quick fix. Now I can, once again, upload the data with a single command.

**Comment by rfjakob** [comment]
Good, thanks for testing!

Note that the duplicate inode numbers will still cause problems when you use a backup program that preserves hard links (like "rsync -H"). It will hard-link those files at the destination.

**Comment by Lord-Simon** [comment]
Aye, I will be carefull. Yet again, thanks.
