### ISSUE TITLE
Reverse view mounted under the plaintext directory encrypts recursively

### ISSUE THREAD

**Issue by tigmac** [rfjakob/gocryptfs#150]
Version 1.2 Ubuntu Zesty/Debian Stretch
Steps to reproduce:

mkdir a
mkdir a/b
gocryptsfs -init -reverse a/
gocryptfs -reverse a/ a/b

Now directory a/b/ contains encrypted view of 'a' but it is possible to descend into encrypted version of b (e.g. a/b/43873uhj538765387/) which contains double encrypted 'a' and so on.
Suggestion: minimal  solution would be to perform check whether the mountpoint is under the plaintext dir in the directory tree structure just at the moment of mounting the reverse view.
Preferred solution: allow mountpoint under plaintext dir but prevent recursive encryption, e.g. always present the encrypted version of the directory where the view is mounted as empty.

**Comment by rfjakob** [comment]
Haha, good find.

Do you think there is a valid use case to mount under the plaintext directory?

**Comment by tigmac** [comment]
Actually, it can be avoided but I stumbled upon this in a real use case when doing automated backups.
The backup script syncs several distinct top level directories so it mounts several encrypted views one after the other.
There are basically two options where to mount the encrypted views: create a temporary directory or use a fixed location. I have taken the second approach and created hidden dot directory under the plaintext dir and because I had excluded hidden files from the backup it all worked well in some cases until the situation when hidden files were not excluded - at that point the backup crashed hard, I needed to reboot the machine.
Even if this is not supported feature it would be good it would be good to cover it as corner case.

**Comment by rfjakob** [comment]
Ok, I was asking to decide between the "minimal solution" and the "preferred solution".

We already had disallowed that the mountpoint contains the backing directory,
with https://github.com/rfjakob/gocryptfs/commit/a1a98abfbb1fe3bd235ca1a7e275f84d41afa417 we now also disallow that the backing directory contains the mountpoint.

So this what you called the minimal solution. It's much easier to do in the code, and to me it looks good enough.

**Comment by rfjakob** [comment]
Thanks for the report!

Fixed by https://github.com/rfjakob/gocryptfs/commit/a1a98abfbb1fe3bd235ca1a7e275f84d41afa417.
