### ISSUE TITLE
DOC: Wikipedia presence is lacking

### ISSUE THREAD

**Issue by kevinf28** [rfjakob/gocryptfs#153]
While the official site / github has lots of information, many users use Wikipedia to compare competing solutions.

I started by adding Gocryptfs to https://en.wikipedia.org/wiki/List_of_cryptographic_file_systems and https://en.wikipedia.org/wiki/Comparison_of_disk_encryption_software#Background_information but a standalone page (even something small like https://en.wikipedia.org/wiki/ECryptfs) would help. Likewise the other sections of on Comparison_of_disk_encryption_software page should be filled in. 

If you would like me to proofread/publish the content you wish to add to https://en.wikipedia.org/wiki/Gocryptfs in order to ensure it meets Wikipedia guidelines, I can do that.

**Comment by rfjakob** [comment]
Thanks for adding gocryptfs to the lists!

The reason i have not created a gocryptfs page is that writing about your own projects on wikipedia is seen as problematic.

I'd appreciate if you or somebody else could create the page with some basic content. You can use everything from github and the website (markdown source code: https://github.com/rfjakob/gocryptfs-website ) also the svg graphics, it's all MIT licensed (will add a license file today in the evening).

**Comment by rfjakob** [comment]
Once the page is established, I can take it from there and will be editing.

**Comment by rfjakob** [comment]
License file added ( https://github.com/rfjakob/gocryptfs-website/blob/master/LICENSE )

**Comment by rfjakob** [comment]
Please ping me with a new ticket if the page gets created! Thanks for the suggestion.
