### ISSUE TITLE
[bug] Error when using ls on empty directory with MEGA

### ISSUE THREAD

**Issue by syddel** [rfjakob/gocryptfs#154]
On my MEGA cloud storage mount, if I try to `ls -la` a new gocryptfs basedir, I get the following error:

```
[syddel@d2:MEGA]$ gocryptfs -q BACKUPS/ backups/
Password: 
[syddel@d2:MEGA]$ ls -la backups/
```
**```ls: cannot open directory 'backups/': Input/output error```**
```
[syddel@d2:MEGA]$ touch backups/test.txt
[syddel@d2:MEGA]$ ls -la backups/
total 16
drwxrwxr-x  3 syddel syddel 4096 Nov  6 22:40 .
drwxrwxr-x 11 syddel syddel 4096 Nov  5 19:46 ..
-rw-rw-r--  1 syddel syddel    0 Nov  6 22:40 test.txt
```
Everything works for empty local gocrypt directories, so I'm not sure if this is an issue with gocryptfs or the MEGAsync client on Linux.

**Comment by rfjakob** [comment]
Can you post:
```
ls -la BACKUPS
```
Getting and error when listing a directory means that gocryptfs has only found files it could not decrypt (maybe autogenerated junk)

**Comment by syddel** [comment]
```
[syddel@d2:MEGA]$ ls -la BACKUPS/                                                                                                  
total 36
drwxrwxr-x  3 syddel syddel 4096 Nov  7 09:30 .
drwxrwxr-x 12 syddel syddel 4096 Nov  7 09:30 ..
drwx------  5 syddel syddel 4096 Nov  5 21:33 .debris
-r--------  1 syddel syddel  425 Nov  6 23:11 gocryptfs.conf
-rw-------  1 syddel syddel   16 Nov  4 01:34 gocryptfs.diriv
[syddel@d2:MEGA]$ 

```

**Comment by rfjakob** [comment]
Yes it's the ".debris" directory. What's this?

**Comment by syddel** [comment]
I've just read this from the MEGA help pages:

> Whatever you add / delete to / from your sync folder(s) on your device locally gets added / deleted in your sync folder(s) in Cloud Drive and vice versa. Overwritten or deleted files can be found in your local sync hidden folder called Rubbish or .debris and in your Cloud Drive's SyncDebris folder in the Rubbish Bin.

So yeah, looks like something the MEGAsync client creates.

Closing this as it's a non-issue. Thanks.

**Comment by rfjakob** [comment]
Note that once gocryptfs sees at least one file that looks valid it won't return an error.

In other word, the error goes away once you create a file.
