### ISSUE TITLE
"-info" option does not work with "-config" option

### ISSUE THREAD

**Issue by mhogomchungu** [rfjakob/gocryptfs#157]
What i want is to get properties of a volume that uses an external config file.

Command like below does not work.
```
/usr/bin/gocryptfs -info -config "/home/ink/gocryptfs.conf"
```

**Comment by rfjakob** [comment]
Hmm, cannot reproduce
```
$ gocryptfs -info -config external.config a 
Using config file at custom location /tmp/tmp.6BWwz3pvnN/external.config
Creator:      gocryptfs v1.4.2-3-ge36a0eb-dirty
FeatureFlags: GCMIV128 HKDF DirIV EMENames LongNames Raw64
EncryptedKey: 64B
ScryptObject: Salt=32B N=65536 R=8 P=1 KeyLen=32
```

**Comment by mhogomchungu** [comment]
```
[ink@mtz ~]$ gocryptfs -info -config gocryptfs.conf /root/
Using config file at custom location /home/ink/gocryptfs.conf
Creator:      gocryptfs v1.4.1
FeatureFlags: GCMIV128 HKDF DirIV EMENames LongNames Raw64
EncryptedKey: 64B
ScryptObject: Salt=32B N=65536 R=8 P=1 KeyLen=32
[ink@mtz ~]$ 

```
So,the command seems to require a folder as the last option without carrying about the contents of the folder since it works even with folders it can not access.

It did not occur to me to try the command with cipher folder because i correctly suspected there is nothing worth reading from it.

I think the command should not require the cipher folder path to work correctly.

**Comment by rfjakob** [comment]
It's true that CIPHERDIR is not needed in this case, but it's documented in the help text like that, and it makes command-line parsing so much easier.

However, you used to just get the help text in response to
```
$ gocryptfs -info -config foo.conf
```
which was pretty unclear in explaining what is wrong. So now you get this:
```
$ gocryptfs -info -config foo.conf
CIPHERDIR argument is missing
```
I think this should keep user frustation to a minimum.

**Comment by mhogomchungu** [comment]
Fixed the bug on my end with this[1] commit.

[1] https://github.com/mhogomchungu/sirikali/commit/d6306a50c298581f1001e3df8e47018df57ae94f
