### ISSUE TITLE
add command to print all supported crypto options

### ISSUE THREAD

**Issue by mhogomchungu** [rfjakob/gocryptfs#159]
In the GUI window of cppcryptfs as see here[1], there are options to set "file names" crypto options and "file data" crypto options.

How are these options set in gocryptfs and what are available/valid options?

Looking at gocryptfs CLI documentations,i only see one option " -aessiv" but it does not say it accepts which one among the two and no discussion on what are available options.

It will be nice if gocryptfs will have a command to print all supported crypto options.

[1] https://github.com/bailey27/cppcryptfs

**Comment by rfjakob** [comment]
Looking at the cppcryptfs readme:

> You can choose to have your file names encryped using AES256-EME or not to encrypt the file names (plain text).

This corresponds to `-plaintextnames` in gocryptfs

> You can choose between AES256-GCM or AES256-SIV (RFC 5297) for file data encryption.

This corresponds to `-aessiv` in gocryptfs

@bailey27 I tried to run https://github.com/bailey27/cppcryptfs/releases/tag/1.4.0.6 on a Win 7 64bit box to look at the drop-down menus mentioned above. It would not start (when run from the command line, it returns immediately without any output), have I missed a run-time dependency?

**Comment by mhogomchungu** [comment]
gocryptfs 1.4.2 doesnt seem to like "-aessiv" option.

```
[ink@mtz ~]$ /usr/bin/gocryptfs --init -aessiv AES256-GCM -plaintextnames -q  "/home/ink/www" 
Invalid cipherdir: stat /home/ink/AES256-GCM: no such file or directory
[ink@mtz ~]$ 

```

**Comment by rfjakob** [comment]
-aessiv takes no argument

**Comment by mhogomchungu** [comment]
:-)

I guess i keep expecting a way to set arbitrary number of options  whereas gocryptfs is designed to have only two options,the default and a way to switch to a default's alternative.

Will close this one since i got what i wanted and proof is below.

![screenshot_20171116_153741](https://user-images.githubusercontent.com/3496115/32891807-12f979cc-cae5-11e7-92c0-81ae0f741c56.png)

![screenshot_20171116_154433](https://user-images.githubusercontent.com/3496115/32891816-1ad48006-cae5-11e7-985a-d71eedf56e1d.png)

**Comment by rfjakob** [comment]
Actually I hoped that it could be default-fits-all, but reverse mode broke that ;)

**Comment by mhogomchungu** [comment]
just run cppcryptfs and it run fine here on 64 bit windows 10.

Options for" File name"s are "AES256-EME" and "Plain text".

Options for "File data" are "AES256-GSM" and "AES256-SIV"
