### ISSUE TITLE
Faster `tar xzf linux-3.0.tar.gz`

### ISSUE THREAD

**Issue by rfjakob** [rfjakob/gocryptfs#16]
`tar xzf linux-3.0.tar.gz` is my canonical small-file benchmark. Gocryptfs takes 2x the time compared to EncFS. 
Looking at the cpu profile, this is caused by heavy GC activity that originates in go-fuse. For each created file, an inode object is allocated. Recycling inode objects could reduce GC pressure considerably.

**Comment by kofalt** [comment]
The new(ish) [sync.Pool](https://golang.org/pkg/sync/#Pool) may be of significant help here.

**Comment by rfjakob** [comment]
Pool looks awesome! Is it already in Go 1.3?

**Comment by kofalt** [comment]
I had a look, and in go 1.3.3 this ran without error:

```go
package main

import (
	"sync"
)

func main() {
	p := sync.Pool{
		New: func() interface{} {
			return nil
		},
	}
	p.Get()
}
```

It looks like it was [added in 1.3](https://golang.org/doc/go1.3#library).

**Comment by rfjakob** [comment]
Fixed by https://github.com/hanwen/go-fuse/pull/91

**Comment by rfjakob** [comment]
Merged as https://github.com/hanwen/go-fuse/commit/c4b6b7949716d13eec856baffc7b7941ae21778c .
