### ISSUE TITLE
Slowdown copy files into gocrypt directory

### ISSUE THREAD

**Issue by Kekskruemel** [rfjakob/gocryptfs#160]
Hi,

sadly I have slowdown during copy of large files into a gocrypt directory.
RAM and CPU is barely used.

It slow down from ~100MB/S to 2MB/S goes back up to full speed some time and again slow down.

If I copy the files into a non crypted directory all is fine.
How can I troubleshoot at best ?

Using unraid 6.3.5 on a hp microserver g8.

Thx!

**Comment by Aikhjarto** [comment]
@Kekskruemel What HDD are you using? This is the typical behavior of HDDs using SMR, like the Seagate Archive.

**Comment by rfjakob** [comment]
Good point, can you look at the "%util" column in

iostat -x 1 -d

while it is slow? If 100%, we are blocked by the disk.

Otherwise may be this kernel bug, what version do you run? https://github.com/rfjakob/gocryptfs/issues/11

**Comment by Kekskruemel** [comment]
Hi,

thx for the fast answer drive is a Samsung HD204UI

%util says 100.00 So it's the drive not the controller ? 

I am planning to buy new drives. Which Feature is here required to fix the problem ?

Thx !

**Comment by Aikhjarto** [comment]
The Samsung HD204UI is known for its large access times.
Large access times reduce the throughput significantly when you have lots of small files.

**Comment by rfjakob** [comment]
I wonder why it is fast without gocryptfs, though. How do you copy the files?

Nfs -> gocryptfs -> ext4 -> samsung hd?

**Comment by Kekskruemel** [comment]
Tested via 

local copy to the same disk with rsync and via nfs share.

Both are fast if I copy into a non crypted folder and have alowdowns with the crypted one.

I use

**Comment by Kekskruemel** [comment]
btrfs.

Sorry weiting on phone xD

**Comment by rfjakob** [comment]
No problem :)

I have seen slowdowns with Btrfs before, can you try mounting with

-noprealloc

This fixed the issue at https://github.com/rfjakob/gocryptfs/issues/63

**Comment by Kekskruemel** [comment]
./gocryptfs -noprealloc cipher plain

same problem :/ I can switch the fs on one disk for testing.

**Comment by rfjakob** [comment]
Hmm. gocryptfs uses 128kib writes (kernel limit for FUSE), can you compare with

dd if=/dev/zero of=foo bs=128k

?

**Comment by Kekskruemel** [comment]
dd if=/dev/zero of=foo bs=128k
^C48174+0 records in
48174+0 records out
6314262528 bytes (6.3 GB, 5.9 GiB) copied, 73.5896 s, 85.8 MB/s

**Comment by rfjakob** [comment]
Is it stable at 85mb/s? You can see it in iostat, it has a write speed column. Maybe use "-m" to get mb/s instead of kb/s

**Comment by Kekskruemel** [comment]
Ok something new.

If I use rsync --progress source file to copy into the directory and to see the speed there is something very interesting.

I can see high MB/s in iostats if rsync show low speed and low MB/s in iostat when rsync show high speeds is this caching in some way ?

**Comment by Kekskruemel** [comment]
Hmm unraid 6.4.0 rc 13 fixed the problem for me.

They changed something with the buffer in the betas. Maybe this fixed the problem.

Improved shfs/mover (-rc1)
 
The LimeTech user share file system (shfs) has been improved in two areas.  First, we now make use of FUSE read_buf/write_buf methods.  This should result in significant throughput increases.  Second, the mover script/move program no longer uses rsync to move files/directories between the cache pool and the parity array.  Instead the move program invokes a new shfs ioctl() call.  This should result in complete preservation of all metadata including atime and mtime.

**Comment by rfjakob** [comment]
Good to hear that it's fixed, closing the ticket.

**Comment by wmchris** [comment]
It seems like this issue was not fixed. He just didn't rely on rsync anymore.
I have the same issue: rsync will extremly slow down the whole machine. 
NFS (host EXT4) <-> GCFS. Starts with 80mb/s, ends with 2mb/s. Gradually slowing down.
Has nothing to do with the NFS, also slows down when running directly on the internal SSD.

Using encfs in the same setup has no problem, so i doubt it has something to do with fuse or the os.

Strange behaviour: the whole system slows down extremly, up to being completly unresponsive. Immediately recovers when killing the rsync command.
