### ISSUE TITLE
Extremely long symlinks cannot be handled in reverse mode

### ISSUE THREAD

**Issue by slackner** [rfjakob/gocryptfs#167]
This is not really a critical issue, however it might be useful to document such limitations somewhere and use more meaningful error messages/catch this explicitly.

**Steps to reproduce:**

1. Mount a regular reverse mount point
2. Create a symlink where the target contains 4095 bytes of data (maximum length of ext4)
3. Try to access the corresponding link in the reverse mount - the symlink appears, but doesn't have a target assigned.

GoCryptFS throws the error message:
```
2017/11/23 21:15:58 writer: Write/Writev failed, err: 22=invalid argument. opcode: READLINK
```

The problem is that the encryption and base64 encoding adds a lot of overhead, and the data is apparently too big - not just for ext4, but also for FUSE in general?

**Comment by rfjakob** [comment]
Looks like we return too much data to the kernel, which rejects it with EINVAL. We should rather return ENAMETOOLONG ourselves. I'll take a look

**Comment by slackner** [comment]
Thanks!
