### ISSUE TITLE
Missing check for plaintextnames in many FUSE callbacks

### ISSUE THREAD

**Issue by slackner** [rfjakob/gocryptfs#174]
**Steps to reproduce:**

1. Create a regular GoCryptFS mount point in forward mode and with `-plaintextnames`
2. In the mount point directory try to run `touch gocryptfs.longname.XXX`

This fails with the error `No such file or directory`, but should actually succeed. The problem is that many FUSE calls do not explicitly check if `plaintextnames` is set.

**Comment by slackner** [comment]
On the first sight this affects the following functions:

* [ ] Create
* [ ] Mknod
* [ ] Unlink
* [ ] Rename
* [ ] Link

**Comment by slackner** [comment]
I fear this one was closed a bit too early. Mknod and Unlink are fixed now, but there might be three other functions affected by the same problem. Should I open new bugs for them?

**Comment by rfjakob** [comment]
Was auto-closed through the commit message i guess, just re-open it

**Comment by slackner** [comment]
I would, but apparently I don't have permission to reopen myself.

**Comment by rfjakob** [comment]
Hmm will check if i can allow that somehow
