### ISSUE TITLE
Using gocryptfs directly as filesystem

### ISSUE THREAD

**Issue by sebastianbauer** [rfjakob/gocryptfs#175]
Hi,

I'm looking for an encrypted filesystem to use it with `golang.org/x/net/webdav` or even directly for storing data.

Is there an easy way to use gocryptfs independently or is it too tight coupled with go-fuse?

TIA

**Comment by rfjakob** [comment]
You mean instead of

User request -> FUSE -> go-fuse -> gocryptfs -> ext4

you want

User request -> [some go code] -> gocryptfs -> ext4

?

**Comment by sebastianbauer** [comment]
Exactly. To have an interface like os.* to handle an encrypted filesystem.

**Comment by rfjakob** [comment]
Could work, actually. The package is not exported right  now, but you can call into  https://github.com/rfjakob/gocryptfs/blob/master/internal/fusefrontend/fs.go

**Comment by sebastianbauer** [comment]
Nice. I'll give it a try. Thx. 👍
