### ISSUE TITLE
MacOS: Use new *at functions introduced in 10.10?

### ISSUE THREAD

**Issue by rfjakob** [rfjakob/gocryptfs#181]
Looks like x/sys/unix has added native versions for most of what we have in syscallcompat/emulate.go in commit https://github.com/golang/sys/commit/c4489faa6e5ab84c0ef40d6ee878f7a030281f0f .

Tracking ticket: https://github.com/golang/go/issues/14458

**Comment by rfjakob** [comment]
Acc. to the ticket these function were introduced in MacOS 10.10 Yosemite. This was released in [October 2014](https://en.wikipedia.org/wiki/MacOS_version_history#Version_10.10:_"Yosemite"). Should be long enough for users to have upgraded.

**Comment by slackner** [comment]
Not sure how many users are affected, but at least for the Wine project there were frequently users requesting builds for < 10.8. ;) It probably makes sense to keep the emulation code as a fallback code path, or what do you think?

**Comment by rfjakob** [comment]
I looked at the visitor stats of the gocryptfs website, unfortunately the OS version breakdown is not detailed enough. Maybe I can script something. But it's plausible that people are stuck on older MacOS versions because their hardware has been EOL'd by Apple.

**Comment by rfjakob** [comment]
FreeBSD now also has them: https://github.com/golang/sys/commit/b892924b68aa53038e8a55b255ee0d8391e8eec5

**Comment by rfjakob** [comment]
Found a way to extract the data. Only looking through one week of logs we already have 10_9_2 and 10_6_8 in the mix:
```
$ cd /var/log/apache2/nuetzlich.net/
$ zcat *.gz | cat *.log *.1 | grep "Mac" | csvtool -t " " format '%(10)\n' - | sort -u
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5 (Applebot/0.1; +http://www.apple.com/go/applebot)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36 QQBrowser/4.1.4132.400
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0.2 Safari/604.4.7
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_8; rv:44.0) Gecko/20100101 Firefox/44.0
Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1

```

**Comment by rfjakob** [comment]
Let's not do it.
