### ISSUE TITLE
Enable mounting to "/Volumes" on macOS

### ISSUE THREAD

**Issue by alexanderharm** [rfjakob/gocryptfs#194]
Right now running `gocryptfs encdir /Volumes/encdir` errors out. However, osxfuse automatically creates the `encdir` if mounted to `/Volumes` because this would require `root` permissions which the user might not have.

I guess `mount.go` needs to be modified to not check the directory existence when the mount path matches `/Volumes/*` on macOS.

I'm willing to write a PR myself but I'm a total Go newbie. Not sure that these are the only critical references in the source:
https://github.com/rfjakob/gocryptfs/blob/a4dff6aea0b761a49ba3f3b6f25b7442c846afcf/mount.go#L38-L65

**Comment by rfjakob** [comment]
Sounds like a good idea. I can implement this, can you test?

**Comment by alexanderharm** [comment]
Sure.

**Comment by rfjakob** [comment]
Pushed to https://github.com/rfjakob/gocryptfs/commits/macos_volumes , MacOS binary attached - could you test? Binary: [gocryptfs.gz](https://github.com/rfjakob/gocryptfs/files/1637007/gocryptfs.gz)

**Comment by alexanderharm** [comment]
It creates the dir in Volumes but it is not mounted in Finder. I will read some more tonight and come back.

**Comment by alexanderharm** [comment]
@rfjakob I tested a bit more and it works perfectly fine. However I noticed two things:

* osxfuse always creates the dir even if several levels don't exist. So on macOS one could completely omit the dirstat (e. g. `gocryptfs cipher ~/this/path/does/not/exist` works).

* passing fuse options via `-o` doesn't work (e. g. `-o local`)

**Comment by alexanderharm** [comment]
It might also make sense to pass the following mount options on macOS to avoid the creation of these additional files:

* noapplexattr
* noappledouble

**Comment by rfjakob** [comment]
Do you get an error when passing options via `-o` ?

**Comment by rfjakob** [comment]
Oh, you have to use `-ko` !

**Comment by alexanderharm** [comment]
```bash
gocryptfs test /Volumes/Test -o local
Wrong number of arguments (have 3, want 2). You passed: "test" "/Volumes/Test" "-olocal"
Usage: gocryptfs [OPTIONS] CIPHERDIR MOUNTPOINT [-o COMMA-SEPARATED-OPTIONS]
```

Same result with `-ko`.

**Comment by rfjakob** [comment]
```
$ gocryptfs -ko local a b
Password: 
[...]
```

**Comment by alexanderharm** [comment]
Great!

**Comment by rfjakob** [comment]
I agree, it's not explained very clearly. How about this: https://github.com/rfjakob/gocryptfs/commit/277ad087ffdc59e352c2e554caedc7a7796bbd2d ?

With https://github.com/rfjakob/gocryptfs/commit/bac7ef4834fc3d0536d10e9b2b8823d41235be0c , gocryptfs continues if the mountpoint does not exist, for all paths. I'll declare this DONE :)

**Comment by alexanderharm** [comment]
Great. Thank you very much for your efforts.
