### ISSUE TITLE
Solution for Directory IV Poisoning

### ISSUE THREAD

**Issue by fulldecent** [rfjakob/gocryptfs#195]
Threat model Dragon: https://nuetzlich.net/gocryptfs/threat_model/#gocryptfs-audit

> In gocryptfs, each directory gets a gocryptfs.diriv file on directory creation. This file contains the random DirIV for file name encryption for this directory. It makes sure identical file names generate different ciphertext in each directory.

> However when a directory is created, Dragon can immediately replace the gocryptfs.diriv file with a copy from another directory. When the DirIV is identical, identical file names generated identical ciphertext, so Dragon can see if a file name exists in both directories.

There is a technical solution to this problem. 

```
                          [ Directory path ]
                                   |
                                   V
[ gocryptfs.diriv ] <--> [ two-way encryption ] <--> [ DIRIV ]

```

This prevents the adversary from choosing your DIRIV and the problems that causes.

The novelty here is that you can still do directory moves without recalculating all file contents.

**Comment by fulldecent** [comment]
Reading further, this also seems to solve threat model Mallory.

**Comment by rfjakob** [comment]
How would renaming a directory work?

**Comment by fulldecent** [comment]
1. Read gocryptfs.diriv and decrypt using old path to get DIRIV
2. Move directory
3 Encrypt DIRIV using new new path and save to gocryptfs.diriv

**Comment by danim7** [comment]
What about subdirectories? You shall do the same recursively, and that could be quite costly for big filesystems.

**Comment by rfjakob** [comment]
@fulldecent I think this works. This looks like a very good idea.

> The novelty here is that you can still do directory moves without recalculating all file contents.

**Comment by rfjakob** [comment]
@danim7 The actually used diriv stays the same. This idea just adds a step to verify that the gocryptfs.diriv is in the right directory (and has not been moved around or copied - decryption would fail in this case).

**Comment by fulldecent** [comment]
@danim7 You're right, sorry I should have thought this through more.

----

Version 2 proposal:

* The symmetric key is [name of the directory, decrypted parent directory's DIRIV]

**Comment by danim7** [comment]
@fulldecent Version 2 looks promising, nice idea !

**Comment by rfjakob** [comment]
We'd have to decrypt all diriv's starting from the root - but that's not a big problem.

However, I don't think it helps against the "Mallory" case. He can still replace a file he has plaintext access to with another file's content.

**Comment by danim7** [comment]
@rfjakob I'm not sure to understand the first proposal though... in step 3 you are actually saving to gocryptfs.diriv ... what am i missing ?

**Comment by fulldecent** [comment]
@danim7 The initialization vector is the same. However that vector would now be encrypted deterministically using the file path.

Or in other words, we are no longer leaking IVs into the cipher text.

**Comment by fulldecent** [comment]
Naturally the same approach works with file renames. Currently the File ID is leaked in the ciphertext. This allows O(1). But I don't know if this is useful, because O(1) might not be fast enough [not sarcasm].

**Comment by rfjakob** [comment]
I'm not sure if the extra complexity is worth it, to be honest. I find the Dragon case not very interesting - it is difficult to perform, and you get little info out of it. We agree that it does not help against Mallory, I guess?

About the file id, I would not want to rewrite parts of a file during a rename. If you crash at the right instant, you can lose the file, which is not acceptable IMO.

**Comment by fulldecent** [comment]
Proposal 3 solves the Mallory problem for single file renames. Because when Mallory moves the file it won't be valid at the new location.

But then also you again you get risk of data loss on crash.

---

Fun discussion, thank you, but don't think this is this is a fundamental tradeoff we don't want, so closing the issue.

**Comment by rfjakob** [comment]
If this is implemented it should be **on** for all newly created filesystem. I think users should not have to think about which flags to pass, but get the best possible configuration automatically.

The other side of this is: I think it should only be implemented if it makes sense for most users. At the moment it looks like a "no" for me, because of the format change, and the extra complexity.
