### ISSUE TITLE
Release Announcements

### ISSUE THREAD

**Issue by rfjakob** [rfjakob/gocryptfs#196]
If you want to get notified of new gocryptfs releases, subscribe to this bug.

**Comment by rfjakob** [comment]
gocryptfs v1.4.3 has been released: https://github.com/rfjakob/gocryptfs/releases/tag/v1.4.3

**Comment by rfjakob** [comment]
gocryptfs v1.4.4

**Comment by rfjakob** [comment]
gocryptfs v1.5 has been released.

**Comment by rfjakob** [comment]
Seems that there is no too much interest in getting release info through a github ticket ;)

As nobody has subscribed in 10 months, I'll close this. Release info will, as always, appear in the README and via git tags.

**Comment by yahesh** [comment]
Uhm. I actually subscribed to this and received mails whenever something has been posted in here. Dunno why you think that no-one reads this thread?

**Comment by rfjakob** [comment]
Heh. The "1 participant" (only myself) on the sidebar made me think that. But apparently this does not count people who are subscibed but have not posted. Ok, I'll keep this alive.

First thing: The missing v1.6 announcement:

gocryptfs v1.6 has been released on 2018-08-18.

**Comment by rfjakob** [comment]
gocryptfs v2.0-beta3 has been released

**Comment by rfjakob** [comment]
https://github.com/rfjakob/gocryptfs/releases/tag/v2.0-beta4

**Comment by rfjakob** [comment]
v2.0 final https://github.com/rfjakob/gocryptfs/releases/tag/v2.0

**Comment by rfjakob** [comment]
https://github.com/rfjakob/gocryptfs/releases/tag/v2.0.1

**Comment by rfjakob** [comment]
Looks like you can now (well, since [late 2018](https://github.blog/changelog/2018-11-27-watch-releases/)) subscribe to releases via the "Watch" button (see screenshot below). I'm closing this ticket as it's obsoleted by the built-in "Watch" feature now.

![image](https://user-images.githubusercontent.com/286847/120980727-30481c80-c777-11eb-8757-390971352da5.png)
