### ISSUE TITLE
GoCryptFS questions and more information request

### ISSUE THREAD

**Issue by dakkusingh** [rfjakob/gocryptfs#2]
Hi rfjakob,
Thank you for your replies in my ENCFS thread here: https://github.com/vgough/encfs/issues/122. I am delighted to test GoCryptFS on OSX and provide some feedback. 

I had also read about GoCryptFS in a few reddit threads too and was curious to know more, I hadnt realised you were the author of this :)

I have a few questions, I hope you dont mind:

1) Can filename/foldername encryption be disabled? I only want to encrypt the contents.

2) is it possible to decrypt just one file without having to download the entire folder? This is possible with ENCFS if you disable external IV chain. This is a very useful feature if you just want to download individual files / folders from the cloud and decrypt them.

3) Is it possible to store the keyfile outside of the encrypted folder? Like it is with ENCFS

4) The encryption logic seems very similar to https://github.com/cryptomator/cryptomator, are there any differences/similarities that you are aware of? (I am not that familiar with encryption)

Thanks

**Comment by pepa65** [comment]
There seems to be no man-file or other documentation, so I have similar questions.
1. see above
2. Is reverse mounting possible? Ie. mount a normal folder and come up with a fuse encrypted one?
3. see above

**Comment by rfjakob** [comment]
Testing on OSX would be wonderful!

Questions:

@dakkusingh
1) Haha, I did not see this one coming ;) No, not at the moment.
I guess the use case is that you want to download single files from Dropbox, and with encrypted filenames you obviously cannot choose the right one.
I will add a parameter, probably `--plaintextnames`, to enable this.

2) Yes. Every file is independent.

3) Is planned, but there is no parameter yet. For now, you can use a symlink to achieve the effect. (store the gocryptfs.conf somewhere else, place a symlink in the encrypted directory).

4) I did not know about cryptomator until now. The crypto indeed looks similar.
The main difference I see right now is that cryptomator uses WebDAV while gocryptfs uses FUSE to provide access to the decrypted files.
This means that cryptomator works on Windows (no FUSE available) but also that it will be a lot slower than gocryptfs.

@pepa65
The command-line parameter are documented in the help text only at the moment, I have added that to the repo at https://github.com/rfjakob/gocryptfs/blob/master/USAGE.txt

2) No, and this is not planned at the moment. The thing is, AES-GCM (the encryption mode that gocryptfs uses) needs a random value for each block. For forward encryption, this random value is stored on disk inside the encrypted files. For reverse mode, there is no place to store that value.

**Comment by pepa65** [comment]
@2 Thanks for replying and for adding the USAGE.txt. I see about gocryptfs being non-reversable... Love the "reverse" feature, but don't like the security issues of encfs.

**Comment by pepa65** [comment]
While we're asking questions, because it's Go, could it be made to run on Windows as well? (Cross-platform support is an attractive feature.)

**Comment by rfjakob** [comment]
The problem with windows is that it does not have FUSE support. Linux has
it built-in and Mac has the OSXFuse project.
On windows, the only thing i am aware of is http://encfsmp.sourceforge.net/
. They SOMEHOW managed to get encfs (which also uses FUSE) running on
windows, using a closed-source windows kernel driver and lots of black
magic.

**Comment by dakkusingh** [comment]
Thanks rfjakob for the prompt responses. I am going to create a couple of standalone issues for the requests above so we can track these better..

**Comment by rfjakob** [comment]
Thanks @dakkusingh for creating the tickets. I am replying to them individually and closing this one.
