### ISSUE TITLE
test.bash fails on CentOS 7

### ISSUE THREAD

**Issue by portnoy** [rfjakob/gocryptfs#20]
**~/src/github.com/rfjakob/gocryptfs/test.bash**
```
gocryptfs v0.9-rc1-2-g37a9b4c; on-disk format 2
?   	github.com/rfjakob/gocryptfs	[no test files]
--- FAIL: TestDirOverwrite (0.00s)
	main_test.go:351: rename /tmp/gocryptfs_main_test/plain/DirOverwrite1 /tmp/gocryptfs_main_test/plain/DirOverwrite2: file exists
FAIL
FAIL	github.com/rfjakob/gocryptfs/integration_tests	2.070s
ok  	github.com/rfjakob/gocryptfs/internal/configfile	0.796s
ok  	github.com/rfjakob/gocryptfs/internal/contentenc	0.009s
ok  	github.com/rfjakob/gocryptfs/internal/cryptocore	0.006s
?   	github.com/rfjakob/gocryptfs/internal/fusefrontend	[no test files]
ok  	github.com/rfjakob/gocryptfs/internal/nametransform	0.006s
?   	github.com/rfjakob/gocryptfs/internal/toggledlog	[no test files]
ok  	github.com/rfjakob/gocryptfs/openssl_benchmark	0.006s
```
I've also attached the test.bash -v output in case it is more helpful:
[gocrypyptfs.txt](https://github.com/rfjakob/gocryptfs/files/175125/gocrypyptfs.txt)

I'm running CentOS 7.2  3.10.0-327.4.5.el7.x86_64 .

Thank you

**Comment by rfjakob** [comment]
Could you remove the "`//`" in lines 60 and 61 in https://github.com/rfjakob/gocryptfs/blob/master/integration_tests/helpers.go and run test.bash -v again? This should give much more output.

**Comment by rfjakob** [comment]
db72fcea41f01f24ac3edb1cbf86d6b0be60f137 has fixed several issues I found during fsstress testing, could you test again with latest master?

**Comment by portnoy** [comment]
Unfortunately, I hit another error preventing me from re-testing:
git -C is not supported on my system. I'm running CentOS7 and 
```
git --version
git version 1.8.3.1

```

So, I'm getting 
```
bash -x ./test.bash
+ set -eu
++ dirname ./test.bash
+ cd .
+ source build.bash
++ set -eu
+++ dirname ./test.bash
++ cd .
+++ git describe --tags --dirty
++ GITVERSION=v0.9-2-g4d79fba
+++ git -C /home/eugene/go/src/github.com/hanwen/go-fuse rev-parse --short HEAD
Unknown option: -C

```
Should probably open a separate issue for this?

**Comment by rfjakob** [comment]
Nah, fixed that one right away.

**Comment by rfjakob** [comment]
How is it going? Did you try again?

**Comment by portnoy** [comment]
This is what I'm getting with the recent code:
```
./test.bash
gocryptfs v0.10-rc3-5-g30f0ae3; on-disk format 2; go-fuse 1628b02
?   	github.com/rfjakob/gocryptfs	[no test files]
--- FAIL: TestDirOverwrite (0.00s)
	main_test.go:351: rename /tmp/gocryptfs_main_test/plain/DirOverwrite1 /tmp/gocryptfs_main_test/plain/DirOverwrite2: file exists
FAIL
FAIL	github.com/rfjakob/gocryptfs/integration_tests	1.458s
ok  	github.com/rfjakob/gocryptfs/internal/configfile	0.705s
ok  	github.com/rfjakob/gocryptfs/internal/contentenc	0.003s
ok  	github.com/rfjakob/gocryptfs/internal/cryptocore	0.003s
?   	github.com/rfjakob/gocryptfs/internal/fusefrontend	[no test files]
ok  	github.com/rfjakob/gocryptfs/internal/nametransform	0.002s
ok  	github.com/rfjakob/gocryptfs/internal/prefer_openssl	0.002s
ok  	github.com/rfjakob/gocryptfs/internal/stupidgcm	0.272s
?   	github.com/rfjakob/gocryptfs/internal/toggledlog	[no test files]

```
Attaching -v output as well.
[gocryptfs.test.txt](https://github.com/rfjakob/gocryptfs/files/287493/gocryptfs.test.txt)

**Comment by rfjakob** [comment]
Finally go around to set up a VM with CentOS 7. The cause seems to be XFS. It surprisingly returns a different error when you try to overwrite a non-empty directory with a directory.

If you do this in ext4

    $ cd $(mktemp -d) ; mkdir foo bar bar/foo ; touch bar/foo/file ; mv foo bar

you get

    mv: cannot move 'foo' to 'bar/foo': Directory not empty

But on XFS you get

    mv: cannot move ‘foo’ to ‘bar/foo’: File exists

With commit e994ffa27d5c, gocryptfs now handles both cases and the tests pass. Thanks again for reporting!
