### ISSUE TITLE
macOS: Homebrew formula is available

### ISSUE THREAD

**Issue by alexanderharm** [rfjakob/gocryptfs#202]
As of today `gocryptfs` is available via Homebrew.

To install Homebrew follow the guidelines here: https://brew.sh/

To install `gocryptfs` do

```bash
brew install gocryptfs
```

@rfjakob: You might want to mention this in the docs.

**Comment by rfjakob** [comment]
Awesome! I have added it to https://nuetzlich.net/gocryptfs/quickstart/ .
