### ISSUE TITLE
Stuck building on Void Linux

### ISSUE THREAD

**Issue by pepa65** [rfjakob/gocryptfs#209]
I'm trying to build gocryptfs on Void Linux. Got stuck here after `build.bash`:
```
# pkg-config --cflags libcrypto
Package libcrypto was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcrypto.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcrypto' found
pkg-config: exit status 1
```
I have libcrypto41 (other version in their repo: 37 and 38) and libssl43 (also available: 38 and 39). In `/usr/lib/pkgconfig` there is nothing related to libcrypto. So I am missing `libcrypto.pc`. Is there any workaround for this or does it just not build on Void?

**Comment by rfjakob** [comment]
Can you try this?

```diff
--- a/internal/stupidgcm/stupidgcm.go
+++ b/internal/stupidgcm/stupidgcm.go
@@ -5,7 +5,7 @@
 package stupidgcm
 
 // #include <openssl/evp.h>
-// #cgo pkg-config: libcrypto
+// #cgo LDFLAGS: -lcrypto
 import "C"
 
 import (
```

Otherwise, you can always `./build-without-openssl.bash` which does not depend on libcrypto.

**Comment by pepa65** [comment]
That did the trick! Thanks a lot.

**Comment by rfjakob** [comment]
On macos there is no advantage with openssl
 I recommend to use

    ./build-without-openssl.bash

**Comment by WindProphet** [comment]
I done well, thanks
