### ISSUE TITLE
Build-error "use of internal package not allowed" when using Go 1.6 on ArchLinux

### ISSUE THREAD

**Issue by tradem** [rfjakob/gocryptfs#21]
Hi,

im currently trying to compile gocryptfs by using the bash script which ends in the following build error:

```
package .
    imports github.com/rfjakob/gocryptfs/internal/configfile: use of internal package not allowed
package .
    imports github.com/rfjakob/gocryptfs/internal/contentenc: use of internal package not allowed
package .
    imports github.com/rfjakob/gocryptfs/internal/cryptocore: use of internal package not allowed
package .
    imports github.com/rfjakob/gocryptfs/internal/fusefrontend: use of internal package not allowed
package .
    imports github.com/rfjakob/gocryptfs/internal/nametransform: use of internal package not allowed
package .
    imports github.com/rfjakob/gocryptfs/internal/toggledlog: use of internal package not allowed
```

<code>go build</code> produces the same result.

Any hints or advice to overcome this build error. I am using Go 1.6.

BTW: Building with **gcc-go** results in 

```
could not determine kind of name for C.SSLv3_method
```

I installed _openssl_ (there is no extra dev-Packge for ArchLinux) before.

**Comment by rfjakob** [comment]
Looks like I missed a detail when I converted the packages to "internal",
and Go 1.6 is not happy about. I will take a look tomorrow!

**Comment by rfjakob** [comment]
Hmm. I cannot reproduce this, it builds just fine on my machine with Go 1.6. I have added Go 1.6 to the Travis build options, and it seems to work there as well: https://travis-ci.org/rfjakob/gocryptfs/jobs/120486918

**Comment by alphazo** [comment]
Same issue on ArchLinux. According to one member from the ArchLinux forum:
>  The problem is that it's looking for SSLv3, which Arch doesn't ship as it's old and insecure

For information ArchLinux currently ships with openssl 1.0.2.g-3.

**Comment by rfjakob** [comment]
I see. Maybe i can drop the dependency to spacemonkey and call openssl
directly.

**Comment by rfjakob** [comment]
Ok I have begun working on this, seems to be doable. Stay tuned, I think I can finish it next week.

**Comment by rfjakob** [comment]
I have just released gocryptfs v0.10-rc1 that has dropped the dependency to spacemonkeygo. Please give it a try!

**Comment by alphazo** [comment]
Thanks. It compiles just fine now under ArchLinux.

**Comment by alphazo** [comment]
FYI, gocryptfs can now easily be compiled & installed on ArchLinux via AUR.

https://aur.archlinux.org/packages/gocryptfs/
