### ISSUE TITLE
How to build gocryptfs static on Android.

### ISSUE THREAD

**Issue by babam86** [rfjakob/gocryptfs#210]
I have successfully built gocryptfs with command ./package-static.bash but the result is not static.

I use Termux https://play.google.com/store/apps/details?id=com.termux to build gocryptfs.

**Comment by rfjakob** [comment]
What do you get when you run `ldd gocryptfs` ? You should get
```
$ ldd gocryptfs
	not a dynamic executable
```

**Comment by babam86** [comment]
ldd gocryptfs
libc.so
libdl.so

**Comment by rfjakob** [comment]
Strange, because package-static.bash check the ldd return code:
https://github.com/rfjakob/gocryptfs/blob/a3694e0c073b686b33c7ba34508c6e18a5508dd5/package-static.bash#L8
Anyway, you can cross-compile and just copy the binary - check the crossbuild.bash script!

**Comment by babam86** [comment]
I built it directly on my Android device.

You can try it, to build gocryptfs on Android using Termux does not require root access.

**Comment by rfjakob** [comment]
Tried it, can confirm that it is not static.

**Comment by babam86** [comment]
What is the cause?

**Comment by rfjakob** [comment]
I don't know yet.

By the way, does mounting a gocryptfs filesystem work?

**Comment by babam86** [comment]
It works, fusermount and rooted device is required.

**Comment by rfjakob** [comment]
I tried cross-compiling for android on my PC, does not work:
```
$ CGO_ENABLED=0 GOOS=android go build -tags without_openssl
# github.com/rfjakob/gocryptfs
warning: unable to find runtime/cgo.a
```
Maybe Go on Android does not support compiling statically? This https://github.com/golang/go/issues/8877 seems to confirm that.

**Comment by rfjakob** [comment]
I guess that's the conclusion - Go on Android always needs libc

**Comment by kfaji** [comment]
So you where able to build it with termux.
I get linking errors.

What packages did you install?
And does it work? If I build it with Linux, I cannot mount it due to fuse error...

**Comment by mirfatif** [comment]
https://github.com/rfjakob/gocryptfs/issues/239#issuecomment-626144226

**Comment by bingoxo** [comment]
check out https://github.com/hardcore-sushi/DroidFS
