### ISSUE TITLE
Usage of /dev/random vs. /dev/urandom

### ISSUE THREAD

**Issue by yahesh** [rfjakob/gocryptfs#212]
While reading some parts of the code I saw that the creation of the masterkey may resort to reading [from /dev/random](https://github.com/rfjakob/gocryptfs/blob/master/internal/configfile/config_file.go#L54) which might be a bad idea, given that /dev/random - in contrast to /dev/urandom - may be blocking on systems like Linux.

For more details see for example https://www.2uo.de/myths-about-urandom/

P.S.: Maybe one should consider to stay away from using /dev/random and /dev/urandom completely as they may be maliciously linked to other sources of non-randomness which is why the [getrandom() syscall](https://www.systutorials.com/docs/linux/man/2-getrandom/) has been introduced.

**Comment by rfjakob** [comment]
Hehe, that's a complicated story. The reason why this exists are detailed in https://github.com/rfjakob/gocryptfs/pull/161 , but to summarize, /dev/random is only used if the user passes the "-devrandom" flag. In all other cases the getrandom syscall is used, as you have suggested.

**Comment by yahesh** [comment]
Ah, I see.

So reading from /dev/random is used because rand.Read() in Golang doesn't provide a possibility to set the GRND_RANDOM flag for the getrandom() syscall.

Hadn't seen that this has been purposefully introduced for embedded devices. My bad.

"Won't fix" seems appropriate then. :)

**Comment by rfjakob** [comment]
That function really needs a comment explaining why it exists
