### ISSUE TITLE
fuse / inotify support incomplete

### ISSUE THREAD

**Issue by mbiebl** [rfjakob/gocryptfs#215]
Version: 1.4.3
Debian sid

Hi,

my use case is, that I have two users, which share a nextcloud folder with a gocryptfs volume.
If userA adds/removes/moves/deletes files, those changes are not properly propagated to userB. If I have a nautilus window open, it doesn't get notified about these changes (via inotify) and I need to hit F5 to see that userA has created or moved or deleted files.

Interestingly enough, inotify seems to work when editing an existing file.
Say both userA and userB have file foo.txt open in gedit, and userA adds some changes, then a few seconds later, after the changes have been synced, gedit for userB will tell me that the file has been changed and offers to reload it.

**Comment by rfjakob** [comment]
Looking at https://github.com/libfuse/libfuse/wiki/Fsnotify-and-FUSE and [fuse_kernel.h](https://github.com/libfuse/libfuse/blob/21b55a05a158b1c225ba312529bc068cadd5431d/include/fuse_kernel.h) , `FUSE_FSNOTIFY` does not seem to be implemented (yet?)

**Comment by mbiebl** [comment]
hi @rfjakob, do you have an idea why the text editors notice when I modify an existing file, but nautilus does not detect when I create/delete files? If fsnotify does not work with fuse, how do the editors get the notification about the file change?

**Comment by rfjakob** [comment]
Not yet but I'll try to find out

**Comment by rfjakob** [comment]
I tested this - gedit does not pick up the change immediately. Only when you switch to the gedit window it will notify you. And it does that by reading the file timestamp - in other words, by polling for changes.

**Comment by mbiebl** [comment]
thanks for checking, @rfjakob 
I wasn't aware of this limitation of FUSE

**Comment by rfjakob** [comment]
I'm afraid the "solution" involves patching the kernel source and compiling yourself.

Does it work on kbfs?

**Comment by DiagonalArg** [comment]
Haven't gotten so far as to do that - might be beyond my capabilities.  I did find many people looking for a way, and ultimately having to rely on just regular polling.  I guess that's where I'm at.

**Comment by rfjakob** [comment]
I'm afraid with the stock linux kernel, we can't have inotify on FUSE filesystems. The function is not there in stock linux...

**Comment by MisterTea** [comment]
Can we submit a change to the Linux kernel upstream so that a future version would support inotify+fuse?

**Comment by TCB13** [comment]
Why is this closed? Is the problem fixed by now? Again the lack of inotify makes gocryptfs unsuitable for a lot of things.
