### ISSUE TITLE
Feature request: support for extended file attributes

### ISSUE THREAD

**Issue by rr-** [rfjakob/gocryptfs#217]
```console
rr-@tornado:~/test_gocryptfs_mountpoint$ touch test_file
rr-@tornado:~/test_gocryptfs_mountpoint$ attr -s key -V value test_file
attr_set: Operation not supported
rr-@tornado:~/test_gocryptfs_mountpoint$ setfattr -n key -v value test_file
setfattr: test_file: Operation not supported
```

:(

For a good start, these don't even need to be encrypted (as long as it's mentioned in the manpage).

**Comment by rfjakob** [comment]
Will try to get this done. Should be encrypted from the start, though, to avoid an opportunity for shooting oneself in the foot.

**Comment by rfjakob** [comment]
You are on Linux?

**Comment by rfjakob** [comment]
Implemented and merged to master. Both xattr names and values are encrypted.
