### ISSUE TITLE
Feature: Remove the need for gocryptfs.conf, with secure master password input

### ISSUE THREAD

**Issue by antofthy** [rfjakob/gocryptfs#218]
One of the things I do with EncFS is use the ENCFS6_CONFIG environment variable to read the config from a different location to the toplevel ".encfs6" file in the encrypted filesystem.  That is I don't store the config with the encrypted data.  Actually, the config is not even stored in a file but in a secure database along with the decryption password. The env var is used to specify a UNIX named pipe (fifo) which is used to give EncFS the config file. EncFS reads this file, once only, on startup, after which the named pipe is then deleted.

From what I can see GoCryptFS does not even need a config file at all, only the master password to use, which would be ideal.  Unfortunately you only provide the ability to give this critical information via the insecure command line!  Manpage even mentions how insecure this really is!

Please provide more secure means of passing the master password to GoCryptFS.  Either from a file (or named pipe that is read only once), or from a file descriptor (such as STDIN).

OR...  Provide the means to read the "gocryptfs.conf" from a user specified file (or pipeline), in the same way that EncFS does.   The Manpage lists no such options, or Environment Variables, to do this.

**Comment by rfjakob** [comment]
Check out "-config",
https://github.com/rfjakob/gocryptfs/blob/master/Documentation/MANPAGE.md

**Comment by antofthy** [comment]
TX.  Still it would be good to allow more secure input of the master key

**Comment by charles-dyfis-net** [comment]
Insofar as the config file can be a named pipe, `/dev/fd/...` link, &c., I'm hard-pressed to see how it's less secure than other methods.

**Comment by antofthy** [comment]
No not the config file..

Passing master key using...  -masterkey   With a secure input for that a
config file is not needed at all!

**Comment by rfjakob** [comment]
The problem is this: There's lots of settings that gocryptfs reads from the config file ([list](https://github.com/rfjakob/gocryptfs/wiki/Compatibility)). So when you mount with "-masterkey", all the settings stay at their default value. So when a new gocryptfs version with changed defaults (added features) comes along it will break.

**Comment by rfjakob** [comment]
You can now let gocryptfs read the masterkey from stdin by passing `-masterkey=stdin`, commit: https://github.com/rfjakob/gocryptfs/commit/9bc039a4bac6b51d9ebe116de5c311e90343a088

**Comment by antofthy** [comment]
Thank you.
