### ISSUE TITLE
Known limitation: Replacing a file with the same file will lead to problems when diffing rsync backups of the encrypted content

### ISSUE THREAD

**Issue by yahesh** [rfjakob/gocryptfs#220]
Hi there,

I started using gocryptfs to encrypt files and use `rsync` to backup the encrypted files and `diff -rq` to check the consistency of the backed-up files. While verifying the state of the backup with `diff -rq` I encountered several differences that `rsync` didn't catch while backing up the content.

By default `rsync` checks for the file size and the modified date to find modifications. As `rsync` didn't find any differences that meant that the modified date and the file size of the mismatching files where unaltered.

To countercheck whether the files are corrupt I mounted the original folder and the backed-up folder and checked them for differences with `diff -rq` as well. Here no differences could be found.

I remembered which steps I had done while filling the encrypted folder with content and learned what the problem at hand is: **When replacing a file in a mounted folder with the same file (e.g. when merging two folders with the same content into one) then the file name of the replaced file and the modified date of the file stay the same while the content of the file is completely reencrypted.**

IMHO this should be documented somewhere as a known limitation as it took me some time to understand the issue at hand which might be the case for other people as well that try to deduplicate files in a gocryptfs mount.

P.S.: Steps to reproduce the issue:
```bash
# create the necessary folders and a test file
mkdir test test-mount test-backup test-backup-mount
echo "test" >test.txt

# intialize and mount the test folder
gocryptfs -init test
gocryptfs --quiet test test-mount

# copy the test file into the mounted folder while retaining the timestamp
cp -p test.txt test-mount/

# rsync the encrypted folder to the backup folder
# will copy all files from test/ to test-backup/
rsync -aEP --delete test/ test-backup/

# copy the test file into the mounted folder again while retaining the timestamp
cp -p test.txt test-mount/

# update the backup folder via rsync of the encrypted folder
# will copy no files as file size and modified date are unaltered
rsync -aEP --delete test/ test-backup/

# diff the encrypted folder and the backup folder
# will find a diff because the file content differs
diff -rq test/ test-backup/

# mount the backup folder
gocryptfs --quiet test-backup test-backup-mount

# diff the mounted folder and the mounted backup folder
# will find no diff because the unencrypted file content does not differ
diff -rq test-mount/ test-backup-mount/
```

**Comment by rfjakob** [comment]
This is actually a feature: from the ciphertext, it is impossible to determine if two files contain the same plaintext.

**Comment by yahesh** [comment]
@rfjakob Yes, that's why this is not a bug report but something to consider when using rsync in conjunction with gocryptfs. I didn't think about this implication until I hit the mentioned problem during a restore test.

**Comment by lechner** [comment]
Is that phenomenon a limitation of the standard settings in `rsync`?

**Comment by yahesh** [comment]
@lechner `rsync` has the `-c` or `--checksum` parameter to overwrite files based on their checksum instead of their size and modified date. However, especially for remote backups over pure file transport connections (e.g. SFTP) this induces a major penalty as all files have to be downloaded to calculate the checksum. By default `rsync` only needs to `stat` the directories and files on the remote target which is a lot faster.

**Comment by rfjakob** [comment]
I would say the problem here is that doing `cp -p` lies about the modification time. rsync will then believe it the file has not been changed, while in fact it has been completele rewritten.

Not sure where to document this, maybe this ticket is good enough, as it will show up in search engines? Thanks for the detailed report!
