### ISSUE TITLE
Documentation: How to identify corrupted files

### ISSUE THREAD

**Issue by yahesh** [rfjakob/gocryptfs#221]
A benefit of gocrypt's reverse mode is that you get automatic integrity protection thanks to the AEAD encryption scheme without having to store additional checksum information. However, I couldn't find a documentation how best to identify corrupted files.

 I looked at what happens when a file gets corrupted by manually manipulating encrypted files. The easiest thing to identify corrupted files is to just call `file` on the corresponding files in the mounted directory. gocryptfs will produce read errors when the authenticated decryption of a file fails.

This way you can produce a list of corrupted files:
```bash
# find all files in a directory that produce some kind of error
find . -type f -exec file {} \; | grep "ERROR:"
```

P.S.: Each found file will produce an entry like:
```
./test.txt: ERROR: cannot read `./test.txt' (Input/output error)
```

**Comment by rfjakob** [comment]
Good idea, however, "file" does not read the whole file. So you will miss corrupt blocks in the middle of bigger files.

**Comment by yahesh** [comment]
@rfjakob Ah, yeah that might actually be true. I only tested this with smaller files. Maybe I'll find something that's more appropriate for bigger files.

**Comment by rfjakob** [comment]
The plan is to have a dedicated command, "gocryptfs -fsck", to do that (and a bit more). I have added your shasum snippet to https://github.com/rfjakob/gocryptfs/issues/191 , thanks!
