### ISSUE TITLE
Question: Moving files in gocryptfs

### ISSUE THREAD

**Issue by Lord-Simon** [rfjakob/gocryptfs#226]
I have a question regarding a file move in gocryptfs.

Let's say I have a folder ```A``` that is reverse-mounted onto folder ```B```.
The structure of ```A``` is ```/1/2/3/```, and the folder ```1``` contains a file named ```test.txt```.
Now I will copy the folder(contents) ```B``` somewhere else and mount it in forward mode onto folder ```C```.

As the documentation states, the reverse mode uses deterministic encryption and per se will derive the IV from the encrypted path. Which to say will have the ```gocryptfs.diriv``` up to folder ```/1/2/3/```.

And now the actual question. If I move the file ```test.txt``` in the ```C``` mount from the  folder ```/1/``` to ```/1/2/3/``` will it use the ```diriv``` that the folder provides for the filename encryption like in reverse mode ? 
And following from there, if I create the folder ```/1/2/3/4/``` will it use the deterministic method or the standard urandom stuff  for the ```diriv``` ?

Thanks in advance.

**Comment by rfjakob** [comment]
Hi!

On Fri, Apr 13, 2018, 21:52 Simon <notifications@github.com> wrote:

> I have a question regarding a file move in gocryptfs.
>
> Let's say I have a folder A that is reverse-mounted onto folder B.
> The structure of A is /1/2/3/, and the folder 1 contains a file named
> test.txt.
> Now I will copy the folder(contents) B somewhere else and mount it in
> forward mode onto folder C.
>
> As the documentation states, the reverse mode uses deterministic
> encryption and per se will derive the IV from the encrypted path. Which to
> say will have the gocryptfs.diriv up to folder /1/2/3/.
>
> And now the actual question. If I move the file test.txt in the C mount
> from the folder /1/ to /1/2/3/ will it use the diriv that the folder
> provides for the filename encryption like in reverse mode ?
>
Yes!

> And following from there, if I create the folder /1/2/3/4/ will it use
> the deterministic method or the standard urandom stuff for the diriv ?
>
No, it will create a random one

**Comment by rfjakob** [comment]
This just switches the encryption mode from aes-gcm to aes-siv. It has no effect on diriv

**Comment by rfjakob** [comment]
You may be interested in looking at https://github.com/rfjakob/gocryptfs/issues/108 . If you also want that feature, please comment there!
