### ISSUE TITLE
gocryptfs has anything to do with boxcryptor?

### ISSUE THREAD

**Issue by ccchan234** [rfjakob/gocryptfs#236]
from start of boxcryptor 1.x, they already say they are using encfs as their program have .encfs6.xml in the root.

now they upgraded to 2.x,
and in each of their folder, there is a folderkey.bch,
which I found in each gocryptfs has a .diriv !

is it just happening by chance?

I just worry if they "steal" the program and make it commercial...... thanks

**Comment by rfjakob** [comment]
Interesting! However, there is a changelog at https://www.boxcryptor.com/en/help/about/windows/ , and the first 2.x release seems to be older than gocryptfs:

> Version 2.0.400.116 (06/05/2013)

gocryptfs had its first version, v0.1, in 2015
