### ISSUE TITLE
https://nuetzlich.net/gocryptfs site is down?

### ISSUE THREAD

**Issue by ccchan234** [rfjakob/gocryptfs#237]
thank you

This site can’t be reached
nuetzlich.net took too long to respond.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_TIMED_OUT

**Comment by rfjakob** [comment]
Yes it is, unfortunnately. The datacenter (hetzner.com) where the site hosted is experiencing a power loss, https://www.hetzner-status.de/#8842

**Comment by rfjakob** [comment]
Still down - github mirror: https://github.com/rfjakob/gocryptfs-website/blob/master/docs/index.md

**Comment by ccchan234** [comment]
site is up and running now, thx
