### ISSUE TITLE
unstable with ocamlfuse?

### ISSUE THREAD

**Issue by ccchan234** [rfjakob/gocryptfs#238]
hi~

i tried ocamlfuse with gocryptfs,
i can mount and read the most outer folder's .txt file,
but when do deeper, seems it's not working/not stable?

it is a disadvantage as if in windows,
i am very ok with google file stream + cppcryptfs,
which give me encryption to unlimited space.

thanks~

**Comment by rfjakob** [comment]
We had a similar case with Amazon Cloud Drive ( https://github.com/rfjakob/gocryptfs/issues/71 ). In the end, the problems were all caused by bugs in the Amazon Cloud Drive clients, which would return garbage data in some cases.

**Comment by ccchan234** [comment]
so...

currently in linux, gocryptfs, g suit.

we cant use "file stream" alike function yet, rite? thx

**Comment by Nodens-** [comment]
Use rclone mount instead. It works perfectly fine with gocryptfs on top.

**Comment by ccchan234** [comment]
but have u tried rclone mount urself? is it read-only?
stable in read/write?

thx

**Comment by Nodens-** [comment]
Like I said it works perfectly. Read/write. I am using it for months with gocryptfs on top of it.

**Comment by rfjakob** [comment]
I don't think we can do anything about this on the gocryptfs side? Closing the ticket
