### ISSUE TITLE
android/mobile version?

### ISSUE THREAD

**Issue by ccchan234** [rfjakob/gocryptfs#239]
any idea on using gocryptfs/cppcryptfs data on android/mobile?

encfs enjoyed longer history so there are several FOSS or even commercial one for that.

ps: just ask, i am a layman.

thanks

**Comment by rfjakob** [comment]
No, sorry, Android development is not my cup of tea. I'll keep the ticket open so maybe somebody who wants to develop something sees that there is user interest.

**Comment by rfjakob** [comment]
I'll close this for now, looks like there are not too many volunteers...

**Comment by mirfatif** [comment]
Try this: [gocryptfs_static_aarch64_v1.7.1](https://forum.xda-developers.com/showpost.php?p=76462538&postcount=68) (with OpenSSL (libcrypto))

@rfjakob thanks for maintaining this wonderful project.

**Comment by dabeeeenster** [comment]
I have that static build working, and have an android build of fusermount from [here](https://forum.xda-developers.com/android/development/fusermount-android-rclone-mount-t3866652) but I get an fusermount error when i try and mount a folder. This is on a non-rooted Android device. Does it have to be rooted? Is there a command I can pass to gocryptfs that will just decrypt all the files as opposed to try and mount a directory?

I was using Termux to do all this as its the only way to run binaries on a non rooted phone as far as I can tell.

**Comment by mirfatif** [comment]
> Does it have to be rooted?

It's not possible to use FUSE on Android without root.

**Comment by bingoxo** [comment]
check out https://github.com/hardcore-sushi/DroidFS

**Comment by nikkoearion** [comment]
> Try this: [gocryptfs_static_aarch64_v1.7.1](https://forum.xda-developers.com/showpost.php?p=76462538&postcount=68) (with OpenSSL (libcrypto))
> 
> @rfjakob thanks for maintaining this wonderful project.



> Try this: [gocryptfs_static_aarch64_v1.7.1](https://forum.xda-developers.com/showpost.php?p=76462538&postcount=68) (with OpenSSL (libcrypto))
> 
> @rfjakob thanks for maintaining this wonderful project.
Agreed, thanks for working on this project!

Hi @mirfatif you wouldn't happen to have an armhf build for the newer gocrypt? Getting a bug in the 1.4 build that has been solved in later builds.

**Comment by lizhi1989** [comment]
Hi, may I know is there an option to use gocryptfs on android with data store on onedrive?

**Comment by araafroyall** [comment]
Use droidFS app which may help android users

**Comment by ccchan234** [comment]
> 

no, their author already said they don't want to arm race /w google on file structure, on the document provider.

**Comment by augreed** [comment]
> Use droidFS app which may help android users

DroidFS cannot mount encrypted folders on my SSD. Even with the latest 2.0 version.

**Comment by Mario-Eis** [comment]
> Use droidFS app which may help android users

There is also no way to mount my 3TB vault on my NAS SMB share. It's just local files ONLY.
