### ISSUE TITLE
Certificate expired on nuetzlich.net

### ISSUE THREAD

**Issue by lxp** [rfjakob/gocryptfs#24]
nuetzlich.net uses an invalid security certificate. The certificate expired on 2016-05-06 10:57. The current time is 2016-05-08 14:41.

**Comment by lxp** [comment]
Sorry, I guess I should have opened the issue on the gocryptfs-website repository.

**Comment by rfjakob** [comment]
Ohh that's bad. Never mind which repository, thank you very much for the report. Certificate has been renewed!

**Comment by rfjakob** [comment]
Well, I have that domain monitored by uptimerobot.com, and they claim the check certificate expiry here:
http://blog.uptimerobot.com/support-for-self-signed-ssl-certificates-and-how-https-urls-are-handled/ 
But if you read the comments below, the users have found out that it does not actually work. What a piece of junk.
