### ISSUE TITLE
Best practices and intended use write up

### ISSUE THREAD

**Issue by oblivian** [rfjakob/gocryptfs#241]
Hi,

I've been looking around for some documentation on best practices and intended use of gocryptfs.
E.g. is it intended for backups, cloud storage, both, etc?
I am looking for an alternative to ecryptfs for storing encrypted sensitive data in a u/p protected non-sensitive git repo. I.e. lots of non-sensitive code, but some sensitive config files...
And the gocryptfs.conf file, is it secret or can it be stored in "the cloud" together with the rest of the encrypted files?

Thanks! 

EDIT: Are you planning to release updated static binaries anytime soon? I was struggeling to make -masterkey=stdin work before I realised the option isn't implemented in v1.4.4.

**Comment by rfjakob** [comment]
Good idea, I should list some example use cases somewhere.

Yes, gocryptfs is intended for both cloud storage and backups, and also as a secure local storage if you don't want to run full-disk encryption.

What is "u/p"? If the password is strong, you can publish gocryptfs.conf along with the encrypted files.

About the next release, yes I think it's time to release 1.4.5. Within the next weeks!

**Comment by oblivian** [comment]
Thanks, and thanks for this wonderful piece of code. And a perfect tool in this "GDPR times"!
Our passwords looks something like this: 
`A$AcL@=Tx4NfUsH&C:^N5CHvQC,@g#r#`
Auto-generated and backed up from/in Keepass...

**Comment by rfjakob** [comment]
I meant, I don't know what the abbreviation "u/p" means ;)

As for password strength, I usually recommend at least 64 bits of entropy. Depending on the character set, this translates to these password lengths:

Character Set (number of different characters) | Password length for >= 64 bit of entropy
-- | -- 
`0-9` (10) | 20
`a-z0-9` (36) | 13
`A-Za-z0-9` (62) |  11
`A-Za-z0-9%$&/...` (95) |  10

gocryptfs uses *scrypt* password hashing. The [scrypt paper](https://www.tarsnap.com/scrypt/scrypt.pdf) includes this table that estimates the cost for cracking a password in one year:

![scrypt-table1](https://user-images.githubusercontent.com/286847/40873575-2b7c6436-6663-11e8-827c-ee327269d826.png)

With a 32-character random password, you are good :)

**Comment by rfjakob** [comment]
I have added the password strength info to the wiki as I believe it is helpful to users: https://github.com/rfjakob/gocryptfs/wiki/Password-Strength

**Comment by rfjakob** [comment]
Hi @bexelbie ! When you look at the changelog,

**Comment by bexelbie** [comment]
@rfjakob thank you for the information.  I've added a note to the wiki page.

**Comment by zell-mbc** [comment]
Talking use cases, is there a way to make the un-encrypted view of an encrypted folder available over the network?
My use case is a file server with encrypted files I'd like to mirror to a cloud storage account (OneDrive) 
while the machines on my network work with the un-encrypted files. Gocryptfs works fine when logged into the server but when I try to access the plain folder from a different machine (SAMBA) I only get an empty directory.

./gocryptfs /OneDrive/Encrypted /GoCryptFS/plain

/OneDrive/Encrypted -> synced with OneDrive
/GoCryptFS/plain -> Somehow made accessible over the network (SAMBA?)

**Comment by bexelbie** [comment]
FWIW, I created this wiki page: https://github.com/rfjakob/gocryptfs/wiki/Best-Practices

I suspect this issue can be closed unless I missed something here.  I don't know if @zell-mbc's qustion is resolved or not.

**Comment by rfjakob** [comment]
Thanks! Also I added some info here: https://nuetzlich.net/gocryptfs/quickstart/#cloud-storage
