### ISSUE TITLE
-exec vs -o exec

### ISSUE THREAD

**Issue by mhogomchungu** [rfjakob/gocryptfs#245]
Version 1.5 introduced options like ```-exec``` and ```-noexec``` and documentation says they are to be used as written but i noticed ```-o exec``` and ```-o noexec``` works just as well but this way of setting these options is not documented.

Is the latter supported way of setting these new options?

**Comment by rfjakob** [comment]
Yes, you can specify **all** options also via `-o`.

Check the manpage at https://github.com/rfjakob/gocryptfs/blob/master/Documentation/MANPAGE.md#-o-comma-separated-options :
> For compatibility with mount(1), options are also accepted as "-o COMMA-SEPARATED-OPTIONS" at the end of the command line. For example, "-o q,zerokey" is equivalent to passing "-q -zerokey".
