### ISSUE TITLE
Q: How to Reverse a Reverse?

### ISSUE THREAD

**Issue by geneticgrabbag** [rfjakob/gocryptfs#246]
I've created a reverse in order to backup files offline securely.
How can I then "reverse the reverse" so that I can see the original files?
This would be helpful if my laptop is stolen, I can copy the encrypted files back from cloud and then reverse mount them to get the originals.

Thanks in advance!

**Comment by rfjakob** [comment]
Hi! You can mount the encrypted folder like a normal gocryptfs filesystem to get the plaintext files.
