### ISSUE TITLE
Support of ACL

### ISSUE THREAD

**Issue by DjMotte** [rfjakob/gocryptfs#249]
Is it possible to have acl support?

May it's possible to get the same acl for the plain file as the crypted file has.

This would make it possible to use gocryptfs in a samba environment with more users and groups.

Bests,
Michael

**Comment by rfjakob** [comment]
Just being curious about the use cases, and how gocryptfs could support them.

Are you talking about having a Linux Samba server and Windows clients?

**Comment by DjMotte** [comment]
Yes indeed Linux Samba Server with windows clients.

It‘s planned to have some folders encrypted and to have their plain folders/subfolders shared to various users. And there under a common used share can be subfolders which are accessible to special users only.
Until a few weeks ago ecryptfs was used but there is an issue with long plain filenames > ~130 chars length. Since this is a must have it has counted the days of ecryptfs.
My research lead me to your project and I was very happy that all belongings matched except the acl.

Do you think there is a chance? I can offer myself as a tester 😄

Best regards,
Michael

Am 02.07.2018 um 22:34 schrieb rfjakob <notifications@github.com<mailto:notifications@github.com>>:


Just being curious about the use cases, and how gocryptfs could support them.

Are you talking about having a Linux Samba server and Windows clients?

**Comment by rfjakob** [comment]
Looks like ACL support for FUSE was merged into Linux in 4.9 ([commit](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/include/uapi/linux/fuse.h?id=60bcc88ad185d512f5718f2f8dcccb483ea8fb73)), so it does seem possible, at least.

**Comment by DjMotte** [comment]
Since I‘m a software developer too I know that the problem is in the detail. For me a solution to pass through the plain file ACL would be sufficient. For me it’s not necessary to have different ACL for the plain and encrypted file.

Bests
Michael

Am 02.08.2018 um 21:35 schrieb rfjakob <notifications@github.com<mailto:notifications@github.com>>:


Looks like ACL support for FUSE was merged into Linux in 4.9 (commit<https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/include/uapi/linux/fuse.h?id=60bcc88ad185d512f5718f2f8dcccb483ea8fb73>), so it does seem possible, at least.

**Comment by CTDragon** [comment]
I'd also like to be able to set the ACL so I can share decrypted folders over samba

**Comment by CTDragon** [comment]
Ping

Any plans or timeline for this. This is also required for me to be able to backup the unencrypted files. Even if I abandon samba, this is not a viable encryption solution without being able to backup the data.

**Comment by rfjakob** [comment]
Fixed in gocryptfs v1.8.
