### ISSUE TITLE
kde plasma vault and gocryptfs

### ISSUE THREAD

**Issue by fabiopesaju** [rfjakob/gocryptfs#250]
will the kde plasma vault fetch the gocryptfs?

https://github.com/KDE/plasma-vault

**Comment by rfjakob** [comment]
Looking here https://github.com/KDE/plasma-vault/tree/master/kded/engine/backends , it seems to only support encfs and cryfs.

**Comment by fabiopesaju** [comment]
and why not produce support for gocryptfs?

**Comment by rfjakob** [comment]
Well, I'm not interested in doing it. There is already another graphical interface, [SiriKali](https://mhogomchungu.github.io/sirikali/), that works fine. Maybe ask the Plasma Vault people if they are interested in working on it?

**Comment by teohhanhui** [comment]
For future travellers:

Just run:

    $ qdbus org.kde.kded5 /modules/plasmavault requestImportVault

(The textboxes for selecting the paths are buggy, so just manually change the text in them and you'd be fine.)

But you'd probably want to delete the auto-generated `.directory` file (and remove the trash directory as well, of course...)

https://bugs.kde.org/show_bug.cgi?id=386200#c35

**Comment by teohhanhui** [comment]
Uhh... Looks like you'd also have to provide the `gocryptfs` binary yourself. Just put it in e.g. `~/.local/bin/gocryptfs`
