### ISSUE TITLE
error Unsupported feature flag "HKDF"

### ISSUE THREAD

**Issue by Cyrix126** [rfjakob/gocryptfs#251]
Hi,

I used gocryptfs to do an encrypted backup.
When I try to decrypt the backup i get the following error: Unsupported feature flag "HKDF"

```
cat .password | gocryptfs -reverse -init -- /home/user
cat .password | gocryptfs -reverse  -- /home/user /home/backup_encrypted
rsync -xarut --del /home/backup_encrypted -e "ssh -p 22" serveur@xx.xx.xx.xx:/backup/


```
Then to decrypt from another computer (from sshfs)

```
gocryptfs /SSHFS/backup/  /tmp/decrypted
Password: 
Decrypting master key
Unsupported feature flag "HKDF"
```

The two computers have gocryptfs is v1.5-22-g01a078e

**Comment by rfjakob** [comment]
Does mounting /home/backup_encrypted on the first computer work?

**Comment by rfjakob** [comment]
If yes, please run "gocryptfs -version" on the second computer.

**Comment by Cyrix126** [comment]
From my commands above the /home/backup_encrypted contains  encrypted view of home/user.

If I do this on the first computer
```

gocryptfs /home/backup_encrypted /home/decrypted-view
Password:
Decrypting master key
Filesystem mounted and ready

```
It works.

When I type gocryptfs -version on the second computer I only get

`gocryptfs`

I compiled gocryptfs from source today. The first computer is Neon KDE 5.13 and the second is Debian 9 Stable

On the first computer
```

gocryptfs -version
gocryptfs v1.5-22-g01a078e; go-fuse v20170619-40-g291273c; 2018-07-02 go1.10.3


```

**Comment by rfjakob** [comment]
When you get only "gocryptfs" from "gocryptfs -version", you have the pretty old debian stable version!

**Comment by rfjakob** [comment]
Debian 9 stable has gocryptfs v1.2, hkdf was added in v1.3.

I recommend to upgrade gocryptfs on the second computer.

**Comment by Cyrix126** [comment]
I installed the latest release from the github on the second computer and placed the executable in /usr/bin.

This solved the problem.

Sorry I was persuaded to use the same version.
Thank you.

**Comment by lechner** [comment]
If you prefer to stick to Debian binaries, you could probably enable the `testing` sources via apt or, in a pinch, download the package file from the web and run `sudo dpkg -i gocryptfs_{VERSION}.deb`.

**Comment by rfjakob** [comment]
No problem! Also, thanks for the good idea @lechner!
