### ISSUE TITLE
Differences between -serialize_reads and -ko sync

### ISSUE THREAD

**Issue by trumblejoe** [rfjakob/gocryptfs#252]
Asking really for just a deeper understanding - what would be the major differences in how -serialize_reads is handled vs -ko sync? With my setup, rclone mount gdrive: > rclone cache of gdrive: > gocryptfs mount on rclone cache, I'm seeing the bottleneck being gocryptfs. I'm hoping that I may find some way of speeding things up to make this more usable.

**Comment by rfjakob** [comment]
serialize_reads disables parallelization of read requests. This was a workarkound for performance problems in amazon cloud drive.

I don't think the sync option does anything for fuse filesystems.
