### ISSUE TITLE
Running concurrent tasks?

### ISSUE THREAD

**Issue by trumblejoe** [rfjakob/gocryptfs#253]
My question is essentially, does gocryptfs support concurrency? The ManPage options make mention so I believe so, but so perhaps I am doing something something wrong you could point out? My mount command is simple, the only option I add is -allow_other.

My use-case for gocryptfs on linux is a mount over an rclone cache of an rclone remote pointed at cloud storage. On windows I have something similar, a gocryptfs (cppcryptfs) mount over a NetDrive mount pointing to cloud storage. 

In both of these examples, I am unable to use Plex (media server), to scan my library, while simultaneously watching something, or vice versa...or watch something while the daughter is watching something else on her tablet, etc. My original pain-staking way around this was to create multiple NetDrive mounts, with individual gocryptfs mounts on each one for each Plex Library and just never watch two things from the same library at the same time. It worked, and it really isn't that bad on windows, but for some practical reasons and my own sanity I would like to not continue this on my linux box.

**Comment by rfjakob** [comment]
Yes, *all* reads should run concurrently, and writes to different files should run concurrently.

The "rclone cache" is a local folder? Or is it some kind of mountpoint?

**Comment by trumblejoe** [comment]
It's a mount of a local cache folder.
