### ISSUE TITLE
Feature Request: Timestamp/metadata encryption. 

### ISSUE THREAD

**Issue by lf-zbw** [rfjakob/gocryptfs#254]
I was using the project to safely backup some personal files to cloud drives but some provider or syncing software doesn't support timestamp so will it be possible to squeeze the timestamp into the encrypted files and folders? 
Here's some of my thoughts about this feature. For files, maybe we can add the metadata information after the file ID. As for the directory, maybe rename the .diriv to something else like .dirdata for which contains directory metadata so that it can provide a easy way to tell whether the metadata encryption is enabled and also prevent the added data to mess with older version of the software.

**Comment by rfjakob** [comment]
Interesting idea, but I think this adds too much complexity to gocryptfs.
