### ISSUE TITLE
Question about the performace of gocryptfs

### ISSUE THREAD

**Issue by didongke** [rfjakob/gocryptfs#255]
The comparison with other projects :  https://nuetzlich.net/gocryptfs/comparison/
What I care about is performance.

![1](https://user-images.githubusercontent.com/28583300/43508729-48a968e6-95a3-11e8-81e3-c30f909afc4b.png)

1. Why is the performance of excuting commands much worse than ecrypfs ?  Where is the time spent? Is it possible to improve?

2. What is the meaning of streaming write/read? Why is the performace better than ecrypfs? What does this mean?

**Comment by rfjakob** [comment]
Hi!

(1) these commands operate on lots and lots of small files from the linux-3.0.tar.gz archive. There is a certain overhead for each file operation because gocryptfs goes through the FUSE layer, and ecryptfs does not.
I will take a look if things can be sped up a little.

(2) streaming read and write is what you get when you read or write a large file. Copying a bunch of photos 2mb each will be faster on gocryptfs.
This is because gocryptfs uses very fast AES-GCM encryption, which probably did not exist yet when ecryptfs was written.

**Comment by didongke** [comment]
I tested performance on a Linux machine by compiling Linux 4.4.  
command:  time make bzImage -j2
The result is as follows.

(1) not use gocrypfs
![111](https://user-images.githubusercontent.com/28583300/43512948-01afa58e-95af-11e8-9015-8c6809178522.png)

(2) use gocryptfs
![112](https://user-images.githubusercontent.com/28583300/43512954-0980f768-95af-11e8-8056-95dad85eeeee.png)

I wonder why the cpu time (user+sys) of latter is a little different from the former, but the real time increased a lot.

**Comment by rfjakob** [comment]
I just tested with [linux-4.4.145.tar.xz](https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.4.145.tar.xz) using `allnoconfig` so I don't have to wait as long:

    make allnoconfig
    time make -j2

On gocryptfs, I noticed that the CPUs were not at 100%, so I tested with `make -j4` even though I have only two cores.
This got both cores to 100% and improved the compile time a bit:

```
ext4 make -j2      gocryptfs make -j2     gocryptfs make -j4
real 1m22.683s     real 2m19.840s         real 1m54.883s
user 1m49.957s     user 1m55.243s         user 2m01.194s
sys  0m17.331s     sys  0m26.698s         sys  0m27.601s
```

**Comment by rfjakob** [comment]
I just realized I ran the tests with a massive amount of debug output in gocryptfs. Here are the results with normal gocryptfs:

|      | make -j2  | make -j4  |
|------|-----------|-----------|
| real | 1m58.190s | 1m50.031s |
| user | 1m55.671s | 2m01.664s |
| sys  | 0m26.520s | 0m27.746s |

**Comment by didongke** [comment]
Thank you. I will do more tests and read code to find out if the performance can be improved.

**Comment by rfjakob** [comment]
Sounds good! Hint for profiling: Use the `-cpuprofile` flag:
```
$ gocryptfs -cpuprofile=cpu.prof cipher plain

### run test workload ###

### unmount cleanly ###
$ fusermount -u plain

### read cpu profile ###
$ go tool pprof cpu.prof 
File: gocryptfs
Build ID: 9b588c39e9e474cbd7d2e25252392cb969af8ea1
Type: cpu
Time: Aug 18, 2018 at 6:40pm (CEST)
Duration: 34.30s, Total samples = 1.77s ( 5.16%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 1330ms, 75.14% of 1770ms total
Showing top 10 nodes out of 232
      flat  flat%   sum%        cum   cum%
     300ms 16.95% 16.95%      320ms 18.08%  runtime.cgocall
     270ms 15.25% 32.20%      270ms 15.25%  syscall.Syscall6
     260ms 14.69% 46.89%      260ms 14.69%  syscall.Syscall
     240ms 13.56% 60.45%      240ms 13.56%  golang.org/x/crypto/scrypt.salsaXOR
      70ms  3.95% 64.41%      110ms  6.21%  runtime.mallocgc
      50ms  2.82% 67.23%       50ms  2.82%  path/filepath.Clean
      50ms  2.82% 70.06%       50ms  2.82%  runtime.scanobject
      30ms  1.69% 71.75%       30ms  1.69%  crypto/aes.encryptBlockGo
      30ms  1.69% 73.45%       30ms  1.69%  golang.org/x/crypto/scrypt.blockXOR
      30ms  1.69% 75.14%       50ms  2.82%  runtime.deferreturn
(pprof)

**Comment by rfjakob** [comment]
Note: Ignore `scrypt` in the cpu profiles. This is the password hashing function that only runs once on startup. You can use `gocryptfs -init -scryptn=10 cipher` to reduce the hashing strength. This makes it effectively disappear from the cpu profiles.

**Comment by rfjakob** [comment]
I'll close this for now - feel free to reopen if any further questions!
