### ISSUE TITLE
Fchmodat does not support AT_SYMLINK_NOFOLLOW

### ISSUE THREAD

**Issue by rfjakob** [rfjakob/gocryptfs#259]
These were silently ignored until now (!) but are rejected by Go 1.11 stdlib: https://github.com/golang/go/issues/20130 for more info.

From the fchmodat man page:

     AT_SYMLINK_NOFOLLOW ... This flag is not currently implemented.

@slackner Ideas?

**Comment by slackner** [comment]
As I see you have already temporarily removed the flag, that is also what I would have suggested.
Do you think it makes sense to implement a workaround based on `openat` and then `fchmod`?

**Comment by rfjakob** [comment]
Good idea, that would fix it. I'll benchmark the performance impact.

**Comment by rfjakob** [comment]
Haha. Problem with `openat`: We cannot do it if we don't have read permissions for the file:
```
--- FAIL: TestChmod (0.00s)
    matrix_test.go:905: chmod 000 -> 111 failed: permission denied
    matrix_test.go:905: chmod 000 -> 123 failed: permission denied
    matrix_test.go:905: chmod 000 -> 321 failed: permission denied
```
