### ISSUE TITLE
Can -oallow_other be passed to fuse when mounting?

### ISSUE THREAD

**Issue by jjellinek** [rfjakob/gocryptfs#26]
Sorry, don't know if this is an issue, or just my not knowing how to do something. I want to samba share my unencrypted fuse mount and my understanding is that fuse needs -oallow_other sent to it upon mount request. Is there a way to get gocryptfs to pass this flag through to fuse when starting/mounting my encrypted directory?

(You may think I'm mad to samba share this, but it's for very transient use between a group of people in an enclosed private network)

**Comment by rfjakob** [comment]
No, not yet, but I have started working on it. It's a simple addition but I have hit an issue in the fuse library ( https://github.com/hanwen/go-fuse/issues/107 ). Should be resolved shorty, stay tuned.

**Comment by rfjakob** [comment]
Fixed in e7f78135b3092bbd2479beac5b7da077cb5d1497 . Please report back if you hit any problems.

**Comment by jjellinek** [comment]
Hi,
Seems to be working fine thank you :) Took me a while to create a VM to compile etc. as I can't compile on Ubuntu Trusty.
