### ISSUE TITLE
Compatibility issues with gvfs mountpoints

### ISSUE THREAD

**Issue by guillaumeautran** [rfjakob/gocryptfs#262]
gocryptfs cannot mount a gvfs mount point and fusermount abort with exit code 256. 

```
/bin/fusermount: mount failed: Invalid argument
fuse.NewServer failed: fusermount exited with code 256
```

How to reproduce: 
You will need a windows share where your gocryptfs encrypted FS is and gvfs installed on your ubuntu 16.04 desktop.
- Mount your windows share using gvfs (typically use the file explorer for this) 
- Initialize a gocrpytfs mount on a gvfs mount point
- try to mount (using gocryptfs) your newly initialized file system to a different mount target

**Comment by rfjakob** [comment]
Hi! Where is the mount target?

**Comment by guillaumeautran** [comment]
Sample commands which do not work are: 
`gocryptfs /run/user/1001/gvfs/smb-share\:server=nas\,share=data_share/ /home/user/mnt/plaintext/`

From my debugging of the code, the fusemount code does not properly escape the `:` and `,` characters from the `from` path.

Simpler test to run would be:
```
$ mkdir ./test\,s\;\:\=\char
$ mkdir ./plaintext
$ gocryptfs -init ./test\,s\;\:\=\char
Choose a password for protecting your files.
Password: *****
Repeat: *****

Your master key is:

    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

If the gocryptfs.conf file becomes corrupted or you ever forget your password,
there is only one hope for recovery: The master key. Print it to a piece of
paper and store it in a drawer. This message is only printed once.

The gocryptfs filesystem has been created successfully.
You can now mount it using: gocryptfs ./test\,s\;\:\=\char MOUNTPOINT
$ gocryptfs ./test\,s\;\:\=char/ ./plaintext/
Password: ****
Decrypting master key
fuse.NewServer failed: found ',' in option string "fsname=/home/user/test,s;:=char"
$
```

**Comment by guillaumeautran** [comment]
The error seems to come from here: https://github.com/hanwen/go-fuse/blob/master/fuse/server.go#L152
So, might be an issue with the `go-fuse` library

**Comment by rfjakob** [comment]
Well, you could also call this a limitation in go-fuse. Anyway, the only purpose of `fsname=` is to have the path displayed in `df -T`, so I now replace any commas with underscores in commit https://github.com/rfjakob/gocryptfs/commit/5ca6243eeb0df43ba0387029c2d8eceffa3172e2 . Does it solve your problem?

**Comment by guillaumeautran** [comment]
Worked like a charm! Thanks!

**Comment by guillaumeautran** [comment]
Humm, I may have spoken too fast. 
mounting the e_FS works and file / directory creation works as well. However, creating non-zero size file (aka files with data in there) seems to fail with `Write error: operation not supported`

This is with a gvfs mounted FS then mounting a gocryptfs. Are you seeing the same thing on your side or is it just me?

**Comment by rfjakob** [comment]
I can reproduce the problem without gocryptfs. Inside a gvfs mount:

    dd if=/dev/zero of=foo bs=1 count=1 conv=notrunc
    dd: failed to open 'foo': Operation not supported

It seems like gvfs does not support writing to files without truncating them (same problem was hit here: https://github.com/restic/restic/issues/1831).

I recommend to mount via /etc/fstab. For example, this is what I do:

    //192.168.0.3/public /mnt/synology/public cifs nofail,username=jakob,password=xyz,uid=jakob,gid=jakob 1 1

**Comment by rfjakob** [comment]
Wtf. Gvfs seems to be pretty broken.
```
$ rm foo
rm: cannot remove 'foo': No such file or directory
$ echo asdasd > foo
bash: foo: No such file or directory
```

**Comment by guillaumeautran** [comment]
Yeah. don't really understand what's going on here. I used GVFS all the time for user mounts of SMB or device file systems. and it did work fine. 

Anyway, I'll revert back to mounting in the fstab file. Just not as convenient in some cases but works for me. 
Thanks for your help. This issue can probably be closed now.

**Comment by rfjakob** [comment]
I tried to work around the [openat failure](https://github.com/restic/restic/issues/1831#issuecomment-395829330), but immediately hit the next issue: gvfs does not support `pwrite` :

```
[pid  6431] pwrite64(5, "\0\2\16\341!}\357ke\266\301\271<{\314Z\3549", 18, 0 <unfinished ...>
[pid  6431] <... pwrite64 resumed> )    = -1 EOPNOTSUPP (Operation not supported)
```
gocryptfs must use `pwrite` instead of regular `write` because it runs multithreaded, and multiple writes may happen at the same time. I guess that's why gvfs works fine with simple operations, like copying a file to it. This is all single-threaded, and can be done with regular `write`.

Sorry, but there's no fixing that, short of gvfs implementing `pwrite`.

**Comment by stephane-21** [comment]
With the latest version of gocryptfs :
gocryptfs v1.7-41-gf1b538e; go-fuse v2.0.2-1-ga3bb218; 2019-08-10 go1.10.4 linux/amd64
and :
gvfs 1.40.1-1ubuntu0.1

It still doesn't work even when copying manually a single file.
