### ISSUE TITLE
Mount point not visible through Samba

### ISSUE THREAD

**Issue by casper** [rfjakob/gocryptfs#264]
This may be more of a support question, but why is the gocrypt mount point not visible through any SMB connection (running on Ubuntu 18.04)?

I've mounted the encrypted folder in my home directory, and I'm accessing it through the Samba smb.conf `[homes]` section (i.e. with user based credentials), but it's still not visible.

Are there some additional tricks I need to do to make it visible, or why is it not showing up?

**Comment by rfjakob** [comment]
Do you an error message when you access it?

**Comment by rfjakob** [comment]
(please try mounting with -allow_other)

**Comment by rayfoss** [comment]
Thank you! had this same problem with samba and gcsfuse. Samba won't show sub mounts from a non root user unless user_allow_other is configured in fuse and the mount option is set.
