### ISSUE TITLE
Tests failing on Centos 7.5

### ISSUE THREAD

**Issue by simpz** [rfjakob/gocryptfs#267]
I have build version 1.6-26 but basically the latest version from GIT and a large number of tests fail on Centos 7.5. They used to be clean with my previous production version v1.4-21. 

I'm using
go version go1.9.4 linux/amd64

But the tests fail if I use the prebuild static binary too.

Attached the version output of the the tests.

Any ideas or am I doing something wrong?

Also the test don't appear to clean up the test mounts they do after they are finished,

[gocrypt3.txt](https://github.com/rfjakob/gocryptfs/files/2464269/gocrypt3.txt)

**Comment by rfjakob** [comment]
Hmm, what filesystem do you use?

The test suite gets tougher in each version, maybe the now-failing tests did not exist in 1.4.

The next test run will clean up any remaining filesystems.

**Comment by simpz** [comment]
I'm using the default XFS.

**Comment by rfjakob** [comment]
Looking through the log:

    sys_common_test.go:21: [...]: file name too long

XFS seems to have a lower limit than ext4. Strange but harmless.

    panic: -wpanic turns this warning into a panic: Getdents: convertDType: received DT_UNKNOWN, falling back to stat

This is harmless, but causes later tests to fail.

    panic: inconsistent result: stat=true open=false readdir=false [recovered]

This is bad, but only affects reverse mode.

**Comment by rfjakob** [comment]
I fixed one issue that I found when testing on XFS, but your tests abort before they even hit that problem.

I installed CentOS 7 in a VM with Go 1.11, and things look very different here: I only get the one `FAIL: TestReadlinkat (0.00s)`, everything else passes. I will try downgrading to Go 1.9.

**Comment by rfjakob** [comment]
I fixed the one failure I saw, and now the tests are clean. What is you kernel version? I have 
```
# uname -a
Linux localhost.localdomain 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

My tests:
```
[jakob@localhost gocryptfs]$ ./test.bash
gocryptfs v1.6-29-g57a5a87 without_openssl; go-fuse v20170619-66-g6df8ddc; 2018-10-11 go1.9.4
gocryptfs v1.6-29-g57a5a87; go-fuse v20170619-66-g6df8ddc; 2018-10-11 go1.9.4
ok  	github.com/rfjakob/gocryptfs	0.042s
?   	github.com/rfjakob/gocryptfs/gocryptfs-xray	[no test files]
ok  	github.com/rfjakob/gocryptfs/internal/configfile	0.996s
ok  	github.com/rfjakob/gocryptfs/internal/contentenc	0.010s
ok  	github.com/rfjakob/gocryptfs/internal/cryptocore	0.298s
ok  	github.com/rfjakob/gocryptfs/internal/ctlsock	0.015s
?   	github.com/rfjakob/gocryptfs/internal/exitcodes	[no test files]
ok  	github.com/rfjakob/gocryptfs/internal/fusefrontend	0.027s
ok  	github.com/rfjakob/gocryptfs/internal/fusefrontend_reverse	0.005s
ok  	github.com/rfjakob/gocryptfs/internal/nametransform	0.018s
?   	github.com/rfjakob/gocryptfs/internal/nametransform/dirivcache	[no test files]
?   	github.com/rfjakob/gocryptfs/internal/openfiletable	[no test files]
ok  	github.com/rfjakob/gocryptfs/internal/pathiv	0.017s
ok  	github.com/rfjakob/gocryptfs/internal/prefer_openssl	0.055s
ok  	github.com/rfjakob/gocryptfs/internal/readpassword	0.082s
?   	github.com/rfjakob/gocryptfs/internal/serialize_reads	[no test files]
ok  	github.com/rfjakob/gocryptfs/internal/siv_aead	0.004s
ok  	github.com/rfjakob/gocryptfs/internal/speed	0.004s [no tests to run]
ok  	github.com/rfjakob/gocryptfs/internal/stupidgcm	2.013s
ok  	github.com/rfjakob/gocryptfs/internal/syscallcompat	0.068s
ok  	github.com/rfjakob/gocryptfs/internal/tlog	0.010s
ok  	github.com/rfjakob/gocryptfs/tests/cli	2.493s
ok  	github.com/rfjakob/gocryptfs/tests/defaults	3.410s
ok  	github.com/rfjakob/gocryptfs/tests/example_filesystems	5.469s
ok  	github.com/rfjakob/gocryptfs/tests/fsck	0.833s
ok  	github.com/rfjakob/gocryptfs/tests/hkdf_sanity	0.160s
ok  	github.com/rfjakob/gocryptfs/tests/matrix	27.541s
ok  	github.com/rfjakob/gocryptfs/tests/plaintextnames	0.097s
ok  	github.com/rfjakob/gocryptfs/tests/reverse	2.378s
?   	github.com/rfjakob/gocryptfs/tests/symlink_race	[no test files]
?   	github.com/rfjakob/gocryptfs/tests/test_helpers	[no test files]
ok  	github.com/rfjakob/gocryptfs/tests/trezor	0.017s
ok  	github.com/rfjakob/gocryptfs/tests/xattr	0.133s
```

**Comment by rfjakob** [comment]
Can you post your

    df -Th

? Looks like this here:

```
[jakob@localhost gocryptfs]$ df -Th
Filesystem              Type      Size  Used Avail Use% Mounted on
/dev/mapper/centos-root xfs       8.0G  1.8G  6.3G  23% /
devtmpfs                devtmpfs  484M     0  484M   0% /dev
tmpfs                   tmpfs     496M     0  496M   0% /dev/shm
tmpfs                   tmpfs     496M   20M  477M   4% /run
tmpfs                   tmpfs     496M     0  496M   0% /sys/fs/cgroup
/dev/vda1               xfs      1014M  130M  885M  13% /boot
tmpfs                   tmpfs     100M     0  100M   0% /run/user/0
tmpfs                   tmpfs     100M     0  100M   0% /run/user/1000
```

**Comment by simpz** [comment]
Hopefully here is the info you need. Sorry for any bad formatting, doing this on a phone.

df -hT
Filesystem     Type      Size  Used Avail Use% Mounted on
/dev/dm-2      xfs       100G   14G   86G  14% /
devtmpfs       devtmpfs   16G     0   16G   0% /dev
tmpfs          tmpfs      16G     0   16G   0% /dev/shm
tmpfs          tmpfs      16G  1.5M   16G   1% /run
tmpfs          tmpfs      16G     0   16G   0% /sys/fs/cgroup
/dev/md127     xfs       993M  360M  634M  37% /boot
/dev/dm-5      xfs       5.4T  4.9T  473G  92% /home
tmpfs          tmpfs     3.2G     0  3.2G   0% /run/user/511
tmpfs          tmpfs     3.2G  4.0K  3.2G   1% /run/user/500

Linux fs01 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rfjakob** [comment]
Yes it is, thanks.

I think we are seeing this problem: https://linux-tips.com/t/readdir-function-on-xfs-filesystem-not-working-properly/115

> In default form, XFS filesystem doesn’t store inode information in directory structure. 
> [...]
> entry->d_type will be equal to DT_UNKNOWN

I guess the XFS default settings in CentOS have changed over time, you still have the old defaults, which is why you get DT_UNKNOWN.

**Comment by rfjakob** [comment]
https://github.com/rfjakob/gocryptfs/commit/e665df71795a3a4656f6eae70211bb59723cd01e should fix the problem! Thanks
