### ISSUE TITLE
fsck autofix

### ISSUE THREAD

**Issue by pos42** [rfjakob/gocryptfs#269]
If taking backup to the cloud, the cloud is just a stupid encrypted backup copy. 

If you do this, speed is not priority no 1, integrity is. If you happened to get a corrupted gocryptfs file, the rsync stalls. As gocryptfs tried multiple times to write the file, speed is incredible slow if you have corruption (i.e your backup sync simple don't work). As the cloud only has a slave copy it is just to delete the corrupted file and sync it again. If you could find the corrupted file of course.....

- Is it possible to add an fsck autofix flag for this purpose (or autodelete the corrupted file if fix it is a problem)?
- Or maybe a flag for better integrity (to the cost of speed of course) when writing the file?

If so..., you do not have to check the syslog to notice you have a problem and then manually fix it. Such an option will make backups to the cloud with gocryptfs more reliable. If it slows down speed to do it, for me it does not matter as it goes over cron during night. I think this would be a good feature for those who use it for this purpose and care for reliability, which is for me, just one way of using this magnificent piece of software :)

/Peo

**Comment by pos42** [comment]
Maybe this is a different error... But here is what I see....

Run like a non privileged user with home dir /data/pcloud in a cloud-backup-sync-vm...
[pcloud@cloud-storage ~]$ df -h|grep -i pcloud
pCloud.fs                                     2.0T  511G  1.6T  25% /data/pcloud/pCloudDrive
/data/pcloud/pCloudDrive/gocryptfs-encrypted  2.0T  511G  1.6T  25% /data/pcloud/VOLUMES/gocryptfs-unencrypted
[pcloud@cloud-storage ~]$ 

A sync like this as root from cron....
`su - pcloud -c "/usr/bin/rsync -av -e "ssh" --delete --delete-excluded \
--exclude='.DS_Store' --exclude=/data/.snapshots/  --exclude=/data/TimeMachine/ \
--exclude=/data/exports/ --exclude=/data/BACKUPS/ \
root@apollo.incedo.org:/data \
/data/pcloud/VOLUMES/gocryptfs-unencrypted/apollo.incedo.org/"`


always gives a few errors. And every error seems to be retried several times.
`
Oct 17 03:49:46 cloud-storage gocryptfs[1695]: #033[33mdoWrite: Write failed: write /data/pcloud/pCloudDrive/gocryptfs-encrypted/fHRWPg9Ai75eCaLHu4mEFA6fWm3WZjziugmLOs6EwBw/MsFsKr9rOze3z6qwzdEVPw/o-Ev2Q3tUSIbVgHtMr9Fuw/Wgre5HkCkvBMQfZPaZZbtA/_nHco9Yz6ijnVoaWzErj4Q/Nw4HagAMnoKrurRV0soPHg/ucsiTfXQ9VPqObr6QQjuDX75OJO1bz-eWd1KFyOovcnbGICIKz6Qo2UNlHALfwVoHWrUyeJyYpqinU4xXFO94g: interrupted system call#033[0m
Oct 17 03:49:51 cloud-storage gocryptfs[1695]: #033[33mdoWrite: Write failed: write /data/pcloud/pCloudDrive/gocryptfs-encrypted/fHRWPg9Ai75eCaLHu4mEFA6fWm3WZjziugmLOs6EwBw/MsFsKr9rOze3z6qwzdEVPw/o-Ev2Q3tUSIbVgHtMr9Fuw/Wgre5HkCkvBMQfZPaZZbtA/_nHco9Yz6ijnVoaWzErj4Q/Nw4HagAMnoKrurRV0soPHg/ucsiTfXQ9VPqObr6QQjuDX75OJO1bz-eWd1KFyOovcnbGICIKz6Qo2UNlHALfwVoHWrUyeJyYpqinU4xXFO94g: interrupted system call#033[0m
Oct 17 03:49:56 cloud-storage gocryptfs[1695]: #033[33mdoWrite: Write failed: write /data/pcloud/pCloudDrive/gocryptfs-encrypted/fHRWPg9Ai75eCaLHu4mEFA6fWm3WZjziugmLOs6EwBw/MsFsKr9rOze3z6qwzdEVPw/o-Ev2Q3tUSIbVgHtMr9Fuw/Wgre5HkCkvBMQfZPaZZbtA/_nHco9Yz6ijnVoaWzErj4Q/Nw4HagAMnoKrurRV0soPHg/ucsiTfXQ9VPqObr6QQjuDX75OJO1bz-eWd1KFyOovcnbGICIKz6Qo2UNlHALfwVoHWrUyeJyYpqinU4xXFO94g: interrupted system call#033[0m
Oct 17 06:38:13 cloud-storage gocryptfs[1695]: #033[33mdoWrite: Write failed: write /data/pcloud/pCloudDrive/gocryptfs-encrypted/fHRWPg9Ai75eCaLHu4mEFA6fWm3WZjziugmLOs6EwBw/MsFsKr9rOze3z6qwzdEVPw/o-Ev2Q3tUSIbVgHtMr9Fuw/Wgre5HkCkvBMQfZPaZZbtA/_nHco9Yz6ijnVoaWzErj4Q/Nw4HagAMnoKrurRV0soPHg/6s-Lm61dN-g0Rfkt3dmso0_ma-zqhFP9SMpvL_WiliuohWqR796HULYlCAVV00aa: interrupted system call#033[0m
Oct 17 06:38:18 cloud-storage gocryptfs[1695]: #033[33mdoWrite: Write failed: write /data/pcloud/pCloudDrive/gocryptfs-encrypted/fHRWPg9Ai75eCaLHu4mEFA6fWm3WZjziugmLOs6EwBw/MsFsKr9rOze3z6qwzdEVPw/o-Ev2Q3tUSIbVgHtMr9Fuw/Wgre5HkCkvBMQfZPaZZbtA/_nHco9Yz6ijnVoaWzErj4Q/Nw4HagAMnoKrurRV0soPHg/6s-Lm61dN-g0Rfkt3dmso0_ma-zqhFP9SMpvL_WiliuohWqR796HULYlCAVV00aa: interrupted system call#033[0m
Oct 17 06:38:23 cloud-storage gocryptfs[1695]: #033[33mdoWrite: Write failed: write /data/pcloud/pCloudDrive/gocryptfs-encrypted/fHRWPg9Ai75eCaLHu4mEFA6fWm3WZjziugmLOs6EwBw/MsFsKr9rOze3z6qwzdEVPw/o-Ev2Q3tUSIbVgHtMr9Fuw/Wgre5HkCkvBMQfZPaZZbtA/_nHco9Yz6ijnVoaWzErj4Q/Nw4HagAMnoKrurRV0soPHg/6s-Lm61dN-g0Rfkt3dmso0_ma-zqhFP9SMpvL_WiliuohWqR796HULYlCAVV00aa: interrupted system call#033[0m
Oct 17 06:38:28 cloud-storage gocryptfs[1695]: #033[33mdoWrite: Write failed: write /data/pcloud/pCloudDrive/gocryptfs-encrypted/fHRWPg9Ai75eCaLHu4mEFA6fWm3WZjziugmLOs6EwBw/MsFsKr9rOze3z6qwzdEVPw/o-Ev2Q3tUSIbVgHtMr9Fuw/Wgre5HkCkvBMQfZPaZZbtA/_nHco9Yz6ijnVoaWzErj4Q/Nw4HagAMnoKrurRV0soPHg/6s-Lm61dN-g0Rfkt3dmso0_ma-zqhFP9SMpvL_WiliuohWqR796HULYlCAVV00aa: interrupted system call#033[0m
Oct 17 06:38:33 cloud-storage gocryptfs[1695]: #033[33mdoWrite: Write failed: write /data/pcloud/pCloudDrive/gocryptfs-encrypted/fHRWPg9Ai75eCaLHu4mEFA6fWm3WZjziugmLOs6EwBw/MsFsKr9rOze3z6qwzdEVPw/o-Ev2Q3tUSIbVgHtMr9Fuw/Wgre5HkCkvBMQfZPaZZbtA/_nHco9Yz6ijnVoaWzErj4Q/Nw4HagAMnoKrurRV0soPHg/6s-Lm61dN-g0Rfkt3dmso0_ma-zqhFP9SMpvL_WiliuohWqR796HULYlCAVV00aa: interrupted system call#033[0m
Oct 17 09:19:38 cloud-storage dbus[652]: [system] Activating service name='org.freedesktop.problems' (using servicehelper)
Oct 17 09:19:38 cloud-storage dbus[652]: [system] Successfully activated service 'org.freedesktop.problems'
`

And this slows things down.

It maybe depends on a crappy pcloud client. I do not know. Working live with open files every day over a 100GB gocryptfs drive in my MAC that is on iCloud with zero problems. Maybe it is a sync/cache problem in the pcloud cloud client? IF it is... As it is just a stupid slave copy, is it possible to have gocryptfs to auto-correct or auto-delete problematic/corrupt files with a flag and log it?  For example with a flag "-dontblamegocryptfs", "-autodeletecorruptfiles" or similar. A flag to be used for pure backup slave purpose where it is just to sync again with rsync... As said, no problem at all working with open files over gocryptfs using iCloud....

Maybe I have missunderstood something, or it is maybe a bad idea. Just checking.

Please enlighten me :)

/Peo

**Comment by rfjakob** [comment]
Is this the pcloud client you use? https://www.pcloud.com/how-to-install-pcloud-drive-linux.html


I wonder if gocryptfs *should* retry these writes. Will test when i find time!

**Comment by pos42** [comment]
No, I use this CLI client: https://github.com/pcloudcom/console-client (on CentOS 7.5)

(Note that pCloud refer to this on their official page for linux here https://www.pcloud.com/download-free-online-cloud-file-storage.html)

My intention is to use it for backup purpose only. I have bought their 1 time payment to get 2TB for life. No one know how long that really is though :)

Just trying to figure out where the error is generated

**Comment by rfjakob** [comment]
Interesting. We get the error `interrupted system call` (code `EINTR`), which we should not never get, with the exception of a few buggy cases on MacOS ( https://github.com/golang/go/issues/11180 ).

I have added some extra logging to master (commit https://github.com/rfjakob/gocryptfs/commit/4cdf6b9af94232912857138cc1ddcec520d9ceca), could you recompile and try again? Hopefully we get some more info.

**Comment by rfjakob** [comment]
PS: Any error messages from rsync?

**Comment by pos42** [comment]
I have not run rsync with any special options. I have therefor not seen any errors from it. Do you think there is a need increase the logging for rsync as well. My guess is that rsync is innocent regarding this error. But... it is computers, so you'll never know :)

Ok. this is what I use for this test...
[root@cloud-storage ~]# /tmp/gocryptfs-master-20181018 -h
gocryptfs v1.6-36-g1ed08c7; go-fuse v20170619-68-ga53ed6b; 2018-10-18 go1.9.4

Then gocryptfs told me this during re-mount with the new gocryptfs binary....
Oct 18 10:04:20 cloud-storage gocryptfs[10062]: Warning: The underlying filesystem does not support fallocate(2). gocryptfs will continue working but is no longer resistant against out-of-space errors.

The mounts are as follows...
(pCloud CLI client is used on CentOS7 .5)
[pcloud@cloud-storage ~]$ df -h|grep -i cloud
`pCloud.fs   2.0T  552G  1.5T  27% /data/pcloud/pCloudDrive`
`/data/pcloud/pCloudDrive/gocryptfs-encrypted  2.0T  552G  1.5T  27% /data/pcloud/VOLUMES/gocryptfs-unencrypted`
[pcloud@cloud-storage ~]$ 

And the unencrypted mount above goes to...
`/data/pcloud/pCloudDrive/gocryptfs-encrypted/`

This rsync started at 10:47.
`su - pcloud -c /usr/bin/rsync -av -e ssh --delete --delete-excluded --exclude='.DS_Store' --exclude=/data/.snapshots/  --exclude=/data/TimeMachine/ --exclude=/data/exports/ --exclude=/data/BACKUPS/ root@apollo.incedo.org:/data /data/pcloud/VOLUMES/gocryptfs-unencrypted/apollo.incedo.org/`


Here is the output from syslog.... 
`
Oct 18 10:47:09 cloud-storage su: (to pcloud) root on none
Oct 18 16:51:10 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3087611922 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 16:51:15 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3087611922 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 16:51:20 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3087611922 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 16:51:25 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3087611922 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 16:51:30 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3087611922 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 16:51:35 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3087611922 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 16:51:40 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3087611922 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 16:51:45 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3087611922 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 16:51:50 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3087611922 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 16:51:55 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3087611922 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 18:49:08 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3221557266 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 18:49:13 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3221557266 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 18:49:18 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3221557266 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 18:49:23 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3221557266 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 18:49:28 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3221557266 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:16:39 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:16:44 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:16:49 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:16:54 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:16:59 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:17:04 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:17:09 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:17:14 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:17:19 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:17:24 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:17:29 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:17:34 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:17:39 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:17:44 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:17:49 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:17:54 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:17:59 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:18:04 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:18:09 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:18:14 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:18:19 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:18:24 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:18:29 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:18:34 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:18:39 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:18:44 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:18:50 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:18:55 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:19:00 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:19:05 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:19:10 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:19:15 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:19:20 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:19:25 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:19:30 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:19:35 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:19:40 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:19:45 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:19:50 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:19:55 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:20:00 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:20:05 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:20:10 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:20:15 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:20:20 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:20:25 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:20:30 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:20:35 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:20:40 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:20:45 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:20:50 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:20:55 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:21:00 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:21:05 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:21:10 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:21:15 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:21:20 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:21:25 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:21:30 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:21:35 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
Oct 18 19:21:40 cloud-storage gocryptfs[10062]: ino6208769 fh12: doWrite: WriteAt off=3243353106 len=132096 failed: write eO0eEN8N1CvASXUKMfUd1Z7RlNdmpc_UJlSbo7tDdrs: interrupted system call
`

At time of writing (21:03) the rsync that started 10:47 is till going, i.e the encrypted volume is still growing.

Maybe you can tell me what this means.. Buggy pcloud client or maybe gocryptfs that does not like pCloud :)

PS
Do not know why it is not going any faster. I have a 10Gbit symmetric internet fiber connection and usually get around 5-6 Gbit against good test servers. Not blaming gocryptfs that usually is rocket fast (have had 3Gbit speed with gocryptfs over network to a site). This is maybe pCloud that slows it down. However... I do not care that much as long as the backup goes ok.

Tnx
/Peo

**Comment by rfjakob** [comment]
I think the pcloud client is buggy. `interrupted system call` is code `EINTR`, and looking at http://man7.org/linux/man-pages/man7/signal.7.html , this error code should not be returned on disk access.

Giving fsck the ability to fix errors would certainly be good, I'm going to track progress in this earlier ticket: https://github.com/rfjakob/gocryptfs/issues/263
