### ISSUE TITLE
File integrity check / diriv & conf Backups

### ISSUE THREAD

**Issue by loungebob** [rfjakob/gocryptfs#270]
Rather new to the whole encryption thing but love the speed of gocryptfs! Read through the wiki and issues but still have a couple of questions.

I use gocryptfs to encrypt all my data uploaded to google drive file stream.

- does gocryptfs do any data integrity checking after encryption and storing it to the virtual drive? or would this be google’s drive file stream uploader part? or do I have to use another app to make sure, files encrypted and stored to google drive are not corrupt? 

_ if I understood correctly, diriv contains the file names and the conf file basically my encrypted password used to decrypt the encrypted stuff, right? 
what if the conf file gets corrupted or deleted? all encrypted data lost? if so, the conf file should naturally be backed up locally too, not just stored in the cloud, right?
what about the diriv files? I love being able to not just restore the content but also the file names. how does one back-up the diriv files? there’s one of them in every folder...

cheers!

**Comment by trumblejoe** [comment]
I'll chime in on this, an excellent utility for file integrity transfers is rclone at rclone.org. It compares sizes and hashes of file transfers, and will also do a check on modification time. Check out their website for more information. They also have a mount option which will allow you to replace Google Drive File Stream with rclone.

@rfjakob will have to verify but I don't believe gocryptfs uses any type of native file integrity check.

During gocryptfs mounting, you will be displayed a Master Key which you can use for recovering data in the event of a deleted .conf file. For backups, what I personally do is copy the entire encrypted directory structure and its contents as-is. 

I once had an issue where I needed to re-create a directory and add the existing previous contents to that new encrypted directory. My solution was to copy the existing .diriv file and file contents to a non-encrypted location, delete the directory, create the new directory, delete the new .diriv file, and then finally, place the former .diriv file into the directory and re-add the file contents. If you were to paste the contents without exchanging the .diriv files, the contents would still exist but would be invisible to the gocryptfs mount.

Gocryptfs also has a plain-text file-names option too, if you desire.

**Comment by loungebob** [comment]
I really really like GUIs so not too keen on rclone but I think I read I could use rclone check to compare my local files to the encrypted ones stored already on google drive, could that be? that’s basically what I want to do, make sure the remote files are proper before I delete the local copy. so, rclone check? or another tool for that?

by master key you mean the password I enter to mount the encrypted folder/files? if so, what does one need the .conf file for then? if I can mount and decrypt with the master key alone...

since I dont backup but move the data to the cloud in hundreds of folders with lots of files in each folder, is the only way to make sure I can decrypt the file names properly as well, to duplicate the complete folder structure locally and have the corresponding diriv file copied to each folder? and if so, is there a painless way to do this or will this be tedious manual labor?

**Comment by rfjakob** [comment]
Hi!

1) File Integrity
Yes, each 4kiB block gets a cryptographic checksum ([MAC](https://en.wikipedia.org/wiki/Message_authentication_code)). When you run `gocryptfs -fsck`, all the checksums are verified. However, gocryptfs DOES NOT read the data

2) gocryptfs.diriv
These contain random-generated data and are used to randomize the encrypted file names in the directory. This makes sure `Dir1/invoice.pdf` and `Dir2/invoice.pdf` encrypt to totally different names.
I'd just store them like the encrypted files and not keep extra backups. `gocryptfs -fsck` will detect if a diriv file is missing or corrupt.

4) gocryptfs.conf
Yes, it contains the "Master Key", encrypted with your password. If the file gets deleted, you can still decrypt the data if you copy-pasted and saved the Master Key. I recommend to print out the Master Key to a sheet of paper.

**Comment by loungebob** [comment]
thanks @rfjakob

1. does that work for/on windows too? with cppcryptfs?

2. ok wont keep a backup of diriv

3. ok will keep a backup of conf. just for curiosity’s same, which one in that file is the master key?

**Comment by rfjakob** [comment]
1) not sure, maybe make a feature request? The developer responds quite quickly!

3) iirc, it's stored as EncryptedKey
