### ISSUE TITLE
Get masterkey

### ISSUE THREAD

**Issue by norangebit** [rfjakob/gocryptfs#272]
In previous release, when a cipher dir was mounted it was shown the masterkey. In the current release is there a way to get the masterkey.
I don't know is a issue is the right tool for this, in case sorry.

**Comment by rfjakob** [comment]
Hi! Using a ticket for questions is fine!

Yes the behavoir has [changed](https://github.com/rfjakob/gocryptfs#changelog) in v1.6: Now the masterkey is printed on `-init`, but no longer on mount. This  reduces the risk that the masterkey stays in the terminal scrollback buffer for a long time.

You can use gocryptfs-xray (in the gocryptfs-xray dir) to get the master key, example:

    ./gocryptfs-xray -dumpmasterkey myfs/gocryptfs.conf

Is this good enough for your use case?

**Comment by norangebit** [comment]
yes, thank you very much
