### ISSUE TITLE
exclude in reverse-mode with regex

### ISSUE THREAD

**Issue by chrstn-hntschl** [rfjakob/gocryptfs#273]
Is it possible to use regex in combination with --exclude in gocryptfs reverse mode? I need to exclude file types (e.g. based on endings I want to include all *.jpg but exclude all *.CR2 files from an encrypted backup to a cloud hoster for saving storage space). Currently I am doing this with rofs-filtered fuse but an extended exclude option would save me from that additional layer... Thanks!

**Comment by yunesj** [comment]
rofs-filtered works really well though!

**Comment by rfjakob** [comment]
Would shell wildcard be good enough? Or do you think you will need full regex power?

**Comment by chrstn-hntschl** [comment]
I guess shell wildcard would be fine. As I said, my main application scenario is uploading a folder structure with photos in jpeg as well as raw data format and I would like to exclude all raw files to reduce storage space. Files are distributed in subfolders though. Not sure about shell wildcarding here...

**Comment by ekalin** [comment]
To me regex aren't necessary, just shell wildcarding would be enough. But now it seems --exclude considers only full paths, I'd like to specify 'some-file.txt' and have all files with that name hidden from all directories.

A syntax similar to .gitignore would work fine, I suppose. There are some go libraries for parsing and matching that syntax.

I'll try to take a look at this and submit a PR if I can make it work.
