### ISSUE TITLE
integrated FTP server

### ISSUE THREAD

**Issue by Mebus** [rfjakob/gocryptfs#276]
Hallo,

I am looking for a solution to encrypt usb sticks on different platforms without root or Admin privileges. 

Would it be possible to integrate a FTP server into gocryptfs, so that it is possible to start the server on a Windows machine and to open the encrypted files without Admin permissions?

Mebus

**Comment by rfjakob** [comment]
Hi mebus! No, sorry, i don't think this is possible. Running gocryptfs on windows is going to be difficult because it relies on many feautures of the linux kernel. That's why cppcryptfs on windows is essentially a re-implementation.

**Comment by Mebus** [comment]
Can this be implemented in cryptfs?

Mebus

**Comment by rfjakob** [comment]
You'd have to ask over at https://github.com/bailey27/cppcryptfs .

But maybe you should try https://cryptomator.org/ , which *already* uses WebDAV

**Comment by rfjakob** [comment]
PS: WebDAV works out of the box with Windows Explorer.
