### ISSUE TITLE
Cannot copy hard-links back to unencrypted volume

### ISSUE THREAD

**Issue by vsenderov** [rfjakob/gocryptfs#277]
Hi!

I am not sure if this is a bug or it should be so, but I was wondering if the following behavior is OK. I have an gocryptfs encrypted filesystem mount under /mnt/backup-plaintext:

```
/smb/NRM/FA/BIO/BIO_Privat/viktsend/backup-encrypted on /mnt/backup-plaintext type fuse.gocryptfs (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000,max_read=131072)
```

I have a test directory under ~/Temp (in an unencrypted filesystem), which has some hard links:

```
[viktor@roussettus Temp]$ ll -i backup-test/
total 20
3802513 -rwxr-xr-x. 2 viktor viktor  114 Nov 22 10:52 backup-diary.txt
3802509 drwxr-xr-x. 2 viktor viktor 4096 Nov 22 10:34 bigger-files
3802513 -rwxr-xr-x. 2 viktor viktor  114 Nov 22 10:52 hard-link.txt
3802510 drwxr-xr-x. 2 viktor viktor 4096 Nov 22 10:33 some-pics
3802511 drwxr-xr-x. 3 viktor viktor 4096 Nov 22 10:33 weird-filenames
```

I.e. `hard-link.txt` is a link to `backup-diary.txt`. I can copy the directory to the encrypted filesystem without a problem:

```
[viktor@roussettus Temp]$ rsync -aH backup-test /mnt/backup-plaintext/
[viktor@roussettus Temp]$ ll -i /mnt/backup-plaintext/backup-test/
total 8
9452762649550924626 -rwxr-xr-x. 2 viktor viktor 114 Nov 22 10:52 backup-diary.txt
9452758242914478922 drwxr-xr-x. 2 viktor viktor   0 Nov 22 10:34 bigger-files
9452762649550924626 -rwxr-xr-x. 2 viktor viktor 114 Nov 22 10:52 hard-link.txt
9452758247209446220 drwxr-xr-x. 2 viktor viktor   0 Nov 22 10:33 some-pics
9452758255799380814 drwxr-xr-x. 2 viktor viktor   0 Nov 22 10:33 weird-filenames
```

You can see the hard link structure is preserved, both files point to node 9452762649550924626.

However, when I try to restore the files, the hard link structure is not preserved:

```
[viktor@roussettus Temp]$ rm -rf backup-test/
[viktor@roussettus Temp]$ ll -i backup-test/
ls: cannot access 'backup-test/': No such file or directory
[viktor@roussettus Temp]$ rsync -aH /mnt/backup-plaintext/backup-test ~/Temp/
[viktor@roussettus Temp]$ ll -i backup-test/
total 20
3802513 -rwxr-xr-x. 1 viktor viktor  114 Nov 22 10:52 backup-diary.txt
3802509 drwxr-xr-x. 2 viktor viktor 4096 Nov 22 10:34 bigger-files
3802514 -rwxr-xr-x. 1 viktor viktor  114 Nov 22 10:52 hard-link.txt
3802510 drwxr-xr-x. 2 viktor viktor 4096 Nov 22 10:33 some-pics
3802511 drwxr-xr-x. 3 viktor viktor 4096 Nov 22 10:33 weird-filenames
```

The inodes are different 3802513 and 3802514. However, I have to say that something really weird happened: I did the test a few times, and once they were preserved! 

I use a Fedora29 system, the un-encrypted filesystem is extfs4, the encrypted filesystem is on a SAMBA share mount.

Best Regards,
Viktor

**Comment by vsenderov** [comment]
Note that this is probably some sort of SAMBA issue, as I did similar test, when the encrypted filesystem is simply a directory on my Linux box and this behavior did not appear. So it is probably not an issue with gocryptfs.

**Comment by rfjakob** [comment]
Wow, those inode numbers on smb are HUGE. What is the smb server? Windows?

**Comment by rfjakob** [comment]
Question 2: Can you do a

     ll -i backup-encrypted

as well? Are the inode numbers also in the 9452762649550924626 range?

**Comment by rfjakob** [comment]
Closing due to no response
