### ISSUE TITLE
hardcoded paths to /bin

### ISSUE THREAD

**Issue by voobofdoom** [rfjakob/gocryptfs#278]
Exotic distro's (nixos in particular) keep stuff in unusual places, ie /run/current-system/sw/bin.

Is it at all possible to rely on $PATH or better yet, just IO.read the passwd file straight from go? I kinda fail to see the point in spawning a process to get a string from a file with a predetermined location. I didn't exactly go through the codebase either, so there might actually be plenty of good reasons i'm clueless about, no criticism was implied. Seems redundant on the surface, that's all.

This is the place that borked on me a little, not critical, since i could simply use extpass directly, but still would be nice to have it working.
https://github.com/rfjakob/gocryptfs/blob/743c7705b21575fe97e5da5722ec344c76badd60/internal/readpassword/read.go#L102

Thank you so much for this cool piece of software!

**Comment by rfjakob** [comment]
Yeah, the "cat" thing is kind of a hack, but it allows to reuse most of the "extpass" code. This can definitely be improved, I'll take a look!
