### ISSUE TITLE
[newbie] gocryptfs could be mounted on cloud by 2 or more users simutaneously?

### ISSUE THREAD

**Issue by ccchan234** [rfjakob/gocryptfs#279]
I am new and I know gocryptfs is for cloud encryption and should do that.

BUT I googled for more info and I really cant find info to say that
it's SAFE to do that.

as per folder there is a *.diriv I doubt if there is a crash from 2 user,
may render the content not able to read back.

for win, I use: google file stream + cppcryptfs
for linux, I use: rclone mount google drive + gocryptfs.

Pls just point me to the relevant material will be good enough, thanks

**Comment by rfjakob** [comment]
I don't think there is documentation discussing this, so don't feel bad for not finding any ;)

So there are two cases where you can get problems when syncing through the cloud:

1) Two users modify the same file at the same time. Only one version will survive this, the other modification will be inaccessible.

2) Two users create a directory at the same location (same name at same path) at the same time. This is the problem described in https://github.com/rfjakob/gocryptfs/issues/151 . Only one directory will survive this, the other one will become inaccessible.

If you keep this limitation in mind I think you'll be fine with having the filesystem mounted simutaneously.
Even if (1) or (2) happens, the files are still there but inaccessible, though recovering them is a pain.

As another option, both problems disappear when you use `-plaintextnames` when creating the filesystem. Warning: this means file names are not encrypted!
