### ISSUE TITLE
Question about automounting (passwordless)

### ISSUE THREAD

**Issue by xelra** [rfjakob/gocryptfs#281]
I'm using gocryptfs on a remote server. Right now I use it all manually, but I'd really like to change that and I was wondering whether some of you guys know how this could be made possible.

What I want to achieve:
- Automatically mount gocryptfs after a reboot
- Not having to login and enter a password
- Not storing the password on the remote server
- Approving the mount with my smartphone

The main attack I want to guard against is theft of the server or theft of the data while the server is offline. 

I've been brooding over this problem for a long time and my research has always brought me into the realm of PAM modules, but I just can't wrap my head around how this all comes together.

The things I believe could make this possible are `pam_mount`, `pam_yubico`, a YubiKey and/or maybe some systemd stuff.
After a reboot, the system tries to mount the gocryptfs volume. Then `pam_yubico` connects to the YubiCloud and I get a notification on my smartphone. I have to unlock my smartphone and hold my NFC-enabled YubiKey against it. Now the YubiCloud gets back to my server and `pam_yubico` provides the password for mounting the gocryptfs volume.

I have no idea whether this is possible at all or whether something really crucial is missing from that scheme and I'd really like your input on the matter. I also don't know what kind of response I'd get back from the YubiCloud and whether gocryptfs would need some kind of TOTP or HOTP support intergrated.

**Comment by rfjakob** [comment]
I believe the fundamental question is: can yubicloud provide a fixed password on request? As far as i see, totp or hotp are not enough, you need to get the password to gocryptfs, so it can unlock the master key.

If this is possible, I would try to avoid PAM, and have a shell script run on boot that does the work.

**Comment by Slamdunk** [comment]
> can yubicloud provide a fixed password on request?

YubiCloud no, but Yubikey yes: https://support.yubico.com/support/solutions/articles/15000006480-understanding-core-static-password-features

Nevertheless it would be awesome for Gocrypyfs to implement FIDO U2F or FUDO2 standard, there already are some go library, even in official debian/ubuntu repos, that provide API in go to interact with Yubikeys :+1:

**Comment by rfjakob** [comment]
I think fido u2f is not suitable for data encryption, because it needs a trusted server.

**Comment by rfjakob** [comment]
Note to self: Keepassxc apparently can use a yubikey

![screen_007](https://user-images.githubusercontent.com/286847/54948844-ef6ce000-4f3d-11e9-9375-a18e33a1bc67.png)

**Comment by mhogomchungu** [comment]
SiriKali git version now supports yubikey's challenge-response feature.

![Screenshot_20190529_213502](https://user-images.githubusercontent.com/3496115/58582149-c4fb1400-8259-11e9-83d6-6bc329709b47.png)

**Comment by rfjakob** [comment]
Looking at https://developers.yubico.com/yubikey-personalization/Manuals/ykchalresp.1.html , one can use the `ykchalresp` to get a fixed password:

```
$ ykchalresp -2 'Sample #2'
0922d3405faa3d194f82a45830737d5cc6c75d24
```

This can be trivially used as the gocryptfs password, like this:

```
$ ykchalresp -2 'Sample #2' | gocryptfs /path/to/my/fs /path/to/my/mnt
```

However, this needs a locally connected yubikey. I don't see a way to make this work remotely.
