### ISSUE TITLE
Feature request: Support 'volname" argument on MACOS

### ISSUE THREAD

**Issue by mhogomchungu** [rfjakob/gocryptfs#283]
More info about the feature request is here[1].

Gocryptfs currectly doesnt not take the mentioned option and it unconditionally sets it and i think it should allow its users to specify it if they want to use none default value.

SiriKali uses its own default when a user does not set it.

[1]. https://github.com/mhogomchungu/sirikali/issues/83

**Comment by rfjakob** [comment]
I don't see why a user would want to set this to anything but the mountpoint name. It's super confusing when you see different names in Finder and on the shell.
