### ISSUE TITLE
gocrypt-xray and how to use it

### ISSUE THREAD

**Issue by lucaschultz** [rfjakob/gocryptfs#284]
Hi,

please excuse the stupid question but I'm a newbie in the whole cli and programming business. I'm also new on GitHub (created my account to ask you this question) so I'm not a 100% sure it is common to ask questions by filing issues.

My question: how do I use the xray tool you provide? I'm using gocryptfs on macOS, installed via Homebrew. I did some research on google and in your documentation, however I don't get the hang of it.

Do I need to download the xray tool manually and use it like an script? I tried that but can't seem to get it working. Basically I  would like to use it for getting the masterkey of a filesystem that I created using a shell script ...

Thank you for the great tool you provide!

**Comment by rfjakob** [comment]
Yes questions via tickets are fine!

Yes the xray tool is a command line app, there is the help text which you get by running it without any arguments:

```
$ ./gocryptfs-xray 
Usage: gocryptfs-xray [OPTIONS] FILE

Options:
  -dumpmasterkey
    	Decrypt and dump the master key

Examples:
  gocryptfs-xray myfs/mCXnISiv7nEmyc0glGuhTQ
  gocryptfs-xray -dumpmasterkey myfs/gocryptfs.conf
```

If you want to get the master key, you'd use it like this:
```
gocryptfs-xray -dumpmasterkey myfs/gocryptfs.conf
```

**Comment by rfjakob** [comment]
I guess that means the homebrew install does not include gocryptfs-xray ? No problem. Follow https://github.com/rfjakob/gocryptfs#compile , and use `./build-without-openssl.bash` instead of `./build.bash`. Openssl is a headache on MacOS. You will find the gocryptfs-xray application in the `gocryptfs-xray` folder.

**Comment by rfjakob** [comment]
gocryptfs-xray now has a man page at https://github.com/rfjakob/gocryptfs/blob/master/Documentation/MANPAGE-XRAY.md . When you install gocryptfs, you should also get this man page installed, and view it using

    man gocryptfs-xray
