### ISSUE TITLE
Feature request: add key file support

### ISSUE THREAD

**Issue by heinrich-ulbricht** [rfjakob/gocryptfs#288]
Coming from e.g. TrueCrypt one might be used to using one or multiple key files to encrypt a vault. Those key files plus the password would then be needed for mounting. It would be nice to have key file support in gocryptfs.

(The `passfile` parameter currently seems too restricted in its semantics and furthermore can only be specified once.)

**Comment by heinrich-ulbricht** [comment]
(A similar idea was #78 but in a more specific context and with only one key file.)

**Comment by rfjakob** [comment]
What you could currently do is to store the gocryptfs.conf outside the encrypted directory. When mounting, you pass the path via "-config", which is effectively like a (single) keyfile.

**Comment by marek22k** [comment]
The issue has been closed, but I can't figure out how to specify a (binary) keyfile?
