### ISSUE TITLE
Deprecate v0.6 and older filesystems in v1.0

### ISSUE THREAD

**Issue by rfjakob** [rfjakob/gocryptfs#29]
My current plan is to drop support for filesystems created by gocryptfs v0.6 and older in gocryptfs v1.0. This will get rid of a lot of compatibility code and keep the gocryptfs codebase clean and maintainable. Also, users of `<= v0.6` filesystems are missing at least one security improvement (128 bit GCM IVs).

I have created a wiki page showing the compatibility matrix: https://github.com/rfjakob/gocryptfs/wiki/Compatibility 

Opinions? Disagreement?

**Comment by kofalt** [comment]
No objections, assuming that the upgrade path of mounting a newer binary and copying data over still works! :+1:

**Comment by rfjakob** [comment]
Upgrade guide added to the wiki: https://github.com/rfjakob/gocryptfs/wiki/Upgrading

**Comment by rfjakob** [comment]
v1 has been released, this is done.
