### ISSUE TITLE
Symlinks in the plain folder

### ISSUE THREAD

**Issue by willrnsantana** [rfjakob/gocryptfs#291]
I have the following issue

Trying to use goencryptfs to backup my personal data to the cloud
But as the amout of data itself is large, I have it spread on multilple drives using gryhole (https://www.greyhole.net/)

Grayhole creates a dir with the symlinks to the files itself or their copies (when you command it to have more than one copy of those files)

Anyway. I can't reverse crypt the whole drives as I only need backup of part of the data. Let's say:

/myDisk/myDocs/somefile.doc -> /drive1/somefile.doc
/myDisk/myDocs/somefile.jpg -> /drive3/somefile.jpg
/myDisk/myMovies/somemovie.mp4 -> /drive5/somemovie.mp4 (I don't need to backup this)

So I'm creating the reverse crypt dir this way:
gocryptfs -reverse /myDisk/myDocs /myDisk/Encrypted

In the /myDisk/Encrypted folder I have the files names and symlinks obfuscated but any attempt to copy any of them reports:

cp: cannot stat ‘lSpWEA69y51oq2f0s6S2LA’: No such file or directory

Any way to resolve it making the encrypted mount walk the symlinks? Maybe plaintext names (not a very good solution)

Thanks in advance
Will

**Comment by willrnsantana** [comment]
PS: 

Did a reinit in the plain folder, now using plaintext names. In this way the copy/sync tasks work
It seem to be a direct issue with the tasks and the obfuscation of the symlinks targets (pretty obvious)

Have not tried the files itself to see if the backed up files are really encrypted or the plain files targeted by the links

Att,
Will

**Comment by willrnsantana** [comment]
Just did the test

The files targeted by the symlinks in the encrypted folder are not encrypted themselves.
If the file is in the plain folder itself (none in my case but I've created one to test), then it's encrypted normally

So:
- If I obfuscate the names, no backup possible
- If I don't obfuscate the name, the files targeted by the symlinks are not encrypted at all

Att,
Will

**Comment by rfjakob** [comment]
Hi! Looking at https://github.com/gboudreau/Greyhole/wiki/HowGreyholeWorks :

> Samba is configured to use opaque symbolic links, i.e. what are in fact symbolic links in the shares appear as normal files to clients.

I believe you could mount this samba share, and this should make the symlinks regular files. Then you can use gocryptfs -reverse to encrypt.

**Comment by willrnsantana** [comment]
You were absolutely right, @rfjakob 

Using the NFS mounts did the trick. I thought of the same a little after opening the issue and just did the tests with success.
Thank you so much.

Att,
Will
