### ISSUE TITLE
Can filename/foldername encryption be disabled?

### ISSUE THREAD

**Issue by dakkusingh** [rfjakob/gocryptfs#3]
See discussion here
https://github.com/rfjakob/gocryptfs/issues/2#issue-114509562 and here https://github.com/rfjakob/gocryptfs/issues/2#issuecomment-152951598

> No, not at the moment. I guess the use case is that you want to download single files from Dropbox, and with encrypted filenames you obviously cannot choose the right one.
I will add a parameter, probably --plaintextnames, to enable this.

**Comment by rfjakob** [comment]
I have added the "--plaintextnames" option that you can use when creating the filesystem:

    $ gocryptfs --init --plaintextnames my_encrypted_files
    [...]
    $ gocryptfs my_encrypted_files my_decrypted_files

**Comment by dakkusingh** [comment]
rfjakob, thats brilliant stuff, and so fast.. I love it! Thanks you..

**Comment by dakkusingh** [comment]
I am not familiar with GO but this commit looks interesting..
https://github.com/rfjakob/gocryptfs/commit/de56fe9e3503d98e359551072633c804794b94e1

**Comment by rfjakob** [comment]
Normally, gocryptfs.conf is invisible in the decrypted directory because it
is not a valid encrypted filename.
But with filename encryption disabled, we run into trouble if the user
creates an encrypted file with that name.

**Comment by dakkusingh** [comment]
i think this is where a conf parameter like this would be handy :)
https://github.com/rfjakob/gocryptfs/issues/4

**Comment by rfjakob** [comment]
Hehe, yes

**Comment by rfjakob** [comment]
This has also got its own testcase now, see 765411cc70577a6332f2eb3f446364878555a8bd . Closing the ticket.
