### ISSUE TITLE
Providing the password via stdin

### ISSUE THREAD

**Issue by petres** [rfjakob/gocryptfs#30]
Could it be implemented that the password is provided via stdin to the `gocryptfs` command. Right now I am getting: 
> Could not read password from terminal: inappropriate ioctl for device

Additional question: Are there some security concerns in providing the password in that way. It doesn't have to be stdin, some other file descriptor would be also fine.
Thanks!

**Comment by rfjakob** [comment]
Out of interest, where will the password come from? A graphical prompt?
(Also, are you aware of the "-extpass"?)

**Comment by petres** [comment]
I already tried the option `-extpass` with zenity and it works well. 

Basically I want that a program - which knows already the password (and yes, through a graphical prompt) - to be able to call `gocryptfs` and providing directly the password. Sure, I could write the password in a file or an environmental variable and use `-extpass` to grab it from there, but wouldn't a mechanism which doesn't have to exec another program to get the password a better way?

Actually I thought that would be trivial change.

**Comment by rfjakob** [comment]
Makes sense. I'll take a look.

**Comment by rfjakob** [comment]
Should be no problem. I will implement this early next week.

**Comment by rfjakob** [comment]
Here we go. Works for you?

**Comment by rfjakob** [comment]
And no, passing the password through stdin is good and secure.

**Comment by petres** [comment]
It's working like a charm! Thanks!
