### ISSUE TITLE
ListXattr no longer works for files without read/write permission

### ISSUE THREAD

**Issue by slackner** [rfjakob/gocryptfs#308]
This bug report refers to the `symlink_race` branch.

In order to reproduce this issue, run the following commands in a gocryptfs volume:
```
$ touch xattrtest
$ setfattr -n user.foo -v bar xattrtest
$ chmod 000 xattrtest 
$ getfattr xattrtest 
```

On normal file systems, this prints something like:
```
# file: xattrtest
user.foo
```
However, due to the recent changes, it now fails with

```
getfattr: xattrtest: Permission denied
```

More discussion about this issue can be found here: https://github.com/rfjakob/gocryptfs/commit/2286372603f506cf719654a9901de0749c544b12.

**Comment by slackner** [comment]
A similar issue occurs when trying to set extended attributes to a file that only has write permissions (because the internal code will still try to open it with read permissions).

**Comment by rfjakob** [comment]
The /proc/self/fd trick with a directory seems to really work:
```
$ mkdir /tmp/x
$ exec 99< /tmp/x
$ ls -l /proc/self/fd | grep 99
lr-x------. 1 jakob jakob 64 Jan  2 19:33 99 -> /tmp/x
$ touch /tmp/x/foo
$ ls -l /proc/self/fd/99/
-rw-rw-r--. 1 jakob jakob 0 Jan  2 19:33 foo

# Rename the directory
$ mv /tmp/x /tmp/y

# Access through fd still works
$ ls -l /proc/self/fd/99/
-rw-rw-r--. 1 jakob jakob 0 Jan  2 19:33 foo
```

**Comment by rfjakob** [comment]
I just realized that `/proc/$$/fd` would be the actually correct path. The above only works accidentially because ls inherits the file descriptors from bash and does not close them.

**Comment by slackner** [comment]
What might also be an option, before we change the whole code again: Maybe `ListXattr` would also work with `flags = O_PATH`? Then we could just pass the desired flags (read, write, or O_PATH) to `fs.Open`.

**Comment by slackner** [comment]
Hm, I just tested this idea, and unfortunately it does not work. The function complains that it would be a bad file descriptor when using `flags = O_PATH`. :(

**Comment by slackner** [comment]
Awesome, thanks for the fast response! :+1: I've already tested the updated branch and everything seems to work for me.

A minor suggestion: I would suggest to use `RDONLY` instead of `WRONLY` in the mac OS fallback path (see https://github.com/rfjakob/gocryptfs/commit/b214be5e3f76dd17efc9832131f4a7e0414b4cea#r31823221). This bug report can be closed once you've decided if that is something you want to adjust.

**Comment by rfjakob** [comment]
Whoops, copy-paste error. Fixed by https://github.com/rfjakob/gocryptfs/commit/0fd7637624c6994ce50be8a374648352f3f52501 , thanks
