### ISSUE TITLE
rsync: readdir: Invalid argument (22) in reverse mode with rsync --force

### ISSUE THREAD

**Issue by yunesj** [rfjakob/gocryptfs#312]
I'm getting a lot of `rsync: readdir: Invalid argument (22)` errors when rsyncing gocryptfs in reverse mode.

```
sh-3.2# rsync -av --force /Volumes/Encrypted jeff@server:/mnt/rsync_backups/laptop
building file list ...

rsync: readdir("/Volumes/Encrypted/reDzH4YT_BrwYSPzD7pg/qmv3x6KODjIAG0W-KDsQ/D-Ya_f7vRPazfN_izLNw/6snOUlLjVOJ5328PuMLw/k8HqbnZdR7YmPwdijsRw"): Invalid argument (22)
[lots more errors]
```
The paths correspond to normal directories, as far as I can tell (using the socket to decrypt the names).

I've always rsync'ed my reverse mode gocryptfs this without a problem, but noticed some files (those in directories that became symlinks?) were not being copied, so I added `--force`.

Maybe this has something to do with rsync, the force option, and/or temporary rsync files?

**Comment by yunesj** [comment]
Yes, MacOS. It wasn't the same version, which I know because I upgraded gocryptfs so that I could use the `--exclude` option. However, I don't know if the version is the culprit, because I also:

1) upgraded from `rofs-filtered | gocryptfs` to `gocryptfs --exclude`, and
2) added `--force` and later `--delete` in order to address a few expected errors about deleting directories and creating symlinks.

I'm currently using version `gocryptfs v1.6.1; go-fuse [vendored]; 2018-12-17 go1.11.4`.

**Comment by rfjakob** [comment]
Maybe this: https://github.com/hanwen/go-fuse/blob/425e8d5301f6ca119f7abfe798920dbf24a396c7/fuse/nodefs/dir.go#L45

Would you be comfortable with modifying the code a bit and compile yourself for debuggin?

**Comment by slackner** [comment]
If this fixes it, it would mean that its (most likely) the same bug(s) as in https://github.com/hanwen/go-fuse/issues/252. Osxfuse uses a single fuse handle for arbitrary many directory accesses, and expects `Readdir` to work properly.

**Comment by slackner** [comment]
Also see the following paragraph I added to the bug report:

> What this means is that even with the lastOffset handling fixed, there is a slight chance of things going wrong when a process triggers a refill while a different process is just in the middle of enumerating a long list of entries. go-fuse could also work around that by maintaining multiple directory listings, and returning the correct one depending on which offset is passed, but this sounds a bit ugly. Maybe use hashes as offset, and resume based on the given hash (would still mix different states, but at least not skip any entries)? But then the file system could be vulnerable to hash collision attacks...

**Comment by rfjakob** [comment]
I *guess* this has been fixed via https://github.com/hanwen/go-fuse/issues/252#issuecomment-464125203 .
