### ISSUE TITLE
A GUI front end to gocryptfs

### ISSUE THREAD

**Issue by mhogomchungu** [rfjakob/gocryptfs#32]
Greetings.

This is not a bug report but i didnt know of where else to put this so i am saying it here.Hope you dont mind discussing non bugs in your bug tracker.

I have a project called "cryfs-gui[1] and i just added support for unlocking gocryptfs volumes and i though of informing you and users of your project of my GUI tool just in case they want a GUI tool to access their gocryptfs volumes.

Currently,the project can only unlock gocryptfs,it can not create them.

The project can also unlock gocryptfs volumes that uses an external config file(It supports the --config option).

Attached screenshot shows cryfs-gui main windows will unlocked volumes from all supported file systems.

Key points of my tool are:
1. It can manage volumes using passphrases.
2. It can manage volumes using keyfiles.
3. It can manage volumes using a combination of a key and a keyfiles.
4. It can manage volumes using passphrases hosted in KDE's kwallet,GNOME's libsecret and an internal system backed by libgcrypt.

[1] https://github.com/mhogomchungu/cryfs-gui

![screenshot_20160731_223707](https://cloud.githubusercontent.com/assets/3496115/17278904/774d96f4-5770-11e6-8a3b-8de593dc9a90.png)

**Comment by rfjakob** [comment]
Hi! No, that's fine, as gocryptfs doesn't have a mailing list, let's use the ticketing system for everything.

That cryfs-gui got gocryptfs support is pretty awesome :)
I have already noticed cryfs-gui some time ago and it looked pretty good to me. I just cloned, built and tested. Works fine on Fedora 24. I will link it in the [comparison table](https://nuetzlich.net/gocryptfs/comparison/) as a third-party GUI.

If you want to add volume create support, you can just pipe the password into `gocryptfs -init DIRECTORY`. Example in bash:

    mkdir /tmp/foo
    echo mypassword | gocryptfs -q -init /tmp/foo

**Comment by rfjakob** [comment]
Added to the table. Just post to this ticket or write to jakobunt@gmail.com if there is something I can help with.

**Comment by mhogomchungu** [comment]
Thanks for the addition.I think i should add my one question here and my one comment here and then i will close this "bug" and will start opening different bug reports if a reason to do so comes up.

For now,the comment i have is that i think you should support "-rw" option to compliment the "-ro" option. I think most mounting tools accepts both and erroring out with "-rw" option seems odd to me.

The question is,is it possible to implement statfs[1] API to return the properties of the gocryptfs volume and not the file system that hosts the gocryptfs volume?

For example,i have a gocryptfs volume on my home directory and the API currently returns properties of my home folder which is not very useful. Output is below:

```
Block Size: 4 KB
Used Blocks: 40741941
Free Blocks: 5952311
Total Blocks 44431494
Used Space: 155.42 GB
Free Space: 14.07 GB
Total Space: 169.49 GB
Used %: 91.70%
```
Not very informative since those properties seems to be of my home directory and not of the gocryptfs volume.

cryfs-gui seems to do this right since it returns the properties of the encrypted folder as seen below:

```
Block Size: 31.94 KB
Used Blocks: 15688
Free Blocks: 462106
Total Blocks 477794
Used Space: 489.29 MB
Free Space: 14.07 GB
Total Space: 14.55 GB
Used %: 3.28%
```

At a glance,i know the space usage of the cryfs volume is 489MB and it will be nice if it was possible to get the same info with gocryptfs.

[1] http://linux.die.net/man/2/statfs

**Comment by mhogomchungu** [comment]
Its now possible to create gocryptfs volumes.

**Comment by mhogomchungu** [comment]
Just though i should inform that i made a new version of cryfs-gui(1.3.2) that added support for creating and unlocking gocryptfs volumes and binary packages for various distributions can be installed by following instructions in this link: http://software.opensuse.org/download.html?project=home%3Amhogomchungu&package=cryfs-gui

ps:
click the icon the icon of prefered distribution to reveal its instructions.

**Comment by rfjakob** [comment]
Tested 1.3.3 on Fedora 24, works nicely.

**statfs**: gocryptfs does not keep track of the used space, so no, it cannot provide that info. It's pretty cool that cryfs does that, though. I wonder where this is stored.

**Comment by rfjakob** [comment]
Oh, looks like it doesn't actually store it anywhere. It counts it on the fly. You could say it runs "du -s" on the encrypted folder for every statfs.

**rw**: You can use `-o rw` or `-ro=0`, but I don't see the use case for adding a another `-rw` flag

**Comment by mhogomchungu** [comment]
"-o ro" works.
"-o rw" works.

The above two compliments each other and that is good.

"-ro" works.
"-rw" does not work.

The above seems strange to me and that is why i commented on it.

I think i should close this "bug" report since it has served its purpose.

**Comment by mhogomchungu** [comment]
Just though i should write to inform that i have changed the name of my project from "cryfs-gui" to "SiriKali" and the front page for the new name is: https://mhogomchungu.github.io/sirikali/

I though i should change the name and use a neutral one since the tool nolonger works with only cryfs.

Will appreciate if you could update the link where you added "cryfs-gui" and change it to "SiriKali".

**Comment by rfjakob** [comment]
Cool. I have updated https://nuetzlich.net/gocryptfs/comparison/
