### ISSUE TITLE
Gocryptfs does not implement GetPath method called by FUSE

### ISSUE THREAD

**Issue by slackner** [rfjakob/gocryptfs#324]
The loopbackFileSystem class in go-fuse contains a method

```
func (fs *loopbackFileSystem) GetPath(relPath string) string {
	return filepath.Join(fs.Root, relPath)
}
```

This combines the encrypted root directory with the unencrypted relative path, and thus doesn't make much sense. To verify that this method is indeed called by the FUSE layer, apply the following patch and run the tests: http://ix.io/1xB1

**Comment by rfjakob** [comment]
Wow

**Comment by slackner** [comment]
Sorry for the noise. After doing some more tests, I believe this is more a theoretical issue. The patch above doesn't trigger this issue, its necessary to add the `panic` in `go-fuse` itself. However, the only path that goes through `GetPath` is the `.gocryptfs.reverse.conf` file in reverse mode. Since there isn't anything critical to fix, I am closing this bug.

In the long term, to minimize the risk of any operations bypassing gocryptfs, it would actually be better to omit the `loopbackFileSystem` layer altogether. In forward mode we don't use it at all (hopefully, all ops should be implemented), and in reverse mode only for the config file - or am I missing something?
