### ISSUE TITLE
PreserveOwner: switch to Setreuid/Setregid?

### ISSUE THREAD

**Issue by rfjakob** [rfjakob/gocryptfs#339]
This ticket tries tries to summarize the discussion about whether we should use Setreuid/Setregid for handling PreserveOwner correctly. (PreserveOwner = running as root with `-allow_other`) 

Getting all corner-cases right with allow_other is tricky, by calling Setreuid+Setregid we let the kernel handle all the complexity. Open bugs: #327 #336 #337 #338

On Linux, Setreuid+Setregid only affects one thread, so this would work:
1) runtime.LockOSThread
2) Setregid
3) Setreuid
4) runtime.UnlockOSThread

MacOS has settid: https://github.com/rfjakob/gocryptfs/issues/327#issuecomment-452359224

> On macOS there is apparently settid, but we would have to write our own syscall wrappers. Some resources that might help (if we decide to go into this direction):

I'm ok with dropping support for PreserveOwner on MacOS and see if anybody complains.

Proposed patches for Create() by @slackner 

Approach 1: call Setreuid in Create(): http://ix.io/1xX9

> this would be a fix for Create (fixing the mode race condition + fixing all the SGID problems)

Approach 2: add OpenatUser helper: http://ix.io/1xY2

> The approach in my previous draft patch has the disadvantage that it also affects *.name files. While this might seem nice at first (it would be consistent with reverse mode, where *.name files and gocryptfs.diriv files also inherit the uid/gid of the main file/directory), it has the disadvantage of making other operations like Chown, Rename, ... much more complicated. Whenever WriteLongNameAt is used we have to switch to the correct user, even if it was not necessary before.
> 
> A slightly different approach based on changing effective permissions is shown in this patch: http://ix.io/1xY2. By adding new syscallcompat wrappers, we can put all the ugly code in a separate file and minimize the region during which we have to lock OSThread. Similar syscall wrappers would be necessary for other functions that depend on the uid/gid.
> 
> What are your thoughts? Does using effective permissions make things sufficiently easier, or should we stick to the previous Fchown approach (and handle SGID inheritance manually)?

**Comment by rfjakob** [comment]
Performance-testing with this mockup shows no change:

```diff
diff --git a/internal/syscallcompat/sys_linux.go b/internal/syscallcompat/sys_linux.go
index 5c180ec..7a8d032 100644
--- a/internal/syscallcompat/sys_linux.go
+++ b/internal/syscallcompat/sys_linux.go
@@ -59,6 +60,9 @@ func Fallocate(fd int, mode uint32, off int64, len int64) (err error) {
 
 // Openat wraps the Openat syscall.
 func Openat(dirfd int, path string, flags int, mode uint32) (fd int, err error) {
+       runtime.LockOSThread()
+       defer runtime.UnlockOSThread()
+
        if flags&syscall.O_CREAT != 0 {
                // O_CREAT should be used with O_EXCL. O_NOFOLLOW has no effect with O_EXCL.
                if flags&syscall.O_EXCL == 0 {
```

**Comment by slackner** [comment]
Since manual SUID/SGID inheritance involves a lot of complexity (and it is difficult to get all details right), I am in favor of letting the kernel handle it. To avoid breaking things on macOS, we can implement syscall wrappers using the existing `Fchmod*` approach (see the second draft patch above). Of course this is not safe against race-conditions, but the macOS emulation code is not very race-condition safe anyway.

As soon as we have better testing on macOS (I am currently looking into some ways to achieve that), we  can get rid of the emulation code and implement the `settid` approach.

**Comment by slackner** [comment]
One thing I would suggest to change compared to the second draft patch: We can just always pass the fuse context (or `nil`) to `OpenatUser`, i.e.

```
if !fs.args.PreserveOwner {
    context = nil
}
...
if !fs.args.PlaintextNames && nametransform.IsLongContent(cName) {
    ...
    fd, err = syscallcompat.OpenatUser(..., context)
```

It would have the advantage that we can minimize changes to all the FUSE methods (effectively, only have to replace `Openat` with `OpenatUser`). When `context` is `nil`, it will internally fallback to `Openat`.

**Comment by rfjakob** [comment]
> Since manual SUID/SGID inheritance involves a lot of complexity (and it is difficult to get all details right), I am in favor of letting the kernel handle it.

I agree. @slackner has implemented the necessary changes in PR https://github.com/rfjakob/gocryptfs/pull/340 and I have just merged it.
