### ISSUE TITLE
Access FUSE call does not respect passed context

### ISSUE THREAD

**Issue by slackner** [rfjakob/gocryptfs#347]
While further reviewing the code, I noticed that there are still problems with `Faccessat`. The code currently looks like this:

```
// Faccessat exists both in Linux and in MacOS 10.10+, but the Linux version
// DOES NOT support any flags. Emulate AT_SYMLINK_NOFOLLOW like glibc does.
func Faccessat(dirfd int, path string, mode uint32) error {
	var st unix.Stat_t
	err := Fstatat(dirfd, path, &st, unix.AT_SYMLINK_NOFOLLOW)
	if err != nil {
		return err
	}
	if st.Mode&syscall.S_IFMT == syscall.S_IFLNK {
		// Pretend that a symlink is always accessible
		return nil
	}
	return unix.Faccessat(dirfd, path, mode, 0)
}
```

While this statement in the comment at the beginning is true, it looks like `sys/unix` already deals with the lack of `AT_SYMLINK_NOFOLLOW` by implementing the full access check in usermode, see: https://github.com/golang/sys/blob/2be51725563103c17124a318f1745b66f2347acb/unix/syscall_linux.go

My first thought was that we could simplify the code, however, there are even more problems. The original `Access` FUSE call also has a context parameter, which is currently ignored entirely. We would either need a `*User` version, or should always emulate the behavior in usermode. The go code for Linux might be a useful template for that.

**Comment by rfjakob** [comment]
Hmm, looks like we need FacessatUser. As unix.Faccessat calls Geteuid, we could do it like the other *User functions, and let unix.Faccessat handle the complexity.

**Comment by slackner** [comment]
This would be one option. Alternatively we could implement a check similar to what is done in `sys/unix` in usermode, with the option to pass a fuse context to override the current user. This code could be used for both Linux and macOS. Note that (at least to my knowledge) this issue is not security critical, since the kernel cannot rely on the result of the `Access` FUSE call.

**Comment by slackner** [comment]
Correction, it seems like we don't need user impersonation:

> If the default_permissions mount option is given, this method is not called.

For `gocryptfs`, the `-allow_other` option always enables `default_permissions`. I'll still leave this open in case we want to simplify the function or add some comments to clarify why this is not a problem.

**Comment by rfjakob** [comment]
Hmm, the handling for AT_SYMLINK_NOFOLLOW was only added in July 2018: https://github.com/golang/sys/commit/bd9dbc187b6e1dacfdd2722a87e83093c2d7bd6e

Can we depend on this already? Does Debian Testing already have it?

**Comment by slackner** [comment]
I would suggest to keep the current code, and just add a check to return `EACCES` when `PreserveOwner` is set (to avoid that this code is ever used in a situation where the result would be security critical).

* If `PreserveOwner` is false, gocryptfs will still do a proper security check on following operations (since we run all syscalls with the right user, and avoid following symlinks everywhere else).
* If `PreserveOwner` is true (and thus `default_permissions` is enabled), its the kernels job to do the access check for us. The function should thus never be called and we don't have to worry about impersonation.

**Comment by rfjakob** [comment]
Dropped our own helper in https://github.com/rfjakob/gocryptfs/commit/0805a63df1b5f915b228727f6074c2506922d0ad , let's risk it

**Comment by slackner** [comment]
I fear you might have to revert this change. The flag does not appear to exist on macOS, see
https://github.com/rfjakob/gocryptfs/commit/d44fe89ba4f3252c5bd00c4f7730197732f2a26a

**Comment by slackner** [comment]
Note that implementing a user-mode check (as in https://github.com/golang/sys/blob/2be51725563103c17124a318f1745b66f2347acb/unix/syscall_linux.go) would work on both Linux and macOS - but the `sys/unix` wrappers don't do it (yet).

**Comment by rfjakob** [comment]
Reverted. Maybe we can try again in a year or so.

**Comment by rfjakob** [comment]
Checking PreserveOwner is problematic, because it is not set if gocryptfs does not run as root.

**Comment by rfjakob** [comment]
What about just commenting the behavoir, https://github.com/rfjakob/gocryptfs/commit/1a0d23db755f372d182e703f8e61bef8e63b2dcb ?

**Comment by slackner** [comment]
Thats also fine.

**Comment by rfjakob** [comment]
Merged
