### ISSUE TITLE
MacOS: test failure in TestMvWarningSymlink

### ISSUE THREAD

**Issue by slackner** [rfjakob/gocryptfs#349]
```
--- FAIL: TestMvWarningSymlink (0.01s)
    main_test.go:234: mv: cannot resolve /var/folders/6x/tlqzyq0j38j9xw6qkl8p3jcm0000gq/T/gocryptfs-test-parent/987494714/default-plain/TestMvWarningSymlink: /foo
        
    main_test.go:235: exit status 1
FAIL
FAIL	github.com/rfjakob/gocryptfs/tests/defaults	5.738s
```

Needs further investigations.

**Comment by slackner** [comment]
Output with `-fusedebug` and `-d`:
https://gist.githubusercontent.com/slackner/2d844d1f7b201d02afafc01cbbc2a2e5/raw/4e21dc3db7606654b9717fd7ffa338b7e4d9cc64/gistfile1.txt

**Comment by rfjakob** [comment]
Looking at the debug output
```
2019/01/15 12:02:38 rx 4: SYMLINK i1 ["TestMvWarningSymlink" "/foo/bar/baz"] 34b
[...]
2019/01/15 12:02:38 rx 4: READLINK i13 
2019/01/15 12:02:38 tx 4:     OK,  "/foo/bar/baz"
--- FAIL: TestMvWarningSymlink (0.01s)
    main_test.go:234: mv: cannot resolve /var/[...]/TestMvWarningSymlink: /foo
```
I wonder if mv on MacOS always prints a warning when it encounters a broken symlink

**Comment by slackner** [comment]
No, it doesn't. For testing purposes I created a broken symlink and moved it around a couple of times with `mv`. The interesting part though: It also doesn't happen when manually testing in a gocryptfs mount.

Maybe also timing related? There are some really weird race-conditions going on. I was also trying to reproduce #312 - however, instead of the original error, I somehow managed to trigger an `EIO` in `readlinkat` a couple of times.

**Comment by rfjakob** [comment]
Found where the `mv` message comes from: https://github.com/practicalswift/osx/blob/4c9b4581f398ec2d64f102508346cb9e8d764fbc/src/file_cmds/mv/mv.c#L296

**Comment by slackner** [comment]
Ah, that explains a lot. This is the fallback path for moving files to different devices (see the `errno == EXDEV` check). Apparently, moving broken symlinks across devices just isn't handled correctly in the macOS `mv` tool.

I think we can just skip this test on macOS.

**Comment by rfjakob** [comment]
Skipping on error.
