### ISSUE TITLE
Symlinks in encrypted folder

### ISSUE THREAD

**Issue by beornf** [rfjakob/gocryptfs#35]
During running the gocryptfs set of benchmarks I noticed the following error:
`UNTAR: tar: linux-3.0/arch/microblaze/boot/dts/system.dts: Cannot utime: No such file or directory`

This seems to be due to the target of symlinks being encrypted in a different way to encfs. This is an example to reproduce in a mounted folder:
`touch test;
ln -s test symlink;
touch -h symlink;
No such file or directory`

**Comment by rfjakob** [comment]
Thanks for the report! This also has a testcase now: https://github.com/rfjakob/gocryptfs/commit/8f1e51789dd29b9fae82a059e2890bf9873cdd4c
