### ISSUE TITLE
MacOS: test failure in TestUtimesNano

### ISSUE THREAD

**Issue by slackner** [rfjakob/gocryptfs#350]
```
--- FAIL: TestUtimesNano (0.00s)
    matrix_test.go:628: "/var/folders/6x/tlqzyq0j38j9xw6qkl8p3jcm0000gq/T/gocryptfs-test-parent/720506002/default-plain/utimesnano": no such file or directory
FAIL
FAIL	github.com/rfjakob/gocryptfs/tests/matrix	3.027s
```

The exact reasons for this issue are not known yet. Some initial analysis was done in https://github.com/rfjakob/gocryptfs/pull/343:

> Hm, this bug is really mysterious. Here is what I found out so far:
> 
> * Yes, it only worked because of defer. When closing the file immediately the test fails. This can be explained based on the go-fuse code, which uses file-based operations as long as at least one FD is open.
> * Disabling the fuse cache (setting all timeouts to 0) does not help.
> * Disabling the directory fd cache does not help.
> * Adding a time.Sleep of 2 seconds after creating the file also doesn't help.
>
> However, to make sure that the Utimens call is forwarded at all, I put debug messages into the FUSE function. They confirm that ENOENT is returned from the unix.UtimesNanoAt call?!

**Comment by slackner** [comment]
Output with `-fusedebug` and `-d`:
https://gist.githubusercontent.com/slackner/bbeabbc4aeb4b85b103a98ba048ec0a8/raw/18e13c2689aef0f39b84fbcb30c17349fe259341/gistfile1.txt

**Comment by slackner** [comment]
Apparently Utimens is internally a `Setattr` call (mapped in `fuse/nodefs/fsops.go`, function `SetAttr`), however, that still doesn't explain why it doesn't show up.

**Comment by rfjakob** [comment]
Hmm, and syscall.UtimesNano calls setattrlistTimes on MacOS: [code](https://github.com/golang/go/blob/55715c1738adc0a9b6a7037390a700763365e284/src/syscall/syscall_bsd.go#L507)

Maybe setattrlistTimes just does not work at all on FUSE on MacOS?

**Comment by slackner** [comment]
The link above points to `UtimesNano`, but we are using `UtimesNanoAt`. Source code is here:
https://github.com/golang/sys/blob/1b2967e3c290b7c545b3db0deeda16e9be4f98a2/unix/syscall_bsd.go#L562

```
func UtimesNanoAt(dirfd int, path string, ts []Timespec, flags int) error {
	if ts == nil {
		return utimensat(dirfd, path, nil, flags)
	}
	if len(ts) != 2 {
		return EINVAL
	}
	err := setattrlistTimes(path, ts, flags)
	if err != ENOSYS {
		return err
	}
	return utimensat(dirfd, path, (*[2]Timespec)(unsafe.Pointer(&ts[0])), flags)
}
```

It also ends up calling `setattrlistTimes`, which makes me wonder: How is this command supposed to work when the `dirfd` is not even passed?

**Comment by slackner** [comment]
I was wondering what the `dirfd`-based fallback code at the end of the function does. The answer is "apparently nothing":

```
func utimensat(dirfd int, path string, times *[2]Timespec, flags int) error {
	// Darwin doesn't support SYS_UTIMENSAT
	return ENOSYS
}
```

I think we are on the right track here. The only question is how to fix it.

BTW: Should we also get rid of the `loopbackFile` interface? It looks like it is only used for `Utimens`:

```
// Utimens FUSE call
func (f *File) Utimens(a *time.Time, m *time.Time) fuse.Status {
	f.fdLock.RLock()
	defer f.fdLock.RUnlock()
	return f.loopbackFile.Utimens(a, m)
}
```

**Comment by rfjakob** [comment]
Huh. That's an additional problem.

What I meant before is: matrix_test.go:626 calls `syscall.UtimesNano`, which calls `setattrlistTimes` on darwin. And this never shows up in the FUSE log, maybe because OSXFuse does not know how to handle it?

**Comment by slackner** [comment]
> What I meant before is: matrix_test.go:626 calls syscall.UtimesNano, which calls setattrlistTimes on darwin. And this never shows up in the FUSE log, maybe because OSXFuse does not know how to handle it?

Well, the call definitely ends up in `gocryptfs`. I already verified that the code is called by adding a debug statement in our code. My suspicion would be that `ENOENT` occurs exactly because the `dirfd` is ignored and it ends up looking for the file in the current working directory.

> In fusefrontend.File we embed nodefs.NewDefaultFile(), and a normal member "loopbackFile" we have nodefs.NewLoopbackFile(). I think this is OK as calls to loopbackFile must be explicit.

Yes, it is not a big deal, but due to the broken `UtimensNanoAt` wrappers, we now have to carefully investigate/test the problem anyway.

**Comment by slackner** [comment]
Another advantage of getting rid of `loopbackFile`: The macOS go-fuse implementation requires multiple syscalls to emulate `Utimens` on files and does not really support nanosecond timestamp precision. This is also fixed in the draft patch I submitted as a pullrequest.
