### ISSUE TITLE
Empty directories without execute/write permission cannot be deleted 

### ISSUE THREAD

**Issue by slackner** [rfjakob/gocryptfs#354]
Steps to reproduce:

* In a gocryptfs forward mount create some test directories:

```
mkdir -m 0400 testdir0400
mkdir -m 0500 testdir0500
mkdir -m 0600 testdir0600
```

* Try to delete them with `rmdir testdir0400 testdir0500 testdir0600` (or with separate `rmdir` calls).

The expected result would be that all directories can be deleted. However, in current versions this fails with:

```
rmdir: failed to remove 'tempdir****': Permission denied
```

The debug log of gocryptfs shows a similar error for all directories:

```
Rmdir: Renaming gocryptfs.diriv to gocryptfs.diriv.rmdir.10213527197615036096
Rmdir: Renaming gocryptfs.diriv to gocryptfs.diriv.rmdir.10213527197615036096 failed: permission denied
```

While the `Rmdir` FUSE call implementation already has code to handle `EACCES`, this code path is not used here since the directory can be opened without any problems.

**Comment by rfjakob** [comment]
Fixed via https://github.com/rfjakob/gocryptfs/commit/962c52364415496b64a42b49fe5f90d593dc09f7 .
