### ISSUE TITLE
mount point must be empty?

### ISSUE THREAD

**Issue by brainchild0** [rfjakob/gocryptfs#357]
Mounts are usually allowed for nonempty targets, and there are cases when this ability is particularly useful, the actual contents of the mount point being masked until the mount is removed.

However, `gocryptfs` appears to complain in this case.

Was lack of support a design choice?  Would you consider support, as it seems to be the standard?

**Comment by rfjakob** [comment]
Mounting over a non-empty directory is useful in some situations, but most of the time this happens due to user error (already mounted, wrong directory etc). You can pass `-nonempty` to disable the check.

**Comment by befbeflime** [comment]
This no longer works with fuse3. fuse3 has no nonempty anymore and therefore complains when nonempty is used. 

Is there another way to mount a non empty dir with gocryptfs  ?

**Comment by agvantibo-again** [comment]
> This no longer works with fuse3. fuse3 has no nonempty anymore and therefore complains when nonempty is used. 
> 
> Is there another way to mount a non empty dir with gocryptfs  ? 

FUSE2 mounting errors out with `operation not permitted` on NixOS so it's only ever possible to use FUSE3. A config option to skip this check would be great
