### ISSUE TITLE
Unexpected directory unmount after 3-10 seconds | Netdata.io incompatibility?

### ISSUE THREAD

**Issue by crimue** [rfjakob/gocryptfs#358]
I just started using gocryptfs and it is awesome! However: **On my setup the mounted directory got unmounted everytime after 3-8 seconds**. Then I disabled the netdata.io service and it worked perfectly. 

I found this thread: [netdata prevents autofs automatic unmounts #2173](https://github.com/netdata/netdata/issues/2173) and when I exclude my mounted decrypted directory (as described) from the **statvfs()** call it works.

I do not know if this is the right place to post this issue. I hope somebody finds this helpful.

Version: v1.6.1
System: Debian GNU/Linux 9 (stretch)

**Comment by rfjakob** [comment]
Interesting! Do you see something in

journalctl -f

when this happens?

**Comment by crimue** [comment]
I just tested it (without the netdata.io fix) but only this is displayed when it fails/unmounts...

Jan 23 17:49:00 archiv systemd[1]: Removed slice User Slice of root.
Jan 23 17:49:23 archiv systemd[1]: Created slice User Slice of root.
Jan 23 17:49:23 archiv systemd[1]: Starting User Manager for UID 0...
Jan 23 17:49:23 archiv systemd[1]: Started Session c2 of user root.
Jan 23 17:49:23 archiv systemd[1153]: Listening on GnuPG cryptographic agent (access for web browsers).
Jan 23 17:49:23 archiv systemd[1153]: Reached target Timers.
Jan 23 17:49:23 archiv systemd[1153]: Listening on GnuPG cryptographic agent and passphrase cache.
Jan 23 17:49:23 archiv systemd[1153]: Reached target Paths.
Jan 23 17:49:23 archiv systemd[1153]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Jan 23 17:49:23 archiv systemd[1153]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
Jan 23 17:49:23 archiv systemd[1153]: Reached target Sockets.
Jan 23 17:49:23 archiv systemd[1153]: Reached target Basic System.
Jan 23 17:49:23 archiv systemd[1153]: Reached target Default.
Jan 23 17:49:23 archiv systemd[1153]: Startup finished in 13ms.
Jan 23 17:49:23 archiv systemd[1]: Started User Manager for UID 0.


Is there something else I could do?

**Comment by rfjakob** [comment]
Hmm. Can you try mounting like

gocryptfs -fg -nosyslog -fusedebug -debug

?

This should get you a lot of output, hopefully helps to find out what happens.

**Comment by crimue** [comment]
Yep. Got this output: 

OpenSSL enabled
cli args: &main.argContainer{debug:true, init:false, zerokey:false, fusedebug:true, openssl:true, passwd:false, fg:true, versio                                                                                                              n:false, plaintextnames:false, quiet:false, nosyslog:true, wpanic:false, longnames:true, allow_other:false, reverse:false, aess                                                                                                              iv:false, nonempty:false, raw64:true, noprealloc:false, speed:false, hkdf:true, serialize_reads:false, forcedecode:false, hh:fa                                                                                                              lse, info:false, sharedstorage:false, devrandom:false, fsck:false, trezor:false, dev:false, nodev:false, suid:false, nosuid:fal                                                                                                              se, exec:false, noexec:false, rw:false, ro:false, masterkey:"", mountpoint:"/mnt/storage/user/chris/ver3", cipherdir:"/mnt/stor                                                                                                              age/user/chris/cry", cpuprofile:"", extpass:"", memprofile:"", ko:"", passfile:"", ctlsock:"", fsname:"", force_owner:"", trace                                                                                                              :"", exclude:main.multipleStrings(nil), config:"/mnt/storage/user/chris/cry/gocryptfs.conf", notifypid:0, scryptn:16, idle:0, _                                                                                                              configCustom:false, _ctlsockFd:net.Listener(nil), _forceOwner:(*fuse.Owner)(nil)}
Password:
Decrypting master key
CryptoCore.Wipe: Only nil'ing stdlib refs
frontendArgs: {
        "Cipherdir": "/mnt/storage/user/chris/cry",
        "PlaintextNames": false,
        "LongNames": true,
        "PreserveOwner": false,
        "ForceOwner": null,
        "ConfigCustom": false,
        "NoPrealloc": false,
        "SerializeReads": false,
        "ForceDecode": false,
        "Exclude": null
}
Filesystem mounted and ready.
**CryptoCore.Wipe: Wiping AEADBackend 3 key** <-- On Unmount

**Comment by crimue** [comment]
Yep. Got this output: 

OpenSSL enabled
cli args: &main.argContainer{debug:true, init:false, zerokey:false, fusedebug:true, openssl:true, passwd:false, fg:true, versio                                                                                                              n:false, plaintextnames:false, quiet:false, nosyslog:true, wpanic:false, longnames:true, allow_other:false, reverse:false, aess                                                                                                              iv:false, nonempty:false, raw64:true, noprealloc:false, speed:false, hkdf:true, serialize_reads:false, forcedecode:false, hh:fa                                                                                                              lse, info:false, sharedstorage:false, devrandom:false, fsck:false, trezor:false, dev:false, nodev:false, suid:false, nosuid:fal                                                                                                              se, exec:false, noexec:false, rw:false, ro:false, masterkey:"", mountpoint:"XXXXXXXXXX", cipherdir:"XXXXXXXXXX", cpuprofile:"", extpass:"", memprofile:"", ko:"", passfile:"", ctlsock:"", fsname:"", force_owner:"", trace                                                                                                              :"", exclude:main.multipleStrings(nil), config:"XXXXXXXXXX", notifypid:0, scryptn:16, idle:0, _                                                                                                              configCustom:false, _ctlsockFd:net.Listener(nil), _forceOwner:(*fuse.Owner)(nil)}
Password:
Decrypting master key
CryptoCore.Wipe: Only nil'ing stdlib refs
frontendArgs: {
        "Cipherdir": "XXXXXXXXXX",
        "PlaintextNames": false,
        "LongNames": true,
        "PreserveOwner": false,
        "ForceOwner": null,
        "ConfigCustom": false,
        "NoPrealloc": false,
        "SerializeReads": false,
        "ForceDecode": false,
        "Exclude": null
}
Filesystem mounted and ready.
**CryptoCore.Wipe: Wiping AEADBackend 3 key** <-- On Unmount

**Comment by rfjakob** [comment]
Looks like a regular unmount. But why would netdata unmount gocryptfs?

**Comment by crimue** [comment]
I just discovered: When I mount to /tmp/directory it does work even when netdata is running...

**Comment by rfjakob** [comment]
I tried to repro and installed netdata here on my Fedora box. gocryptfs filesystems did not become unmounted. But als they did NOT show up in the netdata webinterface.

What netdata version do you use, and how did you install it? (I noticed that there are several ways to install netdata, with the recommended way being to compile from source)

**Comment by crimue** [comment]
I installed Netdata via the one-line command (bash <(curl -Ss https://my-netdata.io/kickstart.sh)).
Could it be a problem with MergerFS?

Background info: encrypted folder on external USB HDD + disk pooling with MergerFS
Netdata version: netdata v1.12.0-rc3-9-gb537efdb
Gocryptfs version: gocryptfs v1.7-rc1-65-gda3ba5e; go-fuse v20170619-77-g425e8d5; 2019-01-22 go1.7.4

 Thanks for your support!

**Comment by crimue** [comment]
Update: 
Switched Homeserver (new CPU+Motherboard) & new install of debian and now it works without the netdata fix. Maybe incompatible/to old CPU (Intel E8600)? 

Issue solved. 
Thank you again for this awesome piece of software (AES NI on the new CPU make usage extremly fast)!

**Comment by rfjakob** [comment]
Thanks for the update. It's still a mystery to me what happens, though. CPU features are autodetected at runtime, and if that failed, I would expect a crash, not a clean unmount... Let's call it a day, I'll close the ticket.
