### ISSUE TITLE
Go's built in GCM implementation is faster than openssl/stupidgcm?

### ISSUE THREAD

**Issue by fd0** [rfjakob/gocryptfs#36]
Hi,

I had a quick look and the section about the openssl wrapper "stupidgcm" caught my eye. I ran the test and it seems that (at least for Go 1.6 and 1.7) the internal GCM implementation is way faster or at least as fast as openssl. I ran the benchmark on my (rather recent) laptop on linux/amd64:
```
Benchmark4kEncStupidGCM-4   	  200000	     12032 ns/op	 340.42 MB/s
Benchmark4kEncGoGCM-4       	  300000	      4035 ns/op	1014.99 MB/s
PASS
```

And on an older Server VM, also on linux/amd64:
```
Benchmark4kEncStupidGCM-4          20000             62587 ns/op          65.44 MB/s
Benchmark4kEncGoGCM-4              20000             61047 ns/op          67.10 MB/s
PASS
```

Maybe it's time to deprecate the openssl/stupidgcm wrapper :)

Thanks for your work!

**Comment by rfjakob** [comment]
Indeed it is, but only if your CPU has AES acceleration ;) Check this out, on my machine:

```
Benchmark4kEncStupidGCM-2   	   50000	     24397 ns/op	 167.88 MB/s
Benchmark4kEncGoGCM-2       	   20000	     91609 ns/op	  44.71 MB/s
```
gocryptfs automatically chooses the faster implementation depending on your CPU and the Go version.

**Comment by rfjakob** [comment]
If you want so see way more info on that, check https://github.com/rfjakob/gocryptfs/issues/23 . That ticket has benchmarks with lots of CPUs.

**Comment by fd0** [comment]
Ok, that makes sense. I was about to try this on a machine without AES-NI, but couldn't find one ;)
