### ISSUE TITLE
is simultaneous access to the same cipher folder supported?

### ISSUE THREAD

**Issue by mhogomchungu** [rfjakob/gocryptfs#362]
Somebody somewhere claimed that gocryptfs supports having the same cipher folder accessed from multiple mount points at the same time and i am wondering if this statement is correct or not.

A quick search failed to give me an answer

**Comment by rfjakob** [comment]
Yes, this will work OK. I suggest to use the `-sharedstorage` flag to disable caching and get changes from the underlying folder immediately into the mount.

**Comment by slackner** [comment]
With the recent changes, wouldn't it make sense when `-sharedstorage` also disables the directory FD cache?

**Comment by rfjakob** [comment]
Indeed that would make sense

**Comment by mhogomchungu** [comment]
Thanks for the answer and i think this ability should be prominently mentioned in the front page because it sets gocryptfs apart since most other solution do not support this.

**Comment by mhogomchungu** [comment]
The source of my question was a statement made here[1]. SiriKali is now able to store in its favorites entries,mount and display two volumes that share the same cipher folder path.

[1] https://github.com/mhogomchungu/sirikali/issues/91

**Comment by rfjakob** [comment]
Well, mounting the filesystem twice on the same computer... That's unorthodox. Certain things will not work. For example, file locks only affect one mount.
