### ISSUE TITLE
Mounting with sudo

### ISSUE THREAD

**Issue by jaccokrijnen** [rfjakob/gocryptfs#365]
```
$ gocryptfs encrypted decrypted
Cannot open config file: open encrypted/gocryptfs.conf: permission denied
```

This is expected as `gocryptfs.conf` is in this case owned (and only readable) by another user.

Trying with sudo:

```
$ sudo gocryptfs encrypted decrypted
Password: 
Decrypting master key 

Your master key is:
...
Filesystem mounted and ready.
$
```

However, it results in
```
$ ls -lah
...
d?????????  ? ?     ?        ?            ? decrypted
...
```
with no mounted filesystem. I can only remove the `decrypted` directory after killing `gocryptfs` which is still running.

This might just be my incorrect usage, but the result was somewhat unexpected (it can be decrypted just fine under the right user).

**Comment by rfjakob** [comment]
Can you try

sudo ls

?

**Comment by jaccokrijnen** [comment]
That indeed lists the directory correctly. However, even running as root I cannot see any files in the directory (which should be non-empty).

**Comment by jaccokrijnen** [comment]
Edit: ignore the last comment, the directory was indeed supposed to be empty in this case.

**Comment by jaccokrijnen** [comment]
Thanks, it makes sense to me now.

**Comment by slackner** [comment]
By default FUSE file systems can only be accessed by the user who mounted them. Note that you can use the `-allow_other` switch to override that behavior, e.g., when multiple users should be able to access a shared gocryptfs mount point. The kernel will still check the owner/group and access permissions.
