### ISSUE TITLE
Pad files to 4k

### ISSUE THREAD

**Issue by tocrypt** [rfjakob/gocryptfs#366]
It seems like you already have a feature to checksum files, which would add a few bytes to each file.

To prevent directory correlation attacks ("They have exactly this directory -- this directory of PS4 ISO object files"), please add a -pad option to cause _all_ files to be padded to 4k. Perhaps the true file size can be stored in the four bytes at the start of the file, the file contents, and padding with random data to a multiple of 4k.

**Comment by tocrypt** [comment]
Perhaps also, offer a range of padding, --pad-length=x where x would cause the file to have 0 to x additional 4k blocks of padding. This would help randomize the size of the directory.

"If you look at the sub-directories, comparing _all_ of them to this PS4 image, all of them are padded exactly to the correct 4k multiple."

**Comment by rfjakob** [comment]
Hi! Thanks for the suggestion, but due to performance and correctness concerns, this is not planned. There is a detailed discussion in an older ticket: https://github.com/rfjakob/gocryptfs/issues/57
