### ISSUE TITLE
Google File Stream Error

### ISSUE THREAD

**Issue by loungebob** [rfjakob/gocryptfs#368]
When I use gocrypfs on a Google Drive FS account it all works well apart from occasional errors. Every now and the Google Drive Sync/Uploader throws an error saying some files could not be uploaded and had been deleted from Google Drive FS and moved to lost and found. 
When I check the lost and found folder there’s the mentioned files - I assume they are only files since they’re usually a couple of MBs and GBs - but since they are already encrypted I have no way of seeing/telling what those files are.
I figured when I copy those to a folder and then add the conf file (I dont have the diriv file for those) I should be able to mount that folder and see at least the decrypted files without the proper file names. But I could figure out what they are by opening/playing them.
But when I mount the folder I dont see any files in the mounted decrypted drive. Even though they are in the folder thats mounted.
What am I doing wrong?

**Comment by rfjakob** [comment]
I guess what happens here is gocryptfs cannot decrypt the file names and ignores them. This is expected, as the file names only can be decrypted with the right gocryptfs.diriv file. gocryptfs will print warnings whenever it cannot decrypt a file name.

You can work around that like this:

Create a new file in the mounted gocryptfs, let's call it "lost_file_1". This will give you a valid file name in the *encrypted* folder. Now, in the encrypted folder, rename a file you want to look at to the encrypted file name of "lost_file_1".

**Comment by loungebob** [comment]
thank you. that worked.

but it also lead me to another question I asked you before but I think I need to do it again lol.

as I understood it, the diriv files, should they get corrupted, deleted, whatever only amount to not having the proper files names anymore. I assumed, the files would show up with the encrypted file names in the mounted drive, not not show up at all like the above.

so, having stored and encrypted now about 500TB in hundreds of thousands of files, will those be easily recoverable (with whatever filename but the original ones) should the diriv files get lost?

and how would I go about backing those up - I dont assume you plan to include that as an app function? should I use a backup tool and only backup the complete directory structure including only the diriv files?

**Comment by Nodens-** [comment]
Google Drive FS for Linux? As far as I know there is no such client. Are you using cppcryptfs on Windows Google Drive FS client? If so you're in the wrong issue tracker heh.

**Comment by rfjakob** [comment]
> will those be easily recoverable (with whatever filename but the original ones) should the diriv files get lost?

The files can always be recovered using the same process. If it is too many files, you could write a shell script to automate it.

Actually I think that the data files are more important than the diriv files, and I don't think having a backup of just the diriv files is neccessary.

**Comment by rfjakob** [comment]
Closing for now.

**Comment by loungebob** [comment]
yeah sorry, dog needed surgery l, was a bit distracted. I agree, data files top prio. disagree about the importance of being able to easily recover file names. after data of course, to me, file names are kind of the most important aspect of data management. 
but I found an easy way to automate diriv and folder structure backup and focus more on meta data for now. 
thanks for the feedback though, much appreciated.
