### ISSUE TITLE
How to (cross) compile with OpenSSL for ARMv7

### ISSUE THREAD

**Issue by wutr** [rfjakob/gocryptfs#372]
Hi,

I've compiled v1.6.1 for ARMv7 using GOOS=linux GOARCH=arm GOARM=7 on my intel machine, but so far have been unable to work out how to compile with OpenSSL support. I thought it would just work, but when compiling some errors appear that don't clarify anything:

```
[gocryptfs]$ GOOS=linux GOARCH=arm GOARM=7 ./build.bash
# github.com/rfjakob/gocryptfs/internal/cryptocore
internal/cryptocore/cryptocore.go:101:17: undefined: stupidgcm.New
# github.com/rfjakob/gocryptfs/internal/prefer_openssl
internal/prefer_openssl/prefer_go1.5.go:12:5: undefined: stupidgcm.BuiltWithoutOpenssl
```

When looking at the `crossbuild.bash` file it seems using `-tags without_ssl` is required, but performance is abysmal (7.5MB/s) so any improvement would be welcome!

I believe I have the required libraries (dev libs are standard on Arch, right?), or do I need specific ARM versions? Is that a thing?

**Comment by wutr** [comment]
I haven't yet found out how to get it to compile, however, by installing a Debian chroot on the target system using the `armhf` architecture I managed to get a `gocryptfs -speed` result using OpenSSL which was roughly 4x faster than the version I built using `-tags without_ssl`, proving it is possible to compile it for that system.

**Comment by rfjakob** [comment]
Hi! You'll need to have an ARM gcc installed. On my Fedora box, I did
```
sudo dnf install gcc-arm-linux-gnu
```
then, this *could* theoretically work:
```
CC=arm-linux-gnu-gcc CGO_ENABLED=1 GOARCH=arm GOARM=7 go build
```
but I got
```
# runtime/cgo
_cgo_export.c:3:10: fatal error: stdlib.h: No such file or directory
 #include <stdlib.h>
          ^~~~~~~~~~
compilation terminated.
```
so I guess I also need a ARM glibc, and probably also ARM openssl and whatnot.

I think building inside a Debian ARM chroot is easier. Note that you can also build inside a ARM chroot on your Intel box by using qemu-user-static (see [here](https://wiki.debian.org/QemuUserEmulation#Appendix:_chrooting_into_target_file_systems))
