### ISSUE TITLE
support mount with same target and source?

### ISSUE THREAD

**Issue by brainchild0** [rfjakob/gocryptfs#374]
Assuming no conflict presents with FUSE design, would allowing a mount point to be the same as the source location be considered as a feature?

For regular, recurring mounts, a prescribed mount point is easy and preferred, but when working from mirrors or removable storage, accessing gocryptfs volumes requires the creation or preexistence of temporary mount points.

Greater convenience could be derived from an invocation of the mount command that would simply replace, in the system file tree view, the encrypted store with the unencrypted view.  The user could then work on the volume at its source location as if it were not encrypted.

**Comment by rfjakob** [comment]
The problem here is that the encrypted files would become invisible to the gocryptfs process as well.

There are possibilities to work around that, like "cd"ing into the the directory and then using relative paths everywhere, but this all introduces extra complexity and fragility. So while it may be possible, I don't think it's a good idea.

**Comment by brainchild0** [comment]
I understand that this request is not trivial, but I am wondering whether it is at least more feasible than indicated by your characterization.  

I could be very wrong, of course.  

Critically, I can't get very far looking at the Go source, not knowing the language, and I see that this package is built on a framework called `go-fuse`.  But if file access is occurring in user space, then I think you could achieve the effect by acquiring a directory handle to the source location before applying the mount, and  then using that open handle for all tree traversal of the source.  In fact, opening a directory handle may even be what the system does when the application changes the working directory.  However, you are less likely to experience other problems if you avoid changing the directory and just work with the directory handle.

A further benefit of this approach is that if a mounted source gets moved while mounted, the mount could remain functional, as long as the internal tree of the source is preserved.

I am not aware of specific issues that make me think this approach is more fragile than alternatives, such as what you are doing currently.  Maybe you know better.

The handle, as best I recall system I/O considerations, is  a   resource isolated  from changes in the file system,  such as changes to path structure, as long as the handle stays open and the data in the file system continues to exist.  For this reason one can continue reading an open file even if its location is moved after it is opened. 


Relevant C-header information comes from the [`dirent.h`](http://man7.org/linux/man-pages/man0/dirent.h.0p.html) documentation.

Again, I am not pushing this idea or saying it's easy.  But users could find it useful, though, as I would, and I'm not so convinced that the implementation as quite as problematic from a standpoint of stability as your assessment might suggest.  

So if you change your mind, you have my support.
