### ISSUE TITLE
Trezor returns wrong key

### ISSUE THREAD

**Issue by karel-3d** [rfjakob/gocryptfs#377]
Trezor returns wrong key, because of this issue

https://github.com/xaionaro-go/cryptoWallet/issues/7

Note: I am currently rewriting trezord-go so it could be used as a low-lever trezor library, and I am rewriting xaionaro-go to use that (as a high-level library). 

https://github.com/trezor/trezord-go/pull/147

**Comment by karel-3d** [comment]
I guess if this is fixed, then all the encrypted volumes with the old key will be impossible to decrypt; but if that happens, it's not hard to revert I guess

**Comment by xaionaro** [comment]
> I guess if this is fixed, then all the encrypted volumes with the old key will be impossible to decrypt; but if that happens, it's not hard to revert I guess

Yep. It seems there're extra two bytes attached to the real key.

**Comment by xaionaro** [comment]
Update:

It seems there's no problem actually. The unmarshaling was done here:
https://github.com/conejoninja/tesoro/blob/master/tesoro.go#L864

You've just scared me a lot here :)

**Comment by karel-3d** [comment]
It's still not, I am still working on that. But you are right.
