### ISSUE TITLE
Mac Menubar for GoCryptFS

### ISSUE THREAD

**Issue by warmup72** [rfjakob/gocryptfs#378]
Hi,
no issue but a new small GUI for gocryptfs.
Based on the Project https://github.com/matryer/bitbar I have set up a small plugin for mount, umount and automount.
maybe someone find it useful
https://github.com/matryer/bitbar-plugins/pull/1203/commits/6fde96348d12a722e2aae53ad8d119248c677e7a
![cryptbar10](https://user-images.githubusercontent.com/30272587/54492383-5b0fd700-48c6-11e9-8795-76c6b4b15d9a.jpg)

**Comment by rfjakob** [comment]
Nice! If you want to add it, I will accept pull requests for both

https://github.com/rfjakob/gocryptfs/blob/master/README.md#graphical-interface

and

https://github.com/rfjakob/gocryptfs-website/blob/master/docs/comparison.md#overview (row "User Interface")

**Comment by warmup72** [comment]
Okay - fine - i´ve try the pull request coming weekend. I´m not familiar with github :-)
