### ISSUE TITLE
Document manual decryption (if possible)

### ISSUE THREAD

**Issue by rprieto** [rfjakob/gocryptfs#38]
For me, a strong point in favour of `gocryptfs` over other alternatives (e.g. [securefs](https://github.com/netheril96/securefs) or [CryFS](https://www.cryfs.org/)) is that it seems I'll always be able to decrypt my files without much effort. No complex data structures to traverse or chunks to join manually.

For example if I find an old archive (and its master key) 10 years from now, even if I run on a new fancy operating system that `gocryptfs` doesn't support, I could probably write a shell script that renames all files and decrypts them using `openssl`... just like I could do if I manually used `tar` and `gpg`.

Is that accurate? If so it would be awesome to have some something in the website/docs that emphasize the **no vendor lock-in** aspect and show a basic example of decrypting a folder.

**Comment by rfjakob** [comment]
I think the file [file-format](https://github.com/rfjakob/gocryptfs/blob/master/Documentation/file-format.md) and the [used crypto](https://nuetzlich.net/gocryptfs/security/) is quite well documented and should enable you to write a decoder quickly. That's also what @bailey27 , who created [cppcryptfs](https://github.com/bailey27/cppcryptfs), said.

I have started something like a standalone decoder, [gocryptfs-xray](https://github.com/rfjakob/gocryptfs/commit/3a9bd92754e3b6984c97f7012fd5f030d7f8e46c) (does not decrypt the data yet)

However, I'm not sure if can do it just from the command line. The first roadblock is that according to the
[openssl manpage](https://git.openssl.org/gitweb/?p=openssl.git;a=blob;f=doc/apps/enc.pod;h=b3bf82adc2c7932b677e4ec54beb757e455f9d94;hb=HEAD#l216), AES-GCM is not supported by the command line utility.

**Comment by rprieto** [comment]
You're right, and thanks for putting all these docs together!

Good point about `openssl`. I had run the following, but apparently this only means it supports GCM when used as a library, not from the command line.

```bash
 $ openssl enc -help 2>&1 | grep gcm 
-aes-128-gcm -aes-192-gcm -aes-256-gcm
```

Extra binary "helpers" like `gocrypt-xray` sounds really good 👍 Would you consider making it a separate project? I'm asking because I've had trouble building `gocryptfs` on OSX, but since the standalone tools will be very small and don't need `FUSE` support they should be very easy to build cross-platform.

I'm happy to close this issue.

**Comment by rfjakob** [comment]
I think separating the xray tool would make it harder to keep it in sync with gocryptfs.
Actually I thought gocryptfs would build fine (and even work more or less) or OSX. But you can build gocryptfs-xray without having the go-fuse libraries installed, it does not depend on any.

**Comment by rprieto** [comment]
That's a good point. Do you think there will be many changes to the structure and spec now that you've reached 1.0? Otherwise having a formal/canonical spec would be really nice to encourage other tools to be created (if that's something you're interested in).

I'll give building on OSX another try, and also looking forward to releases having Macos binaries!

**Comment by rfjakob** [comment]
I guess the problem on osx, if any, is getting the right version of openssl installed. The use of openssl is optional and only a performance optimization, but currently you always need it for compilation.

I'll add a way to build gocryptfs completely without openssl next week (using Go build tags).

**Comment by rfjakob** [comment]
The file and directory structure is stable and I don't expect changes. However, v1.1 will add another encryption algorithm for file contents, AES-SIV. Which algorithm is used is indicated in the config file.

**Comment by rprieto** [comment]
Thanks. Depending on what I try on macOS, I get a mix of

```bash
gocryptfs/internal/stupidgcm/locking.go:9:10: fatal error: 'openssl/evp.h' file not found
#include <openssl/evp.h>
```

(wrong version of openssl, I'll figure out how to pass the right library paths)

and

```ruby
package .
       	imports github.com/rfjakob/gocryptfs/internal/configfile: use of internal package not allowed
package .
       	imports github.com/rfjakob/gocryptfs/internal/contentenc: use of internal package not allowed
package .
       	imports github.com/rfjakob/gocryptfs/internal/cryptocore: use of internal package not allowed
```

(that's an odd one)

But this is unrelated to this issue, so I'll close it. Looking forward to `gocrypt-xray`!

**Comment by rfjakob** [comment]
You can now build without openssl using `./build-without-openssl.bash`

The `use of internal package not allowed` looks like gocryptfs is not in the directory the Go compiler expects it to be?

**Comment by rprieto** [comment]
Thanks that's brilliant!

*(sorry about `use of internal package not allowed`, that's a weird issue that pops up every few builds but looks related to my setup. Nothing to do with `gocryptfs`)*
