### ISSUE TITLE
Unmount not possible under Ubuntu 16.04

### ISSUE THREAD

**Issue by andreasmuellerka** [rfjakob/gocryptfs#381]
In version 1.7 unmount is not possible any more. The error message says: target is busy.
I reverted to version 1.6.1.

**Comment by andreasmuellerka** [comment]
Is there a bugfix planned? Does the author reproduced the problem?

**Comment by rfjakob** [comment]
Bug will be fixed if it is one, of course! I have not had the time yet to set up a ubuntu vm, in the meantime:

Could you mount like

gocryptfs -fg -nosyslog -fusedebug

then try to unmount, and then post the log output you get?

**Comment by rfjakob** [comment]
I have downloaded an Uubntu 16.04 VM from https://www.osboxes.org/ubuntu/#ubuntu-16-04-vbox and can reproduce the problem.

**Comment by rfjakob** [comment]
Reported upstream at https://github.com/hanwen/go-fuse/issues/281 . Seems to be a go-fuse library and/or kernel bug.

**Comment by navytux** [comment]
kernel bug reported upstream: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1823972.
