### ISSUE TITLE
New Version with Brew

### ISSUE THREAD

**Issue by warmup72** [rfjakob/gocryptfs#382]
Hi,
is it planed to make the new Version 1.7.0 accessible via brew?
Maybe it would be nice to add the "Homebrew"-Symbole on die first page (e.g. like in the Project https://github.com/jbarlow83/OCRmyPDF )

**Comment by yunesj** [comment]
I have a similar request for Ubuntu Bionic, which currently has gocryptfs 1.4.3. I'm happy to make a new issue if that's preferred.

**Comment by rfjakob** [comment]
Hi! So I have no influence over the homebrew package, but adding the icon looks like a good idea.

For ubuntu bionic, you can simply download the latest linux-static binary from https://github.com/rfjakob/gocryptfs/releases . This binary will "just work" on any x64 linux, actually.

**Comment by lf-zbw** [comment]
Homebrew now have the new version. Homebrew/homebrew-core#38184

**Comment by rfjakob** [comment]
Homebrew icon added, thanks for the suggestion!

**Comment by yunesj** [comment]
It's nice that it can be simply downloaded for linux, but a lot of people prefer to install via a package manager so that upgrades with security updates can happen automatically. Also, it would be nice to know that you are in charge of the distributed app so that we can be sure it's not malware.
