### ISSUE TITLE
User hashed password with -passfile

### ISSUE THREAD

**Issue by warmup72** [rfjakob/gocryptfs#383]
I think it would be safer to use a hashed password with the option -passfile.
Didn´t know if it is possible - i havetried  to hash with openssl
==> openssl passwd -1 -salt $(openssl rand -base64 6)
but the password could not be used.

**Comment by rfjakob** [comment]
Well, you could use any hashing scheme that you want, for example
```
$ echo mypassword | sha256sum 
ddec437eeb1da25a146a24c432d1165bc646daa7fecc6aa14c636265c83caa14  -
```
and then change the password to `ddec437eeb1da25a146a24c432d1165bc646daa7fecc6aa14c636265c83caa14`.

But any way you do it, the thing in the passfile will be a **password-equivalent**...
