### ISSUE TITLE
SELinux: chcon on gocryptfs mount

### ISSUE THREAD

**Issue by andryyy** [rfjakob/gocryptfs#384]
Hi,

First of all a big THANK YOU for gocryptfs. :)

I'm trying to change the context of a gocryptfs mount, as it is `fusefs_t` by default (obviously, yes :)).

When trying to change the context, it says "Operation not supported". I am not aware if that's a fuse limitation (that's my sad guess) or if it can be implemented in a way or another.

Any ideas are welcome.

André

**Comment by rfjakob** [comment]
Can confirm. In a gocryptfs mount:

```
mnt$ touch foo
mnt$ ls -Z foo
system_u:object_r:fusefs_t:s0 foo
mnt$ chcon -t user_tmp_t foo
chcon: failed to change context of 'foo' to ‘system_u:object_r:user_tmp_t:s0’: Operation not supported
```

In my home dir:
```
~$ touch foo
~$ ls -Z foo
unconfined_u:object_r:user_home_t:s0 foo
~$ chcon -t user_tmp_t foo
~$ ls -Z foo
unconfined_u:object_r:user_tmp_t:s0 foo
```

Unforunately, looking at https://bugzilla.redhat.com/show_bug.cgi?id=1272868 , it seems that FUSE does not support changing the context.
