### ISSUE TITLE
Request: Also store modification date

### ISSUE THREAD

**Issue by 1-eric** [rfjakob/gocryptfs#389]
What do you store in the 'gocryptfs.diriv' file in each directory?

Is it possible to also store modification date of the files in the gocryptfs.diriv file?

The reason I ask this is because I upload encrypted files to the cloud, but the cloud server I use will not preserve the modification date of the files but instead change the modification date to the date of upload.

The modification date is valuable for example for a directory full of photos. The photo album application on my computer and phone will then sort the photos based on the modification date. Other dates (change and access) are not important, at least I don't see the need to preserve those dates.

**Comment by rfjakob** [comment]
gocryptfs.diriv just stores 16 random bytes. This randomness is used to make the encrypted filenames unpredictable.

Sorry, I don't think I can store additional metadata like timestamps, or permissions - this would complicate things too much...
