### ISSUE TITLE
Error setting up encryption on a network-folder

### ISSUE THREAD

**Issue by warmup72** [rfjakob/gocryptfs#390]
gocryptfs Version: 1.7
Operating System (incl. Version): macOS 10.14.4

I´ve tried to init a new encryption on a network-Volume:
gocryptfs -init /Volumes/FRITZ.NAS/t/

I get the following error-messages

`If the gocryptfs.conf file becomes corrupted or you ever forget your password, there is only one hope for recovery: The master key. Print it to a piece of paper and store it in a drawer. This message is only printed once. sync /Volumes/FRITZ.NAS/t/gocryptfs.conf.tmp: operation not supported`

If iIset up the encryption local and copy the folder to the network-path I can use it in a normal way!

**Comment by rfjakob** [comment]
Hmm, your FritzNAS does not support `sync`. Using what protocol do you access this FritzNAS? SMB?

**Comment by warmup72** [comment]
Yes it´s a 7490 with a mounted USB-Stick.
I use smb

**Comment by rfjakob** [comment]
Fixed in https://github.com/rfjakob/gocryptfs/commit/8459bb15c1a32561c250a8b688ab4a7ecda0a4aa , thanks for the report!

**Comment by lube62** [comment]
Hi.
I have the same mistake.
I have a folder on a Synology NAS shared with SAMBA
![Selezione_001](https://user-images.githubusercontent.com/30412935/84178987-97a88f00-aa85-11ea-9859-fcd28c1927d8.png)

**Comment by lube62** [comment]
the drive is mounted with Sirikali
![Selezione_002](https://user-images.githubusercontent.com/30412935/84179195-e22a0b80-aa85-11ea-9da6-3d20f695d533.png)

**Comment by rfjakob** [comment]
Hi, I see that you use gvfs to access the Samba server. gvfs has many problems, please use cifs instead. Like this:

    sudo mkdir /mnt/smb
    sudo mount -t cifs -o uid=asterix //bignas.local/casa-condivisa /mnt/smb

**Comment by lube62** [comment]
GRAZIE...

In data 9 giugno 2020 23:38:28 rfjakob <notifications@github.com> ha scritto:
