### ISSUE TITLE
Error when using gocryptfs from bash_profile

### ISSUE THREAD

**Issue by kototama** [rfjakob/gocryptfs#391]
I am using this command in `~/.bash_profile`:

```
gocryptfs -passfile ~/.config/gocryptfs-pass-work /home/user/docs/work_enc /home/user/work_dec &> /tmp/gocryptfs.log
```

After starting the content of `/tmp/gocryptfs.log` is:

```
passfile: reading from file "/home/user/.config/gocryptfs-pass-work"
Decrypting master key
Received trailing garbage after the password
```

and the directory is not decrypted.

When I source manually the `.bash_profile` from a terminal with `source .bash_profile` then the content of the file becomes:

```
passfile: reading from file "/home/user/.config/gocryptfs-pass-work"
Decrypting master key
Filesystem mounted and ready.
```

and the directory is decrypted.

Do you have an idea what is the problem and how to solve it? thanks in advance.

**Comment by rfjakob** [comment]
Thanks for the report. It looks like gocryptfs picks up *something* from stdin when it is running inside the login shell. In any case, when you use `-passfile`, it should not even *try* to read from stdin, so the last commit should fix this.
