### ISSUE TITLE
Mounting doesn't work on MacOS Mojave

### ISSUE THREAD

**Issue by nullgraph** [rfjakob/gocryptfs#397]
I'm MacOS Mojave v10.14.4 (18E226), my gocryptfs version is
```
gocryptfs v1.7; go-fuse [vendored]; 2019-03-22 go1.12.1
```
I installed it through brew. Following the quick start guide, I created a `cipher` and a `plain` directory. I could `gocryptfs -init cipher` without any problem, but I ran into a problem with the mounting:
```
$ gocryptfs cipher plain
Password: 
Decrypting master key
fuse.NewServer failed: exit status 2
Maybe you should run: /Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse
```
I ran `load_osxfuse` as suggested, it didn't give me any feedback so I take it that it went fine. Re-run the mounting command gave the same error though. Any idea?

**Comment by rfjakob** [comment]
Can you check if other FUSE filesystems work - for example sshfs ?

**Comment by nullgraph** [comment]
That was a good hint, I don't have sshfs installed, so I went and tried to install it, the first thing it wanted me to do was installing [Fuse for Mac](https://github.com/osxfuse/osxfuse/releases/tag/osxfuse-3.8.3). Installing that solved my problem. Thanks!
