### ISSUE TITLE
`gocryptfs v1.7; go-fuse [vendored]; 2019-03-22 go1.12.1` crashes in reverse mode on OSX 10.14.4

### ISSUE THREAD

**Issue by yunesj** [rfjakob/gocryptfs#399]
`gocryptfs v1.7; go-fuse [vendored]; 2019-03-22 go1.12.1` crashes on OSX 10.14.4

I'm rsyncing from reverse mode:

```
gocryptfs -ctlsock sock -config /usr/local/etc/reverse-gocryptfs-config -reverse --exclude "Volumes/Reversed" --exclude ".DocumentRevisions-V100" [more excludes] / /Volumes/Reversed
rsync -av /Volumes/Reversed jeff@server:/mnt/backups/laptop
```

Soon after the file transfer starts, I get:

```
rsync: readlink "/Volumes/Reversed/[encrypted-path]" failed: Socket is not connected (57)
rsync: readlink "/Volumes/Reversed/[encrypted-path]" failed: Device not configured (6)
rsync: readlink "/Volumes/Reversed/[encrypted-path]/gocryptfs.diriv" failed: Device not configured (6)
```

And a lot more `Device not configured` errors. After the initial error, I can't `ls` the `/Volumes/Reversed` directory.

Using the socket, I decrypted the first file path that gives the (socket) error. I don't notice anything special about the file, and it changes each time, whether or not `-serialize_reads` is enabled.

Thanks!

**Comment by rfjakob** [comment]
Hi! You should get a backtrace in syslog on a crash, that would be very helpful.

**Comment by rfjakob** [comment]
Alternatively, you coukd run with

-fg -nosyslog

Then you should get it to the terminal

**Comment by yunesj** [comment]
I can no longer reproduce the error. Thanks!
