### ISSUE TITLE
Is it possible to store the keyfile outside of the encrypted folder?

### ISSUE THREAD

**Issue by dakkusingh** [rfjakob/gocryptfs#4]
See discussion here.. https://github.com/rfjakob/gocryptfs/issues/2#issue-114509562 and here https://github.com/rfjakob/gocryptfs/issues/2#issuecomment-152951598

>  Is planned, but there is no parameter yet. For now, you can use a symlink to achieve the effect. (store the gocryptfs.conf somewhere else, place a symlink in the encrypted directory).

**Comment by rfjakob** [comment]
Yes, this is possible since https://github.com/rfjakob/gocryptfs/commit/58592330dc33e194e55fa942d3f375124839f058 . Use the `-config` option to set an arbitrary file path.

**Comment by rfjakob** [comment]
There are no unit tests for this feature yet, though. I will keep this ticket open until I have implemented them.

**Comment by rfjakob** [comment]
Tests have been added in https://github.com/rfjakob/gocryptfs/commit/7a2ab0b233fba71fa03c461a94d50c12dcc1d5e3
