### ISSUE TITLE
Errorhandling and repair

### ISSUE THREAD

**Issue by pos42** [rfjakob/gocryptfs#403]
Hi

I love gocryptfs. But... I have a few times got errors where I cannot delete a directory in my mounted unencrypted file system. Seems to be caused by corrupt gocryptfs.diriv files in the encrypted directory structure.  Not often. but it happens...

Then I had to add a file to this unencrypted directory and look at change timestamps in the encrypted file system to find the file to delete.

I looked for a repair switch by running "gocryptfs --help", but could not find anything useful. I use version 1.7

What is the recommended way of handling such errors? From a personal perspective, adding a repair functionality would be better than adding new features.

 /Peo

**Comment by pos42** [comment]
Just saw "-fsck" is in the man page, but not in the quick help "gocryptfs --help"

I guess it is good if this is added :)

/Peo

**Comment by xNathan** [comment]
Happened here after I created a new folder, and no way to delete it.

Tried run `gocryptfs -fsck`:

```
fsck: error opening dir "path/to/corrupted/new/folder": 2=no such file or directory
```

But I don't know how to fix it. gocryptfs seems doesn't have repairing feature.

System specs:

```
gocryptfs v1.7; go-fuse [vendored]; 2019-03-22 go1.12.1

macOS: 10.14.5 (18F132)
OSXFUSE: 3.8.2
```

**Comment by rfjakob** [comment]
fsck added to help text .Progress for repairing/deleting corrupt files will be tracked in this earlier ticket: https://github.com/rfjakob/gocryptfs/issues/263

**Comment by rfjakob** [comment]
Tracked in #263, closing this ticket
