### ISSUE TITLE
Add VERSION file to the repository

### ISSUE THREAD

**Issue by bexelbie** [rfjakob/gocryptfs#404]
I am working on packaging gocryptfs for Fedora.  One thing I'd like to do is to enable as much of the work the Go SIG has done to make packaging easier.  One of those things is to use the GitHub generated source tar, instead of the one uploaded manually for the release.

As far as I can tell the only difference is the VERSION file.

Can we add that file to the main source tree?  I can work around this by either generating the contents on my own or by forcing in the manually built tar, but I would like to explore this option first.

Also, do you want the VERSION string for distribution built copies to have any additional information?

**Comment by lechner** [comment]
> One of those things is to use the GitHub generated source tar, instead of the one uploaded manually for the release.

In Debian, we use the manual uploads because they are signed. How will you validate upstream sources?

**Comment by bexelbie** [comment]
@lechner it is a good question.  I have written the packaging both ways and when doing my comparison had forgotten there was a signature with the manually generated file.  I had been focused on simplification of my spec file :D

I'd still like to explore the question of whether distro built binaries should be flagged as such in the --version output.

**Comment by rfjakob** [comment]
The release tar is generated by https://github.com/rfjakob/gocryptfs/blob/master/package-source.bash , and it adds the VERSION file and the man page. The man page is generated from markdown using pandoc, I have included it so you don't need to have pandoc installed.

I'd like avoid having the VERSION file in git as it is an additional possibilty for human error.

As for the distro version string, I always like having as much information as possible about what a user is running. Something that allows to find the fedora build job and/or the fedora package version would be nice.

**Comment by bexelbie** [comment]
@rfjakob how does this look:

```
$ gocryptfs --version
gocryptfs v1.7-fedora-1.7-1.fc31; go-fuse 1.0.0; 2019-06-23 go1.12.5
```

**Comment by rfjakob** [comment]
Works for me!

**Comment by bexelbie** [comment]
Cool.  I'll open a ticket when I have something testable in bodhi.
