### ISSUE TITLE
Fedora 30 and Rawhide build ready for testing

### ISSUE THREAD

**Issue by bexelbie** [rfjakob/gocryptfs#406]
I've gotten a build that appears to be great working in Fedora rawhide.  Input/testing/feedback welcome:

https://koji.fedoraproject.org/koji/taskinfo?taskID=36249637

(and soon via dnf on rawhide as `sudo dnf install gocryptfs`)

I am working on Fedora 30 builds, but it takes time as I have to land several dependencies and each takes a week to clear bodhi (no karma).

I do not plan to build for Fedora 29.

**Comment by rfjakob** [comment]
Thank you! I installed the rpm on my Fedora 30 desktop:
```
$ gocryptfs -version
gocryptfs v1.7-Fedora-1.7-1.fc31; go-fuse 1.0.0; 2019-06-23 go1.12.7
```
Looks good, the binary passes the test suite, mounting / copying some files / umounting all works fine here!

**Comment by rfjakob** [comment]
Question, I clicked through the logs at https://koji.fedoraproject.org/koji/buildinfo?buildID=1312947 but did not find anything - does (can?) the build process run the test suite?

**Comment by bexelbie** [comment]
I am glad you found it to be working.  I hope to have proper packages for F30 in mid-august, barring the new packages attracting karma.

The builders, aiui, are incapable of running tests that require fuse.  There is a lot of working being done around CI and I hope that one day we can gate the packages there.  This is still not ready, aiui, for use.

**Comment by bexelbie** [comment]
Was there a specific test suite or command you used?

**Comment by rfjakob** [comment]
What I did is to place the gocryptfs binary from the rpm in the gocryptfs source directory, then comment out lines 40 and 43 in [test.bash](https://github.com/rfjakob/gocryptfs/blob/master/test.bash#L40) so the binary does not get overwritten.

Then you'd run `./test.bash` , and all tests that call the binary will call the one from the rpm.

**Comment by Nodens-** [comment]
Great news! Less building from source on my systems heh.
Question though. Are you building with openssl or without or both?

**Comment by bexelbie** [comment]
@Nodens- it should be with openSSL.  I hadn't considered the need to build one without.

**Comment by bexelbie** [comment]
@rfjakob I've gotten more details on the Fedora CI pipeline and I am working on trying to get the testing done there, since it can't be done in koji.  This is a bit slow going, so if anyone wants to look at this with me, let me know.  It is not a gocryptfs problem, it is understanding the CI

**Comment by bexelbie** [comment]
Fedora 30 build is ready for testing.  If you have a FAS account and can give karma or feedback, that is appreciated.

https://bodhi.fedoraproject.org/updates/FEDORA-2019-00256d9917

**Comment by Nodens-** [comment]
@bexelbie Building without openssl, gocryptfs uses the go implementation which is A LOT faster, except in older systems with CPUs that don't support AES-NI (@rfjakob correct me if I'm wrong and something has changed). If memory serves right, it was also the default for the binaries released here.

**Comment by rfjakob** [comment]
No need to build without openssl. gocryptfs selects between go aes-gcm and openssl aes-gcm acc. to your cpu. Check out https://github.com/rfjakob/gocryptfs/wiki/CPU-Benchmarks and `gocryptfs -speed` .

**Comment by rfjakob** [comment]
The binaries released on github are indeed built without openssl, but this is just so the binary is static, has no dependencies, and works on all linux distributions.

**Comment by Nodens-** [comment]
Thanks for the clarification. I tested and it's working fine. Gave karma as well!

**Comment by bexelbie** [comment]
Thank you @Nodens- barring receiving more karma (2 points) this will be pushed to stable and actually usable in 3-4 days (2 days more in testing, manual push, pick up in next refresh, mirrored)

**Comment by bexelbie** [comment]
Built and shipped in F30 now.

Docs update: https://github.com/rfjakob/gocryptfs-website/pull/13

**Comment by rfjakob** [comment]
Great. Website updated: https://nuetzlich.net/gocryptfs/quickstart/
