### ISSUE TITLE
Switch to new go-fuse API

### ISSUE THREAD

**Issue by slackner** [rfjakob/gocryptfs#409]
According to the go-fuse authors, the pathfs API should be considered deprecated. A documentation for the new API is available at:

https://godoc.org/github.com/hanwen/go-fuse

Are there already plans (or maybe even experimental patches) to switch to this new API?

Best regards,
Sebastian

**Comment by rfjakob** [comment]
Yes, switching to the new api is planned, I hope to get it done till the end of the year. I'll bump the version to 2.0 once complete.

There are no patches yet.

**Comment by rfjakob** [comment]
Work is ongoing now in the gofuse_v2api branch: https://github.com/rfjakob/gocryptfs/commits/gofuse_v2api

Mounting forward mode already works.

**Comment by rfjakob** [comment]
gocryptfs v2.0 uses the new API. v2.0-beta1 & 2 have been released: https://github.com/rfjakob/gocryptfs/releases
