### ISSUE TITLE
fix linter warnings

### ISSUE THREAD

**Issue by vgough** [rfjakob/gocryptfs#41]
I started working on a PR, and noticed that Go lint gives lots of warnings.

Would you accept PRs to fix lint warnings, such as variable names & comments not matching Go standards?

**Comment by rfjakob** [comment]
Yes i think so

**Comment by vgough** [comment]
created pr #42 with most warnings fixed.  There are some additional warnings about package naming (due to underscores in names).

**Comment by rfjakob** [comment]
Oh yes, please let me keep those underscores in internal packages. I think it improves readability a lot.

**Comment by rfjakob** [comment]
Merged as b764917cd5c1b1d61b8ce08e7af0b29793fbbb80
