### ISSUE TITLE
Permission denied errors on vboxsf

### ISSUE THREAD

**Issue by ohir** [rfjakob/gocryptfs#411]
`# gocryptfs v1.7, k4.12.4 x86_64 GNU/Linux`

Strictly related to #105 and to the "write into fd of read-only created" hack.

1) I can not get a rationale behind aforementioned hack. Threat model this hack mitigates stopped to be real somewhen thirty years ago when we moved from the 0777 /tmp to the 01777 one and subsequently to the mkstemp within. If any local adversary can possibly race with us within own by us fs space (0700 dir), he does need not to race at all - he then may tamper with "our" fds at will and possibly read our master key. Remote adversary that owns our remote space can do anything to any file content, even one that on our side of the wire appears to be immutable. This hack cripples gocryptfs and mitigates nothing of real.

2) at its current state — just for the hack against paleothreat — gocryptfs is unusable for any "live" home or other "live" subtree. For backend fs to be mounted over sshfs or vboxsf or even NFS we need to fiddle with mountoptions to force u=rw on the whole tree (what renders $HOME virtually noexec) or to force u=rwx (what makes $HOME vulnerable to plenty of real threats).

@rfjakob : Please consider  -withrw flag and file opens that are not against contemporary OS practices. Making 0700 mandatory for the top of the crypted tree would do more good.
(It would be 0770 for -sharedstorage).

---
P.S. Workaround for others struggling with consequences of this.

Example of shared vboxsf mount, per user in fstab:
```fstab
usersharename /home/.backup_luser vboxsf defaults,uid=nnnn,gid=nn,cache=none,dmode=0700,fmode=0600,umask=077 0 0
```
where nnnn and nn are uid and gid of this particular user. [Do not do fmode=0700! Users must learn to live with noexec home as it used to be 20+ yrs ago.]

**Comment by rfjakob** [comment]
Hi! Sorry i did not get it - what is the problem here?

**Comment by ohir** [comment]
@rfjakob Problem is that many backednd fs-es will not allow the writable fd for a ro opened file.
I stumbled on it trying to use vboxsf/HFS+ stack as backing (crypted) fs. Since both are strict about permissions, gocryptfs fails miserably on them. 

Ie. gocryptfs is opening a 0400 diriv file in hope that it will then write to its fd. Wrong assumption - it can not - then it is reading back the zero file. In this particular stack and NFS4 and likely a few other (eg. zfs).

It can be seen with simple untar that makes new dirs:
```
[... stripped many same errors ...]
tar: ./newdir: Cannot mkdir: Permission denied
tar: ./newdir/newfile: Cannot open: Function not implemented
tar: Exiting with failure status due to previous errors
gocryptfs[3165]: mkdirWithIv: rollback failed: directory not empty
gocryptfs[3165]: WriteDirIV: Openat: permission denied 
gocryptfs[3165]: mkdirWithIv: rollback failed: directory not empty
gocryptfs[3165]: WriteDirIV: Openat: permission denied 
gocryptfs[3165]: mkdirWithIv: rollback failed: directory not empty
gocryptfs[3165]: WriteDirIV: Openat: permission denied 
gocryptfs[3165]: mkdirWithIv: rollback failed: directory not empty
gocryptfs[3165]: go-fuse: can't convert error type: wanted 16 bytes, got 0
gocryptfs[3165]: message repeated 11 times: [ go-fuse: can't convert error type: wanted 16 bytes, got 0]
gocryptfs[3165]: WriteDirIV: Openat: permission denied
gocryptfs[3165]: mkdirWithIv: rollback failed: directory not empty 
gocryptfs[3165]: go-fuse: can't convert error type: wanted 16 bytes, got 0
gocryptfs[3165]: message repeated 2 times: [ go-fuse: can't convert error type: wanted 16 bytes, got 0]
```

**Comment by rfjakob** [comment]
I see. This also happens with sshfs?

**Comment by rfjakob** [comment]
No, sshfs is fine, I just tested it. NFS is also fine as the problem was fixed in https://github.com/rfjakob/gocryptfs/issues/105 . I find it unlikely that ZFS has this problem, as it would be a POSIX violation.

So that leaves only vboxsf, right?

**Comment by ohir** [comment]
It is ok with linux fs-es. I'll test sshfs/HFS+ stack and report later. (_Excuse me for the delay, first prolonged by the bank holiday weekend, now other work is calling_.)

**Comment by rfjakob** [comment]
The thing is, creating the file as 0400 has several advantages

* Protects against programming errors in gocryptfs
* Protects against other apps inadveredly modifying gocryptfs.diriv files
* Saves a chmod syscall

This is not a hack, this is well-document behavoir, check out the note to O_CREAT in https://manned.org/open.2 :

>  Note that this mode applies only to future
>  accesses of the newly created file; the open() call that creates
>  a read-only file may well return a read/write file descriptor.

This is a bug in vboxsf, and as it has a workaround available (" force u=rwx") I don't think gocryptfs should do anything. Please report it against vboxsf.
