### ISSUE TITLE
Directory names in reverse mode

### ISSUE THREAD

**Issue by kovica** [rfjakob/gocryptfs#412]
I don't know if this is a correct way, but I didn't find any mailing lists where I could ask this.
I'm using gocryptfs for about two years now on Ubuntu. I'm using it in reverse mode for folders I want to backup. I want everything that leaves my computer to be encrypted. The problem I have is how to know what folder has what name when it is encrypted.
So, if a folder has a name pictures than encrypted might be 0hhTFnIBboQk0FN52v1fIg== (this folder gets backed up). SInce I have couple of TB backed up it is impossible to find only one folder I want to restore.

**Comment by rfjakob** [comment]
Hi, when you do the reverse mount, please add `-ctlsock $HOME/ctlsock`. You can then use

https://github.com/rfjakob/gocryptfs/blob/master/contrib/ctlsock-encrypt.bash

with this control socket.

**Comment by rfjakob** [comment]
I should probably integrate ctlsock-encrypt.bash functionality into gocryptfs-xray. As gocryptfs-xray has a man page, it can be documented there.

**Comment by rfjakob** [comment]
Closing in favor of https://github.com/rfjakob/gocryptfs/issues/416

**Comment by slackner** [comment]
@rfjakob Note that those ctlsock scripts do not properly escape variables at various places. The `"$IN"` variable, for example, might contain quotes or slashes, that will lead to some incorrect json string. Also, in bash there is a difference between passing `$SOCK` (argument is split by spaces) and `"$SOCK"` (argument is passed as-is). This is probably something that should be improved when people want to use it on a regular basis.

@kovica Depending on the exact use-case, you could also use sshfs to access the remote server containing the backup, and then `gocryptfs` to mount a decrypted version of your remote backup. Now you can directly copy the files you want to restore.

If you want to decrypt many filenames (e.g., a log file of your backup), you could also use https://github.com/slackner/gocryptfs-inspect/blob/master/gocryptfs-deobfuscate.py which was written for exactly this purpose.

**Comment by Nodens-** [comment]
@slackner @kovica Depending on what the remote storage actually is, [rclone](https://rclone.org/) mount (even with SFTP remote) may be a much better option than sshfs.

**Comment by kovica** [comment]
I do not have access to remote storage. The backup I'm using uses their own client and everything you do you use that client.

**Comment by Nodens-** [comment]
May I ask what backup service are you using? Rclone mount can work with most cloud storage services, even some aimed directly for backup/cold storage.

**Comment by kovica** [comment]
I'm using Crashplan (https://www.crashplan.com/).

**Comment by rfjakob** [comment]
> @rfjakob Note that those ctlsock scripts do not properly escape variables at various places.

Functionality is now integrated into gocryptfs-xray and I have delete the horrible bash script
