### ISSUE TITLE
how to setting file name length 

### ISSUE THREAD

**Issue by ivanhertanto** [rfjakob/gocryptfs#423]
how to setting file name length? 

i got error while sync with onedrive because filename its to long

**Comment by rfjakob** [comment]
Can you test what the limit is for onedrive?

Nextcloud has a similar problem: https://github.com/rfjakob/gocryptfs/issues/99#issuecomment-353048640

**Comment by ivanhertanto** [comment]
one drive 200 char
how to setting length file name gocrypfs?
