### ISSUE TITLE
Google Drive FS

### ISSUE THREAD

**Issue by loungebob** [rfjakob/gocryptfs#424]
Help. Before I knew Google wont let me transfer ownership of content across domains, I used 3 domains to upload and store content - of course encrypted with gocryptfs. Now I need to download all content from 2 of the domains and re-up to my main domain A where I want to consolidate it all.
Unfortunately, I used a shared folder on domain A to upload to from domain B and C. So all content is shared among those 3 domains and appears as one drive when mounted and unencrypted.
The issue is, since whoever creates the content on Google Drive FS is the owner, I sometimes ended up with a scenario like Folder was created and is owned by domain A, most content is owned by domain B but the last content added was by domain C.
Am I assuming correctly that a scenario like this also means, that the diriv file for the whole folder contents would now be owned by domain C since it wrote last to the folder?
I’m trying to figure out how I would even know what content belongs to the 2 domains I want to merge into the main domain. 
On the Google Drive FS web interface I can see ownership but only encrypted file/folder names and theres the above mentioned mixed domain ownership issue.
When mounted and encrypted I can see all content but have no way of seeing ownership information so I could choose which content do download.
I know this has more to do with Google Drive FS and my lousy way of planning but maybe someone in here has an idea or some experience on how to untangle something like this?

**Comment by lechner** [comment]
Others here will be able to provide more extensive help.

I would download all content locally and create a mapping between plain and encrypted paths using `inode` numbers (`find -inum` in Linux). Then I would separately figure out the owner for each encrypted path, and divide the plaintext accordingly.

**Comment by loungebob** [comment]
Maybe I should have mentioned that ALL content would be 1.2 PB, which is not an option. Domain B and C however are only about 60TB but how do I filter them out? Do you mean move all content owned by domain B to a folder ignoring folder structure and potentially missing diriv, downloading that folder and using some inode magic?

**Comment by lechner** [comment]
No, I would never ignore the folder structure. In fact, I might replicate the folder structure locally, including all `diriv`s, and then work on sub-directories recursively. You could upload files elsewhere when done, to save space locally.

I think you have to break your problem down into smaller pieces. Do you have a way to tell which domain owns an encrypted path?

**Comment by loungebob** [comment]
smaller pieces sounds right. all I can do through the web interface is list all files and folders owned by a specific user and domain. but I dont see how that does me any good since all file and folder names are encrypted I dont even know what it is I’m looking at. but yes I can tell which paths are owned by what domain. 
I wonder what happens if I just un-share the 2 other domains. what happens to a folder/subfolder/files combo when the folder is owned by domain A, the subfolder by domain B and the files by domain C and everything gets un-shared. Will domain C just be left with a bunch of files and no folder structure?

**Comment by rfjakob** [comment]
> the diriv file for the whole folder contents would now be owned by domain C since it wrote last to the folder?

No the diriv file is created when the directory is created, and never written to again.

> all I can do through the web interface is list all files and folders owned by a specific user and domain. but I dont see how that does me any good since all file and folder names are encrypted I dont even know what it is I’m looking at.

But if you want to re-upload *all* files for domain B and domain C anyway, do you even need to see the file names?

**Comment by loungebob** [comment]
I’m so confused.

I thought the diriv contained filename information. Without it, the
filenames remain encrypted. So if it’s never written to again after folder
creation, how would it know about files added after it and the folder was
created or about changes in filenames?

I dont want to download domain B and C content and re-upload it to domain A
at all. But this seems to be the only way to consolidate all data under the
domain A since Google does not allow ownership change across domains (I
figure to prevent abuse but it scks soooo much).

So all I can do is download B and C content and reup to A. But I have no
clear and easy way of seeing in the unencrypted drive which content is
owned by B and C.

And in the Google Drive web interface I can only select all content owned
by B or C and move it to a folder and then download that folder but I’ll
lose all hierarchy and most likely the filenames too.

A Google engineer from the Drive Team told me to use the new Shared Drives
to transfer across domains (Shared Drives strip ownership information). But
after testing I found that folders from domains that have not created the
Shared Drive cannot be moved to it, the folder can manually be created and
the files can then be moved into it. This defeats the whole purpose and
seems another abuse prevention scheme or just sloppy programmers work and
logic.

Anyway, I’m frustrated and thinking of just unsharing everything on domain
B and C and then mount the drive with domain B or C credentials and see
what gives, whats left standing.

Unless someone has a better idea :-)



On 15 Sep 2019, at 11:55, rfjakob <notifications@github.com> wrote:

the diriv file for the whole folder contents would now be owned by domain C
since it wrote last to the folder?

No the diriv file is created when the directory is created, and never
written to again.

all I can do through the web interface is list all files and folders owned
by a specific user and domain. but I dont see how that does me any good
since all file and folder names are encrypted I dont even know what it is
I’m looking at.

But if you want to re-upload *all* files for domain B and domain C anyway,
do you even need to see the file names?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rfjakob/gocryptfs/issues/424?email_source=notifications&email_token=ACBJSEOJD77CQ7ZMZY74WNTQJYBADA5CNFSM4IWVCMG2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6XNLRQ#issuecomment-531551686>,
or mute the thread

**Comment by lechner** [comment]
> I thought the diriv contained filename information.

It doesn't. I contains a directory specific [salt](https://en.wikipedia.org/wiki/Salt_(cryptography)) to make sure the same plaintext filename does not yield the same encrypted name when two copies exists in two different places in the filesystem (or something like that). It is done to reduce the attack surface.

> And in the Google Drive web interface I can only select all content owned
> by B or C and move it to a folder and then download that folder but I’ll
> lose all hierarchy and most likely the filenames too.

I would use hashes over the encrypted content to match who owns what in your hierarchy.

**Comment by loungebob** [comment]
“I would use hashes over the encrypted content to match who owns what in
your hierarchy.”

could you elaborate on that or point me to some resources I can read up on?
I learn quickly :-)

On 15 Sep 2019, at 19:40, Felix Lechner <notifications@github.com> wrote:

I thought the diriv contained filename information.

It doesn't. I contains a directory specific salt
<https://en.wikipedia.org/wiki/Salt_(cryptography)> to make sure the same
plaintext filename does not yield the same encrypted name when two copies
exists in two different places in the filesystem (or something like that).
It is done to reduce the attack surface.

And in the Google Drive web interface I can only select all content owned
by B or C and move it to a folder and then download that folder but I’ll
lose all hierarchy and most likely the filenames too.

I would use hashes over the encrypted content to match who owns what in
your hierarchy.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rfjakob/gocryptfs/issues/424?email_source=notifications&email_token=ACBJSEMPD3EIVPJ74GN2JCLQJZXSXA5CNFSM4IWVCMG2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6XVN3A#issuecomment-531584748>,
or mute the thread

**Comment by lechner** [comment]
I would try to create a mapping between the *files for one owner downloaded into a single directory*—for which you know the owner but not the path—and the *files in your whole tree*—for which you know the location but not the owner—based on the condition that their content hashes to the same value.

[Hashes](https://en.wikipedia.org/wiki/Cryptographic_hash_function) are small, and often unique representations of larger data. They can be short or long, and your basic trade-off is speed vs. having collisions (meaning, you encounter the same hash for different data). I would start with [`sha1`](https://en.wikipedia.org/wiki/SHA-1) and possibly move to [`sha512`](https://en.wikipedia.org/wiki/SHA-2), if your data consists of many small files.

The matching would happen via two tables. One links a hash over the content with the plaintext or encrypted path; the other links a content hash with the file's owner. Those seem to be the pieces of information you would like to reunite.

A count could provide a basic measure that you processed all files.

**Comment by loungebob** [comment]
I’ll go read lots of stuff to figure out what you just said and report back.

**Comment by loungebob** [comment]
Sorry, should have let you close this a long time ago. It’s not really solved for me but that’s a me-issue, not a you-issue. Thanks all!
