### ISSUE TITLE
Website outdated

### ISSUE THREAD

**Issue by holgersson32644** [rfjakob/gocryptfs#426]
Hi,
your website is outdated as it does not list the 1.7 release.

Regards,
Nils

**Comment by rfjakob** [comment]
True, thanks! Do you may want to edit the website and add it?
You can edit here: https://github.com/rfjakob/gocryptfs-website/edit/master/docs/index.md

**Comment by holgersson32644** [comment]
Actually, no, because this will be happening with every new release and I think this asks strongly for automation.

Two suggestions:

Either **locally** at our machine, maybe with a shell function,
or **remotely via a webhook**. I didn't find out if you are allowed to
actually edit content this way, though.
https://developer.github.com/v3/activity/events/types/#releaseevent
