### ISSUE TITLE
Saltstack gocryptfs 1.6.1 -> 1.7 regression

### ISSUE THREAD

**Issue by teran-mckinney** [rfjakob/gocryptfs#427]
Now, I don't know where the bug is, but there's some strange regression. I'm probably doing some things I'm not supposed to and I'm okay with that.

This works on Debian 9 or 10, with gocrypft 1.6.1.

https://github.com/vagabondworkstation/hedron/blob/master/gocryptfs/init.sls

https://github.com/vagabondworkstation/hedron/blob/master/one_time_filesystem/init.sls

https://github.com/vagabondworkstation/hedron/blob/master/one_time_filesystem/files/encrypt_dir.sh

If you're thinking, WTF, don't worry, that's okay. I don't blame you.

With 1.7, on Debian 9 or Debian 10, this hangs up on /usr/local. Haven't dug into it deeper. The whole box kind of implodes, I guess because /usr/local/bin comes first in PS1 and it's hung up.

Again, this works on 1.6.1 just fine. If I change to 1.7 and nothing else, it breaks on both Debian 9 and Debian 10.

**Comment by lechner** [comment]
Hi, I am the maintainer of the Debian package and can reinstate version 1.6.1 in Debian, if you have more information on your error.

I just have to weigh if your issue warrrants alienating [users of new features from 1.7.1](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939544).

**Comment by teran-mckinney** [comment]
Hi @lechner,

I can try to figue it out sometime. I don't think this bug relates to Debian and most users may not run into the same issue that I did. I am using the binary from Github directly and not your package.

Thanks,

Teran

**Comment by lechner** [comment]
I would be interested to see if your issue also occurs with the official Debian packages. You can find all past and present versions on the [Wayback Machine](https://snapshot.debian.org/package/gocryptfs/).

**Comment by teran-mckinney** [comment]
Ok, thank you.

**Comment by rfjakob** [comment]
Hi, thanks for the report. How to I execute these sls files?

**Comment by teran-mckinney** [comment]
It's Saltstack. Yaml files describing execution. The encrypt_dir shell script is the interesting one.

It fails when it tries to do encrypt_dir on /usr/local. Still not quite sure why. If it's the amount of files, files locked, etc.

**Comment by rfjakob** [comment]
Sorry, I looked at what Saltstack is, and I looked at https://github.com/vagabondworkstation/hedron , but I still have no idea how to try to reproduce this.

Can you share a command line to run the operation that fails?
