### ISSUE TITLE
`gocryptfs v1.7; go-fuse [vendored]; 2019-08-29 go1.12.9` crashes in reverse mode on MacOS 10.14.6

### ISSUE THREAD

**Issue by yunesj** [rfjakob/gocryptfs#428]
`gocryptfs v1.7; go-fuse [vendored]; 2019-08-29 go1.12.9` crashes on MacOS 10.14.6.

I'm syncing in reverse mode:

```
# gocryptfs -fg -nosyslog -ctlsock sock -config /usr/local/etc/reverse-gocryptfs-config -reverse --exclude "abcdef" --exclude "ghijkl" / /Volumes/Reversed
# rsync -av /Volumes/Reversed jeff@server:/mnt/backup > backup.out 2> backup.err
```

About 44k files transfer successfully, until gocryptfs crashes and the remaining files fail with:

```
rsync: send_files failed to open "/Volumes/Reversed/cXOyX...BaQ/ONG_...3Y6ew/kCXVw...kr4s/v_I...TAg/hk7gJ...uPRA/DNx...gdQ/Cco...pQ/98...rQ": Device not configured (6)
```

gocryptfs prints:

```
2019/10/08 11:18:10 writer: Write/Writev failed, err: 9=bad file descriptor. opcode: GETATTR
ctlsock: Accept error: accept unix /var/root/sock: use of closed network connection
```

I formerly had a similar problem that I failed to reproduce on a restart (https://github.com/rfjakob/gocryptfs/issues/399), but that didn't help this time.

Any suggestions for how to proceed?

**Comment by rfjakob** [comment]
It's possible that gocryptfs is doing something wrong here, but this could also be a problem in OSXFUSE. Maybe cross-post the problem there?

**Comment by rfjakob** [comment]
However, it seems that gocryptfs exits after getting this one `bad file descriptor` error from OSXFUSE. I guess it would be better to return the error to the user but otherwise carry on. Will take a look.

**Comment by rfjakob** [comment]
Hmm, I don't how we would exit the [event loop](https://github.com/hanwen/go-fuse/blob/152e6ac32d543ba3eb6e6510030f3cf05c109d8d/fuse/server.go#L415) because of `Write/Writev failed`. Can you run your test again with `-fusedebug` ?

**Comment by yunesj** [comment]
I'm not currently using gocryptfs in my backup process, so I'll close the issue. Thanks!
