### ISSUE TITLE
Cannot delete corrupted directory

### ISSUE THREAD

**Issue by krumelmonster** [rfjakob/gocryptfs#429]
I had my laptop crash which resulted in lots of corrupted gocryptfs blocks. Luckily, no relevant data seems to be affected and it seems to be possible to simply delete the files `gocryptfs -fsck` lists.
In one case however, a directory itself seems to be corrupted:

```
$ ls -ago
total 20
drwx------  3  4096 Sep 18 16:44 .
drwx------ 86 12288 Oct 18 14:24 ..
drwx------  2  4096 Sep 18 16:40 BrowserMetrics
$ ls -ago BrowserMetrics
ls: reading directory 'BrowserMetrics': Input/output error
total 0
$ rm -rf BrowserMetrics
rm: cannot remove 'BrowserMetrics': Directory not empty
```
How do I get rid of the BrowserMetrics directory?

And by the way: Is there any way to prevent file corruption on power outage?

**Comment by rfjakob** [comment]
Hi, can you post the `gocryptfs -fsck` output?

**Comment by trochdewei** [comment]
I have similar problem
```
$ gocryptfs -fsck ./enc
Password: 
Decrypting master key
fsck: error stating file "series/s01.mkv": 5=input/output error
fsck summary: 1 corrupt files, 0 files skipped
```

**Comment by krumelmonster** [comment]
```
Password: 
Decrypting master key
OpenDir "LAJaeDCnOjMKyDF02U3-sg": could not read gocryptfs.diriv: wanted 16 bytes, got 0
fsck: error opening dir "PLAINTEXT": 5=input/output error
doRead 20317887: corrupt block #4: cipher: message authentication failed
fsck: error reading file "PLAINTEXT" (inum 20317887): 5=input/output error
doRead 20185140: corrupt block #407: cipher: message authentication failed
fsck: error reading file "PLAINTEXT" (inum 20185140): 5=input/output error
doRead 23202665: corrupt block #549: cipher: message authentication failed
fsck: error reading file "PLAINTEXT" (inum 23202665): 5=input/output error
doRead 23204846: corrupt block #132: cipher: message authentication failed
fsck: error reading file "PLAINTEXT" (inum 23204846): 5=input/output error
doRead 20449635: corrupt block #1: cipher: message authentication failed
fsck: error reading file "PLAINTEXT" (inum 20449635): 5=input/output error
doRead 20449761: corrupt block #243: cipher: message authentication failed
fsck: error reading file "PLAINTEXT" (inum 20449761): 5=input/output error
OpenDir "2Zl5JYPm182VCidxxuA9YQ": could not read gocryptfs.diriv: wanted 16 bytes, got 0
fsck: error opening dir "PLAINTEXT/BrowserMetrics": 5=input/output error
fsck summary: 8 corrupt files, 0 files skipped
```
I replaced most files and paths with PLAINTEXT

**Comment by rfjakob** [comment]
@krumelmonster you can find the corrupt directories `LAJaeDCnOjMKyDF02U3-sg` and `2Zl5JYPm182VCidxxuA9YQ` in the encrypted directory and delete it

**Comment by rfjakob** [comment]
@trochdewei strange that the error happens in stat(). Is it possible that the underlying disk has hardware problems? Any errors in `dmesg` when you try the fsck?

**Comment by NotherGithubAccount** [comment]
Sorry for the necromancy. I have the same issue, but I do not get the directory name when running with -fsck.

```
Decrypting master key
Checking filesystem...
OpendirHandle: could not read gocryptfs.diriv: wanted 16 bytes, got 0
fsck: error opening dir ".cache/mozilla/firefox/j8i2fmpt.default-release/safebrowsing": open /tmp/gocryptfs.fsck.1216560570/.cache/mozilla/firefox/j8i2fmpt.default-release/safebrowsing: input/output error

```
Any idea how to find the offending directory?

**Comment by niels** [comment]
@NotherGithubAccount You can try opening all your `gocryptfs.diriv` in the cipherdir until you find the one that can not be opened.

For example, in nushell:

```nushell
ls ~/your-cipherdir/**/gocryptfs.diriv | each { |f| stat $f.name }
```

In my case, the parent directory (containing the gocryptfs.diriv that can not be opened) was imply missing the executable permission.

Say, if the output of the above was

```
stat: cannot statx '/home/your-username/your-cipherdir/sub-a/sub-b/sub-c/gocryptfs.diriv': Permission denied
```

then the fix might be as simple as

```nushell
chmod u+x /home/your-username/your-cipherdir/sub-a/sub-b/sub-c
```

Of course, if your root cause differs, this fix will not work.

**Comment by rfjakob** [comment]
Huh, I'll see if fsck can print it.

In the meantime, get the inode number of the plaintext directory, and find
it in the encrypted directory.
