### ISSUE TITLE
matrix_test failures on Linux w/ btrfs

### ISSUE THREAD

**Issue by vgough** [rfjakob/gocryptfs#43]
The following tests fail for me on Ubuntu 16.04, on a btrfs filesystem:

```
--- FAIL: TestFallocate (0.01s)
	matrix_test.go:215: Expected 2 4k block(s), got 4
	matrix_test.go:244: Expected 2 4k block(s), got 4
	matrix_test.go:252: Expected 3 4k block(s), got 5
	matrix_test.go:265: Expected 4 4k block(s), got 6
--- FAIL: TestLongNames (0.00s)
	matrix_test.go:531: n255s is not in directory listing
FAIL
FAIL	github.com/rfjakob/gocryptfs/tests/matrix	1.082s
```

Are the block size checks specific to a filesystem type?

**Comment by rfjakob** [comment]
Yes, the fallocate test assumes the behavoir of ext4. I'll have to make it filesystem-aware.

The n255s failure is interesting. This also fails on Travis CI, https://github.com/rfjakob/gocryptfs/pull/40
