### ISSUE TITLE
Consider using a go-fuse patched to safely handle ESTALE during GetAttr()

### ISSUE THREAD

**Issue by charles-dyfis-net** [rfjakob/gocryptfs#436]
Back in May, the PR hanwen/go-fuse#300 was submitted to upstream go-fuse, fixing a null pointer dereference reachable when using gocryptfs on top of a NFS filesystem that sometimes can report stale file descriptors.

This is still not merged, and the go-fuse crash in question remains reachable as of gocryptfs 1.7.1.

Would a request to pin a patched release of go-fuse be considered?

**Comment by slackner** [comment]
You are right that the code in question can be simplified. However, I do not see how the current version can cause a panic. Since https://github.com/hanwen/go-fuse/commit/47211c2bf0c4ff9da52f38c039ca6538dc6f363d the the function will error out before accessing `fi` if `GetAttr` fails with `ESTALE`. Does it still crash for you?

I still think your change makes sense to make the code easier to understand. I would recommend to update your commit and pull request messages though, since it is more a stylistic change and not a bug fix. Also, you should probably take a look at https://github.com/hanwen/go-fuse/blob/master/CONTRIBUTING to ensure nothing is preventing your change from being accepted (especially the part about signing the CLA).

**Comment by charles-dyfis-net** [comment]
I've received reports of crashes from a user who turned out to have multiple NFSv4 clients all using the same hostname. Don't have such an environment myself, can't personally reproduce.

**Comment by lechner** [comment]
@charles-dyfis-net I have such a setup, but never use the same export on more than one client. Do you have more details on what it would take to reproduce the crash?

**Comment by charles-dyfis-net** [comment]
I haven't seen the NFS bug triggering ESTALEs with my own eyes for a while -- started with a kernel upgrade; after tracking down the cause, we differentiated our hostnames, and it completely went away. Even then, we're talking a crash every few hours at most, with a number of active systems (each periodically `touch`ing a file unique to that host, and all nodes frequently polling mtimes for all files in that directory).

That said, I've been able to look up the stack trace for the user-reported panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5b8abc]

goroutine 4513478 [running]:
github.com/hanwen/go-fuse/fuse/pathfs.(*pathInode).GetAttr(0xc03c43a330, 0xc035254100, 0x6d3140, 0xc01f027300, 0xc035254198, 0x20)
/tmp/build/src/GO/src/github.com/hanwen/go-fuse/fuse/pathfs/pathfs.go:615 +0x9c
github.com/hanwen/go-fuse/fuse/nodefs.(*rawBridge).GetAttr(0xc00025c2a0, 0xc035254180, 0xc0352540f0, 0x0)
/tmp/build/src/GO/src/github.com/hanwen/go-fuse/fuse/nodefs/fsops.go:139 +0x8a
github.com/hanwen/go-fuse/fuse.doGetAttr(0xc0001be000, 0xc035254000)
/tmp/build/src/GO/src/github.com/hanwen/go-fuse/fuse/opcode.go:246 +0x65
github.com/hanwen/go-fuse/fuse.(*Server).handleRequest(0xc0001be000, 0xc035254000, 0xc035254000)
/tmp/build/src/GO/src/github.com/hanwen/go-fuse/fuse/server.go:404 +0x313
github.com/hanwen/go-fuse/fuse.(*Server).loop(0xc0001be000, 0x52b401)
/tmp/build/src/GO/src/github.com/hanwen/go-fuse/fuse/server.go:376 +0x137
created by github.com/hanwen/go-fuse/fuse.(*Server).readRequest
/tmp/build/src/GO/src/github.com/hanwen/go-fuse/fuse/server.go:284 +0x2cb
```

**Comment by lechner** [comment]
What did you do when you "differentiated ... hostnames", please?

**Comment by charles-dyfis-net** [comment]
> What did you do when you "differentiated ... hostnames", please?

Updated each client of the NFS server to have a distinct hostname, discontinuing a historical practice of sharing them between nodes with an identical software stack.
