### ISSUE TITLE
build errors : use of internal package not allowed

### ISSUE THREAD

**Issue by muralikodali** [rfjakob/gocryptfs#438]
i tried to build on ubuntu 18.04 following instructions on https://nuetzlich.net/gocryptfs/compile/
it  first gave the error :   
cannot find package "github.com/hanwen/go-fuse/v2/splice"
 I created v2 directory and copied splice,intenal etc to v2 directory.
it again gave error:  
../../hanwen/go-fuse/fuse/pathfs/loopback.go:16:2: use of internal package not allowed

**Comment by rfjakob** [comment]
Hi! What is your

    go version

?

**Comment by muralikodali** [comment]
go version is 1.10

**Comment by rfjakob** [comment]
This is a problem with the "v2" module of go-fuse ( https://github.com/golang/go/wiki/Modules ). I'm not completely sure, but maybe you need go 1.11 or newer now.

**Comment by rfjakob** [comment]
I don't understand. Works fine with go1.10.7:

```
$ go version
go version go1.10.7 linux/amd64

$ export GOPATH=$(mktemp -d)

$ go get -d github.com/rfjakob/gocryptfs

$ cd $(go env GOPATH)/src/github.com/rfjakob/gocryptfs

$ ./build.bash
gocryptfs v1.7.1-20-g367b7e8; go-fuse v2.0.2-54-g0e3c45f; 2020-01-14 go1.10.7 linux/amd64
```
