### ISSUE TITLE
reverse mode write conf and diriv files inside the ciphered directory

### ISSUE THREAD

**Issue by jerome-diver** [rfjakob/gocryptfs#439]
Is it safe to put the gocryptfs.conf and gocryptfs.diriv files inside the ciphered directory ?
Because it is what's happening when use reverse mode to cipher a directory.
(use case is to cipher directory then sync files on cloud to backup)
I'm thinking (i may be wrong) that conf and diriv's files should always stay inside the not ciphered directory or better, a special .config/gocryptfs/ directory.

**Comment by rfjakob** [comment]
Yes, this is fine. Just use a decent password.

**Comment by jerome-diver** [comment]
no @rfjakob it is not fine at all.
Not put the .conf file (specificaly this one) inside the ciphered directory should be for sure more safe.
That's it and password only should not become the only one think to protect your data.
Imagine just to NO MORE PUT CONF FILE INSIDE CIPHER DIRECTORY will increase a lot secure.
Just do it for increase safety and stop deny.

**Comment by bexelbie** [comment]
I agree with the current defaults.  The average user will not have files in an unexpected place or have a steep testing/on boarding experience.  The files in question are important and shouldn’t be easily lost.

The average user, with the current defaults, shouldn’t get themselves into trouble if they use a strong password.  If they’re not going to use a strong password, `gocryptfs` and most likely anything related to it is probably not the best system for them.

That said, I also like that we have the flexibility for people like you to use option flags to change the behaviors and locations of various configuration files.  Your use case, that of reverse mode and cloud syncing, when combined with your security model may necessitate something other than the default behavior.  However, there are many other use cases, even for reverse mode and cloud syncing, where the same needs do not necessarily apply.

**Comment by rfjakob** [comment]
I just tried this again, the `-config` option works just fine, also for reverse mode. You can put the config file everywhere you want:

```
$ gocryptfs -init -reverse -config foo.conf a
Using config file at custom location /tmp/tmp.c43V4e58ya/foo.conf
[...]

$ gocryptfs -reverse -config foo.conf a b
Using config file at custom location /tmp/tmp.c43V4e58ya/foo.conf
[...]
Filesystem mounted and ready.

$ ls -la b
total 0
drwxr-xr-x. 2 jakob jakob  40 Dec 30 23:09 .
drwx------. 4 jakob jakob 100 Dec 30 23:09 ..
-r--r--r--. 1 jakob jakob  16 Dec 30 23:09 gocryptfs.diriv
```
