### ISSUE TITLE
Starting with fuse 3.0 the nonempty option has been removed.

### ISSUE THREAD

**Issue by juddmon** [rfjakob/gocryptfs#441]
I ran into this problem in Ubuntu 20.04 beta.

The code for libfuse >= 3.0 had the nonempty mount option removed from fusermount because the standard mount option does not have this option.  This caused gocryptfs to fail when this option is used (fuse doesn't allow that option).  Not using it will not work either if the mountpoint is not empty because the check "isEmptyDir" failed.
http://fuse.996288.n3.nabble.com/ANNOUNCE-libfuse-3-0-0-has-been-released-td14403.html

I submitted a PR to fix this.  https://github.com/rfjakob/gocryptfs/pull/440

**Comment by rfjakob** [comment]
Merged as https://github.com/rfjakob/gocryptfs/commit/db43bfc4c03b37b8b91bef413f4a75e8d769dc15 , thanks!
