### ISSUE TITLE
Mount at login with gnome keyring w/o pam_mount

### ISSUE THREAD

**Issue by palto42** [rfjakob/gocryptfs#442]
I'm using Solus Linux which doesn't support pam_mount currently, so I was looking for an alternative to automatically mount an encrypted folder at login. 

The simple solution I found was to store the passwords in the gnome keyring and pass it to gocryptfs with the CLI tool `secret-tool` wich is part of the `gnome-keyring`package.

```
# store password
secret-tool store --label='MyLabel' attribute value
# use stored password
gocryptfs --extpass="secret-tool lookup attribute value" cipher plain
```

The command can be added to the user auto-start programs to mount the encrypted folder at login without extra password question.

Maybe it's worth to add this in the wiki as an alternative to [pam_mount](https://github.com/rfjakob/gocryptfs/wiki/Mounting-on-login-using-pam_mount).

**Comment by rfjakob** [comment]
Yes, sounds good! Please go ahead and add it!

**Comment by palto42** [comment]
I added a wiki page [Mounting on login with Gnome keyring](https://github.com/rfjakob/gocryptfs/wiki/Mounting-on-login-with-Gnome-keyring)
