### ISSUE TITLE
Follow symlinks in underlying storage

### ISSUE THREAD

**Issue by chkno** [rfjakob/gocryptfs#444]
I would like to use gocryptfs inside [git annex](https://git-annex.branchable.com/), which moves files aside and replaces them with symlinks, an operation that is transparent to simple clients that just access files without special handling of symlinks.  If gocryptfs had a flag that just turned off some of its special handling of symlinks, this seems like it would work fine.  (`-plaintextnames` also turns of filename encryption, which I would like to keep.)

gocryptfs might not be able to support normal symlink semantics inside the encrypted store when operating in this mode, but that's fine for my use case.  Alternatively, gocryptfs could have even more special handling of symlinks, such as by tagging them such that gocryptfs-created symlinks could be distinguished from symlinks created by external programs for storage management.  In this mode, gocryptfs wouldn't even need configuration for this mode -- it would always Just Work -- but it would mean a change to the normal encrypted store format to add the tag to gocryptfs-managed symlinks.

I created a [test case](https://github.com/chkno/gocryptfs/commit/ef7cd5b97e0428ae7449462a54f5ec9982770b6b) that verifies the desired behavior.

**Comment by chkno** [comment]
Oh, I see that there was a bunch of work between 1.6.1 and 1.7 to "never follow symlinks":

* e8d8ae54d3b852d1d35b6db81d4a0beb57fbdce1 fusefrontend: use OpenDirNofollow in openBackingDir ... to be safe against symlink races.
* 22fba4ac3ed09ba07d1defb60436fb7a17095d09 fusefrontent: make Open() symlink-safe
* a1fb4566186ec38ec2b21b936f29df669efbfe4f fusefrontend: make Rename() symlink-safe: Use Openat() and the openBackingDir() helper so we never follow symlinks.
* 897bb8924fe23be5c989b519b62fbf7841a31a4c fusefrontend: make Create() symlink-safe: Use Openat() and the openBackingDir() helper so we never follow symlinks.

Advice?

**Comment by rfjakob** [comment]
Yes, there was some work to make gocryptfs safe against symlink races, but this mostly concerns directory symlinks (i.e. a path like `dir1/file`, and `dir1` is actually a symlink). As far as I understand, git-annex only uses symlinks to files.

The naive change to gocryptfs would be simple:
```diff
diff --git a/internal/fusefrontend/fs.go b/internal/fusefrontend/fs.go
index d03fc77..6f10929 100644
--- a/internal/fusefrontend/fs.go
+++ b/internal/fusefrontend/fs.go
@@ -155,6 +155,7 @@ func (fs *FS) Open(path string, flags uint32, context *fuse.Context) (fuseFile n
                return nil, fuse.EPERM
        }
        newFlags := fs.mangleOpenFlags(flags)
+       newFlags &^= syscall.O_NOFOLLOW
        // Taking this lock makes sure we don't race openWriteOnlyFile()
        fs.openWriteOnlyLock.RLock()
        defer fs.openWriteOnlyLock.RUnlock()
```
This means that when a file is opened through gocryptfs, and the file is actually a symlink pointing to a file, the symlink is followed.

However, unfortunately, that's not how it works. The Linux kernel will notice that the file is actually a symlink, and open the **file the symlinks points to** directly, never passing it through gocryptfs. So to make your idea work, gocryptfs would also need to lie to the kernel that all symlinks are normal files. And this is where things will a get a little complicated, I'm afraid.

I don't know a lot about git-annex, but have you considered using `git annex unlock` ( https://git-annex.branchable.com/git-annex-unlock/ )? The downside is that it will double the required storage space.
