### ISSUE TITLE
How robust is this tool?

### ISSUE THREAD

**Issue by manad777** [rfjakob/gocryptfs#445]
You can have sudden power loss, and then there's the general unreliability of network protocols  (I can't seem to be able to back up my 1GB Documents folder from Windows 10 to a SMB network folder without getting a random error).

Like if writes fail at a critical time for some random reasons, say due to power loss, is there any chance of losing all your data due to a borked write on a critical internal file? Or would you only lose the file being written at the time of the power loss, like with a journaling filesystem?

Let's say some Samba bug tells the app "write successful!" before dropping due to network issues. Does/Can the app do any secondary checks on written data? 

Also, why isn't there Windows support, is this a Go limitation? I'm aware of the 3rd party implementation but using it feels like exposing myself to greater risk of data loss, because the bugs can now come from 2 applications by 2 different developers instead of just 1.

**Comment by rfjakob** [comment]
Hi,

> Like if writes fail at a critical time for some random reasons, say due to power loss, is there any chance of losing all your data due to a borked write on a critical internal file? Or would you only lose the file being written at the time of the power loss, like with a journaling filesystem?

No, only this one file will have a corrupt sector.

About Windows support, this is a Windows limitation. Windows does not have FUSE support built-in. There are third-party alternatives (Dokany and WinFSP) but they are not compatible with Linux FUSE.

**Comment by Nodens-** [comment]
@rfjakob Just a heads up.
I am not sure if you are aware of WinFSP's FUSE3.2 and FUSE2.8 compat layers:
https://github.com/billziss-gh/winfsp/blob/master/inc/fuse3/fuse.h
https://github.com/billziss-gh/winfsp/blob/master/inc/fuse/fuse.h

and of this cross platform Go FUSE library:
https://github.com/billziss-gh/cgofuse

I do not know if these meet gocryptfs requirements but just a heads up that they exist.
