### ISSUE TITLE
Upgrade Debian stable packages to 1.7.1?

### ISSUE THREAD

**Issue by Af0x** [rfjakob/gocryptfs#447]
Hello,

will the Debian stable packages be upgraded to the latest 1.7.1? If yes, when do you think it will happen?

Regards,

Af0x

**Comment by lechner** [comment]
Do you need a particular feature?

**Comment by Af0x** [comment]
no, just starting off with the latest version. Also there seem to be some security fixes.

**Comment by lechner** [comment]
1.7.1 is unlikely to be backported to `stable` because it would require additional backports for `go-fuse` and potentially `golang-1.13`. You can manually install the version from unstable using `dpkg -i` since golang binaries only use system calls.

I think this issue can be closed.

**Comment by Af0x** [comment]
ok, thanks for clarification. Lets say I start with 1.6.1 from stable and upgrade later when testing becomes the new stable. Are there any additional steps I need to do similar to those described in the wiki under "[Upgrading](https://github.com/rfjakob/gocryptfs/wiki/Upgrading)" or will this be a flawless process without the need to copy any files around?

**Comment by lechner** [comment]
I am not aware of any on-disk format changes post `stable`, but recommend 1.7.1 if you use NFS.

**Comment by rfjakob** [comment]
No on-disk format changes since gocryptfs v1.3!

**Comment by rfjakob** [comment]
PS: See https://github.com/rfjakob/gocryptfs/wiki/Compatibility
