### ISSUE TITLE
add option "user", "noauto" and "user_allow_other" for /etc/fstab

### ISSUE THREAD

**Issue by maxadamo** [rfjakob/gocryptfs#449]
if I change the password and I boot another computer, where the old password is still stored in the passfile (mentioned in fstab), the computer probably hangs during the boot, because it cannot mount all the filesystems. 
It would be handy to have `noauto` option, and then let the user mount through the option `user`, which requires `user_allow_other` as well

**Comment by rfjakob** [comment]
Hi, you should use the `nofail` mount option so boot continues, even if the gocryptfs mount fails.

What happens when you have the `user` option in fstab? Do you get an error?

**Comment by maxadamo** [comment]
I get an error with `user`, only if  used in combination with `allow_other`, as it asks to user `user_allow_other` which is not supported.

**Comment by maxadamo** [comment]
_clarification_: the problem is only with `user_allow_other`, which is not really necessary if it's mounted as user. And noauto works. 
I think it's safe to close this question: user_allow_other with user doesn't make much sense and it's not even safe.
