### ISSUE TITLE
Root cannot change file ownership

### ISSUE THREAD

**Issue by temrix** [rfjakob/gocryptfs#451]
I use `gocryptfs v1.7.1 without_openssl` together with `libpam` on Debian 10. I cannot change the ownership (`chown`) of a cipherdir because I get 'operation not permitted'. I have used `gocryptfs` from the Debian repository before but I had the same issue.

This is my `/etc/security/pam_mount.conf.xml`:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE pam_mount SYSTEM "pam_mount.conf.xml.dtd">
<!--
	See pam_mount.conf(5) for a description.
-->

<pam_mount>

		<!-- debug should come before everything else,
		since this file is still processed in a single pass
		from top-to-bottom -->

<debug enable="0" />

		<!-- Volume definitions -->

<volume user="temrix" fstype="fuse" options="rw,nodev,nosuid,nonempty,allow_other" path="gocryptfs#/home/%(USER).cipher/"
mountpoint="/home/%(USER)" />

		<!-- pam_mount parameters: General tunables -->

<!--
<luserconf name=".pam_mount.conf.xml" />
-->

<!-- Note that commenting out mntoptions will give you the defaults.
     You will need to explicitly initialize it with the empty string
     to reset the defaults to nothing. -->
<mntoptions allow="nosuid,nodev,loop,encryption,fsck,nonempty,allow_root,allow_other" />
<!--
<mntoptions deny="suid,dev" />
<mntoptions allow="*" />
<mntoptions deny="*" />
-->
<mntoptions require="nosuid,nodev" />

<!-- requires ofl from hxtools to be present -->
<logout wait="0" hup="no" term="no" kill="no" />


		<!-- pam_mount parameters: Volume-related -->

<mkmountpoint enable="1" remove="true" />

</pam_mount>
```
I have enabled `user_allow_other` in `/etc/fuse.conf`:

```
# /etc/fuse.conf - Configuration file for Filesystem in Userspace (FUSE)

# Set the maximum number of FUSE mounts allowed to non-root users.
# The default is 1000.
#mount_max = 1000

# Allow non-root users to specify the allow_other or allow_root mount options.
user_allow_other
```

`$ mount`:

```
/home/temrix.cipher on /home/temrix type fuse.gocryptfs (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000,default_permissions,allow_other,max_read=131072)
```

I suppose it is just a mount option but I am lost where that could be. Also, I may not fully understand all options in the XML-file. Do you see anything obvious why `chown` would not work?

**Comment by rfjakob** [comment]
No, sorry, this cannot work, because the **gocryptfs** process runs as your user, and not as root. So this is what happens:

chown (as root) -> gocryptfs (as your user) -> chown (as your user) -> fails

**Comment by temrix** [comment]
For anyone wondering: I use the same config as above now successfully whereas the noroot option has had nothing to do with it. I probably did not chown the userdir and cipherdir to the corresponding user at that time. Also, `user_allow_other` needs to be enabled in `/etc/fuse.conf`.
