### ISSUE TITLE
restore gocryptfs.conf

### ISSUE THREAD

**Issue by mabod** [rfjakob/gocryptfs#454]
What do I have to do if I lost gocryptfs.conf but I still have the master key? I can mount the encrypted directory with the master key. But this is inconvenient. I would rather want a new gocryptfs.conf.  Is there a way to do that?

**Comment by rfjakob** [comment]
Yes it is, check https://github.com/rfjakob/gocryptfs/issues/446 . I'll see if I can write this in the wiki somewhere

**Comment by rfjakob** [comment]
Done: https://github.com/rfjakob/gocryptfs/wiki/Recreate-gocryptfs.conf-using-masterkey
