### ISSUE TITLE
lazy unmount fails to finish

### ISSUE THREAD

**Issue by jonleivent** [rfjakob/gocryptfs#459]
I'm using gocryptfs with pam_mount, and noticed that on several occasions gocryptfs daemon and logger daemon are still present after the user has logged out.  In these cases, I have checked `/proc/mounts`, and can see that the target mountpoint is no longer mounted.  

Some experimentation indicates that removing the mountpoint from `/proc/mounts` is the normal behavior of lazy unmounting, as by `fusermount -z -u mountpoint`: the mountpoint will no longer appear in `/proc/mounts` but the daemons will remain until the unmount can complete.  Also, based on syslog msgs, I determined that pam_mount will revert to doing a lazy unmount when needed.

The question is: is it a gocryptfs bug or a fusermount -z bug if the gocryptfs and logger daemons remain when no other user processes exist in the system that need the mount (easy to tell in this case, as I don't use allow_other, so only procs by that user can need the mount to remain - making `ps -u user` sufficient), and `/proc/mounts` shows that the mountpoint has been unmounted?  Does gocryptfs even support lazy unmounting by fusermount?

**Comment by rfjakob** [comment]
Hi, can I get an

    strace -f -p PID

of such a gocryptfs process?

Yes every filesystem supports lazy unmount (the filesystem does not even know about it). This is all handled inside the kernel, which makes the mountpoint invisible until all files are closed, and only then sends the actual unmount command.

So I think this is either:

* Some file is still open (I don't see how, though, `ps -u user` should show that)
* The kernel did not send the unmount command (but why?)
* gocryptfs did not exit after receiving the unmount command (the strace above will show that)

**Comment by jonleivent** [comment]
I neglected to add that it is surprising that the kernel has to resort to lazy unmounts in these cases because I have the user call `fuser -k -TERM -m mountpoint && sleep 5` followed by `rm -r mountpoint/.cache/*` priot to logging out.  Is it possible that the kernel always uses lazy unmount without first trying normal unmount?  Or maybe I need to add `sync -f mountpoint` after the rm?  I thought rm was fully synchronous.

Indeed, the workaround I was considering was to use `<fuseumount>fusermount -u %(MNTPT)</fuseumount>` in pam_mount.conf.xml to hopefully disable lazy unmounting by pam - in combination with the `fuser -k` calls prior to logout so that any remaining daemons would be clearly my fault.

I will try to find a way to setup an strace for gocryptfs.  Unfortunately, as I can't do that in user space, doing this will be a bit of a challenge.  Perhaps I should wrap gocryptfs in a script and have pam_mount use that script instead of gocryptfs.  Can I filter the strace output for certain calls, or must I log all of it?  Because it's going to be a **lot**.  Unless I can instead attach strace only just prior to logout - but again, the issue there is how to do that in user space.

**Comment by rfjakob** [comment]
I suggest to attach strace **after** the logout. Log in as another user or as root, and

    strace -f -p PROCESS-ID-OF-GOCRYPTFS-PROCESS

**Comment by jonleivent** [comment]
On this system, only root can strace.  I will have to create a setuid script, and call it from user logout, making sure it isn't using the mountpoint itself.

BTW - I neglected to add version details: this is Debian 10.3 with the 4.19.0-8-amd64 kernel.  And:
```
$ gocryptfs --version
gocryptfs 1.6.1; go-fuse 0.0~git20190214.58dcd77; 2019-03-11 go1.11.5
```

**Comment by jonleivent** [comment]
Better than setuid: I will put a privilege specification in `/etc/sudoers` to allow the user to strace their own gocryptfs process.

**Comment by rfjakob** [comment]
You can run the strace at any time you notice a leftover gocryptfs process, timing is not critical here

**Comment by jonleivent** [comment]
Oh - that saves a lot of work!  I'll just put in something to notice if there are any gocryptfs daemons after user logout, and then do the rest manually.

**Comment by jonleivent** [comment]
Got one!

```
$ sudo strace -f -p 10054
[sudo] password for root: 
strace: Process 10054 attached with 8 threads
[pid 10061] futex(0xc0000b9640, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10060] read(8,  <unfinished ...>
[pid 10059] futex(0x8669d8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10058] futex(0xc00006a140, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10057] futex(0x866ac0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10056] read(8,  <unfinished ...>
[pid 10055] restart_syscall(<... resuming interrupted futex ...> <unfinished ...>
[pid 10054] read(8, ^Cstrace: Process 10054 detached
 <detached ...>
strace: Process 10055 detached
strace: Process 10056 detached
strace: Process 10057 detached
strace: Process 10058 detached
strace: Process 10059 detached
strace: Process 10060 detached
strace: Process 10061 detached
```
The `^C` is because that's where the strace hung for a while without producing any further output.

**Comment by jonleivent** [comment]
I have the gocryptfs daemon still running if you need further strace output.  I can keep it for a day or so.  I think I know the conditions under which the situation occurred.  It involved a single user process that was cd'ed into the mount point,  doing nothing but sleeping for a while at the time of the logout.  Which should have triggered the lazy umount when it finally finished its sleep and exited - and I can see that it did exit.  I can also see via /var/run/pam_mount that pam believes the user has logged out.

**Comment by jonleivent** [comment]
More info - in this case, /proc/mounts still shows the mount point.  That's different from the scenarios I saw before.  I suspect in this case pam never did the unmount.

Yup - found this error output from pam:
```
(mount.c:76): fusermount: failed to unmount /home/user/.decipher: Device or resource busy
(mount.c:887): unmount of /usr/bin/gocryptfs#/home/user/.cipher failed
```
[subbing user for the user's actual name].  So why didn't pam do a lazy unmount this time?  At one point, I had the <fuseumount> directive in pam_mount.conf.xml, but it's now commented out, so it should have resorted to default behavior.  Maybe I need to put a <fuseumount> directive in with -z option to force lazy now?  That's weird.

**Comment by jonleivent** [comment]
I'm going to assume that pam_mount is somehow "learning" a default unmount behavior from including at one point a <fuseumount>, and continues to use it even when removed, meaning I can't get the original behavior in this configuration.  That's the only way I can make sense of what happened.  So I will put in
```
<fuseumount>/usr/bin/fusermount -z -u %(MNTPT)</fuseumount>
```
and see what happens...

**Comment by jonleivent** [comment]
It finally happened again, after clearing up the confusion above.  This time, the signs are that the lazy unmount occurred: the mountpoint is not in /proc/mounts, and the user is not in `/var/run/pam_mounts`.  And `ps -u user` shows only the gocryptfs and logger processes.

Here's what I hope is enough of the `strace -f -p pid` output:
```
$ sudo strace -f -p 10519
[sudo] password for root: 
strace: Process 10519 attached with 11 threads
[pid 10973] futex(0xc0041ee4c0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10824] futex(0xc0040f6f40, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10823] futex(0xc0040f6bc0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10539] futex(0xc0040f64c0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10527] futex(0xc0000ad640, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10526] read(8,  <unfinished ...>
[pid 10525] futex(0x8669d8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10524] futex(0x866ac0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10523] read(8,  <unfinished ...>
[pid 10522] restart_syscall(<... resuming interrupted futex ...> <unfinished ...>
[pid 10519] read(8,  <unfinished ...>
[pid 10522] <... restart_syscall resumed> ) = -1 ETIMEDOUT (Connection timed out)
[pid 10522] epoll_pwait(5, [], 128, 0, NULL, 0) = 0
[pid 10522] futex(0xc0041ee4c0, FUTEX_WAKE_PRIVATE, 1) = 1
[pid 10973] <... futex resumed> )       = 0
[pid 10522] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 10973] epoll_pwait(5, [], 128, 0, NULL, 0) = 0
[pid 10973] futex(0xc0040f6bc0, FUTEX_WAKE_PRIVATE, 1) = 1
[pid 10823] <... futex resumed> )       = 0
[pid 10522] <... nanosleep resumed> NULL) = 0
[pid 10823] futex(0xc0040f6f40, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 10824] <... futex resumed> )       = 0
[pid 10823] <... futex resumed> )       = 1
[pid 10824] futex(0xc0040f64c0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 10522] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 10824] <... futex resumed> )       = 1
[pid 10539] <... futex resumed> )       = 0
[pid 10522] <... nanosleep resumed> NULL) = 0
[pid 10522] nanosleep({tv_sec=0, tv_nsec=20000}, NULL) = 0
[pid 10522] nanosleep({tv_sec=0, tv_nsec=20000}, NULL) = 0
[pid 10522] nanosleep({tv_sec=0, tv_nsec=20000}, NULL) = 0
[pid 10824] futex(0xc0040f6f40, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10522] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 10539] futex(0xc0040f64c0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10522] <... nanosleep resumed> NULL) = 0
[pid 10522] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 10973] futex(0xc0041ee4c0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10823] futex(0xc0041ee4c0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 10522] <... nanosleep resumed> NULL) = 0
[pid 10973] <... futex resumed> )       = 0
[pid 10823] <... futex resumed> )       = 1
[pid 10973] futex(0x849c88, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 10823] epoll_pwait(5,  <unfinished ...>
[pid 10973] <... futex resumed> )       = 0
[pid 10823] <... epoll_pwait resumed> [], 128, 0, NULL, 0) = 0
[pid 10973] futex(0xc0041ee4c0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10823] futex(0xc0041ee4c0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 10973] <... futex resumed> )       = -1 EAGAIN (Resource temporarily unavailable)
[pid 10823] <... futex resumed> )       = 0
[pid 10522] sched_yield( <unfinished ...>
[pid 10973] nanosleep({tv_sec=0, tv_nsec=3000},  <unfinished ...>
[pid 10522] <... sched_yield resumed> ) = 0
[pid 10522] futex(0x849930, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 10973] <... nanosleep resumed> NULL) = 0
[pid 10522] <... futex resumed> )       = 0
[pid 10973] futex(0xc0041ee4c0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10522] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 10823] futex(0xc0040f6bc0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10522] <... nanosleep resumed> NULL) = 0
[pid 10522] futex(0x849a10, FUTEX_WAIT_PRIVATE, 0, {tv_sec=60, tv_nsec=0}) = -1 ETIMEDOUT (Connection timed out)
[pid 10522] epoll_pwait(5, [], 128, 0, NULL, 0) = 0
[pid 10522] nanosleep({tv_sec=0, tv_nsec=20000}, NULL) = 0
[pid 10522] futex(0x849a10, FUTEX_WAIT_PRIVATE, 0, {tv_sec=60, tv_nsec=0}) = -1 ETIMEDOUT (Connection timed out)
[pid 10522] epoll_pwait(5, [], 128, 0, NULL, 0) = 0
[pid 10522] futex(0xc0040f6bc0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 10823] <... futex resumed> )       = 0
[pid 10522] <... futex resumed> )       = 1
[pid 10823] epoll_pwait(5,  <unfinished ...>
[pid 10522] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 10823] <... epoll_pwait resumed> [], 128, 0, NULL, 0) = 0
[pid 10823] futex(0xc0041ee4c0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 10973] <... futex resumed> )       = 0
[pid 10823] <... futex resumed> )       = 1
[pid 10522] <... nanosleep resumed> NULL) = 0
[pid 10973] futex(0xc0040f64c0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 10823] futex(0x849a28, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=100000} <unfinished ...>
[pid 10522] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 10973] <... futex resumed> )       = 1
[pid 10539] <... futex resumed> )       = 0
[pid 10973] futex(0x849a28, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 10539] futex(0xc0040f64c0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10522] <... nanosleep resumed> NULL) = 0
[pid 10973] <... futex resumed> )       = 0
[pid 10823] <... futex resumed> )       = -1 EAGAIN (Resource temporarily unavailable)
[pid 10522] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 10973] futex(0xc0041ee4c0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10823] futex(0xc0041ee4c0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 10973] <... futex resumed> )       = -1 EAGAIN (Resource temporarily unavailable)
[pid 10823] <... futex resumed> )       = 0
[pid 10522] <... nanosleep resumed> NULL) = 0
[pid 10973] futex(0x849c88, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 10823] epoll_pwait(5,  <unfinished ...>
[pid 10522] sched_yield( <unfinished ...>
[pid 10973] <... futex resumed> )       = 0
[pid 10823] <... epoll_pwait resumed> [], 128, 0, NULL, 0) = 0
[pid 10973] futex(0xc0041ee4c0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10823] futex(0xc0041ee4c0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 10973] <... futex resumed> )       = -1 EAGAIN (Resource temporarily unavailable)
[pid 10823] <... futex resumed> )       = 0
[pid 10973] nanosleep({tv_sec=0, tv_nsec=3000},  <unfinished ...>
[pid 10823] futex(0xc0040f6bc0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10522] <... sched_yield resumed> ) = 0
[pid 10973] <... nanosleep resumed> NULL) = 0
[pid 10522] futex(0x849930, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 10973] futex(0xc0041ee4c0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10522] <... futex resumed> )       = 0
[pid 10522] nanosleep({tv_sec=0, tv_nsec=20000}, NULL) = 0
[pid 10522] futex(0x849a10, FUTEX_WAIT_PRIVATE, 0, {tv_sec=60, tv_nsec=0}) = -1 ETIMEDOUT (Connection timed out)
[pid 10522] epoll_pwait(5, [], 128, 0, NULL, 0) = 0
[pid 10522] nanosleep({tv_sec=0, tv_nsec=20000}, NULL) = 0
[pid 10522] futex(0x849a10, FUTEX_WAIT_PRIVATE, 0, {tv_sec=60, tv_nsec=0}) = -1 ETIMEDOUT (Connection timed out)
[pid 10522] epoll_pwait(5, [], 128, 0, NULL, 0) = 0
[pid 10522] futex(0xc0041ee4c0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 10973] <... futex resumed> )       = 0
[pid 10522] <... futex resumed> )       = 1
[pid 10973] epoll_pwait(5,  <unfinished ...>
[pid 10522] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 10973] <... epoll_pwait resumed> [], 128, 0, NULL, 0) = 0
[pid 10973] futex(0xc0040f6bc0, FUTEX_WAKE_PRIVATE, 1) = 1
[pid 10823] <... futex resumed> )       = 0
[pid 10522] <... nanosleep resumed> NULL) = 0
[pid 10973] futex(0x849a28, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=100000} <unfinished ...>
[pid 10823] futex(0xc0040f64c0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 10522] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 10823] <... futex resumed> )       = 1
[pid 10539] <... futex resumed> )       = 0
[pid 10823] futex(0x849a28, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 10539] futex(0xc0040f64c0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10973] <... futex resumed> )       = 0
[pid 10823] <... futex resumed> )       = 1
[pid 10522] <... nanosleep resumed> NULL) = 0
[pid 10973] futex(0xc0040f6bc0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 10823] futex(0xc0040f6bc0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10522] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 10973] <... futex resumed> )       = 0
[pid 10823] <... futex resumed> )       = -1 EAGAIN (Resource temporarily unavailable)
[pid 10973] epoll_pwait(5,  <unfinished ...>
[pid 10823] futex(0x849c88, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 10973] <... epoll_pwait resumed> [], 128, 0, NULL, 0) = 0
[pid 10823] <... futex resumed> )       = 0
[pid 10522] <... nanosleep resumed> NULL) = 0
[pid 10973] futex(0x849a10, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 10823] futex(0xc0040f6bc0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10522] futex(0x849a10, FUTEX_WAIT_PRIVATE, 0, {tv_sec=60, tv_nsec=0} <unfinished ...>
[pid 10973] <... futex resumed> )       = 0
[pid 10522] <... futex resumed> )       = -1 EAGAIN (Resource temporarily unavailable)
[pid 10973] futex(0xc0040f6bc0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 10522] sched_yield( <unfinished ...>
[pid 10973] <... futex resumed> )       = 1
[pid 10823] <... futex resumed> )       = 0
[pid 10973] futex(0xc0041ee4c0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10823] nanosleep({tv_sec=0, tv_nsec=3000},  <unfinished ...>
[pid 10522] <... sched_yield resumed> ) = 0
[pid 10522] futex(0x849930, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 10823] <... nanosleep resumed> NULL) = 0
[pid 10522] <... futex resumed> )       = 0
[pid 10823] futex(0xc0040f6bc0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10522] nanosleep({tv_sec=0, tv_nsec=20000}, NULL) = 0
[pid 10522] futex(0x849a10, FUTEX_WAIT_PRIVATE, 0, {tv_sec=60, tv_nsec=0}) = -1 ETIMEDOUT (Connection timed out)
[pid 10522] epoll_pwait(5, [], 128, 0, NULL, 0) = 0
[pid 10522] madvise(0xc004000000, 2097152, MADV_NOHUGEPAGE) = 0
[pid 10522] madvise(0xc0041f0000, 8192, MADV_DONTNEED) = 0
[pid 10522] madvise(0xc004000000, 2097152, MADV_NOHUGEPAGE) = 0
[pid 10522] madvise(0xc00410a000, 8192, MADV_DONTNEED) = 0
[pid 10522] madvise(0xc000000000, 2097152, MADV_NOHUGEPAGE) = 0
[pid 10522] madvise(0xc000098000, 8192, MADV_DONTNEED) = 0
[pid 10522] madvise(0xc000000000, 2097152, MADV_NOHUGEPAGE) = 0
[pid 10522] madvise(0xc0000e6000, 8192, MADV_DONTNEED) = 0
[pid 10522] madvise(0xc004000000, 2097152, MADV_NOHUGEPAGE) = 0
[pid 10522] madvise(0xc00412e000, 8192, MADV_DONTNEED) = 0
[pid 10522] madvise(0xc004000000, 2097152, MADV_NOHUGEPAGE) = 0
[pid 10522] madvise(0xc0041ec000, 8192, MADV_DONTNEED) = 0
[pid 10522] madvise(0xc004200000, 2097152, MADV_NOHUGEPAGE) = 0
[pid 10522] madvise(0xc004200000, 16384, MADV_DONTNEED) = 0
[pid 10522] madvise(0xc000000000, 2097152, MADV_NOHUGEPAGE) = 0
[pid 10522] madvise(0xc0000d8000, 16384, MADV_DONTNEED) = 0
[pid 10522] madvise(0xc004000000, 2097152, MADV_NOHUGEPAGE) = 0
[pid 10522] madvise(0xc0041dc000, 16384, MADV_DONTNEED) = 0
[pid 10522] madvise(0xc004000000, 2097152, MADV_NOHUGEPAGE) = 0
[pid 10522] madvise(0xc0041fa000, 16384, MADV_DONTNEED) = 0
[pid 10522] madvise(0xc004000000, 2097152, MADV_NOHUGEPAGE) = 0
[pid 10522] madvise(0xc00417a000, 24576, MADV_DONTNEED) = 0
[pid 10522] madvise(0xc004000000, 2097152, MADV_NOHUGEPAGE) = 0
[pid 10522] madvise(0xc0041e2000, 32768, MADV_DONTNEED) = 0
[pid 10522] madvise(0xc004000000, 2097152, MADV_NOHUGEPAGE) = 0
[pid 10522] madvise(0xc004186000, 286720, MADV_DONTNEED) = 0
[pid 10522] madvise(0xc004200000, 2097152, MADV_NOHUGEPAGE) = 0
[pid 10522] madvise(0xc00421c000, 64897024, MADV_DONTNEED) = 0
[pid 10522] nanosleep({tv_sec=0, tv_nsec=20000}, NULL) = 0
[pid 10522] futex(0x849a10, FUTEX_WAIT_PRIVATE, 0, {tv_sec=60, tv_nsec=0}
```

**Comment by rfjakob** [comment]
There it is:

    [pid 10526] read(8,  <unfinished ...>

Now, let's see what file descriptor 8 is (this is on gocryptfs process I have running here, but it is very likely that it is the same on your box):

    $ lsof -p 127785 | grep 8u
    gocryptfs 127785 jakob    8u      CHR             10,229      0t0    2536 /dev/fuse

So we are still waiting for new requests from /dev/fuse. When unmounting, the kernel closes this connection. But it did not here. Why? I don't know. Something is waiting for something to finish.

Can you run

    sudo grep . /sys/fs/fuse/connections/*/waiting

when you see this again? Should look like this, any value >=1 means that a request got hung somewhere.

```
$ sudo grep . /sys/fs/fuse/connections/*/waiting
/sys/fs/fuse/connections/39/waiting:0
/sys/fs/fuse/connections/40/waiting:0
/sys/fs/fuse/connections/55/waiting:0
/sys/fs/fuse/connections/63/waiting:0
```

**Comment by jonleivent** [comment]
What if there are multiple fuse file systems around?  I use bindfs as well as gocryptfs.  How do these share /dev/fuse?

**Comment by jonleivent** [comment]
I have recently seen a case of this involving bindfs - where all fuse mounts were lazily unmounted (none left in /proc/mounts), but a single bindfs process remained with no other processes by that user.  However, in that case, there was a gocryptfs mount by that user, as well as other bindfs mounts that were lazily unmounted successfully all around the same time - when the user logged out.  I am beginning to suspect that the bug may only occur when there are multiple fuse mounts by the same user, and perhaps at least one is gocryptfs.   I don't have an example where all are bindfs because all of the users involved get a pam_mounted gocryptfs subdir.  I also don't have an example involving gocryptfs alone.  In other words I can't rule out either of those cases.

Is it possible that the multiplexing of /dev/fuse is responsible for the loss of some signals from the kernel?  I searched for an explanation of how the signalling through /dev/fuse works, and have not found a good one.

**Comment by rfjakob** [comment]
Multiple processes can have /dev/fuse open, that's not a problem, this will be mapped to multiple unique file descriptors in the kernel. When the kernel wants to unmount, it will answer all read requests on the specific file descriptor with an error code.

Could be a kernel bug. What kernel version are you running?

**Comment by jonleivent** [comment]
I am running 4.19.0-8-amd64.  I have implemented a workaround that makes sure all user processes are terminated before any attempt to unmount.  This has its own set of problems, but is working for now.

**Comment by rfjakob** [comment]
I will close this as "bug outside gocryptfs", as I have no idea how to debug this anyway.
