### ISSUE TITLE
Problem creating gocryptfs with SiriKali

### ISSUE THREAD

**Issue by mhogomchungu** [rfjakob/gocryptfs#46]
Can you please look into this bug report as i think the problem is in gocryptfs: https://github.com/mhogomchungu/sirikali/issues/12

**Comment by rfjakob** [comment]
Should be fixed via https://github.com/mhogomchungu/sirikali/pull/14 , closing the ticket.
I'm subscribed to https://github.com/mhogomchungu/sirikali/issues/12 if any questings.
