### ISSUE TITLE
-masterkey=stdin does not work with -passwd

### ISSUE THREAD

**Issue by IzzySoft** [rfjakob/gocryptfs#461]
When one has to set a new password using the masterkey, `-masterkey=stdin` unfortunately does not work – which forces the user to specify it at the command line. That way it appears at least in the process list – and if run directly from the command line (instead of setting up a script file) also in the shell history. As `-masterkey=stdin` works in other places (e.g. when mounting via masterpassword), I wonder this is not the case here.

Was that intentional? If not, could it be made possible? Thanks in advance!

**Comment by rfjakob** [comment]
Not intentional. yes, will be made possible

**Comment by IzzySoft** [comment]
Thanks! Looking forward to the "closed" notification then (signalizing it was made possible and I shall grab the update :wink:). Luckily not needed that often, so it's easy to wait patiently :rofl:

**Comment by IzzySoft** [comment]
Yay, cool – thanks a lot! I'm grabbing the update then :+1: :green_heart:
