### ISSUE TITLE
Decrypt with OpenSSL

### ISSUE THREAD

**Issue by myous** [rfjakob/gocryptfs#469]
Hello,

Can I decrypt files encrypted with Gocryptfs with OpenSSL or Go Crypto library?

**Comment by myous** [comment]
Or perhaps directory with Go crypto library. The authentication tag makes it less straightforward.

**Comment by rfjakob** [comment]
Well, with some effort, of course. But I find it unlikely that that you don't find a working gocryptfs binary even 10 years in the future, as gocryptfs is packaged by mayor distributions.

**Comment by rfjakob** [comment]
I just became aware of this: @slackner wrote a Python tool to decrypt individual files https://github.com/slackner/gocryptfs-inspect ! This looks like just what you wanted.
