### ISSUE TITLE
Feature Request: Unlink from reverse view

### ISSUE THREAD

**Issue by elseym** [rfjakob/gocryptfs#47]
Given `gocryptfs -reverse data view`
I would like to periodically `find view -mtime +7 -exec mv "{}" cold-storage \;`
and the corresponding item(s) in _data_ be gone.

In other words:
I'd like to (re-)move files from the reverse-view so that the original file is being unlinked.

**Comment by rfjakob** [comment]
Nice use-case!

But it's pretty easy to shoot yourself in the foot, because

* If you forget to copy the gocryptfs.diriv from the folder the file was in or
* Move the file into the wrong folder

the filename will not decrypt correctly and the file will be inaccessible at first.

**Comment by elseym** [comment]
Yeah... But then, according to your logic, should I use crypto or even basic file manipulation at all? 😆

Also, I'd love to contribute with a PR, but I am fairly new to golang and fuse. So this might take a while. Until then I thought I'd share the idea as an issue/feature-request.

Nice project btw. 👍

**Comment by rfjakob** [comment]
That'd certainly be the safest, but also the most boring ;)

I'll accept a PR for this, though I think the user should have to enable it
with "-allow-unlink".

But for the first iteration let's forget about the details, if you want to
get started quickly:
1) main.go forces ro if reverse is active, comment it out
2) copy the Unlink function from internal/fusefrontend into
internal/fusefrontend_reverse/rfs.go and modify the path handling for
reverse mode (compare how the other functions in rfs.go do it).

Take your time, if any questions, I'm available.

**Comment by elseym** [comment]
Awesome, thanks for the hints. I will give it a try and report back. 😸

**Comment by BrandonIngalls** [comment]
I have a separate use-case for the reverse view not being read-only.

I have multiple servers that backup to [borg](https://github.com/borgbackup/borg) nodes which then get synced to multiple cloud providers. The borg repos are stored normally on the borg nodes in and then I use [encfs](https://github.com/vgough/encfs) with `--reverse` to then sync the encrypted view to cloud storage.

There are also local backups that get made to storage servers, so now if I need to restore a backup from cloud storage I end up having to use an [overlay](https://wiki.archlinux.org/index.php/Overlay_filesystem).

So it would be nice to be able to rsync / [rclone](https://github.com/ncw/rclone) backed up encrypted files to the local copy.

**Comment by rfjakob** [comment]
@BrandonIngalls Sorry did not understand! What gets copied to the storage servers? How do you use the overlay?

**Comment by BrandonIngalls** [comment]
#### Application Server
```bash
[Application Server]
# On app server a borg backup is made to a remote server which stores borg
# backups
$ borg create backup@borg-server.company.local:/srv/borg/app1::'backup1' /var/lib/appdata
```

#### Borg Server
```bash
[Borg Server]
$ ls /srv/app1
borg data

# Have encfs reverse mount the repo when it is time to backup to cloud
$ cat /path/to/password/file.txt | encfs --stdin --reverse /srv/borg/app1 /tmp/app1-mount

# Sync encrypted version of borg repo to B2 bucket
$ rclone sync /tmp/app1-mount/ b2:app1/backup/
```

## Restoring from cloud
The `/srv/borg` folder gets backed up to a local NAS, but I keep cloud backups for some things much longer than the local NAS backups. So if I want to restore from an older backup there is a chance that some of the files in the borg repo have not changed.

To restore a backup I use an overlay
```bash
# make the ro version of the --reverse mount writable (kind of)
mount -t overlay -o lowerdir=/tmp/encfs-ro-mount,upperdir=/tmp/empty-rw-folder,workdir=/tmp/overlay-workdir none /tmp/mount
```

I am then able to use rclone/rsync to sync the encrypted data from a cloud service locally, the encfs folder is ro, so the diffrent files will be stored in the `/tmp/empty-rw-folder` and the updated / synced version of the repo will be available at `/tmp/mount`.

**Comment by burdges** [comment]
If I understand, reverse mode only provides read-only access, making it usable for backups, but not for synchronization?

**Comment by rfjakob** [comment]
Yes exactly

**Comment by rfjakob** [comment]
I think it makes sense to close this for now. PRs still welcome.
