### ISSUE TITLE
There should be a way to print the master key on demand

### ISSUE THREAD

**Issue by rpgdev** [rfjakob/gocryptfs#471]
We need a way to get the master key on demand, preferably after retyping your key again. I started using gocryptfs via sirikali (which is mentioned in this project's homepage) and found out about the existence of the master key after I had already created several volumes via sirikali. Turns out there isn't a way to get the master key after volume creation and [there isn't a way for sirikali](https://github.com/mhogomchungu/sirikali/issues/145) to get it _during_ volume creation either:

> Choose a password for protecting your files.
> Reading Password from stdin
> Not running on a terminal, suppressing master key display
> The gocryptfs filesystem has been created successfully.
> You can now mount it using: gocryptfs /home/ink/333 MOUNTPOINT

**Comment by rfjakob** [comment]
Can do using `gocryptfs-xray -dumpmasterkey CIPHERDIR/gocryptfs.conf`, see https://github.com/rfjakob/gocryptfs/blob/master/Documentation/MANPAGE-XRAY.md
