### ISSUE TITLE
How do you track progress of encryption/decryption?

### ISSUE THREAD

**Issue by Kwbmm** [rfjakob/gocryptfs#472]
Hello!
As per title, is there any way to track progress of encryption/decryption operations?
Suppose I need to run some command on the encrypted files, how can I make sure that the encryption is over?

**Comment by rfjakob** [comment]
Hi, encryption/decryption happens in real time. There is no buffering or delayed encryption. When the command that you run completes, the encryption/decryption has completed already, and the file has already been written to the backing filesystem.
