### ISSUE TITLE
No access to gocryptfs from tmux

### ISSUE THREAD

**Issue by durdin85** [rfjakob/gocryptfs#473]
When gocryptfs is mounted in gnome session in Terminal, it's impossible to access the mount from tmux session. I've tried starting tmux from same terminal or from (my default option) running tmux as service via systemd and both results in same:
```
$ cd gofs
-bash: cd: gofs: Permission denied
$ ls gofs
ls: cannot access 'gofs': Permission denied
```
Running gocryptfs with all kind of debug options shown just nothing when above commands are run. However when accessed from another terminal in same gnome session or from remote ssh session it works with debug showing lot of "GETATTR, STATFS, etc..." and directory is accessible. 
Version: Debian testing, gocryptfs 1.7.1, go1.13.5, fuse 2.9.9.

**Comment by rfjakob** [comment]
Can you run `id` in your tmux and in Terminal and see if they are different?

**Comment by durdin85** [comment]
Without tmux (I've removed non-relevant groups), GID is 1000, and my user is also in group 100:
```
$ id
uid=1000(durdin) gid=1000(durdin) groups=1000(durdin),5(tty),...,100(users),...
```

with tmux, seems my GID changed to 100, and group 1000 is missing in the list:
```
$ tmux
...
$ id
uid=1000(durdin) gid=100(users) groups=100(users),5(tty),...
$ cd gofs
-bash: cd: gofs: Permission denied
$
```
Btw. I've tested it also on Raspbian (based on Debian), where the behavior is same.

**Comment by rfjakob** [comment]
Yes, that's the problem. tmux changes your primary group, and then you cannot access your gocryptfs mount. I could reproduce this using sudo here (my tmux here does not change my group):
```
# Run as my user and my group
$ sudo -u jakob -g jakob ls -la b
total 0
drwxr-xr-x. 2 jakob jakob 100 May 17 15:08 .
drwx------. 4 jakob jakob  80 May 17 15:05 ..
-rw-r--r--. 1 jakob jakob   0 May 17 15:08 file1

# Run as my user with different group
$ sudo -u jakob -g root ls -la b
ls: cannot access 'b': Permission denied
```

You can work around this by passing `-allow_other` to gocryptfs. This allows other users (and other groups) to access gocryptfs mounts.
