### ISSUE TITLE
Feature Request: Add option --one-file-system (don't cross filesystem boundaries) in reverse mode

### ISSUE THREAD

**Issue by slackner** [rfjakob/gocryptfs#475]
Thank you for your continous effort to maintain gocryptfs!

I'm still mostly using gocryptfs in reverse mode for backup purposes, and I'm glad to see that support for backing up files from multiple filesystems has been improved with https://github.com/rfjakob/gocryptfs/commit/518771e4e247762f60c5594de427a8c86f19bd57 and follow-up commits.

In some cases, however, I would actually prefer to just backup a single file system. If I would be using `rsync` directly, I could use the

```
 -x, --one-file-system       don't cross filesystem boundaries
```

switch. With `gocryptfs`, however, information about the source filesystem is lost and I have to manually exclude file systems based on the path that I do not want to backup. Is there maybe a chance to get a similar `--one-file-system` switch (for reverse mode) that just does not follow any other devices? It would not matter if the directory itself is preversed or not (I think `rsync` preserves the directory, it is just empty afterwards).

**Comment by rfjakob** [comment]
Yes, I also thought that this could be useful.
