### ISSUE TITLE
Absolute link targets in release tarball

### ISSUE THREAD

**Issue by lechner** [rfjakob/gocryptfs#476]
Hi,

Debian's `lintian` tool now [disallows absolute link targets in source tarballs](https://lintian.debian.org/tags/absolute-symbolic-link-target-in-source.html). Those tarballs are meant to be unpacked anywhere. The unpacked destination is usually not a filesystem root.

If the links are needed for testing, it may be better to generate them in a script.

Kind regards
Felix Lechner (from Debian)
```
W: gocryptfs source: absolute-symbolic-link-target-in-source tests/example_filesystems/content/abs -> /a/b/c/d
W: gocryptfs source: absolute-symbolic-link-target-in-source tests/example_filesystems/v0.4/TBIgdfhDKwkXVTnWLVzFSg== -> /tTXhw8tmmz4PK9YG21Whug==/Qe8z0HUArb5bZJjUqEo2Nw==/wv68UB9DLF9OfAcxgRKKtQ==/9No5n3deBUGa-BsvPRi3DQ==
W: gocryptfs source: absolute-symbolic-link-target-in-source tests/example_filesystems/v0.6-plaintextnames/abs -> /a/b/c/d
W: gocryptfs source: absolute-symbolic-link-target-in-source tests/example_filesystems/v0.7-plaintextnames/abs -> /a/b/c/d
W: gocryptfs source: absolute-symbolic-link-target-in-source tests/example_filesystems/v1.1-reverse-plaintextnames/abs -> /a/b/c/d
W: gocryptfs source: absolute-symbolic-link-target-in-source tests/example_filesystems/v1.1-reverse/abs -> /a/b/c/d
W: gocryptfs source: absolute-symbolic-link-target-in-source tests/example_filesystems/v1.3-reverse/abs -> /a/b/c/d
```

**Comment by rfjakob** [comment]
Hmm, yes, these symlinks are part of example filesystems that are used for testing. These filesystems were copied as-is into the source tree, and I think that's the right approach.

Seems like a valid reason for a override as listed here http://www.fifi.org/doc/lintian/lintian.html/ch2.html ?
