### ISSUE TITLE
Add ability to decrypt files without fuse

### ISSUE THREAD

**Issue by dabeeeenster** [rfjakob/gocryptfs#477]
It would be super useful to be able to decrypt some files without having to install FUSE onto the device. This would help with decryption on Android, as well as being able to get access to files without having to install a kernel level component on OSX etc. 

I realise it maybe isn't within the philosophy of the library but I'd find that option super helpful.

**Comment by rfjakob** [comment]
You are lucky, there's a Python script that does just that: https://github.com/slackner/gocryptfs-inspect

**Comment by rfjakob** [comment]
PS: Maybe give the repo a star on Github ;)

**Comment by dabeeeenster** [comment]
Ah perfect thanks
