### ISSUE TITLE
Memory used by scrypt doesn't seem to be released whilst FS is mounted

### ISSUE THREAD

**Issue by jpluscplusm** [rfjakob/gocryptfs#478]
Hi folks - thanks for this fantastically useful tool!

Whilst playing around with increased `-scryptn` values (see below for the rationale), I noticed that the persistent gocryptfs process which actually mounts a directory keeps hold of a *lot* of memory when the scryptn value is large.

Going by the comments here (https://github.com/rfjakob/gocryptfs/blob/master/mount.go#L159), am I right to believe that increasing the complexity value for scrypt's N should only increase memory on FS initialisation or at mount time?

`check-mem.sh.txt` is the script I ran to demonstrate the increased memory use, and `script.log` is its output when I run it. Note the `sleep 10` to (hopefully) show that it's not an (obvious) race condition with the GC having just not run, post-mount.

[check-mem.sh.txt](https://github.com/rfjakob/gocryptfs/files/4646183/check-mem.sh.txt)
[script.log](https://github.com/rfjakob/gocryptfs/files/4646184/script.log)

Rationale: I want to sync the encrypted dir to cloud storage, and paying the cost of a relatively brief memory/CPU spike during FS mounting isn't a problem for me, if it buys me significantly "moar encryption" :-) It's only going to be annoying if the memory isn't returned - as I think I'm observing!

**Comment by rfjakob** [comment]
I think what you are seeing is caused by [MADV_FREE used in Go 1.12+](https://golang.org/doc/go1.12#runtime). I tried with `-scryptn 22`, and gocryptfs will consume 4.3 GiB of memory as reported in RSS.

However, looking at /proc/PID/smaps, we see

```
$ grep LazyFree /proc/89792/smaps
[...]
LazyFree:        4042752 kB
[...]
```
that 4 GiB is "LazyFree". This memory is actually available for use.


Let's look at `free -m`'s `available column` (rightmost colum) when I mount a `-scryptn=22` filesystem:
```
$ while sleep 1 ; do free -m | grep Mem ; done
Mem:          23907        7429       13968         911        2509       19272
Mem:          23907        7430       13959         920        2518       19262
Mem:          23907        7430       13959         919        2517       19263
Mem:          23907        7431       13959         918        2516       19263
Mem:          23907        7438       13951         920        2518       19255
Mem:          23907        8150       13239         920        2518       18543
Mem:          23907        8880       12517         911        2509       17821
Mem:          23907        9608       11789         911        2509       17093
Mem:          23907       10337       11060         912        2510       16363
Mem:          23907       11066       10331         912        2510       15634
Mem:          23907       11673        9724         911        2509       15028
Mem:          23907       11673        9724         911        2509       15028
Mem:          23907       11673        9724         911        2509       15028
Mem:          23907       11673        9724         911        2509       15028
Mem:          23907       11673        9724         911        2509       15028
Mem:          23907       11673        9724         911        2509       15028
Mem:          23907       11721        9676         911        2509       14980
Mem:          23907       11721        9676         912        2510       19076
Mem:          23907       11721        9676         912        2510       19076
Mem:          23907       11721        9675         912        2510       19075
Mem:          23907       11673        9709         926        2524       19109
```
The memory goes back to "available" once the filesystem is mounted.
