### ISSUE TITLE
Library for usage in other projects

### ISSUE THREAD

**Issue by darkdragon-001** [rfjakob/gocryptfs#480]
It would be nice if you could provide a library to include gocryptfs (and keep it updated) in other projects. This would also allow cross-compatibility!

Specifically, I am referring to https://github.com/rclone/rclone/issues/637#issuecomment-631380771, https://github.com/rclone/rclone/issues/4194.

**Comment by rfjakob** [comment]
Yes exposing some functionality as a library would certainly be possible, if other projects find it useful.

**Comment by Vesnyx** [comment]
Hey @rfjakob, just wondering if you have any advice for adding gocryptfs as a library for rclone. I don't really want to reuse the entire codebase, and well, frankly, I don't know where to start.

I think I'll start with decrypting and encrypting individual files and later move on to actually creating new file systems, but I'll happily accept any feedback if you think there's an easier way to do this.

**Comment by rfjakob** [comment]
Hi, for encrypting file names you mean? As far as I can see, rclone already does content encryption itself.

**Comment by mattalexx** [comment]
@rfjakob gocryptfs seems to offer more reliable encryption than rclone (https://github.com/rclone/rclone/issues/637, https://defuse.ca/audits/gocryptfs.htm, ...).

**Comment by gotjoshua** [comment]
is there any progress on this?

**Comment by bryankaplan** [comment]
@rfjakob Why was this ticket closed as “completed”?

**Comment by rfjakob** [comment]
Tbh i don't remember.

What functionality would you like to have exported?

**Comment by bryankaplan** [comment]
@rfjakob wrote:
> What functionality would you like to have exported?

@Vesnyx Could you answer that question with more specificity than in https://github.com/rfjakob/gocryptfs/issues/480#issuecomment-664636932? What would the ideal gocryptfs library API look like, to support https://github.com/rclone/rclone/issues/637#issuecomment-631380771 and https://github.com/rclone/rclone/issues/4194?
