### ISSUE TITLE
QA: How to keep the file naming scheme the same between reverse and normal modes?

### ISSUE THREAD

**Issue by gerroon** [rfjakob/gocryptfs#484]
Hi

Is it possible to keep the file name scheme to be the same between reverse and normal modes when both will be synced against each other?

I already copied couple terabytes to a remote computer. It took couple weeks and if I can avoid doing it all over that would be great. 

I am thinking that I can create a folder with the exact same remote folders content and use the reverse mode to get the encrypted versions locally. Then I will remotely create a new Gocryptfs repo and move all those couple tb files into the new remote remotely. 

So far so good, then I want to sync the local reverse mode against the remote normal mode repo. I did couple tests but I cant get the same file names even after copying the salt and the encrypt key portion of the configs.  I am thinking that in theory that should work but it does not work because the file names for folders and files do not match. So this is futile.

I am wondering maybe there is some settings that i can set so they match. I am sure the contents match but without same file naming this wont work

thanks

**Comment by gerroon** [comment]
I also rsynced the reverse folder (in reverse mode) and mounted it to plain. I copied an exact folder to both sides (local/reverse, remote/plain) however I stioll cant get the file names to be the same. Only the first level has the same file name but I assume becasue there is already a .diriv file there.

**Comment by gerroon** [comment]
@rfjakob 

I am still tryign to figure out this issue. One hack I am thinking that could work is this, although I am hoping that there is a proper legit way.

- Copy/Create all the reverse mode folders recursively without any files in them on the remote 
- Copy all the .diriv files recursively  on the remote
- Mount this folder on the remote
- Move all those couple tb backups to the mounted `plain` folder
- Now I can rsync between the local reverse mode and remote cipher folder properly

**Comment by rfjakob** [comment]
Hi, I did not understand completely. So you have

*** Remote PC ***
[ bigfolder plaintext ]



*** Local PC ***
[ bigfolder plaintext ] ---- reverse mount ---> [ bigfolder encrypted ]

?

**Comment by rfjakob** [comment]
If I understood the goal completely, you can do:

Copy gocryptfs.reverse.conf to Remote PC. Then,

*** Remote PC ***
[ bigfolder plaintext ] ---- reverse mount ---> [ bigfolder encrypted ] --- rsync ---->  [ bigfolder encrypted 2 ]

Now you have [ bigfolder encrypted 2 ] on disk that should be identical to [ bigfolder encrypted ] on Local PC.

Then delete [ bigfolder plaintext ].

**Comment by gerroon** [comment]
Hi 

Thanks for the suggestion. Just to be sure, my problem is not getting identical folders, I am able to do that but my main issue is that even thou mounted folders seem identical the **new** file  names on the remote folder are not created identical therefor any syncing would fail since the `reverse on local` is wont be identical to `cipher on remote` 

I will give it a try though.

**Comment by rfjakob** [comment]
This pull request will make it possible to have deterministic file names, which also means they will be the same for forward and reverse mode: https://github.com/rfjakob/gocryptfs/pull/592 . Please subscribe there to track progress!
