### ISSUE TITLE
FR: Do not ask for pass in reverse mode once set

### ISSUE THREAD

**Issue by gerroon** [rfjakob/gocryptfs#487]
Hi

It would be nice Gocryptfs does not ask for a password once the reverse mode is set initially. I see that there is also a a reverse conf in a folder that is used for reverse mode. I am jut wondering why the reverse mode requires subseguent passwords to mount it as reverse, given that it has been mounted successfully prior.

thanks

**Comment by rfjakob** [comment]
This is to keep reverse mode symmetric to forward mode. But you can save your password in a file and use `-passfile mypassword.txt` to mount without being asked for the password.
