### ISSUE TITLE
Why not collaborate with EncFS?

### ISSUE THREAD

**Issue by samrocketman** [rfjakob/gocryptfs#49]
Hello @rfjakob,
I'm curious, why not collaborate with EncFS to help address open security issues rather than start a completely new project from scratch?

Disclaimer: I once migrated EncFS from SVN to Git.  Probably my only meaningful contribution to the project but I've contributed to it none the less.

**Comment by rfjakob** [comment]
Oh I did and still do, check out https://github.com/vgough/encfs/commits?author=rfjakob ;)

I tried to improve EncFS where I could, but ultimately thought that starting a new project was the way to go.

**Comment by samrocketman** [comment]
Oh yeah!  I recognize your username now 👍 I don't know why I didn't before.  Silly me 😃

**Comment by samrocketman** [comment]
I've been going around asking forks of forks that same question because I'm curious what their answers are.  Yours is probably the best haha.

**Comment by Aikhjarto** [comment]
@samrocketman It would be quite interesting who you asked and what they answered. Can you (at some point) publish a summary of your survey?

**Comment by samrocketman** [comment]
Sure, I don't mind publishing a summary.  So far this is only the second project I've asked.  I don't mind linking to the first.  See https://github.com/keepassxreboot/keepassx/issues/43

**Comment by benrubson** [comment]
I also think that it would be nice to keep _encfs_ maintained : it has been audited, so security issues are known, and then could certainly be corrected.
In addition it is widely used, sometimes in production environments, it's then quite difficult to migrate from _encfs_ to another product.
It is also written in C++ which makes it easy to install on a wide range of systems : Linux, FreeBSD, Synology / Qnap...
[Perhaps we could start the dev again ?](https://github.com/vgough/encfs/issues/314) Would be really nice 👍 

But I also understand the idea of starting a new project, for instance _gocryptfs_, and of course thank you for this @rfjakob 👍

**Comment by rfjakob** [comment]
Of course that would be a good thing. I guess somebody will have to step up and lead the project (I'll answer in more detain in the other thread)
PS: I don't know if you are aware, gocryptfs has been audited as well: https://defuse.ca/audits/gocryptfs.htm

**Comment by benrubson** [comment]
No I was not aware, thank you very much for the link !
