### ISSUE TITLE
Possible Master Key Issue / Caching?

### ISSUE THREAD

**Issue by mcgeo33** [rfjakob/gocryptfs#490]
I needed to find out my master key on one of my folders, so I did that, but then forgot to copy the master key to the command. However, the mount was successful even with the wrong key. (Issue 1)

`me@mycomp:~$ gocryptfs-xray -dumpmasterkey ~/Google\ Drive/Folder/gocryptfs.conf`
`Password: `
`<REDACTED>6637006a239f7e`
`me@mycomp:~$ gocryptfs -masterkey <REDACTED>-d36d5d6f  ~/Google\ Drive/Folder/ ~/Vaults/Folder/`
`Using explicit master key.`
`THE MASTER KEY IS VISIBLE VIA "ps ax" AND MAY BE STORED IN YOUR SHELL HISTORY!`
`ONLY USE THIS MODE FOR EMERGENCIES`
`Filesystem mounted and ready.`

Finding this curious, I was playing around with another mount when I noticed the master key doesn't have to be exact (Issue 2) I changed the last character of the master key (f -> e) and the mount was still successful. (ending in f is the actual key)

`me@mycomp:~$ gocryptfs -masterkey <REDACTED>-d36d5d6f ~/Google\ Drive/Private/ ~/Vaults/Private/`
`Using explicit master key.`
`THE MASTER KEY IS VISIBLE VIA "ps ax" AND MAY BE STORED IN YOUR SHELL HISTORY!`
`ONLY USE THIS MODE FOR EMERGENCIES`
`Filesystem mounted and ready.`
`me@mycomp:~$ gocryptfs -masterkey <REDACTED>-d36d5d6e ~/Google\ Drive/Private/ ~/Vaults/Private/`
`Using explicit master key.`
`THE MASTER KEY IS VISIBLE VIA "ps ax" AND MAY BE STORED IN YOUR SHELL HISTORY!`
`ONLY USE THIS MODE FOR EMERGENCIES`
`Filesystem mounted and ready.`

Is there some sort of caching going on that I'm not aware of?
Also, a minor nitpick but the masterkey string produced by the xray has no dashes while the key produced by init does use dashes.

**Comment by rfjakob** [comment]
gocryptfs cannot detect if the masterkey is correct or wrong. The mount will succeed, but if the masterkey it is wrong, all the data will be unreadable (you will see an empty directory).
