### ISSUE TITLE
Feature request: -badname should be honoured when used alongside -plaintextnames

### ISSUE THREAD

**Issue by jpluscplusm** [rfjakob/gocryptfs#493]
As I understand it from reading the source, any files in the encrypted directory matching `-badname` globs are removed from the directory listing presented to the user via the plain text directory during encrypted filename unmunging.

As such, using `-plaintextnames` on FS creation disables the user/admin's ability to communicate that certain files/globs shouldn't be passed through for access from the plain text directory.

Could `-badname` params be honoured when used with the `-plaintextnames` option? I'm happy to write up my use case for this, if it would be a useful datapoint :-)

**Comment by jpluscplusm** [comment]
I've written a minimal implementation of this, and will push it to my fork as soon as I have some decent test coverage.

**Comment by rfjakob** [comment]
Hi, yes, what is the use case for this?

For implementing it, I think `-exclude` would be the right flag. The use case for `-badname` is to make corrupted names **visible** to the user, not invisible.

**Comment by jpluscplusm** [comment]
Oh, I'd totally interpreted that the wrong way round! I'll add a new flag and not overload the badname flag :-)

My use case is gocryptfs-on-git. I.e. storing an overlay FS inside a repo, so that it can be pushed to an untrusted git host. I'm writing the process up to publish shortly, and I'm including how we don't have to give up nice git features like diffs and so on, despite the content being essentially invisible to git. 

However, for the best UX I can currently concoct, certain files need to be visible to git, plaintext in the worktree, -- which is actually the underlying encrypted directory. Files like .gitignore and .gitattributes.

The ability to say "these files aren't exposed in the mounted dir" (or perhaps even "these files are forwarded as plaintext"?) would make the user's experience significantly nicer! Hence this Issue, and my first attempt to write FS-related code :-)
