### ISSUE TITLE
On linux mint dkpg and apt-get won't work with a .DEB file stored inside a gocryptfs decrypted directory

### ISSUE THREAD

**Issue by FernandoJCabral** [rfjakob/gocryptfs#495]
Here is the issue: I have a _X.deb_ file stored in a gocryptfs. Then I mount it. All is well. Then I try to install that deb file either with:

`sudo dpkg -i X.deb`
or with
`sudo apt-get install X.deb`
they both throw out an error message to the effect that "file is not found". It does not matter if I provide a full path, or a relative path. Now, if I copy that file out (to another directory) than it works fine.

So, for some reason, dpkg and apt-get do not see .DEB files when they are in a mounted and decrypted gocryptfs directory.

**Comment by rfjakob** [comment]
When you run this with `sudo`, an application running as root will try to access a file inside your mount. The same thing will happen with `sudo ls`. You have to pass `-allow_other` for this to work.

**Comment by FernandoJCabral** [comment]
Umderstood. Thank you.

Fernando Cabral
Enviado pelo ProtonMail, serviço suíço de e-mail criptografado.

Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Em sábado, 15 de agosto de 2020 às 12:35, rfjakob <notifications@github.com> escreveu:
