### ISSUE TITLE
Packaging request: could gocryptfs-xray be included in future GitHub Releases?

### ISSUE THREAD

**Issue by jpluscplusm** [rfjakob/gocryptfs#496]
Hey there 👋 

tl;dr It'd be Nice To Have a blessed/known-good binary of -xray as part of future GitHub Releases.

So, whilst I can build the gocryptfs-xray binary, I /suspect/ the release process already builds it for every platform whilst building the main binary.

Could the binary be included in the Release assets in the future? Preferably (my opinion serving only as one datapoint!) in a separate archive file, but I'm not picky about that.

TVVM!

**Comment by jpluscplusm** [comment]
I'm happy to help with the legwork to automate this, if that'd be useful!

**Comment by bexelbie** [comment]
FWIW, when I package for Fedora, I put gocryptfs-xray into a separate package.  If we can separate the upstream release artifacts that will help users of Fedora realize why there are two packages.

**Comment by rfjakob** [comment]
@bexelbie Understood, but each extra file is extra work for signing & uploading to Github, so I have added it to the "linux-static" tarball now.

**Comment by jpluscplusm** [comment]
Many thanks @rfjakob! :-)
