### ISSUE TITLE
QA: How to auto-mount the encrypted dir on boot in alpine linux by /etc/fstab?

### ISSUE THREAD

**Issue by Zerorigin** [rfjakob/gocryptfs#497]
I have tries：
https://github.com/rfjakob/gocryptfs/issues/45
https://github.com/rfjakob/gocryptfs/wiki/Mounting-on-login-using-pam_mount
https://github.com/rfjakob/gocryptfs/wiki/Mounting-on-login-with-Gnome-keyring

None of these are work for me.
Maybe I missed some steps which is important, but I don't know where I missed it.
Anyone can give me a little help?

**Comment by rfjakob** [comment]
I just tried this fstab line on my Fedora:
```
/tmp/cipher /tmp/plain fuse./usr/local/bin/gocryptfs nofail,allow_other,passfile=/tmp/password 0 0
```

Works ok:
```
$ sudo mount -av
/                        : ignored
/boot                    : already mounted
passfile: reading from file "/tmp/password"
Decrypting master key
The option "-allow_other" is set. Make sure the file permissions protect your data from unwanted access.
Filesystem mounted and ready.
/tmp/plain               : successfully mounted
```
