### ISSUE TITLE
How to tell which files belong to gocryptfs?

### ISSUE THREAD

**Issue by chrisisbd** [rfjakob/gocryptfs#498]
I think (but I'm not really sure) that I have old encfs encrypted files in a gocryptfs encrypted directory.  When I changed from using encfs to gocryptfs I didn't think of this problem!

Given an encrypted directory how can I tell which files belong to gocryptfs?

**Comment by rfjakob** [comment]
Hi, you can run

    gocryptfs -fsck DIRECTORY

It will complain about all files it cannot decrypt.
