### ISSUE TITLE
Is reverse mounting possible?

### ISSUE THREAD

**Issue by dakkusingh** [rfjakob/gocryptfs#5]
Is reverse mounting possible? Ie. mount a normal folder and come up with a fuse encrypted one?

> No, and this is not planned at the moment. The thing is, AES-GCM (the encryption mode that gocryptfs uses) needs a random value for each block. For forward encryption, this random value is stored on disk inside the encrypted files. For reverse mode, there is no place to store that value.

See discussion here https://github.com/rfjakob/gocryptfs/issues/2#issuecomment-152918526 and here https://github.com/rfjakob/gocryptfs/issues/2#issuecomment-152951598

**Comment by rfjakob** [comment]
Even after having thought about it for a while I see no sane way to do this in gocryptfs.

**Comment by rfjakob** [comment]
I want to mention that there is Attic ( https://attic-backup.org/ ) that provides a superior alternative to reverse mode for encrypted backups. I am using it myself with great results.
The key point for encrypted backups is that the encryption must happen locally. This is what encfs reverse mode can be used for, but this is also what attic does.
