### ISSUE TITLE
Document how to mount cipher in a cloud folder and how files are deleted

### ISSUE THREAD

**Issue by Brixy** [rfjakob/gocryptfs#501]
Thank you for developing and maintaining gocryptfs!

I have two issues concerning the docs:

**1)**

When you mount `cipher/` within a cloud storage folder (e.g. `~/Sync/`) your cloud service will unencryptedly sync your secret files and folders from `~/Sync/plain/` (roughly tested with one cloud storage service only).

This is a way to prevent this (also only roughly tested):

```
cd ~/Desktop/ && gocryptfs ~/Dropbox/cipher plain
```

Should something like this be documented in [Quickstart](https://nuetzlich.net/gocryptfs/quickstart/) or [Best Practices](https://github.com/rfjakob/gocryptfs/wiki/Best-Practices)?

**2)**

When you delete files from within mounted `plain/`, these files are not moved to trash but ‘really’ deleted.

Are these files deleted safely or just with something like `rm`? Maybe this could be documented, too?

Thank you!

**Comment by impredicative** [comment]
About (1), obviously `plain` should not be mounted inside `~/Sync/`. I don't see a problem here. It is common-sensical.

About (2), Ubuntu can move the deleted files to `plain/.Trash` instead of actually deleting them, but `rm` should actually delete them just fine.

**Comment by Brixy** [comment]
Thanks you!

Ad 1) You are right, it is obvious, but maybe not to all users. The quickstart explains how to mount a filesystem in the same folder where `cipher` is located. For cloud services something like this would be a helpful addition:

```
gocryptfs ~/sync-folder/…/cipher ~/Desktop/plain
```

Many cloud services store versions of files—even if they were deleted. So I think this is an important aspect.

**Comment by rfjakob** [comment]
(1) Added "Cloud Storage" section to https://nuetzlich.net/gocryptfs/quickstart/

(2) Files are deleted like "rm". That means the encrypted content may stay on disk for some time.
If you want to overwrite immediately, you can delete from the plain folder using the `shred` utility.
