### ISSUE TITLE
Question- is there a way to restore data if the gocryptfs.diriv is lost?

### ISSUE THREAD

**Issue by ashjas** [rfjakob/gocryptfs#502]
Hello,

I upload the encrypted files from a reverse gocrypt volume.

If for any reason the gocryptfs.diriv gets corrupted or goes missing, is there any way to resotre the data ?
e.g:
plain.text -> plain.crypt
i upload "plain.crypt" folder to cloud which contains the gocryptfs.diriv file.

Later, if i download the plain.crypt folder from the cloud, and for some reason, i am not able to restore few files, which could include the gocryptfs.diriv file(maybe it got corrupted or some other issue).

Under this state, if i mount the plain.crypt folder to get back the plain.text folder, i generally get the "can not open directory" on accessing it.
Is there still any way to get back my data?

Thanks.

**Comment by ashjas** [comment]
So how do I restore if I can't do `ls` with the file missing?

**Comment by rfjakob** [comment]
Yes you can, it works like this:

1) Check encrypted directory for how many files are there and note that number (let's assume 10 files here)
2) Create new `gocryptfs.diriv` file to replace the missing one: `dd if=/dev/urandom of=gocryptfs.diriv bs=16 count`
3) Create 10 empty files in the plaintext directory, maybe file1 file2 .... file2
4) Check `ls -ltr` on the encrypted directory and note the 10 new encrypted file names
5) Delete the empty files from plaintext directory
6) Rename all files in the encrypted directory to one of the 10 new encrypted file names
