### ISSUE TITLE
Implement hardware authentication via FIDO2

### ISSUE THREAD

**Issue by prusnak** [rfjakob/gocryptfs#504]
It is possible to use FIDO2 authenticators to produce an encryption keys via FIDO2 hmac-secret extension. There is a project go-libfido2 which wraps libfido2 library into Go. It's documentation even contains HMAC secret example: https://github.com/keys-pub/go-libfido2/blob/master/README.md

**Comment by prusnak** [comment]
I am not a Go developer, but I think the steps could be the following:

1. introduce `-fido2` option which will act similary to `-extpass` but would query FIDO2 tokens instead of running an external shell script

2. When doing `-init` call the FIDO2 `MakeCredential` method to generate a credential and store `attest.CredentialID` into the config file, also random `hmacSalt` needs to be generated and stored

3. In order to obtain the encryption/decryption key (both during the init phase and mount phase), gocryptfs needs to call FIDO2 `Assertion` method, pass it the stored `CredentialID` and `hmacSalt` to obtain the assertion. Afterwards `assertion.HMACSecret` can be used as an encryption/decryption key.

**Comment by prusnak** [comment]
Created an implementation here: https://github.com/rfjakob/gocryptfs/pull/505 - comments are welcome!

**Comment by rfjakob** [comment]
Implementation included in v2.0-beta1, thanks!
