### ISSUE TITLE
No newline at EOF in gocryptfs.conf

### ISSUE THREAD

**Issue by xelra** [rfjakob/gocryptfs#51]
As the title already says, when `cat`-ing `gocryptfs.conf` I've noticed that the file doesn't have a newline at the end.

**Comment by rfjakob** [comment]
This is how I get from `json.MarshalIndent`, but I guess there is no reason to not have a trailing newline. Done in a74a7e7f547e021abc9b9fd956f3cae54d740dd3 , thanks.
