### ISSUE TITLE
finer control over master keys

### ISSUE THREAD

**Issue by brainchild0** [rfjakob/gocryptfs#510]
Applications are available that scan a Btrfs volume for duplicate blocks. When found, one of the duplicates is deleted to free disk space, without affecting the files, due to the multi-tier design of the system, the same feature that makes possible lightweight, CoW file copying.

This process, called de-duplication, is beneficial even for gocryptfs volumes, but a major limitation is that either the scanned blocks must be in the same gocryptfs store, or in stores that have the same master key. Otherwise, the utility would not discover any duplicated physical data.

For two existing stores with different master keys, it would be useful to change the master key on one store to match  that of the other. Because such a procedure involves transcryption of an entire store, it may be impractical generally. 

A much simpler feature would be to support the creation of a new store that  uses the same master key as an existing store (for which the password is given). 

Then duplicate files entered into the second store would also be physical duplicates, and would benefit from the de-duplication utilities.

**Comment by brainchild0** [comment]
An informal test has seemed to suggest that sharing a master key and content is not sufficient to produce an identical encrypted representation? The test consisted of creating a store, forking it, then populating mounts of both with the same data.

Does the system include session-level salt to obfuscate the encrypted representation?

**Comment by rfjakob** [comment]
That is correct, there is 16 bytes of random data in each 4kiB block.

I think to do what you want, you need https://github.com/rfjakob/gocryptfs/issues/108 ?

**Comment by brainchild0** [comment]
> I think to do what you want, you need #108 ?

Yes, it seems that way.

**Comment by rfjakob** [comment]
I will close this in favor of the older ticket #108
