### ISSUE TITLE
Move/copy encrypted files between encrypted file systems mounts

### ISSUE THREAD

**Issue by loungebob** [rfjakob/gocryptfs#511]
Dont really know where to ask this but can I move encrypted files (the actual encrypted files) between different mounts with the same password? I tried, didnt work. 
I would like to move encrypted file A from the encrypted file system mount A to encrypted file system mount B, the actual encrypted file, not the decrypted, and then being able to read it in mount B. I tried this - used the same password for mount A and for mount B, even tried the create a text doc file then use that filename to change the encrypted file names name (which usually works when using files created within mount A and used in mount A) but it did not work, judging by the file size it stayed encrypted and I cant read it.
Cant I do that, move files between encrypted file systems when the password is the same?

**Comment by brainchild0** [comment]
Unless the two stores use the same master key, then achieving this idea is impossible even if principle. The password is not used to encrypt the content, only the master key, which in turn is used, among perhaps other data, to encrypt the content. This method enables changing a password without changing the encrypted content, only changing the encrypted representation of the master key.

**Comment by loungebob** [comment]
ok, get it. 

and the reason I cant change to master key on an existing store is, all data would not be decryptable anymore since it was encrypted with another master key, right?

**Comment by brainchild0** [comment]
> and the reason I cant change to master key on an existing store is, all data would not be decryptable anymore since it was encrypted with another master key, right?

For that reason at least, yes. Actually I am not very knowledgeable about ciphers, but I am confident that the master key, which is generated when the store is initialized, is required to decrypt anything placed into it.

**Comment by rfjakob** [comment]
Correct.

@loungebob You can only achieve moving files from A to B by using the same gocryptfs.conf (so you have the same master key) on both A and B.
