### ISSUE TITLE
Mounting Error RaspberryPi - DietPi

### ISSUE THREAD

**Issue by sharkeydavid** [rfjakob/gocryptfs#512]
**Device model : RPi 4 Model B (armv7l)
OS: DietPi_RPi-ARMv6-Buster
Notes: External Drive mounted in /mnt/myDrive using DietPi panel (formatted EXT4)**

Issue: When mounting in the system using standard gocryptfs setup, the mounting point is not accessible. I have tried mounting inside and outside the external drive with no success. Latest Fuse installed and mounting works on my Mac no problem. 

![Screen Shot 2020-10-06 at 14 31 11](https://user-images.githubusercontent.com/19961868/95208283-ca1e8a80-07e0-11eb-88c3-2627259b37af.png)

Below is the output when -debug is enabled:

`dietpi@DietPi:/$ sudo gocryptfs -d /mnt/myDrive/myCrypt ./plain
OpenSSL enabled
cli args: &main.argContainer{debug:true, init:false, zerokey:false, fusedebug:false, openssl:true, passwd:false, fg:true, version:false, plaintextnames:false, quiet:false, nosyslog:false, wpanic:false, longnames:true, allow_other:false, reverse:false, aessiv:false, nonempty:false, raw64:true, noprealloc:false, speed:false, hkdf:true, serialize_reads:false, forcedecode:false, hh:false, info:false, sharedstorage:false, devrandom:false, fsck:false, trezor:false, dev:false, nodev:false, suid:false, nosuid:false, exec:false, noexec:false, rw:false, ro:false, masterkey:"", mountpoint:"/plain", cipherdir:"/mnt/myDrive/myCrypt", cpuprofile:"", extpass:"", memprofile:"", ko:"", passfile:"", ctlsock:"", fsname:"", force_owner:"", trace:"", exclude:main.multipleStrings(nil), config:"/mnt/myDrive/myCrypt/gocryptfs.conf", notifypid:2103, scryptn:16, _configCustom:false, _ctlsockFd:net.Listener(nil), _forceOwner:(*fuse.Owner)(nil)}
Password: 
Decrypting master key
frontendArgs: {
	"Cipherdir": "/mnt/myDrive/myCrypt",
	"PlaintextNames": false,
	"LongNames": true,
	"PreserveOwner": false,
	"ForceOwner": null,
	"ConfigCustom": false,
	"NoPrealloc": false,
	"SerializeReads": false,
	"ForceDecode": false,
	"Exclude": null
}
Filesystem mounted and ready.`

Any help appreciated - love the project.

**Comment by rfjakob** [comment]
Hi, can you try

    sudo ls

?

**Comment by sharkeydavid** [comment]
Hi - damn you're quick. 

Yes see below:

<img width="355" alt="Screen Shot 2020-10-06 at 14 51 43" src="https://user-images.githubusercontent.com/19961868/95210522-7e211500-07e3-11eb-932d-d5c54da2700f.png">


I already feel this is going to be something stupid simple.

**Comment by sharkeydavid** [comment]
This issue can be closed. I `chown -R dietpi:dietpi ./*`in the directory and it was visible instantly. Strange i didn't have this issue before but maybe there was some other changes I made before.
