### ISSUE TITLE
gocryptfs-xray feature request: decrypt individual encrypted file, from STDIN or other FD

### ISSUE THREAD

**Issue by hlein** [rfjakob/gocryptfs#513]
I'm considering using gocryptfs in a situation[*] where it would be useful to sometimes be able to decrypt a given file's contents, but the file isn't available on-disk any more. So for that case, it'd be great if gocryptfs-xray could be told "hey, here's all the metadata and key material you need, please decrypt this blob from STDIN" (maybe using the myfs.sock approach?).

It sounds like decrypt-and-cat-an-encrypted-file has been discussed as a possible eventual feature for -xray. Is the idea of reading contents from STDIN or another file descriptor practical, or does gocryptfs need to be able to seek through the file, etc., making a pipe infeasible?

[*] I'm experimenting with using a fuse encrypted filesystem where the encrypted contents are stored in a git repo. I've written a git-wrapper that can detect when it is being run from an encrypted fuse-mounted dir, find the real encrypted backing-store git repo, and convert plaintext file-paths to the correct encrypted path where necessary, and Do What I Mean for most git commands (add, rm, commit, mv, pull, push, etc.). But git diff is a problem. If I could invoke gocryptfs-xray cat like I described, then I could do something like (very roughly):

```
# Examine diff between HEAD version and working copy of a file:
$ git diff foo.txt -->
  diff <(git cat-file object_corresponding_to_encrypted_foo.txt | gocryptfs-xray cat ... -) foo.txt

# Examine diff between two existing revisions of a file:
$ git diff dead..code foo.txt -->
  diff <(gocryptfs-xray cat ... <(git cat-file ...dead)) <(gocryptfs-xray cat ... <(git cat-file ...code))
```

Thanks!

**Comment by rfjakob** [comment]
I don't think I will implement this, but I would accept a patch to add that functionality.

But, the **gocryptfs Inspection Tools** @ https://github.com/slackner/gocryptfs-inspect can do this, today!
