### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by impredicative** [rfjakob/gocryptfs#516]
Is it safe to release a stable new version? It says there are 150 commits since v1.8.0. Thanks.

**Comment by impredicative** [comment]
Disregard. I see v2.0-beta1 is out.

**Comment by rfjakob** [comment]
But I forgot to create a release on github - done now, thanks

**Comment by impredicative** [comment]
@rfjakob I trust you will as usual add a binary that I can download. Thanks.

**Comment by rfjakob** [comment]
Will you try it out if I do? ;)

**Comment by impredicative** [comment]
Yes, I want to.

**Comment by impredicative** [comment]
I will both try it and write about it to make others aware, assuming it works well. I understand it is a beta release.

**Comment by rfjakob** [comment]
Appreciate it! Binary uploaded. Should work ok, but slow. Performance  optimizatios are in progress the way ( https://github.com/rfjakob/gocryptfs/commit/c943ed32aaf94a4e60d96c7a513180d29b15a40a ,
https://github.com/rfjakob/gocryptfs/commit/6697ffd6e213828ff4cd873cd1d104877096a230 )
