### ISSUE TITLE
Keeping crypt dir in git

### ISSUE THREAD

**Issue by impredicative** [rfjakob/gocryptfs#518]
Are there any objections to keeping and tracking the crypt dir in a dedicated git repo? This is a serious intended use case for me. The crypt dir will therefore also contain a `.git` dir, which I suppose gocryptfs will ignore.

For safety, I mounted the decrypted dir while using the `-sharedstorage` option. Did I miss anything?

**Comment by rfjakob** [comment]
I see no issues here. Only thing is that gocryptfs will complain in syslog about the ".git" filename it cannot decrypt. Of course the git history will show which encrypted blocks have changed in which files.

**Comment by impredicative** [comment]
I'm wondering if would be recommended to either:
1. Update gocryptfs to ignore the `.git` folder. That's because this can become a popular use case.
2. For the user to keep the crypt data in a subfolder, e.g. `mygitrepo/crypt`, so gocryptfs doesn't see the `mygitrepo/.git` folder at all.

**Comment by impredicative** [comment]
To prevent any possible conflict between gocryptfs and git, I now keep the crypt data in my git repo in a subdirectory named `fs`.

**Comment by impredicative** [comment]
I put together a simple bash utility at https://github.com/impredicative/gec to help me with my abovementioned use case.

**Comment by impredicative** [comment]
Just to update, I have been heavily using v2.0-beta1 of gocryptfs. Thank you.

I have further developed `gec`, and it may now also be used by some other users. This indirectly means more users of gocryptfs.

I trust that v2.* of gocryptfs will of course not cause any breaking changes.
