### ISSUE TITLE
Feature request: Splitt encrypted files into configurable chunks

### ISSUE THREAD

**Issue by tolotos-rgu** [rfjakob/gocryptfs#52]
Hi, I try to use gocryptfs with amazon cloud (https://github.com/yadayada/acd_cli). Unfortunately amazon has a size limit to its upload. I want to use it for a storage of my multi media data center. Ripped bluray movies are larger than the allowed 10GiB per file. It would be nice if gocryptfs split the files automatically. 
-- Tolotos

**Comment by rfjakob** [comment]
Unfortunately, splitting up files makes all operations on them fragile. Renames, deletes, chmod are no longer atomic. If the computer crashes in the middle, you are left with a mess. Even opening a file becomes difficult (you have to open all chunks to prevent concurrent deletion AND keep track when chunks are added to the file).

Filesystems like ext4 handle the non-atomicity problem by having a journal that they replay to recover from a crash. And that's not something I want to re-implement in gocryptfs.

**Comment by BrandonIngalls** [comment]
@tolotos-rgu if your goal is to backup large files you may want to look into [borg](https://github.com/borgbackup/borg).

**Comment by tolotos-rgu** [comment]
I want to use the amazon storage as the file system for a media center. 
As amazon has this size limitations and no usable split solution can be found I stop my media-senter in the cloud project and continue using my local server.
