### ISSUE TITLE
Urgent Request For Assistance With Argon2ID Integration

### ISSUE THREAD

**Issue by Librechain** [rfjakob/gocryptfs#520]
## I'm Not Good at Headers

I've used gocryptfs for some time. It is by far the best fs encryption command line tool out there. 

However, it is a **critical mistake to omit Argon2id**. I know that Scrypt is implemented on the protocol, but Argon2id is of a higher caliber. It is recommended by the IETF and has been adopted as a standard in php versions >7.0 

It won the global PHC (password-hashing competition) amid strong contenders. You know all of this. 

## Blockchain Exposed That Argon2id is Stronger Than Scrypt 

You're familiar with Bitcoin, I'm sure. There are other cryptocurrencies. I want to reference one called, 'Litecoin'. One major difference between Litecoin & Bitcoin is that Litecoin uses 'Scrypt' rather than SHA256 as its hash algorithm of choice (*all transaction data is hashed with a nonce value by miners, with the nonce increasing incrementally until miners achieve an output that is below a given hexadecimal / binary value [can't remember which]*). 

ASICs were easily created for SHA256. No problem. Merkle-Damgard hashes are designed for speed - hence why they are the standard for sha-1 & sha-2. 

Scrypt was chosen in lieu of sha256 for Litecoin for the sake of thwarting ASIC chip manufacturers. I won't get into the reasons why - but this is relevant to this discussion because we have the same end goal here in selecting a password hashing algorithm. We are seeking one that is **not fast**, but rather 'slow' / memory-intensive in the hopes that we can remove the age-old, first on the list threat of brute force attempts (rainbow tables etc.) 

## ASICs Were Eventually Developed For Scrypt 

As well as FPGAs & of course, GPUs. These chips have been optimized by large organizations with valuations in the billions of dollars (meaning they have immeasurable and endless resource). Given Litecoin's existence, we now live in a world where those same devices that have been manifested to mine Litecoin can easily be re-directed for nefarious purposes (i.e., attempting to brute force gocryptfs passwords hashed with scrypt). 

## Litecoin Stats 

At the time of writing, there are approximately 260+ TH operations per second being executed on the protocol

![Litecoin hash rate](https://user-images.githubusercontent.com/59129716/96808655-3efbe200-13e7-11eb-9c78-a76ae4466f95.png)

Below is a conversion table, showing us how many individual hashes we're talking about here:

![Hash rate conversion table](https://user-images.githubusercontent.com/59129716/96808855-b3368580-13e7-11eb-9235-1250c617eba8.png)

## There Are Also Blockchain Protocols That Use Argon2id

To date, there are **no commercially available ASICs capable of providing a viable improvement for hashing Argon2id**. 

In fact, there are no legitimate, validated **GPU solutions for Argon2id that exist to my knowledge**. I'm not sure there are any FPGAs manufactured for Argon2id either. 

If we stop here, then Argon2id is the clear winner. 

## There is No Reason to Omit Adding Argon2id 

Perhaps this was reasonable in 2018. But now? Its a willful decision to forego something that would make gocryptfs indisputably **more secure, cryptographically sound, and elite** (i.e., using the latest and greatest in peer-reviewed, comprehensively raked-through cryptographic schemes). 

Swapping out scrypt or even adding Argon2id as an option alongside Scrypt would be a **trivial** task. Argon2id essentially uses the same syntax as 'Scrypt' as well (for the parameters that it takes in). 

There are well-maintained and commonly distributed packages for Argon2 in any langauge - hell, you could even make argon2 a requisite dependency for users downloading gocryptfs and simply integrate in with current command line options. 

## If the Maintainer is Unwilling to Consider This Clear Improvement / Enhancement Then I Humbly Ask For Directions / Guidance on What Part o the Code I Must Augment in Order to Implement This Myself 

I'll do all the heavy lifting if necessary. It won't take me (or you if you choose) any longer than 20-30 minutes, I imagine. 

This is your project & its open source though - so I'm not going to beat you over the head to do it because you don't work for me or anyone else on that. Ultimately, your maintenance of this project is a charity to the computing world. 

With that being said, I am hopeful that this does not mean that you will serve as a **barrier** for those that are willing to pursue integrating something into gocryptfs that will only improve it as a tool if they would like to. If not, then we've undermined the whole purpose and beauty of **open source** + **collaboration**. 

I don't understand the principle of security / cryptography that says 'go with less than optimum'.

**Comment by rfjakob** [comment]
Hi, I will accept a PR for this. The Go package for argon2 is https://pkg.go.dev/golang.org/x/crypto/argon2 .

You'll need to integrate the key derivation here: https://github.com/rfjakob/gocryptfs/blob/832e58cad4567aa60ce8d390802262c82c5bfba3/internal/configfile/config_file.go#L256 

Expand the config file to store the argon2 parameters:
https://github.com/rfjakob/gocryptfs/blob/832e58cad4567aa60ce8d390802262c82c5bfba3/internal/configfile/config_file.go#L41

Add a command-line parameter to enable argon2 here: https://github.com/rfjakob/gocryptfs/blob/832e58cad4567aa60ce8d390802262c82c5bfba3/cli_args.go#L126

And add a test that verifies that the command-line parameter works here:
https://github.com/rfjakob/gocryptfs/blob/master/tests/cli/cli_test.go

**Comment by Librechain** [comment]
Is there no way to integrate system calls (i.e., bash commands) that pipe some input into argon2? 

Below is a sample script that I created when in my free time while playing around w the idea of stateless password generation: 

```
#!/bin/sh

echo 'Enter Your Password'
stty -echo
read pass
salt=$(echo 'entersomesalthere')
echo $pass | argon2 $salt -id -t 3 -m 12 -p 2 -l 256 -r -v 13 | openssl dgst -shake256 >> outcome.txt
tail -c 65 outcome.txt | xclip -sel clip -rmlastnl
# set -- bleachbit shred "outcome.txt"
bleach='bleachbit -s "/home/user/outcome.txt" > "/dev/null" 2>&1'
eval "$bleach"
stty echo
exit
```

Politely asking for help here in integration if possible. 

Based on your response, it seems that this would be **really easy for you to implement**. I don't know Golang. 

I think that at least including this little command line option would be a super minor yet much appreciated add to this tool that can only make it a more secure solution. 

Perhaps I'm wrong, but from the progress of gocryptfs over the past few months & years, you seem to be someone that's not afraid to provide users with the strongest cryptographic setups out there. 

The fact that this algo won the PHC is something worthy of major consideration as well imo.

**Comment by Librechain** [comment]
> Hi, I will accept a PR for this. The Go package for argon2 is https://pkg.go.dev/golang.org/x/crypto/argon2 .
> 
> You'll need to integrate the key derivation here:
> 
> https://github.com/rfjakob/gocryptfs/blob/832e58cad4567aa60ce8d390802262c82c5bfba3/internal/configfile/config_file.go#L256
> 
> Expand the config file to store the argon2 parameters:
> 
> https://github.com/rfjakob/gocryptfs/blob/832e58cad4567aa60ce8d390802262c82c5bfba3/internal/configfile/config_file.go#L41
> 
> Add a command-line parameter to enable argon2 here:
> 
> https://github.com/rfjakob/gocryptfs/blob/832e58cad4567aa60ce8d390802262c82c5bfba3/cli_args.go#L126
> 
> And add a test that verifies that the command-line parameter works here:
> https://github.com/rfjakob/gocryptfs/blob/master/tests/cli/cli_test.go

If your stance is to masquerade with this project as though it were some sort of truly "open" source solution that protects users whilst publicly refusing to implement a **clear, palpable upgrade on what is currently available** reveals you to be a **bad actor** and a untrustworthy individual. 

So I will take your advice above (without the pull request) and simply fork this project and promote my forked branch as the **honestly developed version of gocryptfs that actually looks out for the end user instead of apathetically ignoring valid issues due to an inability to accept any criticism**. 

Thin-skinned developers are the demise of an effective project. 

My organization is designed to go to war with people like you that are holding back the entire open source community with your actions. In my opinion, this dialogue qualifies this project to be considered malware. And I will propagate as much to the general public on all mediums so that they can steer clear of **your malicious version of gocryptfs**.

**Comment by rfjakob** [comment]
Librechain, the time and energy I have to work on gocryptfs is limited. When somebody makes a sensible feature request (I think you did, Argon2 makes sense), and suggest to implement it as well (as you did: "I'll do all the heavy lifting if necessary"), then I gladly take the offer.

**Comment by rfjakob** [comment]
I will skip over your rant about gocryptfs being malware, I think these comments are off the rails.

Instead, I want to look at wehter Litecoin miners can really crack gocryptfs passwords. This answer says no:  https://security.stackexchange.com/a/53040 , but let's look at the details.

From https://security.stackexchange.com/a/53040 :
> Litecoin's scrypt parameters are fixed at N = 1024; p = 1; r = 1. (http://cryptocur.com/litecoin/)

From https://bitcoin.stackexchange.com/questions/36642/why-did-litecoin-choose-the-scrypt-factors-that-they-did :
> Litecoin uses the scrypt factors (N=1024, r=1, p=1) This means that each hashing thread takes 128kB of memory. The scrypt paper recommends r=8.

So we take that Litecoin uses N=1024, r=1, p=1. Using the scrypt memory usage formula from https://blog.filippo.io/the-scrypt-parameters/ confirms the 128kiB memory usage:

    mem = 128 x N x r = 128 x 1024 x 1 = 131072 = 128kiB

gocryptfs uses N=65536, r=8, p=1. That gives a memory usage of

    mem = 128 x N x r = 128 x 65536 x 8 = 67108864 = 64MiB

It seems unlikely that the Litecoin ASICs can deal with 512 times higher memory usage. By the way, the N value can be set from the gocryptfs command line via `scryptn=xxx`. 16 is the default which represents 2**16=65536. Increasing by 1 doubles the memory usage (you can go as high as you want).

**Comment by Librechain** [comment]
I agree with you about the 'off the rails' comment lol. Was in a passionate crusader mode. 

I really don't have that much time on my hands either, but in this very thread you explicitly broke down, step by step how to integrate this into the codebase - which  means that you essentially did all of the work necessary to add it in, stopping just short of *actually* doing it. 

And that's what I found confusing. 

### RE: Litecoin Miners 

To be clear, never suggested that Litecoin miners could "crack" Scrypt. That would be preposterous. 

Also, I think its optimistic thinking to assume that every end user's version of Script is equally as secure. 

### Final Question - Why Forego Optimization? 

While I understand your points regarding schedule, time constraints, and general desire, it is worth noting that you are still actively maintaining the project. 

I'm just a fan of consistent logic. 

If we're going to say, 'Meh, XYZ  should work even though ABC is *more secure' by consensus', then why use Scrypt vs. PBKDF2-SHA1?

**Comment by lechner** [comment]
@rfjakob You are very kind. Personally, I would not correspond any further with this individual.

I can't speak for everyone at Debian, but we appreciate your work very much. `gocryptfs` secures many of my personal files. I recommend to anyone who asks. Thank you!

Kind regards
Felix Lechner

**Comment by Librechain** [comment]
## Closing This Issue

Hey @lechner , I'm going to open up another issue here because one thing that I failed to mention prior was the fact that Scrypt is vulnerable to timing attacks, which Argon2id mitigates almost entirely (on top of the fact that it provides options for users to either implement it in its 'i' or 'd' iteration, either of which can make the algorithm more memory-intensive or more resistant to timing attacks). 

A subsequent issue (#2) will be opened re: the instructions that were given above for implementation of Argon2id. 

I originally had proposed this as an additional option for users to choose from, but in lieu of well-established research attesting to the **feasibility** of executing this attack - I am going to wholly recommend for its replacement. 

Additionally, since the use of Scrypt within the context of Gocryptfs is to KDF the password that effectively allows one to mount a Gocryptfs container - which means that this password is responsible for the **encryption & decryption of the container's contents**. 

Thus, if this password can be compromised (and it can - with ease; which I will outline in a subsequent issue), then the entirety of Gocryptfs is at risk here. 

The presence of gocryptfs (as well as the mount location) on a user's system is also information that can be easily obtained from one's bash history since the initiation **and preferred parameters for every aspect of the container mount** are either solicited or stated explicitly in one command (for a non-interactive mount)

I am also going to close this
