### ISSUE TITLE
static build needs fuse?

### ISSUE THREAD

**Issue by misterhsp** [rfjakob/gocryptfs#521]
The static build of gocryptfs still needs fuse in the system or is that also included?

Thanks...

**Comment by rfjakob** [comment]
Needs fusermount installed, yes!

**Comment by rfjakob** [comment]
Just checked, README has this info https://github.com/rfjakob/gocryptfs/blob/master/README.md#installation :
> If you use the standalone binary, make sure you install the fuse package from your distributions package repository before running gocryptfs.

**Comment by misterhsp** [comment]
Thanks for the info.

...

**Comment by misterhsp** [comment]
I still have a small question. Does gocryptfs need fuse2 or fuse3?

Thanks

**Comment by rfjakob** [comment]
Should work with both, if in doubt, choose fuse3. Fuse2 is deprecated. Regards
