### ISSUE TITLE
More testing of -sharedstorage

### ISSUE THREAD

**Issue by impredicative** [rfjakob/gocryptfs#525]
The [`-sharedstorage` section in the man page](https://github.com/rfjakob/gocryptfs/blob/master/Documentation/MANPAGE.md#-sharedstorage) says:

> Running gocryptfs on shared storage does not receive as much testing as the usual (exclusive) use-case. Please test your workload in advance and report any problems you may hit.

I am heavily dependent on this option. To ensure it doesn't break, can it receive more testing? I don't have any bug to report in this regard. I just think this use case is important.

**Comment by jpluscplusm** [comment]
@impredicative Heya 👋 

Just a thought, as I do a drive-by of the issues for gocryptfs: you might find folks more able to help with this if they had more specifics! At the moment your issue could mean a number of things, and adding "all the tests" isn't a very achievable single issue 😆 

What's your:

- OS
- storage protocol & version
- rough latency between you and the storage provider
- "kind" of file access (e.g. live editing of source code in a text editor? a few, large files, rsync'd? many small files? lots of symlinks? etc etc)

Also:

- who or what is the storage shared with?
- are you expecting/mitigating other readers of the same files? other writers?
- anything else specific to your usage?

All the best!

**Comment by impredicative** [comment]
Ubuntu Linux

ext4

NVMe on laptop

Mixed sizes up to 100 MB and mixed access patterns

**Comment by jpluscplusm** [comment]
👍 

Just for clarity, what's the "shared" element there?

**Comment by impredicative** [comment]
The crypt dir is stored in a git repo in git commits.
