### ISSUE TITLE
Notification on autounmount (-idle option)

### ISSUE THREAD

**Issue by petrarca-arezzo** [rfjakob/gocryptfs#526]
I like the idea of the gocryptfs folder being unmounted after some idle time (since it's sometimes easy to forgot about the mounted filesystem). Question: Is there an easy way of being notified about the unmount (so one could do a short pop-up with zenity, or remove the empty mount folder)? I had a look at stat but did't get far really...

**Comment by rfjakob** [comment]
I suggest something like this:

    # Wait until mountpoint disappears
    while grep /tmp/my.mountpoint /proc/self/mounts ; do sleep 1 ; done
    # Notify user
    echo "UNMOUNTED!!!"
    # zenity etc....
