### ISSUE TITLE
macOS version of gocryptfs deprecated?

### ISSUE THREAD

**Issue by Tekl** [rfjakob/gocryptfs#527]
When I install gocryptfs with homebrew I'll get this message:

`gocryptfs has been deprecated because it requires FUSE!`

**Comment by llucps** [comment]
Yes me too. Is there any action that could be taken to amend this? Is it complicated?

I've been using gocryptfs for quite a while and it has always worked perfectly, I would like to continue using it for long time.

Thanks!

**Comment by rfjakob** [comment]
I guess this has something to do with go-fuse (the FUSE library that gocryptfs uses) not supporting macfuse 4.0.0 ( https://github.com/hanwen/go-fuse/issues/379 )

**Comment by rfjakob** [comment]
Oh, macfuse 4.x is no longer open source: https://github.com/Homebrew/homebrew-core/pull/64491

That's how the macfuse 4.x source code looks like now: https://github.com/osxfuse/osxfuse/tree/macfuse-4.0.3

Acc. to https://github.com/Homebrew/homebrew-core/pull/64491 gocryptfs will still be available to install but may eventually be removed. If and when this happens I could start releasing macos binaries like I do for Linux (example: https://github.com/rfjakob/gocryptfs/releases/tag/v1.8.0 )

**Comment by lakemike** [comment]
Is there any update on how to install on macOS?

**Comment by rfjakob** [comment]
Plz check https://github.com/rfjakob/gocryptfs/issues/556

You have to install macfuse and compile gocryptfs, but it works. In the future i may provide a macos binary for download
