### ISSUE TITLE
Allow limiting file size in crypt dir

### ISSUE THREAD

**Issue by impredicative** [rfjakob/gocryptfs#528]
It will help me if the max file size in the crypt dir can be limited to a user defined value during `-init`. Larger plain files will then have to be split by gocryptfs into smaller crypt files, similar to what `tar` does. Some remotes like GitHub limit the max allowable file size to ~100M, so it'll help if I can configure it. This is a low-priority feature request.

**Comment by rfjakob** [comment]
Hi, thanks for the feedback, but splitting files makes renames non-atomic, and causes a number of similar issues. Having such non-atomic operations in a highly concurrent system like gocryptfs is a big risk. No can do, sorry!

**Comment by impredicative** [comment]
I acknowledge that atomicity is vital, but for the sake of understanding, how does [cryfs](https://github.com/cryfs/cryfs/) do it?

Its docs [say](https://www.cryfs.org/howitworks/):

> CryFS splits the content of a file

**Comment by rfjakob** [comment]
By having many problems :)

Example: https://github.com/cryfs/cryfs/issues/155
