### ISSUE TITLE
Is there any way to make all folders use the same gocryptfs.diriv ?

### ISSUE THREAD

**Issue by karibertils** [rfjakob/gocryptfs#529]
I want to keep encrypted folders but get rid of all the small files. Is this possible ?

**Comment by impredicative** [comment]
Why would you want to do this?

**Comment by karibertils** [comment]
Because I have alot of folders and am using cloud drive with file limit. And I think it's also reducing performance quite a bit when listing folders since accessing small files can be quite slow on cloud drive.

**Comment by impredicative** [comment]
This seems a bit hard to believe. Do you have a means to sync Cloud Drive files from and to your computer?

**Comment by karibertils** [comment]
Yes I am using rclone. I use it both for syncing files and mounting. I synced the files from gocrypt reverse mode and then mounted with rclone + gocrypt decrypt.

gocrypt works fast locally. But it's running order of magnitude slower than the rclone internal encryption when working with many folders.

Anyway feel free to close this, I will just use the rclone encryption.

**Comment by impredicative** [comment]
Does rclone work in reverse mode?

For what it's worth, have you tried gocryptfs in regular mode?

**Comment by karibertils** [comment]
I don't believe you can mount in reverse mode using rclone. But you can do normal sync using rclone and the cleartext files arrive encrypted on the cloud drive.

Here is a simplified scenario I run into with the file limit.

Say I have 500 thousand project folders. Each folder with 100's of small files and one larger result file.

With google drive each drive has 750K file limit, It's far from possible to upload all the files to a single drive. But it would be possible to upload all the results files (500K files each in a seperate folder).

So if I sync with rclone filtering on large files. It will need to create 500K folders and 500K small files for those folders, the drive will already contain 500K files before even starting uploading the 500K larger result files... It is possible to spread stuff between many drives each with 750K file limit, so possible to work around that limitation.

Using either gocrypt reverse + rclone sync or rclone mount + gocrypt standard for uploading. The uploading spends alot of time sending small files utilizing almost no bandwidth during those, taking maybe 2-3 seconds for each file. Increasing the rclone threads was only helpful to a certain degree causing google drive to start throttling API requests with too many threads. Using rclone internal encryption it just uploads the larger files, maxing out the available bandwidth straight away with low threads and remaining there for the entire upload time.

Using gocrypt standard + rclone mount. It takese longer time listing each folder contents compared to rclone internal encryption mount. On second try listing folder contents with rclone mount it's cached and works immediately. With gocrypt it remains slow on listing folder contents every time.

FWIW, this is what i noticed with gocryptfs. I will simply use rclone alone as it works better for my use case.
