### ISSUE TITLE
additional options (UID, GID, UMASK)

### ISSUE THREAD

**Issue by tolotos-rgu** [rfjakob/gocryptfs#53]
How can I use this options on mount: -ko uid=$USER_ID,gid=$GROUP_ID,umask=$UMASK_PROP?
All files copied into plain will chown $USER_ID:$GROUP_ID and chmod using $UMASK_PROP in plain and cipher.

**Comment by rfjakob** [comment]
Hmm, none of these options is understood by the kernel.

You have the uid thing by starting gocryptfs as the user you want the files to end up with:
``` 
sudo -u USER gocryptfs -allow_other a b
```
Umask is a client-side thing, the files will end up with the umask the process has that created it.

**Comment by charles-dyfis-net** [comment]
@rfjakob, ...if I wanted to implement uid/gid options to allow gocryptfs with allow_other to be used in situations where the user to be permitted to access a given tree and the user with OS-level write permissions to the backing store differ, would such a patch have a prayer of a chance of being merged? (For context, see https://serverfault.com/questions/852324/configuring-nfsv4-anonymous-ownership-mapping-idmapd-conf-per-subtree-or-mount -- I have a single mount from a NFS server, for which all files appear to be owned by `nfsnobody`, and want to expose different subtrees to different applications with different ownership).
