### ISSUE TITLE
Using XChaCha20-Poly1305 on a Raspberry Pi 4b

### ISSUE THREAD

**Issue by mr0xf00** [rfjakob/gocryptfs#531]
Hi, 

After running ```gocryptfs -speed``` on a Raspberry Pi 4b running ubuntu 20.10 64bit I get the following results :
```bash
gocryptfs 1.8.0; go-fuse 2.0.3; 2020-11-27 go1.15.5 linux/arm64
AES-GCM-256-OpenSSL 	  21.44 MB/s	(selected in auto mode)
AES-GCM-256-Go      	  21.06 MB/s	
AES-SIV-512-Go      	  17.70 MB/s	
XChaCha20-Poly1305-Go	 122.86 MB/s	
```

But it seems that AES-GCM-256-OpenSSL is the one actually being used  : 
```
test@rpi:~/enc$ mkdir base mount
test@rpi:~/enc$ gocryptfs -init base
test@rpi:~/enc$ gocryptfs base mount
test@rpi:~/enc$ dd if=/dev/zero of=mount/test.bin bs=500K count=10000 status=progress
247296000 bytes (247 MB, 236 MiB) copied, 10 s, 24.7 MB/s^C
```
Is there any way to have gocryptfs use XChaCha20-Poly1305-Go in auto mode ? An option for manually selecting it while mounting would also be appreciated.

Thanks !

**Comment by rfjakob** [comment]
Thanks for the benchmark results, I have added it to https://github.com/rfjakob/gocryptfs/wiki/CPU-Benchmarks#arm-devices ! gocryptfs currently does not support using XChaCha20-Poly1305-Go for encryption, but may in the future, please see https://github.com/rfjakob/gocryptfs/issues/452 . It shows up in `gocryptfs -speed` to see if it *makes sense* to support it - looks like it does!
