### ISSUE TITLE
"invalid entry, bad message" when trying to open a folder

### ISSUE THREAD

**Issue by platinum55** [rfjakob/gocryptfs#538]
Hello,

suddenly one folder is "empty", so I looked in the syslog and found this:

```
gocryptfs[589]: OpenDir "PlxWeQirjOfYrn4X7Rc18g": invalid entry "H822nx6Bqhvzo8ifJlTUog": bad message
gocryptfs[589]: OpenDir "PlxWeQirjOfYrn4X7Rc18g": invalid entry "glal5MGJd7KBQUW-WxMeng": bad message
```

I tried to copy a subfolder out of those to the main folder which seems unreadable, but the same log message appeared.

Any idea how to recover the data? Backend is Gdrive, so I think the data itself is not corrupted.

Using this version:
gocryptfs v1.8.0 without_openssl; go-fuse v1.0.1-0.20190319092520-161a16484456; 2020-05-09 go1.14.2 linux/amd64

**Comment by rfjakob** [comment]
This means the names
* `H822nx6Bqhvzo8ifJlTUog`
* `glal5MGJd7KBQUW-WxMeng`

cannot be decrypted (garbage data was detected after decryption).

Did you move them to a different folder? The encrypted names are bound to the `gocryptfs.diriv` file in their folder, so moving them somewhere else would cause this.

You can recover the file contents by creating new empty files in the decrypted view, maybe "file1" and "file2". This will give you two valid names in the encrypted view. Then delete "file1" and "file2" and rename your two invalid names to the two valid names.

**Comment by platinum55** [comment]
thanks for this hint, I found out that the two subfolders/diriv was broken - thanks god the subfolders they contain are OK - I mounted them with masterkey and all filenames are readable :)
