### ISSUE TITLE
aessiv flag not implied consistently (mounting reverse-encrypted files with masterkey)

### ISSUE THREAD

**Issue by danielb42** [rfjakob/gocryptfs#541]
Hi, I have an offsite backup that was created by rsyncing the contents of a reverse-mode-mountpoint to a remote location. That backup can be accessed (mounted) fine as long as the password is supplied. Mounting that backup with the masterkey however results in an unusable mount. The folder structures are fine but accessing any file or link results in I/O errors resp message authentication errors appear in syslog.

I fiddled around and figured out that I need to specify the `-aessiv` flag when mounting the backup with masterkey. With that flag being present, the mount is usable as expected.

So for a quick reality check - obviously "password-mode" can recognize that the encrypted data was "created" in reverse-mode and assumes `-aessiv` implicitly when mounting. That doesn't fly with "masterkey-mode" as `-aessiv` has to be specified explicitly to get a usable mount.

I can't find anything in the docs that tells me about this inconsistency between password- and masterkey-usage. I feel quite lucky to have connected the dots here myself, but I guess any other day I'd just have trashed that backup as it is supposedly corrupt.

Can masterkey-mode be taught to assume `-aessiv` when needed?

Thanks!

// I'm using gocryptfs 1.8.0

**Comment by danielb42** [comment]
As `gocryptfs -init -reverse` creates a `.gocryptfs.reverse.conf` that indeed has `AESSIV` listed under FeatureFlags, I think this really is just a bug with `-masterkey` not honoring the presence of that FeatureFlag.

**Comment by rfjakob** [comment]
Thanks for the report, but this behavoir is expected and documented here: https://github.com/rfjakob/gocryptfs/blob/master/Documentation/MANPAGE.md

**Comment by rfjakob** [comment]
https://github.com/rfjakob/gocryptfs/blob/master/Documentation/MANPAGE.md#-masterkey-string

**Comment by danielb42** [comment]
Ah, thanks! I still think it wouldn't hurt to mention this on the CLI when using `-masterkey`, as I won't be the only one to miss that section and assume corrupted data.. however I'm glad it's not a bug.

I'm closing this issue, and thank you very much for the marvelous tool!
