### ISSUE TITLE
Qu: Performance comparison cryptographic file systems

### ISSUE THREAD

**Issue by saxofooon** [rfjakob/gocryptfs#545]
Hi, in your performance comparison the container based systems like Veracrypt are a lot faster. What is the reason for that? How is the performance when only one file (or a few) are involved in the encryption process?

**Comment by rfjakob** [comment]
I believe you mean https://github.com/rfjakob/gocryptfs/wiki/Performance-Comparison (as https://nuetzlich.net/gocryptfs/comparison/ does not have truecrypt).

Fundamentally, container-type and full-disk-encryption systems have one layer less than file-based systems like gocryptfs, so they are supposed be faster. Should be the same with one or a few file (even though I don't know how much faster).
