### ISSUE TITLE
Failed to unmarshal config file

### ISSUE THREAD

**Issue by savchenko** [rfjakob/gocryptfs#546]
When trying to execute `gocryptfs-xray`, it fails no matter which file is targeted:
```bash
$ gocryptfs-xray -dumpmasterkey gocrypt/Ic3au7fQ5qYIkaRfio2yZA/utNHDQdMCla2bbvTdkjUb/4OVU6nMEM2F9KN61dhwMFg 
Password: 
Failed to unmarshal config file
invalid character '\x00' looking for beginning of value
$
```
Filesystem: EXT4
gocryptfs: v1.8.0; go-fuse 2.0.3; 2021-01-20 go1.15.6 linux/amd64
libfuse2: v2.9.9
kernel: v5.10.12
`-info` output:
```
Creator:      cppcryptfs v1.4.3.5
FeatureFlags: EMENames LongNames DirIV HKDF Raw64 GCMIV128
EncryptedKey: 64B
ScryptObject: Salt=32B N=65536 R=8 P=1 KeyLen=32
```
Is this some sort of expected incompatibility between implementation of [cppcryptfs](https://github.com/bailey27/cppcryptfs) and the native one?

**Comment by rfjakob** [comment]
For -dumpmasterkey, you have to target gocryptfs.conf

**Comment by savchenko** [comment]
> For -dumpmasterkey, you have to target gocryptfs.conf

Dang, I was clearly using it wrong! Sorry. I was trying to recover human-readable name of the corrupted file and was under the false impression `gocryptfs-xray` is the right tool for it.

Ended-up following your guide from https://github.com/rfjakob/gocryptfs/issues/138#issuecomment-323598744 which doesn't restore the name, but allows to get back some content enough for identification.

As an afterthought, wouldn't it be neat to have a command that allows to derive plaintext name from an encrypted one? Given that user knows password/master-key and `*.diriv` is intact.

**Comment by rfjakob** [comment]
gocryptfs-xray can do this by querying a gocryptfs filesystem mounted with `gocryptfs -ctlsock`. See 3rd example here:

https://github.com/rfjakob/gocryptfs/blob/master/Documentation/MANPAGE-XRAY.md#examples

Feel free to report back if this does not work for you
