### ISSUE TITLE
Odd problems with permission on ARM7

### ISSUE THREAD

**Issue by egorenar** [rfjakob/gocryptfs#547]
I'm using `master` version of gocryptfs on an ARM7 router and facing strange issue with permissions.
If i mount the filesystem with option `-allow_other` then everything works fine but omitting this option results in this:
```
$ gocryptfs -noprealloc cipher plain
Password:
Decrypting master key
fs.Mount failed: permission denied

$ ls -l
drwxr-xr-x 1 egorenar egorenar 102 Feb 20 20:46 cipher
d????????? ? ?        ?          ?            ? plain

$ ls -l plain
ls: cannot access 'plain': Permission denied
```
And this is the result with `-allow_other`:
```
$ gocryptfs -noprealloc -allow_other cipher plain
Password:
Decrypting master key
The option "-allow_other" is set. Make sure the file permissions protect your data from unwanted access.
Filesystem mounted and ready.

$ ls -l
total 0
drwxr-xr-x 1 egorenar egorenar 102 Feb 20 20:46 cipher
drwxr-xr-x 1 egorenar egorenar 102 Feb 20 20:46 plain
```

Any idea what could go wrong ? Maybe my kernel is missing some features ??? Currently my BTRFS kernel module has no ACL support.

I'm having the same issue with 1.8 release although mount succeeds w/o  `-allow_other` but still with the same permission problem :(

Compiled for ARM with:
`GOARM=7 GOOS=linux GOARCH=arm go build -tags without_openssl`

Thanks
Regards

**Comment by rfjakob** [comment]
Looks like gocryptfs somehow runs as a different user...? Maybe it is setuid-root and runs as root?

Can you check "ps auxwww" for which user the gocryptfs process runs as? It it does run as root, "sudo ls" would work.
