### ISSUE TITLE
Derive plaintext filename from encrypted one

### ISSUE THREAD

**Issue by savchenko** [rfjakob/gocryptfs#548]
Sometimes (oftentimes if your synchronisation creates conflicts) it is useful to quickly find-out a plain-text filename to understand what file is affected.

Currently I use a workaround with creating a new folder where decrypted cipherdir is mounted, `touch`'ing a new file and then copying content of the conflict into it. This allows to see where conflict has occurred, but tedious to do every time.

I would be great to have something like `gocryptfs-xray -fname FILENAME`, enter password and see `Filename:` in addition to `Header:` and `Block 0:`.

**Comment by rfjakob** [comment]
gocryptfs-xray can do this by querying a gocryptfs filesystem mounted with `gocryptfs -ctlsock`. See 3rd example here:

https://github.com/rfjakob/gocryptfs/blob/master/Documentation/MANPAGE-XRAY.md#examples

Feel free to report back if this does not work for you
