### ISSUE TITLE
Related: gocryptkeeper

### ISSUE THREAD

**Issue by xxxserxxx** [rfjakob/gocryptfs#551]
I threw together another UI for gocryptfs: [gocryptkeeper](https://hg.sr.ht/~ser/gocryptkeeper). It's a GTK tray app that's basically a copy of [cryptkeeper](https://github.com/tomm/cryptkeeper/).  It's more focused than sirikali, and uses GTK rather than Qt, and is written in Go; but mainly I wrote it because I prefer the cryptkeeper UI.

This is FYI; thanks for gocryptfs.

**Comment by rfjakob** [comment]
Would you like to add it to the "User Interface" row in https://nuetzlich.net/gocryptfs/comparison/ ?

----> https://github.com/rfjakob/gocryptfs-website/edit/master/docs/comparison.md

**Comment by xxxserxxx** [comment]
Yup.
