### ISSUE TITLE
Feature request: specify filename length limits more precisely

### ISSUE THREAD

**Issue by fortran77** [rfjakob/gocryptfs#552]
All over the Internet I am seeing filename length limits discussed. In almost every case, writers are not specifying which lengths they are referring to. I also see error messages that don't specify which length was exceeded.

Given a file called

`/aaa/bbb/ccc/ffff.txt`

there are three different possible length limits.

- Length limit of `"/aaa/bbb/ccc/ffff.txt"` is the length limit of the entire pathname.
- Length limit of `"aaa"` or `"bbb"` etc. is the length limit of each directory ccomponent.
- Length limit of `"ffff.txt"` is the length limit of the base filename.

These limits might be all different for a particular operating system or filesystem or software package, so should be specified separately. Too often I see a single number specified with no clarification as to which of these limits is being referred to.

I highly recommend separately specifying each of these limits in documentation and in tables comparing encrypted filesystems.

**Comment by rfjakob** [comment]
FYI the https://github.com/rfjakob/gocryptfs/blob/master/contrib/maxlen.bash utility now also detects the max path length.

Example output:
```
$ ./contrib/maxlen.bash /tmp
Testing /tmp
  Maximum filename length: 255
  Maximum dirname length:  255
  Maximum path length with   1 chars per subdir: 4095
  Maximum path length with  10 chars per subdir: 4095
  Maximum path length with 100 chars per subdir: 4095
  Maximum path length with 255 chars per subdir: 4095
```
