### ISSUE TITLE
Do install instructions need updating?

### ISSUE THREAD

**Issue by dsedivec** [rfjakob/gocryptfs#553]
Hi!  I build gocryptfs from source on macOS, and the instructions don't seem to work for me: If I run `go get -d github.com/rfjakob/gocryptfs`, I don't have a `src` directory appear under `GOPATH`, only a `pkg` directory (and don't think that's meant to be equivalent to `src`).  This is on macOS 11 (AKA Big Sur) with Go 1.16.2 installed from MacPorts (instead of Homebrew).

I don't understand much of anything about Go packaging, but https://blog.golang.org/go116-module-changes led me to try doing

    GO111MODULE=auto go get -d GitHub.com/rfjakob/gocryptfs

and that did create `GOPATH/src/github.com/rfjakob/gocryptfs`.

Do the instructions from source need to be updated?

Thanks for gocryptfs!

**Comment by rfjakob** [comment]
Good catch. Thanks for the report!
