### ISSUE TITLE
Question: Does it help to provide a password longer than the master-key?

### ISSUE THREAD

**Issue by pico-prob** [rfjakob/gocryptfs#554]
Hi,
in my naive understanding is the master-key, the key which actually encrypts the data. The key I provide encrypts in turn the mk.
In this case it would _not_ make sense to choose a longer password than the mk.

However if this is true, I'd assume you choose a much longer mk..

So.. should I choose a longer password than the mk? And if yes, what did I miss?

BTW: Great tool.. Thank you!

**Comment by rfjakob** [comment]
Hi, your understanding is right. It does not make sense to have a password that is "longer" (has more bits of entropy) than the master key. The master key has 256 bits for use in AES-256, which is the strongest mode of AES.

I think 64 bits are good enough for the password, and more than 128 bits do not make sense. See https://github.com/rfjakob/gocryptfs/wiki/Password-Strength for details. HTH!
