### ISSUE TITLE
Feature Request: File Redundancy/Parity

### ISSUE THREAD

**Issue by Vesnyx** [rfjakob/gocryptfs#555]
I believe that implementing an extra-layer of file redundancy to help preserve the file integrity would be very valuable in the space of encrypted files. PAR is a direct data redundancy and WinRAR allows you to add Reed-Solomon error correction to its volumes. However, both of them require the user to manually apply the error redundancy before encryption.

PicoCrypt (https://github.com/HACKERALERT/Picocrypt) was recently released an incorporates the error correction alongside the file encryption. To my understanding, this may add an extra bit of time for encryption, but it does allow for additional file protection and somewhat allows users to avoid having to use an external program for file parity. 

I propose adding a new encryption/decryption method that takes advantage of error correction.

**Comment by rfjakob** [comment]
Hi, thanks for the idea! But sorry no, this would make gocryptfs too complicated.

**Comment by Vesnyx** [comment]
Completely understandable. If I wanted to add this to a fork do you have any advice about where I could start with the implementation?

I was thinking about trying it somewhere in https://github.com/rfjakob/gocryptfs/blob/master/internal/cryptocore/cryptocore.go or https://github.com/rfjakob/gocryptfs/blob/master/internal/contentenc/content.go

**Comment by rfjakob** [comment]
That would be contentenc. You could maybe put it in doEncryptBlock().
