### ISSUE TITLE
Include the --dumpmasterkey option into gocryptfs instead of gocryptfs-xray

### ISSUE THREAD

**Issue by yahesh** [rfjakob/gocryptfs#559]
After years of using `--quiet` to not print the masterkey to the console I've learned that it is only printed once during the `--init` step for quite some time now. I've also learned that you cannot retrieve the masterkey of an existing repository without the additional tool `gocryptfs-xray` tool that is not provided as a pre-compiled binary through GitHub. In my opinion it is a bit problematic that an information like the masterkey that is crucial for a worst-case recovery is not available through the core application.

I would therefore propose to include the `--dumpmasterkey` option directly in the `gocryptfs` application so that it is readily available no matter which distribution channel of gocryptfs is used. Would this be possible?

**Comment by rfjakob** [comment]
The gocryptfs v2.0 final release and future releases will also include gocryptfs-xray in the tarball. You can fetch a pre-release now from: https://github.com/rfjakob/gocryptfs/issues/558#issuecomment-808744111

Having --dumpmasterkey in the main binary is not a bad idea, maybe I will add it some day, but for now please use gocryptfs-xray.
