### ISSUE TITLE
How can I map some encrypted paths to decrypted paths?

### ISSUE THREAD

**Issue by impredicative** [rfjakob/gocryptfs#563]
I have a **subset** of encrypted file and directory paths, for example these two:

```
## master...origin/master
Bpg-8tNbahNFL3upLJMf3A/rDEIUAFCs1sBu__HGn256A/mVcRaDwHVQO24dSH_NaYKQ/FR2ekFkyS6JcALPtx-jJlQ
Bpg-8tNbahNFL3upLJMf3A/rDEIUAFCs1sBu__HGn256A/mVcRaDwHVQO24dSH_NaYKQ/LRBND8xSLNfTpehv_2wANw/CKPEURURiyHizgnRbyVYYA/
```

I want to know which decrypted paths these correspond to. Can gocryptfs perhaps provide a command to allow me do this 1:1 mapping? I assume this will require a mounted state which is fine. Ideally this gocryptfs command should accept the encrypted path list over stdin, and output the corresponding decrypted path list on stdout in the same order.

**Comment by rfjakob** [comment]
yes you can use `gocryptfs-xray -decrypt-paths`, see https://github.com/rfjakob/gocryptfs/blob/master/Documentation/MANPAGE-XRAY.md#examples

**Comment by impredicative** [comment]
Thank you. Is it possible to provide this functionality in the gocrypfs binary itself? It's easier to install and manage one binary rather than two.
