### ISSUE TITLE
Feature request: allow some control on the encrypted file name

### ISSUE THREAD

**Issue by Freeedim** [rfjakob/gocryptfs#567]
Hi there!

Thanks for gocryptfs which I have been happily using for quite a while now.

I use gocryptfs with cloud clients. I make great use of cloud clients' feature allowing to ignore files with names matching a certain pattern (whether regex or wild card-based).

I would love to extend that behaviour to my files that are encrypted with gocryptfs and have encrypted names too.

For example, with Office temporary files starting with ~$, I would love to have a gocryptfs option allowing me to spot their encrypted counterparts and tell my cloud clients to ignore them. I can see several ways of presenting this to the user, either:
- a simple exclusion scheme like the one existing for reverse mode, where files having a name matching the provided pattern would simply be excluded from file name encryption (when file name encryption is enabled, of course) and keep their plain name in the encrypted folder;
- an option like `-preserved-name-prefix 'PREFIX'` where any file with a plain name starting with `PREFIX` would have it prepended in plain text to the otherwise-encrypted name (maybe a `-preserved-name-suffix 'SUFFIX'` would be useful to some people, while we are at it);
- a more sophisticated option allowing to map plain text name patterns to output patterns added to encrypted names (but I wouldn't be able to figure out how that works and it exceeds my needs).

Thanks for your attention and great work!

**Comment by rfjakob** [comment]
I'm afraid this will lead to way too many corner-cases in the implementation, and it seems pretty difficult to configure correctly.

Can't you have a `tmp` directory in your folder, find out what its encrytped name is, and ignore this?

**Comment by Freeedim** [comment]
I have many folders with many sub folders deployed on many users' machines. And Excel or Word will put temp files starting with $~ right next to the opened file. I don't know if there is a setting in MS Office for temp files path, but even if so, I won't be able to make sure all of my users will set it correctly.

Anyway, thanks for having considered the suggestion
