### ISSUE TITLE
feature request : option to force passing masterkey through non terminal stdout for integration 

### ISSUE THREAD

**Issue by GaelC92** [rfjakob/gocryptfs#573]
Using mac automator to ease the creation of an encrypted folder from the finder, the output of the masterkey is blocked, to avoid finding it later in a log file. 

However it could be allowed as an option, even with a warning, since not having the masterkey is another kind of risk.

**Comment by rfjakob** [comment]
You can use
```
  gocryptfs-xray -dumpmasterkey myfs/gocryptfs.conf
```

**Comment by GaelC92** [comment]
This could be a workaround, but it would require one more user validation for the same outcome, and a change in the brew formula since it does not install the xray binary as far as I can tell.
