### ISSUE TITLE
Build failing - pkg-config: exec: "pkg-config": executable file not found in $PATH

### ISSUE THREAD

**Issue by ar-daniel** [rfjakob/gocryptfs#575]
__Description__
Downloaded the source package from release section, extracted and build.
Build throws output as pkg-config: exec: "pkg-config": executable file not found in $PATH
Please refer build output below and suggest solution. Thanks in advance.

__Output__
on $ sudo ./build.bash
```
go: downloading github.com/hanwen/go-fuse v1.0.0
go: downloading github.com/hanwen/go-fuse/v2 v2.1.1-0.20210508151621-62c5aa1919a7
go: downloading golang.org/x/sys v0.0.0-20200501145240-bc7a7d42d5c3
go: downloading golang.org/x/crypto v0.0.0-20200429183012-4b2356b1ed79
go: downloading github.com/rfjakob/eme v1.1.1
go: downloading github.com/sabhiram/go-gitignore v0.0.0-20180611051255-d3107576ba94
go: downloading github.com/jacobsa/crypto v0.0.0-20190317225127-9f44e2d11115
# pkg-config --cflags  -- libcrypto
pkg-config: exec: "pkg-config": executable file not found in $PATH
```
__Version & system info__

gocryptfs_v2.0.1_src.tar.gz
https://github.com/rfjakob/gocryptfs/releases/download/v2.0.1/gocryptfs_v2.0.1_src-deps.tar.gz

System 
Ubuntu server 20.04 LTS
Golang (installed via snap)
go version go1.16.4 linux/amd64
openssl (installed from source)
OpenSSL 1.1.1k  25 Mar 2021

Dependency - libssl  installed
...
Setting up libssl1.1:amd64 (1.1.1f-1ubuntu2.4) ...
Setting up libssl-dev:amd64 (1.1.1f-1ubuntu2.4) ...
...

**Comment by dhammel** [comment]
Do you have pkg-config installed? The error says that it wasnt found in your path, so install it. On debian/ubuntu should be in main apt repo (sudo apt install pkg-config)

Also, may I ask why your running the build.bash script with sudo? That may be problematic, as the built binaries for example will have root rights rather than current user permissions.

**Comment by dhammel** [comment]
It seems like pkg-config wasn't found. Try installing it via sudo apt install pkg-config

May want to avoid the use of sudo when running build.bash script, as to avoid the built binaries aquiring root permissions as not needed.

**Comment by rfjakob** [comment]
Looks like i missed pkg-config in the instructions at

https://github.com/rfjakob/gocryptfs#compile

**Comment by ar-daniel** [comment]
Thank you for the revert. I had used the pre-built binary for now and it worked fine. I'll try building from source next time.
