### ISSUE TITLE
autohide mountpoint when using it with syncthing

### ISSUE THREAD

**Issue by BigStar0916** [rfjakob/gocryptfs#576]
the v1.8 gocryptfs ALWAYS autohide mountpoint when using it with syncthing in openwrt system.after autohide the mount point, i need run fusermount -u /mnt/...  then run gocryptfs -allow_other /mnt/... again

**Comment by rfjakob** [comment]
Ok, I think I understand now. You say that gocryptfs gets unmounted by itself?

What do you get in the system logs in this case?
