### ISSUE TITLE
fsck: unPad16 error: Padding too long

### ISSUE THREAD

**Issue by Ranczo** [rfjakob/gocryptfs#577]
Hello,

it looks like some of my files got corrupted while using gocryptfs 1.8.0.
I got errors like: `fsck: corrupt entry in dir "index": "JwWf-ZpKlJ0gKlDuDt2TUi3iTiesFADTpk2NsEJge2k"`

Now I updated to gocryptfs version 2.0.1 and ran fsck again, it gives me the following:
```Reading Password from stdin
Decrypting master key
DecryptName "JwWf-ZpKlJ0gKlDuDt2TUi3iTiesFADTpk2NsEJge2k": unPad16 error: Padding too long, padLen=21 > 16
OpenDir "giQvuuhJAtaAOQDX-bMmKw": invalid entry "JwWf-ZpKlJ0gKlDuDt2TUi3iTiesFADTpk2NsEJge2k": bad message
DecryptName "SqmdrhIGbfMZq2-7m9oME1zaMVpxg6kbCyj-H7k1UNuhcOurj0e5iEuME1K-f_sl": unPad16 error: Padding too long, padLen=219 > 16
OpenDir "giQvuuhJAtaAOQDX-bMmKw": invalid entry "SqmdrhIGbfMZq2-7m9oME1zaMVpxg6kbCyj-H7k1UNuhcOurj0e5iEuME1K-f_sl": bad message
fsck: corrupt entry in dir "index": "JwWf-ZpKlJ0gKlDuDt2TUi3iTiesFADTpk2NsEJge2k"
fsck: corrupt entry in dir "index": "SqmdrhIGbfMZq2-7m9oME1zaMVpxg6kbCyj-H7k1UNuhcOurj0e5iEuME1K-f_sl"
fsck summary: 2 corrupt files, 0 files skipped
```

Is there any way to fix this?

**Comment by rfjakob** [comment]
These two file names decrypt to garbage. Would be interesting how this happened. Do you use some kind of two-way syncing?

**Comment by rfjakob** [comment]
You can recover the content of these two files manually, process is described here: https://github.com/rfjakob/gocryptfs/issues/538#issuecomment-755257433

**Comment by Ranczo** [comment]
No, I'm not using two-way sync.

It's inside a Docker container to encrypt content in a local volume (host directory).
I suppose the container might have been killed while something was being written to the disk.
Could that have caused the issue?

Also the app in the container might have been accessing the unencrypted view at the same time, moving files or directories.

The two undecryptable names belong to directories by the way, if that makes any difference.

Thanks for the info how to rescue the file contents!
However, I ended up deleting the directories, since it luckily was just some index data which got already recreated automatically.

**Comment by rfjakob** [comment]
> I suppose the container might have been killed while something was being written to the disk.
> Could that have caused the issue?

No, killing gocryptfs at any time should not cause fsck errors.

> Also the app in the container might have been accessing the unencrypted view at the same time, moving files or directories.

Yes, this would fit. My guess: The gocryptfs.diriv file does not match the filenames in this directory, maybe because an operation was interrupted.
