### ISSUE TITLE
writer: Write/Writev failed, err: 2=no such file or directory. opcode: INTERRUPT

### ISSUE THREAD

**Issue by aj-ash** [rfjakob/gocryptfs#578]
Execute ``gocryptfs -fsck DEST`` prompt "writer: write/writev failed, err: 2 = no such file or directory.opcode: interrupt" when using version [2.0.1].
It is normal to roll back to version 1.8.0.

[2.0.1]: https://archlinux.org/packages/community/x86_64/gocryptfs/

**Comment by rfjakob** [comment]
Yes this message is normal and harmless. This message is already removed ( https://github.com/hanwen/go-fuse/commit/eefea5e0a5492b499d6bc51546a4b6357065d985 ), will be in the gocryptfs v2.1 release.
