### ISSUE TITLE
Root directory inode number is missing

### ISSUE THREAD

**Issue by stevegt** [rfjakob/gocryptfs#580]
The root directory inode number has gone missing in recent gocryptfs builds.  I ran into this while hacking on https://github.com/hanwen/go-fuse/issues/399 -- more details there.  I'm running into this myself with a toy filesystem, but still can't tell yet whether this is something we're both doing wrong with the go-fuse v2 fs API, or if it's a bug in go-fuse. 

Here's the latest binary release:

```
$ /tmp/gocryptfs_v2.0.1_linux-static_amd64/gocryptfs -version
gocryptfs v2.0.1 without_openssl; go-fuse v2.1.1-0.20210508151621-62c5aa1919a7; 2021-06-07 go1.13.15 linux/amd64

$ /tmp/gocryptfs_v2.0.1_linux-static_amd64/gocryptfs /tmp/cipher /tmp/plain
Password: 
Decrypting master key
Filesystem mounted and ready.

$ ls -lai /tmp/plain
total 244
        ? drwxr-xr-x   3 stevegt stevegt   4096 Jun 23 20:04 .
114556929 drwxrwxrwt 345 root    root    237568 Jul  5 15:17 ..
115353656 -rw-r--r--   1 stevegt stevegt      0 Jun 23 20:03 asfd
118631539 drwxr-xr-x   2 stevegt stevegt   4096 Jun 23 20:04 oiewurj
```

The inode number was there in this older version from an Ubuntu package:

```
$ /usr/bin/gocryptfs -version
gocryptfs 1.7.1; go-fuse 0.0~git20190214.58dcd77; 2019-12-26 go1.13.5 linux/amd64

$ /usr/bin/gocryptfs /tmp/cipher /tmp/plain
Password: 
Decrypting master key
Filesystem mounted and ready.

$ ls -lai /tmp/plain
total 244
115353655 drwxr-xr-x   3 stevegt stevegt   4096 Jun 23 20:04 .
114556929 drwxrwxrwt 345 root    root    237568 Jul  5 15:20 ..
115353656 -rw-r--r--   1 stevegt stevegt      0 Jun 23 20:03 asfd
118631539 drwxr-xr-x   2 stevegt stevegt   4096 Jun 23 20:04 oiewurj
```

**Comment by stevegt** [comment]
This is starting to look more like a go-fuse bug -- gocrypt's translation map is setting the root node's `Ino` correctly in [Getattr()](https://github.com/rfjakob/gocryptfs/blob/2a9d70d48f4cc715a6864849cdec91ab08b6fd03/internal/fusefrontend/node.go#L66), but then it's getting overwritten with a zero in [fs/bridge.go](https://github.com/hanwen/go-fuse/blob/24a1dfe6b4f8d478275d5cf671d982c4ddd8c904/fs/bridge.go#L563).

**Comment by rfjakob** [comment]
gocryptfs v1.x uses the go-fuse v1 api

Can confirm the problem with gocryptfs v2.x (**Inode: 0**)

```
$ stat mnt
  File: mnt
  Size: 80        	Blocks: 0          IO Block: 4096   directory
Device: 3fh/63d	Inode: 0           Links: 2
```

**Comment by rfjakob** [comment]
...but @stevegt do you maybe want to close this ticket in favor of https://github.com/hanwen/go-fuse/issues/399 ?

**Comment by rfjakob** [comment]
Scratch that, one is for go-fuse the other one for gocryptfs. All good.

**Comment by stevegt** [comment]
Depending on which way the consensus goes in https://github.com/hanwen/go-fuse/issues/399#issuecomment-874972645, gocryptfs may need changes.  

Option (1) in that thread would require no change to gocryptfs (as long as the fix doesn't break anything else -- see the caveats there).

Options (2) and (3) would need changes in the way the root node instance is initialized.

I'm curious if you can see any better alternatives -- given that I'm brand new to the code base, I feel like I've got to be missing something.

**Comment by rfjakob** [comment]
I took a quick look earlier, looks like a blind spot in the api
