### ISSUE TITLE
Vendored build dependencies are not used by default

### ISSUE THREAD

**Issue by Dekedro** [rfjakob/gocryptfs#581]
Steps to reproduce:
- Install go 1.16.5
- Get gocryptfs_v2.0.1_src-deps.tar.gz, unpack
- Make sure dependencies are not cached
- Run `build-without-openssl.bash` (or `build.bash` if openssl is installed)

Output:
```
...
go: downloading github.com/hanwen/go-fuse v1.0.0
go: downloading golang.org/x/sys v0.0.0-20200501145240-bc7a7d42d5c3
go: downloading golang.org/x/crypto v0.0.0-20200429183012-4b2356b1ed79
go: downloading github.com/rfjakob/eme v1.1.1
go: downloading github.com/hanwen/go-fuse/v2 v2.1.1-0.20210508151621-62c5aa1919a7
go: downloading github.com/sabhiram/go-gitignore v0.0.0-20180611051255-d3107576ba94
go: downloading github.com/jacobsa/crypto v0.0.0-20190317225127-9f44e2d11115
...
```

Expection: Compilation script uses vendored dependencies.
Solution: Add flag "-mod=vendor" to `go` invocations if "vendor" directory exists. [More info](https://golang.org/ref/mod#vendoring)

**Comment by rfjakob** [comment]
Thanks for the report! https://github.com/rfjakob/gocryptfs/commit/51bddd826ef29e5807b581dd037110e4502127cf should fix this.
