### ISSUE TITLE
Google Drive sync App / gocryptfs.diriv not synced

### ISSUE THREAD

**Issue by loungebob** [rfjakob/gocryptfs#582]
every now and then google drive insists it could not sync (or better upload) a gocrypftfs.diriv file (for whatever reason). and moves it to lost and found. I can see the file there. 

if I understood all correctly, the only job of the gocrypftfs.diriv file is to make sure duplicate file names in other directories do not encrypt to the same file name, right? 

so if this file is missing from a directory (like it would if google drive client didnt upload it), the file or files would still be there, just not with a plain text file name, right?

if I now check all the data uploaded within that session where the diriv file was supposedly not snyced/uploaded I should still see the files in the directory where the diriv is missing but only in encrypted file name form, right? or wouldnt I see them at all in the decrypted mount, just in the encrypted view (google mount)?

sorry, that's probably all basic stuff but I did check every directory uploaded in that session and I cant see any encrypted file names nor do I see any files missing (that is harder to judge though since there are a lot of files and it's not a sync but an upload so there is nothing to compare it to).

I guess there is no way to know where the gocryptfs.diriv file sitting in the lost and found folder was supposed to go or what it contains so I could hunt more specifically?

also, it is quite possible, that google drive still uploaded that mentioned diriv file and then still complained about not having uploaded it. would not be the first time. just want to make sure.

**Comment by rfjakob** [comment]
> if I understood all correctly, the only job of the gocrypftfs.diriv file is to make sure duplicate file names in other directories do not encrypt to the same file name, right?

Correct

> so if this file is missing from a directory (like it would if google drive client didnt upload it), the file or files would still be there, just not with a plain text file name, right?

The content is still there, but the file name cannot be decrypted

> if I now check all the data uploaded within that session where the diriv file was supposedly not snyced/uploaded I should still see the files in the directory where the diriv is missing but only in encrypted file name form, right? or wouldnt I see them at all in the decrypted mount, just in the encrypted view (google mount)?

File names that cannot be decrypted are invisible in the plaintext view. Use `-badname=*` to show them ( https://github.com/rfjakob/gocryptfs/blob/master/Documentation/MANPAGE.md#-badname-string )

> I guess there is no way to know where the gocryptfs.diriv file sitting in the lost and found folder was supposed to go or what it contains so I could hunt more specifically?

No, but hopefully there are not too many folders with gocryptfs.diriv missing. You can try to move each gocryptfs.diriv to see if the filenames can be decrypted.
