### ISSUE TITLE
/usr/bin/fusermount: failed to access mountpoint - permission denied

### ISSUE THREAD

**Issue by iio7** [rfjakob/gocryptfs#586]
I can combine EncFS and SSHFS and do the following:

```
$ sshfs example.com://home/foo/estorage estorage/ -o uid=$(id -u) -o gid=$(id -g)
$ encfs ~/estorage/ ~/storage/
```

All files that goes into `~/storage` gets encrypted on-the-fly to the "estorage" folder on example.com.

However, if I try to do the same with gocryptfs I get:

```
$ sshfs example.com://home/foo/estorage estorage/ -o uid=$(id -u) -o gid=$(id -g)
$ gocryptfs -config gocryptfs.conf -reverse ~/storage/ ~/estorage/
Using config file at custom location /home/foo/gocryptfs.conf
Password: 
Decrypting master key
/usr/bin/fusermount: failed to access mountpoint /home/foo/estorage: Permission denied
fs.Mount failed: fusermount exited with code 256
```

Is it not possible to do the same with gocryptfs as with EncFS?

**Comment by rfjakob** [comment]
Yes this should work, but I think you mount the wrong way around. Did you maybe mean to do

    gocryptfs -config gocryptfs.conf ~/estorage/ ~/storage/

?

**Comment by iio7** [comment]
I thought as much, but then I get input/output errors:

```
$ gocryptfs -config gocryptfs.conf ~/estorage/ ~/storage/
Using config file at custom location /home/foo/gocryptfs.conf
Password: 
Decrypting master key
Filesystem mounted and ready.
~ $ ls -la storage/
ls: reading directory 'storage/': Input/output error
total 0
```

**Comment by rfjakob** [comment]
This probably means that you have files that cannot be decrypted in the "estorage" folder. Details are logged to syslog!

**Comment by iio7** [comment]
Thanks!

I'm sorry, I changed the name of the directory and forgot to initialize!

```
gocryptfs[1420]: OpenDir ".": could not read gocryptfs.diriv: no such file or directory
```

It works now.
