### ISSUE TITLE
--include in reverse mode

### ISSUE THREAD

**Issue by jcbedacuk** [rfjakob/gocryptfs#588]
I would like to use reverse mode to present an encrypted view (for backup) of only a few directories in my home directory. As far as I see, gocryptfs only offers --exclude. Is there any chance of rsync style general include/exclude options?

**Comment by rfjakob** [comment]
This *may* be already possible with --exclude-wildcard, as it uses gitignore syntax, and gitignore syntax supports negated matches with "!" ( https://git-scm.com/docs/gitignore#_pattern_format ). Let me check.

**Comment by rfjakob** [comment]
It was *not* possible due to a bug, now fixed. Works like this: First exclude everything then include the folder "important":

    gocryptfs -reverse -exclude-wildcard '*' -exclude-wildcard '!/important' /home/user /mnt/user.encrypted

**Comment by jcbedacuk** [comment]
Thanks!
