### ISSUE TITLE
Add needed changes to use gocryptfs with singularity

### ISSUE THREAD

**Issue by jmfernandez** [rfjakob/gocryptfs#590]
Singularity is a daemon-less container platform very popular in HPC environments. One of its many features is mounting 
FUSE filesystems before switching from host to container context, assuring these user space mounts are only visible inside the container (see  https://sylabs.io/guides/3.7/user-guide/bind_paths_and_mounts.html#fuse-mounts).

Currently, gocryptfs is not compatible with singularity due two different reasons I'm going to explain in next scenario. Imagine next command line:

```bash
singularity run --fusemount "host:gocryptfs --params crypted_in_host uncrypted_in_container" docker://ubuntu
```

What singularity does under the hood is building a command line similar to this:

```bash
gocryptfs --params crypted_in_host /dev/fd/number -f
```

in order to fire the fuse mount command in foreground, and use as mountpoint the filehandler of the mountpoint directory within the container. This last feature is only supported by a subset of FUSE filesystems, like `sshfs` or [cvmfs](https://cvmfs.readthedocs.io/en/stable/cpt-configure.html#pre-mounting), which are usually linked against libfuse3.

Could you consider in your roadmap the support of these features, please?

**Comment by rfjakob** [comment]
libfuse commit: Allow passing /dev/fuse file descriptor from parent process https://github.com/libfuse/libfuse/commit/64e11073b9347fcf9c6d1eea143763ba9e946f70

**Comment by rfjakob** [comment]
The problem with `-f` at the end should be fixed now via https://github.com/rfjakob/gocryptfs/commit/f53f52b0464f747a370618bcdf152fad585f1eb5 . This gets rid of the bash wrapper.

**Comment by rfjakob** [comment]
Want to give

[gocryptfs.gz](https://github.com/rfjakob/gocryptfs/files/6977398/gocryptfs.gz)
(gocryptfs v2.0.1-52-g9a8dfd9-dirty without_openssl; go-fuse v2.1.1-0.20210802120645-15a8bb029a4e => ../../hanwen/go-fuse; 2021-08-12 go1.16.5 linux/amd64)

a try?

Looks pretty good here:

```
$ singularity run --fusemount "host:gocryptfs --extpass echo --extpass test /tmp/a /mnt" docker://ubuntu
INFO:    Using cached SIF image
Reading password from extpass program "echo", arguments: ["test"]
Decrypting master key
bash: /home/jakob/.cargo/env: No such file or directory
bash: /home/jakob/.cargo/env: No such file or directory
bash: /home/jakob/.cargo/env: No such file or directory
Singularity> Filesystem mounted and ready.
Singularity> 
```

**Comment by jmfernandez** [comment]
Yes, you got it! It is working!!! 👏👏👏👏👏👏👏👏👏👏👏👏

**Comment by rfjakob** [comment]
Merged to master now.
