### ISSUE TITLE
Encrypt without FUSE

### ISSUE THREAD

**Issue by Wouter0100** [rfjakob/gocryptfs#591]
As an alternative on #477, I'm interested if it is possible to encrypt files without the use of fuse. I can't seem to find any issues about this.

Our usage would be to encrypt project files in a CI/CD process, or in the build process of a custom OS we're building for an IoT-based project where the project files itself are encrypted. We plan on serving the gocryptfs master key or password (not looked into this, but I think masterkey) through an API to authenticate the device in a centralized environment before it is granted access to the project files.

Thank you very much!

**Comment by rfjakob** [comment]
No, sorry, I'm not aware of any way to do that yet. 

However, i guess it would be easy to add to https://github.com/slackner/gocryptfs-inspect if you know python.

Also note that FUSE works on github actions (that's how the gocryptfs test suite runs) and also on travis ci (that's where it ran before).
