### ISSUE TITLE
Minimum version of FUSE for 2.1 release

### ISSUE THREAD

**Issue by lechner** [rfjakob/gocryptfs#594]
Hi,

I tried to build 2.1 for Debian today but got the error below. What is the current minimum version of FUSE, please?

Is the return type adjusted in `golang-github-hanwen-go-fuse 2.1.0` (which is quite similar to your current release version)?

Thank you!

Kind regards
Felix Lechner

```
github.com/rfjakob/gocryptfs/internal/fusefrontend_reverse
# github.com/rfjakob/gocryptfs/internal/fusefrontend_reverse
src/github.com/rfjakob/gocryptfs/internal/fusefrontend_reverse/excluder.go:23:2: too many arguments to return
        have (*ignore.GitIgnore, error)
        want (*ignore.GitIgnore)
```

**Comment by rfjakob** [comment]
https://github.com/sabhiram/go-gitignore has changed, it's this commit: https://github.com/sabhiram/go-gitignore/commit/223ce5d391b0bfb8af397c4baf55ba4f0c9cd04c

**Comment by rfjakob** [comment]
Hmm, but i see that the author has not created a release after this change. If this causes pain for debian, I can revert back to the older go-gitignore version. I don't think there are any bugfixes.

**Comment by lechner** [comment]
> I can revert back

Not necessary; I can simply patch the Debian version. Please just identify your commit.

I can conveniently carry the patch forward as needed, which may not require a tagged release there.

Ubuntu may soft-freeze tomorrow, so your timely advice could help getting 2.1 in there. Thanks!

Kind regards
Felix Lechner

**Comment by rfjakob** [comment]
https://github.com/rfjakob/gocryptfs/commit/a7fa91764abbd97a1f5eb525e8d3cdb608546798

**Comment by rfjakob** [comment]
Note that go-fuse has seen some important fixes too, most important imo is https://github.com/hanwen/go-fuse/commit/a90e1f463c3f172a7690a6449fe5955a180dfec3 , which fixed https://github.com/rfjakob/gocryptfs/issues/549

**Comment by lechner** [comment]
Unfortunately, I do not maintain `go-fuse` and cannot ethically effect an upload in time for the Ubuntu freeze (there are no technical obstacles) but I will make sure Debian receives an update soon.

**Comment by lechner** [comment]
Hi, how about this one?
```
src/github.com/rfjakob/gocryptfs/mount.go:374:8: mOpts.EnableAcl undefined (type *fuse.MountOptions has no field or method EnableAcl)
dh_auto_build: error: cd obj-x86_64-linux-gnu && go install -trimpath -v -p 8 -ldflags "-X main.GitVersion=2.1 -X main.GitVersionFuse=2.0.3 -X main.BuildDate=2021-08-18" github.com/rfjakob/gocryptfs github.com/rfjakob/gocryptfs/contrib/atomicrename github.com/rfjakob/gocryptfs/contrib/findholes github.com/rfjakob/gocryptfs/contrib/findholes/holes github.com/rfjakob/gocryptfs/contrib/getdents-debug/getdents github.com/rfjakob/gocryptfs/contrib/getdents-debug/readdirnames github.com/rfjakob/gocryptfs/contrib/statfs github.com/rfjakob/gocryptfs/contrib/statvsfstat github.com/rfjakob/gocryptfs/ctlsock github.com/rfjakob/gocryptfs/gocryptfs-xray github.com/rfjakob/gocryptfs/internal/configfile github.com/rfjakob/gocryptfs/internal/contentenc github.com/rfjakob/gocryptfs/internal/cryptocore github.com/rfjakob/gocryptfs/internal/ctlsocksrv github.com/rfjakob/gocryptfs/internal/ensurefds012 github.com/rfjakob/gocryptfs/internal/exitcodes github.com/rfjakob/gocryptfs/internal/fido2 github.com/rfjakob/gocryptfs/internal/fusefrontend github.com/rfjakob/gocryptfs/internal/fusefrontend_reverse github.com/rfjakob/gocryptfs/internal/inomap github.com/rfjakob/gocryptfs/internal/nametransform github.com/rfjakob/gocryptfs/internal/openfiletable github.com/rfjakob/gocryptfs/internal/pathiv github.com/rfjakob/gocryptfs/internal/readpassword github.com/rfjakob/gocryptfs/internal/serialize_reads github.com/rfjakob/gocryptfs/internal/siv_aead github.com/rfjakob/gocryptfs/internal/speed github.com/rfjakob/gocryptfs/internal/stupidgcm github.com/rfjakob/gocryptfs/internal/syscallcompat github.com/rfjakob/gocryptfs/internal/tlog returned exit code 2
```

**Comment by rfjakob** [comment]
Needs this commit https://github.com/hanwen/go-fuse/commit/62c5aa1919a718ae4db57a7b145be533ccc14748
