### ISSUE TITLE
Make `-devrandom` option a no-op?

### ISSUE THREAD

**Issue by rfjakob** [rfjakob/gocryptfs#596]
Commit f3c777d5eaa682d878c638192311e52f9c204294 added the `-devrandom` option:

    commit f3c777d5eaa682d878c638192311e52f9c204294
    Author: @slackner 
    Date:   Sun Nov 19 13:30:04 2017 +0100

    main: Add '-devrandom' commandline option
    
    Allows to use /dev/random for generating the master key instead of the
    default Go implementation. When the kernel random generator has been
    properly initialized both are considered equally secure, however:
    
    * Versions of Go prior to 1.9 just fall back to /dev/urandom if the
      getrandom() syscall would be blocking (Go Bug #19274)
    
    * Kernel versions prior to 3.17 do not support getrandom(), and there
      is no check if the random generator has been properly initialized
      before reading from /dev/urandom
    
    This is especially useful for embedded hardware with low-entroy. Please
    note that generation of the master key might block indefinitely if the
    kernel cannot harvest enough entropy.

* We now require Go 1.13 (https://github.com/rfjakob/gocryptfs/commit/a5f88e86d186cdbc67e1efabd7aacf389775e027)

* However, it looks like kernel 3.16 is still alive with the last commit only a year ago: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-3.16.y

@slackner do you think `-devrandom` is still useful?

**Comment by slackner** [comment]
I don't mind if it is removed / replaced with a no-op, at least for me it is no longer that relevant (due to the newer Go version and modern Linux kernels used).

Note that Linux now also generates entropy instead of returning low quality randomness to usermode right after startup: https://lwn.net/Articles/802360/.

Best regards,
Sebastian

**Comment by rfjakob** [comment]
Done in https://github.com/rfjakob/gocryptfs/commit/61ef6b00a675456ee05d40f1ce44d693bc4be350
