### ISSUE TITLE
-allow_other option not working on top of ACD

### ISSUE THREAD

**Issue by vampywiz17** [rfjakob/gocryptfs#60]
Hello there,

I try to mount `-allow_other` switch (i enable it in fuse.conf) but if try to mount it, i get access denied if i try to open the folder. 

i try it with and without sudo, but same result: no access the mounted folder. 

Without -allow other, the mount is working well.

Hint: I try to mount  a acd_cli mounted folder.

**Comment by rfjakob** [comment]
You are mounting gocryptfs on top of acdcli? I guess you also need
allow_other in acdcli.

(Did you try gocryptfs on top of a normal folder? Unless I broke it
recently, allow_other should work there)

**Comment by rfjakob** [comment]
Hmm. Actually, using allow_other with gocryptfs should be completely invisible to acdcli. There must be something else going on. I'll check tonight.

**Comment by vampywiz17** [comment]
I tested it, and yes, the allow_other working well on normal folder. Only if i use a acd_cli mounted folder on encrypted files exist the error.

**Comment by rfjakob** [comment]
I justed tested this here, and it seems to work.

As my normal user, I mounted acdcli, without any options. Then I mounted gocryptfs with -allow_other, again with my normal user. I a root shell I can "ls" the mounted gocryptfs directory.

**Comment by vampywiz17** [comment]
I mount it acd_cli with sudo and `-allow_other` becouse if i use a other method, my plex server (and "plex" user) don't see the folder. 

I would like to keep the unencrypted mount (with allow_other) and inside, i would like a encrypted folder, that mounted my server. It is my plan.

**Comment by rfjakob** [comment]
Can you copy-paste your terminal session so I understand better what is going on?

**Comment by tcf909** [comment]
I ran in to the same issue. The problem is according to gocrypts manpage:
```
This option is equivalent to "allow_other" plus "default_permissions"
```
To resolve I did -ko allow_other instead of -allow_other. This passes just "allow_other" to the kernel and removes the "default_permissions" which for some reason caused the issue.

**Comment by rfjakob** [comment]
Cleaning up old tickets. I guess this one is solved via @tcf909's workaround.
