### ISSUE TITLE
Files emptied after power loss

### ISSUE THREAD

**Issue by robsmith11** [rfjakob/gocryptfs#600]
I've recently switched my entire home directory to gocryptfs, and it's been working well, but after my laptop's battery died today, two files I was editing in the last few minutes are now empty after remounting gocryptfs.  Is there any possibility to recover them or prevent this from happening the future?

```
$ gocryptfs -fsck /.m
Password:
Decrypting master key
DetectQuirks: Btrfs detected, forcing -noprealloc. See https://github.com/rfjakob/gocryptfs/issues/395 for why.
readFileID 9838447: incomplete file, got 18 instead of 19 bytes
fsck: corrupt file "REDACTED" (inode 9838447)
readFileID 9838449: incomplete file, got 18 instead of 19 bytes
fsck: corrupt file "REDACTED" (inode 9838449)
fsck summary: 2 corrupt files, 0 files skipped
```

**Comment by rfjakob** [comment]
This looks like Btrfs had not written the content to disk when the power went out.

It is strange that Btrfs did write the first 18 bytes (file header) but not the rest.

What editor did you use?

**Comment by robsmith11** [comment]
Ok, interesting.  So if I switch to ext4, I likely won't run into this again?

The text files were edited with neovim and were a few hundred lines of code and saved multiple times before the power failure.
I didn't notice it at first, but I also lost my entire Firefox cookies sqlite file during the power failure.  (I believe it didn't show up with fsck because Firefox had already overwritten it.)

**Comment by rfjakob** [comment]
> saved multiple times before the power failure

Whaaat!?

I'm looking how neovim saves a file right now, and so far I don't like it.

Also check this out: https://github.com/neovim/neovim/issues/9888

**Comment by rfjakob** [comment]
How neovim saves file is totally unsafe. It does not "fsync" the file, and it deletes the backup copy of the old data immediately.

This could happen just the same on ext4.

**Comment by rfjakob** [comment]
Revisiting the unanswered points:

> Is there any possibility to recover them or prevent this from happening the future?

I would say recovering anything here is virtually impossible.

But you can prevent this from happening again by enabling the "fsync" option in neovim.

> I didn't notice it at first, but I also lost my entire Firefox cookies sqlite file during the power failure. (I believe it didn't show up with fsck because Firefox had already overwritten it.)

Would have been interesting to see what fsck thinks about it. But maybe you have syslog entries from gocryptfs when firefox tried to access it first? It is possible that the file had incomplete blocks, an gocryptfs would return an I/O error in this case, and this may have triggered firefox to nuke it from orbit.

**Comment by rfjakob** [comment]
PS: I noticed that neovim stores .swp files of files it has open in

    ~/.local/share/nvim/swap/

Have you looked there?
