### ISSUE TITLE
OpenSSL 3 & FIPS 

### ISSUE THREAD

**Issue by ojamin** [rfjakob/gocryptfs#601]
https://www.openssl.org/blog/blog/2021/09/07/OpenSSL3.Final/
https://www.openssl.org/docs/man3.0/man7/fips_module.html

Now OpenSSL v3 has been released with its in built support for a new FIPS module & provider that is going through certification, it would be really great to work out how to specifically compile gocryptfs with OpenSSL 3 and start it with the FIPS provider turned on.

My main interest in this comes from running encfs compiled to run with OpenSSL's previous/old FIPS module - being able to port over to gocryptfs and OpenSSL 3 would be really great (and I'd expect I'm not the only one in a similar situation).

**Comment by rfjakob** [comment]
Looking at https://www.openssl.org/docs/man3.0/man7/fips_module.html , enabling the fips module could be as easy as

```
$ OPENSSL_CONF=/my/nondefault/openssl.cnf gocryptfs
```

But about how to compile with OpenSSL 3.0, I have not idea yet :)
