### ISSUE TITLE
Wiki page not indexed

### ISSUE THREAD

**Issue by lechner** [rfjakob/gocryptfs#602]
Hi,

When searching for `gocryptfs libpam_mount` [on Google](https://www.google.com/search?q=gocryptfs+libpam_mount) the resulting overview showed "No information is available for this page." and also "[Learn why](https://support.google.com/webmasters/answer/7489871?hl=en)". Following the link yields "You are probably seeing this result for the following reason: The page is blocked by robots.txt."

This is [the affected page](https://github.com/rfjakob/gocryptfs/wiki/Mounting-on-login-using-pam_mount) in the Wiki.

The Wiki seems like information intended for public consumption.

Kind regards
Felix Lechner

**Comment by rfjakob** [comment]
https://github.community/t/request-github-open-up-project-wiki-pages-to-web-indexes/122096

**Comment by nelsonjchen** [comment]
https://github.com/github/feedback/discussions/4992

**Comment by rfjakob** [comment]
I set up a mirror at https://nuetzlich.net/cgit/gocryptfs.wiki/tree/ . Let's see if it gets picked up by Google.

**Comment by nelsonjchen** [comment]
> I set up a mirror at https://nuetzlich.net/cgit/gocryptfs.wiki/tree/ . Let's see if it gets picked up by Google.

You can monitor how well it gets picked up with https://search.google.com/search-console/ .

**Comment by rfjakob** [comment]
https://nuetzlich.net/cgit/gocryptfs.wiki/tree/ is indexed by Google now. I think that's all I can do here.

**Comment by nelsonjchen** [comment]
Awesome, and it looks like it is ranking higher than the general purpose mirror I put out.
