### ISSUE TITLE
decrypt using the masterkey is not showing up the files

### ISSUE THREAD

**Issue by ginolhac** [rfjakob/gocryptfs#604]
Hello,

we are using `gocryptfs` (v1.7.1; go-fuse [vendored]; 2020-10-23 go1.14.1 linux/amd64)

in an HPC environment (@t-valette can help describing it if needed). 

When decrypting files (at least using plainnames) using the passwd works as intended but **not** using the masterkey.

Example below:
- create the `vault` folder and initialized, write down the masterkey.

```bash
$ mkdir vault plain
$ gocryptfs -init -plaintextnames vault
```
- write some fake content in `plain` using the passwd.

```bash
$ gocryptfs vault plain
$ echo "foo" > plain/bar
$ fusermount -u plain
```
- decrypt using the masterkey

```bash
$ gocryptfs -masterkey=d8dc4acf-a2ee12d0-775d31c0-51d807b8-184ed259-7c0a8b35-16033fb2-fb654d0c vault plain
Using explicit master key.
THE MASTER KEY IS VISIBLE VIA "ps ax" AND MAY BE STORED IN YOUR SHELL HISTORY!
ONLY USE THIS MODE FOR EMERGENCIES
Filesystem mounted and ready.

$ ls plain
total 0
```
file is NOT shown, nor accessible.
- decrypt using passwd

```bash
$ gocryptfs vault plain
Password:
Decrypting master key
Filesystem mounted and ready.
$ cat plain/bar
foo
```
works as attended.

Many thanks in advance for your help.

**Comment by rfjakob** [comment]
Hi, thanks, but I cannot reproduce this (please see below). Are you sure you use the right masterkey?

```
$ ./gocryptfs -version
gocryptfs v1.7.1 without_openssl; go-fuse v2.0.2-4-g8458b8a; 2019-10-06 go1.12.9 linux/amd64
$ mkdir vault plain
$ ./gocryptfs -init vault
Choose a password for protecting your files.
Password: 
Repeat: 

Your master key is:

    d78fc1f7-1558003f-6eadc7e0-432a3304-
    e09364bc-0d24a242-cffe605f-ab00c83a

If the gocryptfs.conf file becomes corrupted or you ever forget your password,
there is only one hope for recovery: The master key. Print it to a piece of
paper and store it in a drawer. This message is only printed once.
The gocryptfs filesystem has been created successfully.
You can now mount it using: gocryptfs vault MOUNTPOINT
$ ./gocryptfs vault plain
Password: 
Decrypting master key
Filesystem mounted and ready.
$ echo foo > plain/bar
$ fusermount -u plain
$ ./gocryptfs -masterkey=d78fc1f7-1558003f-6eadc7e0-432a3304-e09364bc-0d24a242-cffe605f-ab00c83a vault plain
Using explicit master key.
THE MASTER KEY IS VISIBLE VIA "ps ax" AND MAY BE STORED IN YOUR SHELL HISTORY!
ONLY USE THIS MODE FOR EMERGENCIES
Filesystem mounted and ready.
$ ls plain
bar
$ cat plain/bar 
foo
```

**Comment by ginolhac** [comment]
Hi,

Thanks for answering so quickly. 
Unless using the key without the new line is important, yes I am sure about the masterkey. I created the reprex several times (so different masterkeys) and it never worked. Another user (@t-vallette) also reproduced the issue

**Comment by rfjakob** [comment]
Whoops, missed it the first time, now I see the problem.

You need `-plaintextnames` when mounting too, like this:

    gocryptfs -plaintextnames -masterkey=d8dc4acf-a2ee12d0-775d31c0-51d807b8-184ed259-7c0a8b35-16033fb2-fb654d0c vault plain

With `-masterkey`, gocryptfs does not read gocryptfs.conf file, as it's supposed to work even when the file is missing. That means all options you have passed to `-init` need to be passed manually.

**Comment by ginolhac** [comment]
Indeed! thanks a LOT @rfjakob, works now!
Didn't know this crucial info. Thanks again, that's a relief.
