### ISSUE TITLE
[Feature request] An option to decrypt without revealing the masterkey

### ISSUE THREAD

**Issue by porobov** [rfjakob/gocryptfs#605]
Every time I mount the decrypted folder terminal shows my master key. I sometimes work with people behind my back, which makes me feel very uncomfortable. I thought it would be nice to add an option to hide the master key. Something like -hide-master-key would be very cool! Thanks!

**Comment by rfjakob** [comment]
Hi, gocryptfs no longer does this since v1.6 , released in 2018 ( https://github.com/rfjakob/gocryptfs/commit/6d64dfe8f7acd8e9ca4a659d26318e442c2db85a ).

What version are you running?

But in any case, you can use `-q` (quiet flag) to not print the masterkey.

**Comment by uti5** [comment]
But how do I now get the master key, if that's what I want?

**Comment by rfjakob** [comment]
Using gocryptfs-xray .
