### ISSUE TITLE
Command to "upgrade" the algorithm of existing cipher directory

### ISSUE THREAD

**Issue by balupton** [rfjakob/gocryptfs#607]
Now that v2.2.0 is out and supports a crypto algorithim that is much better suited for my Raspberry Pi 4 setup, it would be nice for a command to "upgrade/convert" the cipher directory to the best algorithm for my machine. Having downtime that causes an unmount / prevents mounting while the conversion occurs is fine as long as there is an ETA.

My current thoughts would be to setup a new one, then just `mv` everything over, then `rm -Rf` the old one once done, then mv the new cipher dir to the old cipher dir, and then mount it to the old plain dir.

The host file system is btrfs if that matters.

```
> gocryptfs --info redacted
Creator:      gocryptfs 1.7.1
FeatureFlags: GCMIV128 HKDF DirIV EMENames LongNames Raw64
EncryptedKey: 64B
ScryptObject: Salt=32B N=65536 R=8 P=1 KeyLen=32

> gocryptfs --speed
gocryptfs v2.2.0.HEAD; go-fuse v2.1.1-0.20210825171523-3ab5d95a30ae; 2021-09-26 go1.16.7 linux/arm64
cpu: BCM2835; no AES acceleration
AES-GCM-256-OpenSSL       	  22.52 MB/s	(selected in auto mode)
AES-GCM-256-Go            	  23.45 MB/s
AES-SIV-512-Go            	  18.93 MB/s
XChaCha20-Poly1305-OpenSSL	 206.33 MB/s	(selected in auto mode)
XChaCha20-Poly1305-Go     	 149.29 MB/s

> uname -a
Linux redacted 5.11.0-1017-raspi #18-Ubuntu SMP PREEMPT Mon Aug 23 07:34:31 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by rfjakob** [comment]
Yes, create a new filesystem and copy the data over. I recommend using rsync because it can resume interrupted copies. And I think it also gives an ETA. I have written it down some time ago here: https://github.com/rfjakob/gocryptfs/wiki/Upgrading

**Comment by balupton** [comment]
Cool thanks, I'll work on a script and post back.

**Comment by balupton** [comment]
I also noticed that -init without any cipher flags does not auto select the faster algorithm for the platform. It would be nice if it did, or if there was a flag to do that.

**Comment by rfjakob** [comment]
I'm reluctant to change the algorithm automatically, because then the filesystem cannot be mounted on older gocryptfs versions or on Windows ( https://github.com/bailey27/cppcryptfs ).

However, I added this now to `-init`:

    Notice: Your CPU does not have AES acceleration. Consider using -xchacha for better performance.

**Comment by balupton** [comment]
This is the script that I came up with:

https://github.com/bevry/dorothy/blob/14e619275b9313bf52a99baacce9bf60297ff1a4/commands/sharebox#L565-L641

I can make it more generic if there is interest.
