### ISSUE TITLE
when i writed audio and video files into the decrypted directory was super slow

### ISSUE THREAD

**Issue by kindusmithkindu** [rfjakob/gocryptfs#608]
It takes about one to two hours what write 50g audio and video files into the decrypted directory and then synchronize encrypt to the encrypted directory.

**Comment by rfjakob** [comment]
That's 6.9 Megabytes per second, not too fast, yes. Can you run

    gocryptfs -speed

and post the results?

**Comment by kindusmithkindu** [comment]
gocryptfs v2.2.0; go-fuse [vendored]; 2021-09-25 go1.17.1 linux/amd64
cpu: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz; with AES acceleration
AES-GCM-256-OpenSSL       	2704.76 MB/s
AES-GCM-256-Go            	3706.72 MB/s	(selected in auto mode)
AES-SIV-512-Go            	 190.10 MB/s
XChaCha20-Poly1305-OpenSSL	1624.21 MB/s
XChaCha20-Poly1305-Go     	1960.09 MB/s	(selected in auto mode)
