### ISSUE TITLE
[Feature request] Option to remove all colorization?

### ISSUE THREAD

**Issue by a-mnesia** [rfjakob/gocryptfs#617]
Is there any kind of option for removing all colorization from prompts and messages from the gocryptfs client software?

If not, could I request this as an option for a future release?

Thank you very much.

**Comment by a-mnesia** [comment]
Hi. Thank you for your reply!

I use colors in a very specific way on my desktop, and I prefer all my terminal
programs to be non-colorized. This includes "ls", "vi", "emacs", etc., and
I'd like to be able to select the same behavior with "gocryptfs".

If possible, I would just like some sort of --no-color option. If not, I can
work around this, because I can download the source code and add
that option, myself. But I'm just thinking that other users might also
like a --no-color option.

**Comment by a-mnesia** [comment]
I understand. However, I specifically prefer to not see colors in all
programs that I am running in terminal windows.

Again, I can code this myself, using the gocryptfs code base. But I'm
thinking that there might be other users who might also like some sort
of --no-color option.

**Comment by rfjakob** [comment]
Feature request makes sense and is easy to do. I will implement this.

Do you know / prefer the `NO_COLOR` env variable? https://no-color.org/

**Comment by lechner** [comment]
Thanks for that pointer! Lintian [now does](https://salsa.debian.org/lintian/lintian/-/commit/275a48e628120100a38cbcd5a4f7f5b70c5ab47d), too.
