### ISSUE TITLE
Add support for reflinks under linux

### ISSUE THREAD

**Issue by redneb** [rfjakob/gocryptfs#62]
Some linux filesystems (curretly btrfs and xfs) support a new feature called reflinks. This is a new concept that allows you to create a "clone" of an existing file, such that the clone does not occupy any extra disk space and instead it reuses the space occupied by the original file. Additionally, the clone can be modified independently of the original file and only then new disk space will be allocated (i.e. copy-on-write is used). So you can think of this operation as something between a hardlink and full copy of a file. This feature is accessible programmatically by calling the [FICLONE](http://man7.org/linux/man-pages/man2/ioctl_ficlone.2.html) ioctl.

It would be nice if `gocryptfs` supported this. I think this can be implement it, `gocryptfs` could accept `FICLONE` ioctl requests and forward them to the underlying filesystem. This will leak some information, but I think that this is acceptable as hardlinks are supported too and they leak similar information. Also, I am not 100% sure that fuse supports "capturing" this ioctl, but I think it does.

Recent versions of `cp` from GNU coreutils support this with the `--reflink` flag. So if this was implemented in `gocryptfs`, users would be able to do `cp --reflink old-file old-file-copy` in a `gocryptfs` volume.

Note that there are two related ioctls: FICLONERANGE and FIDEDUPERANGE, but I do not think they can be implemented by `gocryptfs`. Also, the `FICLONE` cpp constant was introduced in linux 4.5, but there is another constant, `BTRFS_IOC_CLONE`, which has existed for much longer and has the exact same value, so you may want to use that instead.

**Comment by rfjakob** [comment]
FUSE does support this, but the go-fuse library does not yet, as it seems: 

https://github.com/hanwen/go-fuse :
> * Missing support for FUSE_INTERRUPT, CUSE, BMAP, POLL, IOCTL

**Comment by redneb** [comment]
I wrote a simple fuse filesystem in C to do some testing. When I call `FICLONE` on a file in that filesystem, it was not received by it at all. So I looked at the kernel source, and it appears[1] that the `FICLONE` ioctl is not sent to fs driver. Instead, the driver is expected to define the `clone_file_range` member of its file operations struct (`struct file_operations`). Currently fuse doesn't do that, so my conclusion is that it is not possible to support `FICLONE` from fuse at the moment. Hopefully someday, fuse will add a special callback for that.

[Relevant](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/fs/ioctl.c?id=c8d2bc9bc39ebea8437fd974fdbc21847bb897a3#n666) [bits](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/fs/ioctl.c?id=c8d2bc9bc39ebea8437fd974fdbc21847bb897a3#n218) in the [kernel](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/fs/read_write.c?id=c8d2bc9bc39ebea8437fd974fdbc21847bb897a3#n1624).

**Comment by rfjakob** [comment]
Just checked again in the latest kernel. The `file_operations` bits are here:

Declaration of [struct file_operations](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/linux/fs.h?id=c6cdd51404b7ac12dd95173ddfc548c59ecf037f#n1691), contaning clone_file_range

Operations that FUSE supports are defined in [fuse_file_operations](
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/fs/fuse/file.c?id=c6cdd51404b7ac12dd95173ddfc548c59ecf037f#n3012). Still no clone_file_range, unfortunately.

I think we can revisit this once patches for kernel support are available, but I'll close this for now.

**Comment by digitalsignalperson** [comment]
Is this now supported? Relevant commit in libfuse: 
https://github.com/libfuse/libfuse/commit/fe4f9428fc403fa8b99051f52d84ea5bd13f3855
```
libfuse: add copy_file_range() support
Add support for the relatively new copy_file_range() syscall. Backend
filesystems can now implement an efficient way of cloning/duplicating
data ranges within files. See 'man 2 copy_file_range' for more details.
```

**Comment by trapexit** [comment]
copy_file_range isn't the same thing as FICLONE which is typically what "reflink" tends to use as mentioned in the original description.

https://trapexit.github.io/mergerfs/faq/technical_behavior_and_limitations/#does-ficlone-or-ficlonerange-work

It's something that might not be difficult to add to FUSE but requires discussion with kernel devs.
