### ISSUE TITLE
-extpass adds an extra dash to its argument

### ISSUE THREAD

**Issue by redneb** [rfjakob/gocryptfs#621]
A few months a go I wrote a script that automatically mounts a gocryptfs volume. The script uses the `-extpass` option which used to work just fine, but does not work anymore in . The script looks like this:
```
gocryptfs \
	-extpass PROGRAM \
	-extpass -n \
	-extpass PARAMETER \
	CIPHERDIR MOUNTPOINT
```
i.e. it passes multiple `-extpass`, one per parameter. The problem is that this does not work anymore because `PROGRAM` complains that it was passed a `--n` argument (instead of `-n`).

Here's my version of `gocryptfs`:
```
$ gocryptfs -version
gocryptfs v2.2.1 without_openssl; go-fuse v2.1.1-0.20210825171523-3ab5d95a30ae; 2021-10-20 go1.17.2 linux/amd64
```

**Comment by rfjakob** [comment]
Uhhh shoot, the move to pflag broke this. Will check how to fix.

**Comment by rfjakob** [comment]
Does it work with

-extpass=-n

?

**Comment by redneb** [comment]
Yes, it does! So, even though (I guess) this can still be considered a bug, there is a reasonable workaround and therefore as far as I am concerned, you close this issue.

**Comment by rfjakob** [comment]
Unfortunately, I don't see show to fix this without forking https://github.com/spf13/pflag .

I documented the bug and workaround in the man page: https://github.com/rfjakob/gocryptfs/commit/8722b894a6fb86945b96e5c3b2cc778853e21d17
