### ISSUE TITLE
Use fuse 3?

### ISSUE THREAD

**Issue by mattfbacon** [rfjakob/gocryptfs#626]
FUSE had a bug where it was missing Exfat on the allowlist for filesystems. As far as I can tell, the fix was merged in FUSE 3 (not 2). However, gocryptfs uses fuse2 specifically. This means I can't use it on my Exfat drive.

Is there a possibility to migrate to FUSE 3?

**Comment by rfjakob** [comment]
Thanks for reminder, I will try to push https://github.com/hanwen/go-fuse/issues/394 , but I will close this thicket in its favor

**Comment by rfjakob** [comment]
Just if you are not aware: the workaround is to mount to $HOME/mnt or something like this.

**Comment by mattfbacon** [comment]
Good to know. I just gave up and reformatted to ext4 though.
