### ISSUE TITLE
gocryptfs forbidds "/" in Extended Attribute Names

### ISSUE THREAD

**Issue by dragotin** [rfjakob/gocryptfs#627]
When you try to set an extended attribute with a `/` in the name, gocrpytfs bails out with an error like 
```
EncryptName "foo@https://bar": invalid plainName: contains forbidden bytes
```
The reason is that the function `encryptXattrName(attr string)` uses `EncryptName()` which checks if the name contains an `/`. While that is true for file names, I wonder if the restriction for extended attribute names is also valid. I do not think so.

**Comment by rfjakob** [comment]
Wow - Does this work on ext4?

**Comment by dragotin** [comment]
Yes, on my test system with ext4 I could set the the extended attribute `user.drago@https://foo` to `bar`.
