### ISSUE TITLE
Docs / Wiki - add KDE Wallet how to

### ISSUE THREAD

**Issue by benedictjohannes** [rfjakob/gocryptfs#628]
As the wiki currently has the howto for [Gnome Keyring](https://github.com/rfjakob/gocryptfs/wiki/Mounting-on-login-with-Gnome-keyring), I think it would be great if KDE Wallet also get its wiki entry.

I'd like to contribute the wiki entry, using `kwallet-query` fed to the `extpass` option, similar to how it's achieved with Gnome Keyring, along with a more detailed instruction on adding automatic mounting on GUI login (by adding scripts to `~/.config/autostart` or `~/.config/plasma-workspace/env`. Please let me know if you'd be okay with this.

**Comment by rfjakob** [comment]
Sure, go ehead!

**Comment by benedictjohannes** [comment]
Created the [page](https://github.com/rfjakob/gocryptfs/wiki/Mounting-on-login-with-KDE-Wallet), thanks @rfjakob
