### ISSUE TITLE
Unable to write regular files in gocryptfs folder mounted via FTP

### ISSUE THREAD

**Issue by Pecacheu** [rfjakob/gocryptfs#630]
Hi, I can't get gocryptfs to work properly on my system. I'm connecting to a server via FTP, mounted using curlftpfs. In the mounted image, I can read/write fine and do anything I need, but when I mount inside that as a gocryptfs, it can only read but not write. Weirdly, I can create directories fine, but any attempt to write with any application (even just copying a file with cp) results in a not supported error.

```
$ curlftpfs <IP> /mnt/remote -o user=<USER:PASS>,rw,umask=002,allow_other
$ mkdir /mnt/gocrypt
$ gocryptfs -passfile=gocrypt.pwd /mnt/remote /mnt/gocrypt
passfile: reading from file "gocrypt.pwd"
Decrypting master key
Filesystem mounted and ready.
$ cp test.txt /mnt/gocrypt
cp: cannot create regular file '/mnt/gocrypt/test.txt': Operation not supported
```

I'm using Debian and my gocryptfs version is `1.8.0; go-fuse 2.0.3; 2021-07-18 go1.15.9 linux/amd64`

**Comment by rfjakob** [comment]
I can reproduce the problem. Setup:

    vsftp server -> curlftpfs mount -> gocryptfs mount

Let's try to create a file:

```
$ echo 123123 > f2
bash: f2: Operation not supported
```

`strace -f -p` against the gocryptfs process shows:

```
[pid 756056] openat(9, "1rvfs8_ILJms_AGalCNBPw", O_RDWR|O_CREAT|O_EXCL|O_TRUNC|O_LARGEFILE|O_NOFOLLOW, 0100644 <unfinished ...>
[pid 756056] <... openat resumed>)      = -1 EOPNOTSUPP (Operation not supported)
```

Which means that opening the encrypted file failed with `Operation not supported`.
But the file is still created empty:

```
$ ls -l
-rw-r--r--. 1 root root    0  2. Jan 10:43 f2
```

Looks like https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=556012 , in that curlftpfs does not support O_RDWR .

I will take a look if I can workaround this in gocryptfs.

**Comment by Pecacheu** [comment]
Ah, thanks for looking into it. Yeah, I figured it was some sort of unsupported file operation in curlftpfs, given that gocrypt worked fine on a local folder. I'd have no idea what to do about the issue though, I don't know much about file system operations.

Though, today I managed to get it working on sshfs to the same server. However, ssh/scp is known to be much slower than FTP, so I would've preferred to get that working. Still, it's better than nothing and has been working so far, so clearly gocryptfs CAN work via a remote mounted filesystem, so it must be a curlftpfs issue.

**Comment by Pecacheu** [comment]
Also FWIW I did a speed test comparison using sshfs with or without gocryptfs and gocrypt didn't actually slow it down too much on either reading or writing a file, and didn't hog the CPU as much as I thought either. So great work on this software!

**Comment by rfjakob** [comment]
Thanks for the update. I did some more testing (details) below, and there seem to be additional issues in curlftpfs.

Given that the project seems dead (last release 2008: https://sourceforge.net/projects/curlftpfs/files/ ; best fork I could find is https://github.com/ikn/curlftpfs-ng ), I don't think it makes sense to work around all of them.

As you found out, please use sshfs instead.

----------

I set up a Debian 11 VM now and tried again, but even creating a gocryptfs filesystem is proving difficult:
```
ftp.mnt$ mkdir a
ftp.mnt$ gocryptfs -init -q a
Password: 
Repeat: 
write /tmp/ftp.mnt/a/gocryptfs.conf.tmp: input/output error
```

Ok. No problem, let's create it outside and copy it:

```
$ cp -r a ftp.mnt
cp: error copying 'a/gocryptfs.conf' to 'ftp.mnt/a/gocryptfs.conf': Input/output error
cp: failed to close 'ftp.mnt/a/gocryptfs.conf': Input/output error
cp: error copying 'a/gocryptfs.diriv' to 'ftp.mnt/a/gocryptfs.diriv': Input/output error
cp: failed to close 'ftp.mnt/a/gocryptfs.diriv': Input/output error
```
Uhh.

**Comment by Pecacheu** [comment]
Alright. One other thing is, with sshfs I did notice that gocryptfs gives this warning: `Warning: The underlying filesystem does not support fallocate(2). gocryptfs will continue working but is no longer resistant against out-of-space errors.`

But I'm not sure how big a deal that is, so far haven't had to deal with an out-of-space error so I can't say what happens.
