### ISSUE TITLE
Performance with one mount vs multiple mounts

### ISSUE THREAD

**Issue by RedKage** [rfjakob/gocryptfs#639]
Hello,

I'm using gocryptfs to secure multiple folders which are not in the same parent folder.
This means I have `-init` multiple times, and set up multiple folders passwords.
And I mount them one by one by running gocryptfs

I then realized that I had multiple gocryptfs processes running at the same time. Each one of them handling a different folder.
Then I wondered, what if instead I made a single folder, and put all my content inside?
My content is not just static files, there are stuff in there which gets read/write all the time.

This observation made me ask a simple question:
CPU-wise, is it better to have multiple gocryptfs processes, or to have a single one handling everything?
How would CPU usage vary? Can a single process handle concurrent stuff as well as multiple distinct processes?

I'm curious.

Thanks!

**Comment by rfjakob** [comment]
Hi, performance, cpu usage and memory usage should be similar. gocryptfs is fully multi-threaded, even one process can handle unlimited concurrency.
