### ISSUE TITLE
unix domain sockets are created with the wrong owner

### ISSUE THREAD

**Issue by redneb** [rfjakob/gocryptfs#64]
Suppose that you are running `gocryptfs` as root with the `-allow_other` option. Then if a non-root user creates a (regular) file in the `gocryptfs`, it will be owned by that user. But that doesn't seem to happen with unix domain sockets, they are instead always owned by root.

Here's how to reproduce this (with the help of `socat`):
As root, run the following:

    mkdir /tmp/gocryptfs-sock-test{,.enc}
    gocryptfs -init -extpass="echo test" /tmp/gocryptfs-sock-test.enc
    gocryptfs -allow_other -extpass="echo test" /tmp/gocryptfs-sock-test{.enc,}
    chmod 0777 /tmp/gocryptfs-sock-test

Then as a non-root user run this:

    socat unix-listen:/tmp/gocryptfs-sock-test/test.sock -
    
You can check now that the socket `/tmp/gocryptfs-sock-test/test.sock` will be owned by root.

`encfs` with the `--public` option, doesn't seem to have that problem:

    # as root:
    mkdir /tmp/encfs-sock-test{,.enc}
    encfs --public --standard --extpass="echo test" /tmp/encfs-sock-test{.enc,}
    chmod 0777 /tmp/encfs-sock-test
    
    # as non-root:
    socat unix-listen:/tmp/encfs-sock-test/test.sock -
    # /tmp/encfs-sock-test/test.sock is owned by the non root user

**Comment by rfjakob** [comment]
Looks like a bug in gocryptfs. Thanks for the report.

**Comment by redneb** [comment]
I was just doing some more testing and it appears that this issue does not only affect unix domain sockets, it also affects all other special file types: character devices, block devices, pipes, and even symlinks.

**Comment by rfjakob** [comment]
Should be fixed via e3c5e3f1c8db31e62bbb781a238da4cf76ed1ffc and 55df8acac30c382390ca59474f1732b0f1b230b8 , just pushed to master!

**Comment by redneb** [comment]
It now works like a charm. Thanks for the quick fix.

**Comment by rfjakob** [comment]
Thanks for testing! Closing the ticket.
