### ISSUE TITLE
Bounty

### ISSUE THREAD

**Issue by giraffe2k** [rfjakob/gocryptfs#642]
This feature request was closed some time ago
https://github.com/rfjakob/gocryptfs/issues/452

My understanding is that the only way to award the bounty is for @rfjakob to claim it, otherwise it will be retained by Bountysource when two years pass.
https://app.bountysource.com/issues/88137741-feature-request-encryption-primitives-for-devices-without-aes-cpu-instructions

**Comment by rfjakob** [comment]
Thanks for the reminder! It looks like they backpedaled on the two years ( https://github.com/bountysource/core/commit/b9774692fa72ab96021d6ac6113aa08c0abf8c7a#diff-35dd4be6162e67fb7bb10fc698ed61126e6f700cc73a101dcceada0b1d796448 ), but it makes no sense to leave the money at bountysource, I guess.

**Comment by rfjakob** [comment]
Money seems to be in my bountysource account now and I have requested a transfer to paypal! Thanks for the bounty!
