### ISSUE TITLE
repository config file names without "crypt" part ?

### ISSUE THREAD

**Issue by clickdimension** [rfjakob/gocryptfs#643]
Hi,

this is maybe only cosmetic, maybe exaggerated security:
Is it possible in cryptes repository different names for the config file.
I would like to make up fantasy names for "gocryptfs.conf" and "gocryptfs.diriv" for example.
So some courious would not suspect the tool name...

Would like to know if this is tweakable...

**Comment by rfjakob** [comment]
So, there's two things:

1) gocryptfs.conf: You can use any name you like using the `-config` option
2) gocryptfs.diriv: You can get rid of them altogether using the `-deterministic-names` option. This slightly reduces the security of the file name encryption (content encryption is unaffected).
