### ISSUE TITLE
Restoring data in reverse mode

### ISSUE THREAD

**Issue by pgrm** [rfjakob/gocryptfs#644]
Hello, according to a lot of documentation and https://github.com/rfjakob/gocryptfs/issues/47#issuecomment-374829559 reverse mode is only meant for encrypted backups.

What is the best way to restore these backups? Would I need to have 2x of the backed up storage available, so I can first copy over the encrypted folders and files, and afterwards copy them out of the on-the-fly decrypted folder onto the disc?

Or is there anything I missed?

**Comment by rfjakob** [comment]
So to restore files, you have to mount the encrypted directory.

If you cannot mount them from the backup location, you need twice the storage, yes.

**Comment by rfjakob** [comment]
PS: A 2nd option is to not copy the files out of the mountpoint, but access them through the on-the-fly decryption.

This way the reverse mode becomes normal forward-mode.
