### ISSUE TITLE
not able to mv folders

### ISSUE THREAD

**Issue by BrsyRockSs** [rfjakob/gocryptfs#645]
When I try to run command "mv test1 test2" I am getting "mv: cannot move ‘test1’ to ‘test2’: Function not implemented"
![image](https://user-images.githubusercontent.com/46119880/156605335-741d5fc2-89da-410d-88b4-881488ca3183.png)
![image](https://user-images.githubusercontent.com/46119880/156605400-1a09200f-7246-4d47-b8ff-9dde6e9d1c3b.png)
Please help 
ty

**Comment by BrsyRockSs** [comment]
What can I do to provide you with more information about debug?

**Comment by rfjakob** [comment]
Uhmm, what distribution is this, and what filesystem does it use (ext4 etc)?

**Comment by BrsyRockSs** [comment]
I use Linux deploy to install Ubuntu bionic on my mobile phone, then use rclone to mount WebDAV locally, and then use gocryptfs.
The file system is ext4

**Comment by rfjakob** [comment]
From what i have seen so far, all webdav mounts are so broken that running gocryptfs on top is impossible.
See also https://github.com/rfjakob/gocryptfs/issues/619
