### ISSUE TITLE
file permissions unclear after upgrading debian

### ISSUE THREAD

**Issue by matthijsbro** [rfjakob/gocryptfs#649]
I installed gocryptfs when on Debian 10 and used it to encrypt my Nextcloud’s data-dir. This worked fine. Today I upgraded to Debian 11, at first it worked but I think a reboot broke this.

I have trouble with mounting the dir. I can mount it as user 'admin' (or as root) with `gocryptfs encryptedatadir ncdata2` and the password still works and I can see the data. But the other user then cannot read it. For example:

```
#ls -lha
ls: cannot access 'ncdata2': Permission denied
total 1.5K
drwxrwx--- 5 nextcloud nextcloud 144 Apr  1 16:44 .
drwxrwx--- 6 nextcloud nextcloud 552 Apr  1 17:06 encryptedncdata
drwx------ 2 nextcloud nextcloud   0 Mar 10 06:55 lost+found
d????????? ? ?         ?           ?            ? ncdata2
```
Now nextcloud of course complains that it cannot find a data-dir or no .ocdata file. What kind of issue is this? Best I could find elsewhere is 'it is a mounting problem'. 
How to solve this? Could it be because gocryptfs upgraded from 1.6.1 to 1.8.0?

**Comment by rfjakob** [comment]
Hmm, what does the `ls -lha` look like when you run it as root?

What command line do you use for mounting?

**Comment by matthijsbro** [comment]
It looked like below. But, I reverted to an earliers snapshot. I updated from debian 10 to 11 again today and so far no problems. So... dunno. 
```
# ls -lha
ls: cannot access 'ncdata2': Permission denied
total 1.5K
drwxrwx--- 5 nextcloud nextcloud 144 Apr  1 16:44 .
drwxrwx--- 6 nextcloud nextcloud 552 Apr  1 17:06 encryptedncdata
drwx------ 2 nextcloud nextcloud   0 Mar 10 06:55 lost+found
d????????? ? ?         ?           ?            ? ncdata2
```

As I said, no problem today, ncdata2 now just has nextcloud as owner/group too.
