### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by jsalatiel** [rfjakob/gocryptfs#65]
Is there any chance to build a android binary ?

**Comment by rfjakob** [comment]
Whew, I don't think so. I don't want to develop on Android, and additionally it seems that FUSE is not really useable on Android: http://stackoverflow.com/questions/29215427/fuse-filesystem-in-userspace-support-on-android

**Comment by jsalatiel** [comment]
hi @rfjakob , i am not talking about an android app. Just a binary executable like there is already for encfs ( unnoficial ). If there is a binary external application could use it to mount gocryptfs =)

**Comment by rfjakob** [comment]
I just pushed a change that might enable this. Can you `git pull` and try:

```
GOARCH=arm ./build-without-openssl.bash
```

You will get an "Exec format error" (harmless, build.bash tries to call the binary to print the version).
The resulting binary looks good:

```
$ file gocryptfs
gocryptfs: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, not stripped
```
This is statically compiled, so *should* work fine on Android as well. Feedback welcome!

**Comment by jsalatiel** [comment]
It run... now i only have to see about fuser mount.
![teste](https://cloud.githubusercontent.com/assets/5522389/20947608/ca107d7e-bbee-11e6-80be-0d4ba9a7d43a.png)

**Comment by jsalatiel** [comment]
Is the fusermount binary really needed ? I can mount encfs just fine with the unnoficial encfs binary and i think it does not use this fusermount.

**Comment by rfjakob** [comment]
It looks like mounting a FUSE filesystem requires root permissions for the setup phase, which is why `fusermount` is a SUID binary. I'm not sure if encfs can mount without `fusermount` - what encfs version do you use on Android?
Also, what do you get when run try running `fusermount` on the command line?

**Comment by jsalatiel** [comment]
Hi @rfjakob, i'm already running as root and there is no fusermount binary on android.
I tried using the encfs binary from the cryptonite app, just to test it.
https://play.google.com/store/apps/details?id=csh.cryptonite&hl=pt_BR

**Comment by nnvn** [comment]
An android app will be awesome.

**Comment by rfjakob** [comment]
Looking at https://github.com/neurodroid/cryptonite , it seems they build their own copy of fusermount (part of libfuse).

So if you get https://github.com/neurodroid/android-platform-external-libfuse to compile and run on android, I guess gocryptfs may work.

**Comment by rfjakob** [comment]
But I don't think can integrate libfuse into gocryptfs like the cryptonite guys have done, this needs a person dedicated to Android.

**Comment by burdges** [comment]
I suppose the solution would be 
(1) a C library that extracts, and provides entirely user space access to, the FUSE kernel module and Linux VFS,
(2) an Android library that uses (1) to provides a filesystem-like GUI of FUSE file systems, and
(3) Android applications that use (2) to access sshfs, cryfs, etc.
Ignoring all the Android development for (2) and (3), I think even (1) sounds fairly arduous already even for basic FUSE access, but if you want cryfs on sshfs, etc. then you're starting to import much of Linux' VFS.  

I'll note the GNU Hurd's modular design would've resolved (1) nicely, but sadly [libfuse-hurd](https://www.gnu.org/software/hurd/hurd/libfuse.html) sounds rather unfinished.

**Comment by burdges** [comment]
In fact, I think the easiest route would be adjusting go-fuse so that gocryptfs can compile with [davfuse](https://github.com/rianhunter/davfuse), and accessing it via one of the many Android WebDAV GUI clients.

**Comment by rfjakob** [comment]
Patches welcome :)

**Comment by burdges** [comment]
I won't have time and davfuse might not be too well maintained.

**Comment by mirfatif** [comment]
https://github.com/rfjakob/gocryptfs/issues/239#issuecomment-626144226

**Comment by bingoxo** [comment]
take a look at https://github.com/hardcore-sushi/DroidFS

**Comment by rfjakob** [comment]
Nice, added to https://nuetzlich.net/gocryptfs/ and https://nuetzlich.net/gocryptfs/comparison/ !
