### ISSUE TITLE
Package for Fedora 36

### ISSUE THREAD

**Issue by pesader** [rfjakob/gocryptfs#650]
Now that Fedora 36 is right around the corner, it would be great to have `gocryptfs` packaged for it :)

I've never had a smoother folder encryption experience than that of gocryptfs paired with the [Vaults](https://github.com/mpobaschnig/Vaults/tree/0.3.0) frontend, so please let me know if there's anything I can do to help (testing, for example).

Thanks for developing this amazing program :rocket::heart:

**Comment by rfjakob** [comment]
Hi, thanks! Vaults does look nice!

About the Fedora package, it's kinda sad that there is none. However, the released [binaries](https://github.com/rfjakob/gocryptfs/releases/tag/v2.2.1) work everywhere as long as it's x86_64. I unfortunately don't have the time to maintain distro packages.

**Comment by pesader** [comment]
It worked indeed! Thank you so much!

**Comment by pesader** [comment]
Just in case someone is still looking for a gocryptfs package for recent Fedora versions, it is now available on a COPR repository:

https://copr.fedorainfracloud.org/coprs/dawid/gocryptfs/

**Comment by nuqleo** [comment]
Yet one Fedora repo with goryptfs built from sources 
https://copr.fedorainfracloud.org/coprs/nucleo/gocryptfs/
