### ISSUE TITLE
Doesn't exist in latest fedora

### ISSUE THREAD

**Issue by BirdInFire** [rfjakob/gocryptfs#659]
As we can see it's orphaned for more than 6 week and it doesn't in the repo anymore : https://src.fedoraproject.org/rpms/golang-github-rfjakob-gocryptfs

**Comment by dagdrommer** [comment]
I would be also interested in a comeback of gocryptfs in Fedora.

**Comment by twiddler** [comment]
@rfjakob Are you planning to bring gocryptfs to Fedora 36 repos?

**Comment by rfjakob** [comment]
No, sorry, it's sad to see this package go, but even though I use Fedora, I don't have the time to maintain distro packages. The binaries that can be downloaded from the Github releases work everywhere.

**Comment by dtantsur** [comment]
@rfjakob could you remove Fedora from https://github.com/rfjakob/gocryptfs#installation to avoid confusion?

**Comment by lechner** [comment]
Wow, what do those folks use? Is there another hot encrypted filesystem in town?

**Comment by rfjakob** [comment]
Removed from the readme, thanks!
