### ISSUE TITLE
mounting over filesystem type 0x00004d44 is forbidden, but works with root

### ISSUE THREAD

**Issue by Xephobia** [rfjakob/gocryptfs#662]
Hi, I have a USB key formatted with FAT32, and when I try to mount a gocryptfs container is fails with : 
```
/usr/bin/fusermount: mounting over filesystem type 0x00004d44 is forbidden
fs.Mount failed: fusermount exited with code 256
```
The mount works with root, but then I cannot `cd` to it (permission denied)

additionally, the file permissions and owner are unknown? (`d?????????  ? ?    ?           ?            ?  sauce`)

**Comment by rfjakob** [comment]
This is a restriction in fusermount (like https://github.com/libfuse/libfuse/issues/572).

It does not affect the use of FAT32 as storage for gocryptfs, just you cannot mount it to the USB stick.

I suggest to mount to /tmp/gocryptfs.mnt or /run/$UID/gocryptfs.mnt or something.
