### ISSUE TITLE
How to setup gocryptfs systemd unit automatically without having to use a password file?

### ISSUE THREAD

**Issue by alexanderadam** [rfjakob/gocryptfs#663]
It's probably not the best place to ask but I don't know any better place to ask this.

I'm using Ansible to setup my systems but this topic is probably independent from the used system.
The basic idea is to use gocryptfs as a systemd service, since defining runtime dependencies is trivial with systemd (I don't want to have applications running if their mount directory destination is not available).

I tried to use a "dumb" password script that gocryptfs can use to fetch a password on the fly (i.e. from ENV or an interactive input as a fallback).
For systemd services this is only achievable by either providing `systemctl --user import-environment GOCRYPTFS_SECRET` (which cause _all_ other systemd services to also have this environment variable) or by writing the variable in a plain text file.

Both solutions doesn't seem optimal as the best solution would be that only gocryptfs knows about the secret (at least more or less).
So maybe this isn't the best approach?

**PS:** I also asked about the general idea [on superuser](https://superuser.com/q/1722412/512312).

**Comment by rfjakob** [comment]
Maybe a named pipe (fifo)?
```
$ mkfifo -m 0600 /tmp/password-fifo
$ echo 12345 > /tmp/password-fifo
```
On 2nd terminal:
```
$ gocryptfs -passfile /tmp/password-fifo a b
```

**Comment by rfjakob** [comment]
No idea how to make Ansible write to the fifo, though.

The simpler (and less secure) method would be to write the password into a plaintext file on tmpfs (/dev/shm is always a tmpfs) and have systemd delete it after mounting using

```
ExecStartPost=rm /dev/shm/password-file
```
