### ISSUE TITLE
Password incorrect after syncing or opening with newer version.

### ISSUE THREAD

**Issue by grugel-maintro** [rfjakob/gocryptfs#668]
After syncing a folder over a sync service to another device the password stooped working on other devices as well as on the same device after an update. The version of gocryptfs used is 1.6.1 due to the LTS repos used in Tails. Due to the creation of the folder over SiriKali the secretkey is not backed up. Is there a way to recover the data?

**Comment by rfjakob** [comment]
Hi, you write "opening with newer version". Unless the "older version" was v0.6 or earlier, gocryptfs can open the filesystem (
https://github.com/rfjakob/gocryptfs/wiki/Compatibility ). Note that gocryptfs v0.7 was [released in 2015](https://github.com/rfjakob/gocryptfs/releases/tag/v0.7), so it's unlikely that you used to use gocryptfs v0.6.

The password is only checked against `gocryptfs.conf`, and this file is NEVER written by gocryptfs, except when the filesystem is created or the password is changed.

Does your sync service offer a file history? If so, I suggest to check when and how `gocryptfs.conf` was changed.

**Comment by grugel-maintro** [comment]
The file system has a history and i reset the folder to the first upload ever where the password was working in the past but still it is not working now. This is really strange but i have had multiple people accessing the folder with the same password that doesn't work now.

**Comment by rfjakob** [comment]
I'm sorry, I have no idea. I don't use SiriKali. Have you tried mounting directly on the command line? Did that work before the upgrade?
