### ISSUE TITLE
passfile does not work in /etc/fstab in debian bullseye / 11

### ISSUE THREAD

**Issue by lduesing** [rfjakob/gocryptfs#669]
Per Documentation:
> grep cipher /etc/fstab
/tmp/cipher /tmp/plain fuse./usr/local/bin/gocryptfs nofail,allow_other,passfile=/tmp/password 0 0

> sudo mount /tmp/plain 
mount: /tmp/plain: wrong fs type, bad option, bad superblock on /tmp/cipher, missing codepage or helper program, or other error.

> tail -1 /var/log/syslog
gw-demo kernel: [ 6525.928206] fuse: Unknown parameter 'passfile'

**Comment by rfjakob** [comment]
I cannot reproduce this problem here (Fedora 36). Are you sure that `/usr/local/bin/gocryptfs` is correct?

Here's how it goes on my machine:

```
$ grep cipher /etc/fstab
/tmp/cipher /tmp/plain fuse./usr/local/bin/gocryptfs nofail,allow_other,passfile=/tmp/password 0 0
```
```
$ sudo mount /tmp/plain
passfile: reading from file "/tmp/password"
Decrypting master key
DetectQuirks: tmpfs detected, no extended attributes except acls will work.
The option "-allow_other" is set. Make sure the file permissions protect your data from unwanted access.
Filesystem mounted and ready.
```

**Comment by lduesing** [comment]
Yes, it is correct. The problem seems to be somewhere in libfuse.

**Comment by lduesing** [comment]
Sorry. Error on my side. It seems to be possible to use fuse without installing the mount.fuse binary. After installing it, everything is ok.
