### ISSUE TITLE
Folder is empty after mounted.

### ISSUE THREAD

**Issue by kuoe0** [rfjakob/gocryptfs#671]
I have a vault that has lots of folders. One of the folders has many files in the encrypted vault and the gocryptfs.diriv is also there. But it got empty folder when I decrypted and mounted it. 

Other folders in the same vault are normal.

Version: v2.2.1
OS: Mac (M1 & non-M1)

**Comment by rfjakob** [comment]
Hi,

1) Check your system log, do you see messages like this?

    gocryptfs[990942]: OpenDir "atHqyU5z9AlJaQYVqqrj-w": invalid entry "xxxxxxxxxx": bad message

2) Do you have a 2nd copy of gocryptfs.diriv in this folder? Something like `gocryptfs.diriv (copy 2)` that some sync tool may have created?

3) You can mount with `-badname=* to see all files, including files that have names that cannot be decrypted.

**Comment by kuoe0** [comment]
Hi, thanks for answering!

> 1. gocryptfs[990942]: OpenDir "atHqyU5z9AlJaQYVqqrj-w": invalid entry "xxxxxxxxxx": bad message

No, I didn't see it.

> 2. Do you have a 2nd copy of gocryptfs.diriv in this folder? Something like gocryptfs.diriv (copy 2) that some sync tool may have created?

No, there is only one gocryptfs.diriv.

> 3. You can mount with `-badname=* to see all files, including files that have names that cannot be decrypted.

Yes, I can see them with encrypted names that could be accessed now.

---


Does it mean I would lose all of the filenames? Is there a way to recover filenames?

**Comment by rfjakob** [comment]
Does the file content in the GOCRYPTFS_BADNAME files look sane? (You can check with `file` to see what it thinks).

I'm really interested to understand how that happened. It seems that the `gocryptfs.diriv` file does not belong to this folder.

1) Did you modify the encrypted folder? Maybe with a sync tool like Dropbox or Syncthing?

2) What's the modified date on the gocryptfs.diriv compared to the files?

3) Do you have earlier backups of the folder?

**Comment by kuoe0** [comment]
Yes, they looks sane by `file` command.

Yes, I actually use `openssl` to encrypt the `gocryptfs.diriv` files to make it more secure. But, I think only one folder got broken is weird.

I don't have earlier backup... deleted after I thought everything is okay.

**Comment by rfjakob** [comment]
Content of gocryptfs.diriv is just 128 bits of random data, it is not secret, no need to encrypt it.

I suggest to run

    gocryptfs -fsck CIPHERDIR

to see if any other folders are broken.

With the gocryptfs.diriv file lost, there is no way to recover the filenames, no, sorry. You can recover the content using `-badname` as mentioned before, but not the names.
