### ISSUE TITLE
Any plans for a Windows version in Go?

### ISSUE THREAD

**Issue by lonnietc** [rfjakob/gocryptfs#673]
Hello,

I hope that everyone is doing well.

I know of the cppcryptfs version 

```
https://github.com/bailey27/cppcryptfs
```

But I need to locate a pure Go version to build on for a project that I am researching to start and wanted to know if there were any plans for a Windows Go version of gocryptfs?

**Comment by rfjakob** [comment]
Hi, no, sorry, no plans.
