### ISSUE TITLE
Google Drive limits gocryptfs mount to 32G 

### ISSUE THREAD

**Issue by sbgit** [rfjakob/gocryptfs#676]
I don't think this has much to do with gocryptfs but wanted to ask just incase someone had a workaround.  

The gocryptfs mounts seem to be limited are to 32G when using the Goolge Drive mount (streaming version).  I have tried multiple versions of gocryptfs and macfuse but always have the same issue.  When using gocryptfs on non-google mounts the file system correctly identifies the free space. 

-------------------
Versions:
OSX 12.4

Google Drive
Version: 60.0.2.0 (Intel)

gocryptfs v2.2.1-32-ga2b54cf without_openssl; go-fuse v2.1.1-0.20211219085202-934a183ed914; 2022-02-04 go1.15.3 darwin/amd64

macFUSE 4.4.0

-----------------------
Drive Space:
Google Drive
Filesystem                                                         Size   Used  Avail Capacity   iused     ifree %iused  Mounted on
//DRIVE@127.0.0.1:65255/Google%20Drive  2.0Ti  472Gi  1.5Ti    24% 123820733 412998967   23%   /Volumes/GoogleDrive

OSX SSD
Filesystem        Size   Used  Avail Capacity iused     ifree %iused  Mounted on
/dev/disk1s1  466Gi  379Gi   70Gi    85% 2799341 733563800    0%   /System/Volumes/Data

----------------------
Mount:
t.enc is on Google Drive and tmp is on SSD
gocryptfs t.enc ~/tmp/p
Password:
Decrypting master key
InoMap: opening spillMap for {{956301316 0} 4790028678176935451}

df -h ~/tmp/p
Filesystem                                                            Size   Used  Avail Capacity   iused     ifree %iused  Mounted on
/Volumes/GoogleDrive/My Drive/data/t.enc   32Gi  7.4Gi   25Gi    24% 123879115 412940585   23%   /Users/foo/tmp/p

**Comment by rfjakob** [comment]
Is this just about what is displayed as the size of does it stop working once you get above 32GB?
