### ISSUE TITLE
Protection against active adversaries

### ISSUE THREAD

**Issue by gutsle** [rfjakob/gocryptfs#679]
To quote the audit report:

> Against a less-powerful active adversary who can modify the
> ciphertexts but has no access to the mounted filesystem, gocryptfs keeps file contents
> secret and provides imperfect integrity protection. In at least one case, imperfections
> in the integrity protections lead to a break of confidentiality.

Have there been any improvements since the report?
For something that might potentially be used in a context like Dropbox this sounds pretty devastating.

**Comment by rfjakob** [comment]
What you quote from the abstract probably refers to this on page 4 in the pdf:

> [...] imagine the gocryptfs ciphertext is kept synchronized with a cloud
> storage provider, and the user has a cronjob that regularly publishes a
> nonsecret file (say, their favorite text editor’s configuration) to their
> website. The cloud storage provider can replace the cron-uploaded file with
> any ciphertext file, wait for the cronjob to run, and then download the
> plaintext.

No, there's nothing to do here. Just don't cron-upload stuff from your plaintext folder to the internet.
