### ISSUE TITLE
gocryptfs Filename Initialization Vector Chaining Status

### ISSUE THREAD

**Issue by jtrumble** [rfjakob/gocryptfs#68]
I've done some reading but wasn't able to find an answer to my question, 

From Hacker News : https://news.ycombinator.com/item?id=12140050
"Just one security level roughly equivalent to EncFS "paranoia" mode, at the speed of "default" mode."

Does this include Filename IV Chaining? (Which is a default selected paranoia option in EncFS) I ask because moving encrypted files around inside an encrypted directory structure from a third-party interface is something I need to do.

If it is supported, is this something the windows port cppcryptfs would also support?

**Comment by rfjakob** [comment]
You mean this feature, right?
>       _("Enable filename initialization vector chaining?\n"
>         "This makes filename encoding dependent on the complete path, \n"
>         "rather then encoding each path element individually."));
( from https://github.com/vgough/encfs/blob/v1.9.1/encfs/FileUtils.cpp#L922 )

The answer is no. The filename only depends on the `gocryptfs.diriv` file in its directory.

**Comment by rfjakob** [comment]
But you cannot move an encrypted file to a different directory under the same name.

Two files called "foo" in two different directories get different encrypted names because of the random `gocryptfs.diriv` in each directory.

**Comment by jtrumble** [comment]
Yes that feature. I see that gocryptfs uses Per-Directory IV not Filename IV; just not 100% sure of the difference between the two.

Say L is my mount point and it is C:\Users\Desktop\Cryptlocal.

Say L:\encDirectoryA and L:\encDirectoryB and in encDirectoryA I create encFileA.

If I go to C:\Users\Desktop\Cryptlocal and move the encrypted encFileA to encDirectoryB; will I be able to navigate to L:\encDirectoryB and open encFileA without issues?

(I know I'm using windows paths but the principle of what I'm asking is the same).

**Comment by rfjakob** [comment]
Is using `-plaintextnames` an option? Then you can move around the files freely.

**Comment by jtrumble** [comment]
Good to know but not something I would prefer to go with tbh. What happens if I drop my file into a top-level directory, but later move it into a lower sub-directory? Is just the filename encrypted again? Assuming gocryptfs doesn't use any other initialization vectors for file-names, it should be (theoretically) possible to re-calculate the needed file-name by running the original file-name through all the same AES-256-EME, base-64, less than 255 chars steps but using the proper directory IV...Then you'd just have to rename the file in-question with the generated file-name? (It could also be a command line option like emenames, something along the lines of specifyDirIV)

I still think the easiest solution is keeping a local copy of the directory structure for right now. Sorry for being such a pain with these questions! I have to request and wait for this be installed on the linux box in question, so I need to make sure I'm doing my due diligence.

**Comment by rfjakob** [comment]
Yes, only the file name is encrypted again. Renaming or moving files is
virtually instant in gocryptfs.

**Comment by jtrumble** [comment]
Ok, this sounds like it will work for what I want then thanks!
