### ISSUE TITLE
Unable to initialize with "gocryptfs.diriv: permission denied"

### ISSUE THREAD

**Issue by marcmk6** [rfjakob/gocryptfs#682]
Hi,

I tried to create an encrypted folder in a NFS mounted by [Mountain duck](https://mountainduck.io) but I got the following error.
```
Warning: fsync failed: sync NFS_PATH/cipher/gocryptfs.conf.tmp: permission denied
WriteDirIV: Close: close gocryptfs.diriv: permission denied
close gocryptfs.diriv: permission denied
```
It seems the identical problem reported [here](https://github.com/rfjakob/gocryptfs/issues/105#issue-224136098) but I still don't have any idea what the problem is.

The permission of `cipher` is `drwxr-xr-x`.

**Comment by rfjakob** [comment]
Hi, does this also happen when you mount through Finder like this https://apple.stackexchange.com/a/269817 ?

**Comment by marcmk6** [comment]
Hi,

As you tagged, this may be something unrelated to gocryptfs. I found I can create the cipher folder elsewhere and move it to the place it can't be created directly.
