### ISSUE TITLE
Use full semver when tagging releases (v2.x.y, not v2.x)

### ISSUE THREAD

**Issue by dtscd** [rfjakob/gocryptfs#688]
installing with `go install github.com/rfjakob/gocryptfs/v2@latest` will not recognize the latest release "v2.3", even if explicitly requested by tag. Right now it fetches "v2.2.1" which is in the format it recognizes.

I understand I can use git clone directly. But, perhaps a minor tweak would be alright.
Thanks.

**Comment by rfjakob** [comment]
Thanks for the report. I was not aware of this limitation in Go's fetching logic.

**Comment by rfjakob** [comment]
Pushed tag v2.3.0 (identical to v2.3). Does this fix it?

**Comment by rfjakob** [comment]
proxy.golang.org seems happy now:

https://proxy.golang.org/github.com/rfjakob/gocryptfs/v2/@v/v2.3.0.info
