### ISSUE TITLE
Build on (some) 64-bit architectures

### ISSUE THREAD

**Issue by davesteele** [rfjakob/gocryptfs#69]
The build process fails on some architectures with a complaint about the page size:

```
GOPATH=/«PKGBUILDDIR»/obj-powerpc64le-linux-gnu go test -v  github.com/rfjakob/gocryptfs
2016/12/08 04:11:22 page size incorrect: 65536
panic: page size incorrect: 65536
```
(from https://buildd.debian.org/status/fetch.php?pkg=gocryptfs&arch=ppc64el&ver=1.2-1&stamp=1481170286)

Affects arm64, ppc64el, and ppc64.

https://buildd.debian.org/status/package.php?p=gocryptfs

Logged as Debian bug #[849662](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=849662)

**Comment by rfjakob** [comment]
Panic is here: https://github.com/hanwen/go-fuse/blob/0ad840cf1c835844c01474aba565475b03909a01/fuse/misc.go#L87

**Comment by rfjakob** [comment]
Reported against go-fuse at https://github.com/hanwen/go-fuse/issues/160 . Closing this issue.
