### ISSUE TITLE
Is there any max file size limitation like 64GB due to GCM mode?

### ISSUE THREAD

**Issue by shujaat-github** [rfjakob/gocryptfs#691]
I am worrying if there is any file size limitation due to the GCM mode. Can someone please clear up my confusion?

**Comment by rfjakob** [comment]
Context: https://crypto.stackexchange.com/questions/31793/plain-text-size-limits-for-aes-gcm-mode-just-64gb .

This 64 GiB limit does not matter for gocryptfs as files are split into 4kB blocks that are encrypted separately.

Answering the question: No, there is no file size limit in gocryptfs.
