### ISSUE TITLE
Version 2.3 is unknown at go.dev

### ISSUE THREAD

**Issue by lechner** [rfjakob/gocryptfs#694]
Hi,

I'm trying to package Gocryptfs for my new base system Guix. They have an automatic importer that [seems to use go.dev](https://github.com/guix-mirror/guix/blob/master/guix/import/go.scm#L124), yet the importer [cannot find version 2.3](https://pkg.go.dev/search?q=gocryptfs):

```
guix import go -r github.com/rfjakob/gocryptfs/v2@2.3
guix import: error: version v2.3 of github.com/rfjakob/gocryptfs/v2 is not available
hint: Pick one of the following available versions: 2.2.0 2.2.0-beta1 2.2.0-beta2 2.2.1 2.0.1.
```

The importer may also use [proxy.golang.org](https://go.dev/ref/mod#goproxy-protocol), but I could not figure out how to query data about Gocryptfs with wget.

Thank you for this great software!

Kind regards
Felix Lechner

**Comment by rfjakob** [comment]
Ugh, that sucks. It's https://github.com/rfjakob/gocryptfs/issues/694 , I'll comment there.

**Comment by rfjakob** [comment]
ADDENDUM: I meant https://github.com/rfjakob/gocryptfs/issues/688

**Comment by lechner** [comment]
@rfjakob Thanks! Also, sorry about the duplicate filing. I did not realize the issues were related.
