### ISSUE TITLE
more secure way of passing password within script

### ISSUE THREAD

**Issue by lkolek** [rfjakob/gocryptfs#695]
Hello,

passing password with plain text (or even encoded, but every time the same) using extpass seams to me as a great vulnerability when using script to mount encrypted fs. 

Would it be possible to introduce more secure way of passing pass, eg. with some salt/challenge at designated socket and encoded pass (using salt) or some kind of hash of pass + salt?

**Comment by rfjakob** [comment]
Hi, I think you will end up with a chicken-and-egg problem, whatever you do.

Maybe you want to use a FIDO2 instead of the password?
