### ISSUE TITLE
Where are IV and GHASH stored for each block?

### ISSUE THREAD

**Issue by shujaat-github** [rfjakob/gocryptfs#700]
> Files are segmented into 4KiB blocks. Each block gets a fresh random 128 bit Initialisation Vector (IV) each time it is modified. A 128-bit authentication tag (GHASH) protects each block from modifications.

I wonder where IV(16 bytes) and GHASH(16 bytes) are stored for each block. If each encrypted block of 4KiB gets an extra 16 + 16 = 32 bytes, will 10 blocks contain (4KiB\*10) + (32\*10) bytes?

**Comment by rfjakob** [comment]
Hi, you may find https://github.com/rfjakob/gocryptfs/blob/master/Documentation/file-format.md informative.
