### ISSUE TITLE
ACD (Amazon Cloud Drive) with rclone mount does not work

### ISSUE THREAD

**Issue by tcf909** [rfjakob/gocryptfs#71]
Hello,

Fairly new to gocryptfs, but working on getting an encrypted cloud mount setup.

I have rclone mount working great against ACD, but when trying to initialize a directory for gocryptfs I get:

```
[root@localhost fstest]# gocryptfs -d -fusedebug -init acd
OpenSSL disabled, using Go GCM
Choose a password for protecting your files.
Password:
Repeat:
nonceGenerator.Get(): d650c7467716869da4059d2f
fsync: input/output error
```

The logs of the ACD mount look clean:
```
2017/01/09 13:27:05 : Dir.Attr
2017/01/09 13:27:05 : Dir.ReadDirAll
2017/01/09 13:27:05 : Dir.ReadDirAll OK with 0 entries
2017/01/09 13:27:08 : Dir.Attr
2017/01/09 13:27:08 : Dir.ReadDirAll
2017/01/09 13:27:08 : Dir.ReadDirAll OK with 0 entries
2017/01/09 13:27:13 gocryptfs.conf.tmp: Dir.Lookup
2017/01/09 13:27:13 gocryptfs.conf.tmp: Dir.Create
2017/01/09 13:27:13 gocryptfs.conf.tmp: Dir.Create OK
2017/01/09 13:27:13 File.Attr
2017/01/09 13:27:13 gocryptfs.conf.tmp: WriteFileHandle.Write len=355
2017/01/09 13:27:14 gocryptfs.conf.tmp: WriteFileHandle.Write OK (355 bytes written)
2017/01/09 13:27:14 gocryptfs.conf.tmp: WriteFileHandle.Flush
2017/01/09 13:27:14 gocryptfs.conf.tmp: WriteFileHandle.Flush OK
2017/01/09 13:27:14 gocryptfs.conf.tmp: WriteFileHandle.Release nothing to do
```

I've fiddled with a bunch of the options as well as tried to initialize a local directory and move the contents over to the ACD directory, but ultimately I always get fsync errors (or other errors depending on the scenario).

the options I was using to test rclone mount are:

rclone mount -v --low-level-retries=50 --no-modtime

(Although I use other optimizations for my main mount like readahead, etc).

I tested writing files directly to the ACD mount I'm trying to initialize and use for gocryptfs and everything checks out ok for plain files.

versions:
gocryptfs v1.2; go-fuse 6c2b7d8; 2016-12-04 go1.7.4
rclone v1.35

Hoping you can help, as the gocryptfs filesystem seems like the way to go based on all my research.

**Comment by rfjakob** [comment]
So the fsync problem is quite clear: rclone does not support it. We may gloss over that by just ignoring the error. But what other errors do you get?

**Comment by tcf909** [comment]
I can't remember off the top of my head now. It was mostly around writing
files, so could have been the same issue presenting itself differently
through the various tools I was trying.

**Comment by bgemmill** [comment]
Last I checked, rclone only supports sequential file writes, and gocryptfs is a bit more random. If your goal is to get your files into amazon drive over a fuse mount, have a look at this PR for acdcli: https://github.com/yadayada/acd_cli/pull/374

**Comment by tcf909** [comment]
@bgemmill thanks. I've been watching that thread. Sounds like you've done some great work. 

@rfjakob I opened up an issue with rclone to see about fsync (for another program). He is thinking about just ignoring the fsync on his end as well.

We can mark this as resolved -- fsync just isn't supported on rclone at this time (rclone version 1.35).

**Comment by RinCat** [comment]
Hi,

rclone added a fake fsync support(no online service support it, so just return OK) https://github.com/ncw/rclone/issues/1045

And also rclone said it support partial sync.

So I don't know why it failed without obvious error.

gocryptfs:
`encryptPath 'Untitled2.png' -> 'Kh2ihacnoXUkxD4cBbeXIA' (err: <nil>)
FS.GetAttr failed: 2=no such file or directory
encryptPath 'Untitled2.png' -> 'Kh2ihacnoXUkxD4cBbeXIA' (err: <nil>)
getBackingPath: /home/rincat/.acd/Backup + Untitled2.png -> /home/rincat/.acd/Backup/Kh2ihacnoXUkxD4cBbeXIA
FS.GetAttr('Untitled2.png')
encryptPath 'Untitled2.png' -> 'Kh2ihacnoXUkxD4cBbeXIA' (err: <nil>)
ino4272079392084078412: FUSE Write: offset=0 length=65536
FS.GetAttr('')
encryptPath '' -> '' (err: <nil>)
encryptPath '' -> '' (err: <nil>)
`

rclone:
`2017/05/16 16:35:15 DEBUG : Backup/Kh2ihacnoXUkxD4cBbeXIA: WriteFileHandle.Flush
2017/05/16 16:35:15 DEBUG : Backup/Kh2ihacnoXUkxD4cBbeXIA: WriteFileHandle.Flush ignoring flush on unwritten handle
2017/05/16 16:35:15 DEBUG : Backup/Kh2ihacnoXUkxD4cBbeXIA: WriteFileHandle.Flush
2017/05/16 16:35:15 DEBUG : Backup/Kh2ihacnoXUkxD4cBbeXIA: WriteFileHandle.Flush ignoring flush on unwritten handle
2017/05/16 16:35:15 DEBUG : Backup/Kh2ihacnoXUkxD4cBbeXIA: WriteFileHandle.Release closing
`
