### ISSUE TITLE
Combine gocryptfs with backup features

### ISSUE THREAD

**Issue by Satlinker** [rfjakob/gocryptfs#711]
Encryption and backup programs like Kopia seem to work in the same fashion. The difference is, that backup progs have a hard time to backup encrypted data. Features like deduplication, compression, splitting based on rolling hash doesn't work with encrypted files. On the other hand, I don't know an encryption program that has backup features, only mirroring the local data on cloud storage. Wouldn't it be an idea to combine these programs?
Mounting an encrypted file system and backup the unencrypted files is not ideal, because backup programs store data locally about the backed up files. So the backup might be encrypted again and safe, but not the local data from the backup prog. It also takes a lot of time to decrypt and crypt again.

**Comment by rfjakob** [comment]
What I would do is to backup the mounted gocryptfs filesystem using restic. Yes, this means decrypt-then-encrypt, but gocryptfs is fast, and usually much faster than the network connection.

I don't think I want to add any network features to gocryptfs.
