### ISSUE TITLE
obfuscating file attrs

### ISSUE THREAD

**Issue by bgemmill** [rfjakob/gocryptfs#72]
At the moment, uid, gid, mode, and other file attributes pass through to the underlying filesystem directly.

This means that it's possible to tell what files are executable, read-only, etc, even in the encrypted form, and there's a lot of information that an attacker can get from this especially if file size is also not quite obfuscated.

Is it reasonable to intercept fuse calls to get/set attr and hand them off as an encrypted blob in an xattr or separate file?

**Comment by rfjakob** [comment]
I guess it would be possible, but only at a significant cost in terms of code complexity and operation performance. As such, I don't thinks this will be added.

**Comment by bgemmill** [comment]
Understood if this is a wontfix, I wanted to draw the distinction between obfuscating file size in #57, and thus having to chunk up files and performance penalties, versus hiding uid/gid/mode.

**Comment by rfjakob** [comment]
I think #57 is another candidate for closing. It's been a few months and I still don't see a way to do this without running into all the problems CryFS runs into.

**Comment by bgemmill** [comment]
#57 is definitely a performance hit. I was running around with borg for a while before settling on gocryptfs, and while it's great at what it does, the performance difference is incredible.
