### ISSUE TITLE
Syslog error on Windows Subsystem for Linux

### ISSUE THREAD

**Issue by udit** [rfjakob/gocryptfs#728]
When mounting folder using `gocryptfs cipher plain` on WSL, it throws the following error:
```
Decrypting master key
Filesystem mounted and ready.
SwitchToSyslog: Unix syslog delivery error
SwitchToSyslog: Unix syslog delivery error
SwitchToSyslog: Unix syslog delivery error
SwitchToSyslog: Unix syslog delivery error
SwitchLoggerToSyslog: Unix syslog delivery error
```

Everything else seems to working normally though.

**Comment by rfjakob** [comment]
Hi, i guess syslog is not started - please try to start it and see if the
messages go away:
https://answers.microsoft.com/en-us/windows/forum/all/location-of-syslog-file-in-windows-10-ubuntu-bash/ae40a2d2-005e-4130-b830-d90e768e6fb5

**Comment by udit** [comment]
I did a bit of digging and found that [systemd is not enabled by default on WSL](https://www.reddit.com/r/bashonubuntuonwindows/comments/11zvl69/comment/jdegy85/?utm_source=share&utm_medium=web2x&context=3) and background services like syslog and cron depend on it. I'll look at it further and update.

**Comment by udit** [comment]
Followed the instructions here to enable systemd: https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/.

No more syslog errors.
