### ISSUE TITLE
Have cipher folder path registered with the system start with gocryptfs@

### ISSUE THREAD

**Issue by mhogomchungu** [rfjakob/gocryptfs#73]
Looking at below output of mount and you will see that all fuse based volumes have their cipher folder paths starting with project name followed by "@" and then cipher folder path.

This is important because on a mac,the file system of these fuse based volumes is reported as "osxfuse" and it becomes impossible to distinguish these volumes.

```
[mtz@ink ~]$ mount
/dev/sda10 on / type ext4 (rw,commit=0)
none on /proc type proc (rw)
none on /dev/pts type devpts (rw)
/dev/sda11 on /home type ext4 (rw,commit=0)
tmpfs on /run type tmpfs (rw,noatime,mode=755)
none on /proc/sys/fs/binfmt_misc type binfmt_misc (rw)
gvfsd-fuse on /tmp/runtime-mtz/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,user=mtz)
/home/images/gocryptfs on /home/_/gocryptfs type fuse.gocryptfs (ro,nosuid,nodev,user=mtz)
securefs@/home/images/securefs on /home/_/securefs type fuse.securefs (ro,nosuid,nodev,user=mtz)
encfs@/home/mtz/zzz on /home/_/zzz type fuse.encfs (rw,nosuid,nodev,default_permissions,user=mtz)
[mtz@ink ~]$ 
```

mount command output on a mac looks like below
```
/dev/disk1 on / (hfs, local, journaled)
devfs on /dev (devfs, local, nobrowse)
map -hosts on /net (autofs, nosuid, automounted, nobrowse)
map auto_home on /home (autofs, automounted, nobrowse)
localhost:/bNqIvVr1ZdFBdf19Io81Q4 on /Volumes/MobileBackups (mtmfs, nosuid, read-only, nobrowse)
/dev/disk4 on /Volumes/MyBook (hfs, local, nodev, nosuid, journaled)
cryfs@/Users/mouse/cryfs-raw on /Users/mouse/cryfs-crypt (osxfuse, nodev, nosuid, synchronous, mounted by mouse)
/dev/disk5s3 on /Volumes/DroboOne (hfs, local, nodev, nosuid, journaled, noowners)
/dev/disk7s3 on /Volumes/DroboTwo (hfs, local, nodev, nosuid, journaled, noowners)
/dev/disk6s3 on /Volumes/DroboThree (hfs, local, nodev, nosuid, journaled, noowners)

```

**Comment by rfjakob** [comment]
I understand the issue on Mac, but I don't understand where "encfs@" comes from on Linux. Which EncFS version are you using?
```
$ mount | grep encfs
encfs on /e2 type fuse.encfs (rw,nosuid,nodev,relatime,user_id=1026,group_id=1026,default_permissions)
$ encfs --version
encfs version 1.9.1
$ mount --version
mount from util-linux 2.28.2
```

**Comment by mhogomchungu** [comment]
You have to manually pass a few options to fuse for the entry to show up. I wanted the feature in cryfs and i proposed the additions in that project here: https://github.com/cryfs/cryfs/commit/002dc6ca17e4a7b72b9ba98c5d92f89245743de1#diff-ae4cbf05f3651de86efe25f065c26455R29

**Comment by rfjakob** [comment]
I see. Would adding support for "-o fsname=" be enough?

**Comment by mhogomchungu** [comment]
I have no problem with manually setting them but it will be nice if it happens automatically.

Next version of SiriKali will add support for OS X and i want it to be ready when your project offers official support for that platform. Currently,gocryptfs volumes simply do not show up because SiriKali can not get their volume type from output of mount command on OS X.

**Comment by rfjakob** [comment]
As this is not needed in Linux, I'd rather not always add it.

I have added the option equivalent to libfuse's in https://github.com/rfjakob/gocryptfs/commit/de200aad72f8718041f345b68c3c77332f995861 .

**Comment by mhogomchungu** [comment]
It works,
