### ISSUE TITLE
Unable to change password on WSL

### ISSUE THREAD

**Issue by udit** [rfjakob/gocryptfs#733]
Attempting to change the password throws following error when using gocryptfs on WSL:
`rename /mnt/c/Users/udit/.....gocryptfs.conf.tmp /mnt/c/Users/udit/.....gocryptfs.conf: permission denied`

File permissions:
```
-r-xr-xr-x 1 udit udit 385 Apr 29 19:21 gocryptfs.conf
-r-xr-xr-x 1 udit udit 385 Apr 29 19:22 gocryptfs.conf.tmp
-r-xr-xr-x 1 udit udit  16 Apr 29 19:21 gocryptfs.diriv
```

Looks like gocryptfs creates config files without write permissions for the user.

**Comment by thetuxinator** [comment]
I am trying to understand any usecase for WSL, i mean shouldn't you encrypt the hostsystem's userhome instead of the WSL one for example? Or use the gocryptfs Windows fork?

**Comment by udit** [comment]
Convenience; gocryptfs installs with a single command and my backup script uses rsync which is available on WSL out of the box. cppcryptfs needs you to install it's dependency - dokan, which is not a portable app and installing rsync on windows is cumbersome.

> shouldn't you encrypt the hostsystem's userhome

Yes, Windows' drives are mounted on WSL by default.

**Comment by rfjakob** [comment]
Hi, the files are read only, that's as it should be. gocryptfs only needs
write permission *on the directory*.

Maybe a bug in wsl?

**Comment by udit** [comment]
Right, it was a WSL issue: https://github.com/microsoft/WSL/issues/6193. Issue resolved after updating to latest WSL build. Closing.
