### ISSUE TITLE
FreeBSD support through cgofuse?

### ISSUE THREAD

**Issue by llucps** [rfjakob/gocryptfs#739]
I'm trying to migrate from debian to FreeBSD and the main roadblock is not being able to use gocryptfs since the library https://github.com/hanwen/go-fuse doesn't compile on FreeBSD https://github.com/hanwen/go-fuse/issues/415

Maybe it's a bit of stretch but could gcroptfs use this library on FreeBSD instead? Or it doesn't make sense what I'm proposing.

https://github.com/winfsp/cgofuse

Thanks

**Comment by rfjakob** [comment]
Hi, the platform support of https://github.com/winfsp/cgofuse is impressive.

Unfortunately, the API it provides is completely different to go-fuse.
