### ISSUE TITLE
Information: A GUI to manage gocryptfs volumes in linux and OSX: SiriKali

### ISSUE THREAD

**Issue by mhogomchungu** [rfjakob/gocryptfs#74]
SiriKali 1.2.4[1] was just released and it now works in OSX giving OSX users a GUI solution to manage their gocrypfs volumes.

SiriKali always worked in linux. 

Note: gocryptfs application must be installed for this to work.

[1] https://github.com/mhogomchungu/sirikali/releases/tag/1.2.4

**Comment by rfjakob** [comment]
Added to the README: https://github.com/rfjakob/gocryptfs#graphical-interface
