### ISSUE TITLE
New DirIV file being created?

### ISSUE THREAD

**Issue by jtrumble** [rfjakob/gocryptfs#75]
Ok. Let's start with, I am transferring files from one machine, to google drive storage using rclone copy.

I have a box with cryptlocal, and cryptlocalplain. I have a directory, TV, and a directory The 100 inside of TV. I have previously created TV > The 100 > Season 1; and TV > The 100 > Season 2 and rclone copied both of those at the same time in encrypted form. Ok, they are stored, so then I deleted The 100 directory and all it's contents.

Now if I re-create The 100 directory inside of TV, and create a Season 3 directory, and rclone copy that to storage; it's replacing The 100 DirIV file with a different version. I guess what I'm asking is why isn't the DirIV file the same? I would have thought it would have been if the directory-name is the same.

**Comment by rfjakob** [comment]
No, in "normal" forward encryption mode, the DirIV is randomly generated when directory is created.

**Comment by jtrumble** [comment]
Hmmm, so what is the best way to keep two directory structures like this in sync? I would think there are a lot of examples where a directory would be deleted, and then later re-created to add something too it.

**Comment by rfjakob** [comment]
I guess you delete the local files to reclaim the disk space. You could keep the empty directories intact, only deleting all *.avi etc files.

**Comment by jtrumble** [comment]
Yes, I agree, keeping empty directories is by far the simplest solution, and the one I am going with. For anyone curious, here is the rclone command I ran to bring back my directories and dirIV files from storage; worked like a charm.

rclone copy {remote storage} "cryptlocal" --exclude "*" --include "*.diriv" --max-size 25k
