### ISSUE TITLE
"gocryptfssh" convenience script

### ISSUE THREAD

**Issue by zevv** [rfjakob/gocryptfs#750]
After decades of happy encfs usage (my security needs are moderate), I ran into problems today with encfs crashing when reading my passphrase - openssl 3.0 changed too much and things are no longer compatible.

I just migrated my data to gocryptfs, which is the obvious choice for me. Thank you for providing this!

Encfs came with a nice convenience script called `encfssh`; this creates a temporary directory, mounts the crypted file system on it, chdirs, and spawns a subshell to work in. As soon as the subshell is exited, the crypted fs is unmounted again.

Would a similar wrapper script be appreciated for gocryptfs as well?

**Comment by rfjakob** [comment]
Merged, thanks
