### ISSUE TITLE
Option to suppress masterkey printing.

### ISSUE THREAD

**Issue by brimston3** [rfjakob/gocryptfs#76]
The terminal on a remote system does not need to know the master key every time, especially if the user has already stored it.

Currently, the masterkey will not print if logging to a file, so to work around the missing flag, I currently do the following:
`gocryptfs .gocrypt-store gocrypt |tee /dev/null`

Please add a mount option or short flag to suppress the master key output, or perhaps change the default behavior to only print the master key on init.

gocryptfs v1.2-35-g0f40afc; go-fuse 0ad840c; 2017-02-06 go1.7.4

**Comment by rfjakob** [comment]
Do you know "-q" ?

**Comment by brimston3** [comment]
I didn't; rtfm failure. I like the other info messages, but -q works for this issue. It still concerns me that the default is to print the master key each time--users might not be careful about where they unlock their mounts, but I can accept if this is the design direction you want to stick with.

**Comment by rfjakob** [comment]
The concern that the master key may end up in too many terminal buffers is certainly valid, especially if the user has already saved it somewhere. I think I'll add `Use -q to suppress this message` to the printout to make "-q" more discoverable.

PS: I'm amazed you discovered that the master key is not printed when writing to a pipe :)

**Comment by xaionaro** [comment]
I think that the idea of printing the master key (when the user didn't ask for that) is a very bad idea. It shouldn't be suppressed by an option, it should be not printed without a special option.

**Comment by rfjakob** [comment]
Fixed by https://github.com/rfjakob/gocryptfs/commit/6d64dfe8f7acd8e9ca4a659d26318e442c2db85a . Master key is not only printed on init.

**Comment by newhoa** [comment]
Some of the documentation (the git README.md, and the [home page](https://nuetzlich.net/gocryptfs/)), still says "keep a copy of your master key (printed on mount) in a safe place."

Is there a command option to print out your master key?

If you use a gui like SiriKali to create a volume, you will not see the master key on init. I may be overlooking it but now I do not see a way to print out the master key after init. Thanks.

**Comment by rfjakob** [comment]
It's not in gocryptfs itself but in gocryptfs-xray, option -dumpmasterkey   ( https://github.com/rfjakob/gocryptfs/blob/master/Documentation/MANPAGE-XRAY.md )

I will fix the docs, thanks for the notice

**Comment by newhoa** [comment]
Oh great, I did not know about gocryptfs-xray. Thank you!
