### ISSUE TITLE
Request for password=... option

### ISSUE THREAD

**Issue by balupton** [rfjakob/gocryptfs#762]
For fstab, akin to samba/smbfs/cifs it would be nice if it accepted a `password=...` option rather than needing `passfile` - for my use case, passfile is overkill.

```
# /home/balupton/Testing/cipher /home/balupton/Testing/plain fuse.gocryptfs rw,password=... 0 0
> sudo mount plain
Invalid command line: "gocryptfs" "/home/balupton/Testing/cipher" "/home/balupton/Testing/plain" "-o" "rw,password=...,dev,suid": unknown flag: --password. Try 'gocryptfs -help'.
```

This however works, but is convoluted:

```
# /home/balupton/Testing/cipher /home/balupton/Testing/plain fuse.gocryptfs rw,extpass=echo\040... 0 
> sudo mount plain
Reading password from extpass program "echo", arguments: ["..."]
Decrypting master key
Filesystem mounted and ready.
mount: (hint) your fstab has been modified, but systemd still uses
       the old version; use 'systemctl daemon-reload' to reload.
```

**Comment by rfjakob** [comment]
Hi, I think having `-password=...` is not so good, because it is fundamentally insecure. Having that option would encourage unsafe usage of gocryptfs.

If you really want it, and know what you are doing, there's the `-extpass` hack as you found out.
