### ISSUE TITLE
With firejail i don't can open any file with double-click

### ISSUE THREAD

**Issue by KonoromiHimaries** [rfjakob/gocryptfs#767]
With firejail i don't can open any file with double-click on external program, like. mpv, ristretto, xarchiver and other in the mounted folder.

https://github.com/netblue30/firejail#readme

need be run `sudo firecfg`

**Comment by jumoog** [comment]
It's a firejail problem.

**Comment by rusty-snake** [comment]
Summary of the problem FYI:
- firejail (SUID) searches for profile-files in a few directories, including the current working directory.
- If the cwd is a FUSE mount w/o `allow_root`/`allow_other`, it get's `EPERM`
- Everything except `EACCES` is treated as a hard error.

**Comment by rfjakob** [comment]
Discussed upstream at https://github.com/netblue30/firejail/issues/3798
