### ISSUE TITLE
Feature: Add support for few times and time remain password generator

### ISSUE THREAD

**Issue by KonoromiHimaries** [rfjakob/gocryptfs#768]
how can be work, example commands
```
gocryptfs -ro -ftimes x10 folder <password>
```
```
gocryptfs -ro -tremain 10minutes folder <password>
```

it's be usefull for public clouds and for guests in home, but may be required additional software on user-end that prevent create a copy and multiple thier trials.

**Comment by yahesh** [comment]
Can't decipher what this feature request is meant to mean.

**Comment by rfjakob** [comment]
Not completely sure but sounds like some DRM. Won't have that.
