### ISSUE TITLE
A stable/documented interface external tools can rely on.

### ISSUE THREAD

**Issue by mhogomchungu** [rfjakob/gocryptfs#77]
encfs/cryptkeeper bug[1] made a few rounds a few days ago and it makes me uneasy as somebody who maintains a front end to gocryptfs in SiriKali project.

Will it be possible to document an interface third party tools will be able to depend on and have tests that make sure the interface does not break between releases?

A C based library API will also be very much appreciated it. Observing how CLI tools behave at release XYZ appears to not be very reliable but there seem to be no other way to interface with these CLI only tools that offers folder based encryption solution.

[1] https://github.com/tomm/cryptkeeper/issues/23

**Comment by rfjakob** [comment]
We already have those tests ( [cli_test.go](https://github.com/rfjakob/gocryptfs/blob/master/tests/cli/cli_test.go) ), but some written documentation would be good, I agree!

**Comment by rfjakob** [comment]
(but I don't think I'll want to create a "libgocryptfs" - this would need lots of extra testing!)

**Comment by rfjakob** [comment]
@mhogomchungu I am working on this and thought it would be good to check if data is passed after the password (and exit with an error message if it is). What do you think? I thought this could help catching problems.

Commit is in a staging branch: https://github.com/rfjakob/gocryptfs/commit/17f2a24629818c529d3eb4a297ab1ad6763e08e7

**Comment by rfjakob** [comment]
Seems to work fine with SiriKali. Pushed to master.

CLI documentation is here: https://github.com/rfjakob/gocryptfs/blob/master/Documentation/CLI_ABI.md

**Comment by mhogomchungu** [comment]
I noticed a "CIPERDIR" typo in the document.

I think its a good idea to check if there is still more data after the first encountered new line character.

SiriKali currently only warns with it detects this[1] but i think i should turn it into an error too. The only scenarios where this could happen in SiriKali is when someone uses a keyfile that has a new line character in it. SiriKali just loads the contents on the keyfile,scans for the new line character to warn about it if present and then passes the data along to its backend as a password.Documentation on how SiriKali handle keyfiles is here[2]

Speaking of keyfiles and passwords,what is the maximum lengths of a password? I think there should be a limit and it should also be documented.

I do not understand go and hence i have not looked at your code but i have looked at other supported backends and noticed they do not care about maximum password length and they just read,read,read stdin until they encounter a new line character or a read fail and i think this is a bad idea but i have not opened a bug report for them.

Return values are not documented. 

[1] https://github.com/mhogomchungu/sirikali/blob/1cde7c40695522aaeabca448d1812eed89ddce8a/src/keydialog.cpp#L838

[2] https://github.com/mhogomchungu/sirikali/wiki/Frequently-Asked-Questions#40-what-does-different-key-options-means-in-the-dialog-for-creatingunlocking-volume

**Comment by rfjakob** [comment]
At the moment there is no limit for the password length. I'm not yet sure
if we should have one, when do you think does it help?

**Comment by mhogomchungu** [comment]
It just seems like a good idea. Somebody sending 10GB of data to gocryptfs as a password will do that only to use it to cause memory pressures on the system as a means to do something else. This is not a concern on a single user personal computer but could be a problem on a shared computer.

**Comment by rfjakob** [comment]
Yes that's a good reason. I just tried this, expecting to send the box into OOM:

    cat /dev/zero | gocryptfs -init a

Instead, it hangs with gocryptfs at 100% CPU. This is because the buffer for reading the password is reallocated for every byte read (1 byte bigger than before), causing exponential runtime.

I'll set the limit to 1000 bytes.

**Comment by rfjakob** [comment]
Done in 3784901fcee46d3e14e154b32cc6a7822bcc90f6 . This now fails instantly:

    $ cat /dev/zero | gocryptfs -init a
    Choose a password for protecting your files.
    Reading password from stdin
    fatal: maximum password length of 1000 bytes exceeded

I have reopened the ticket until I have the exit codes sorted out, it's a mess currently, and, as you noted, undocumented. Do you check for specific values already?

**Comment by mhogomchungu** [comment]
1000 is good enough but its a strange number for a computer system. I think it should be 1024.

SiriKali currently check for zero return value as a sign of success. Any other value causes it to parses output strings to figure out what error occurred. The error it cares the most about is the wrong password error.

**Comment by charles-dyfis-net** [comment]
I actually would have gone for 2048 to provide parity with EncFS's password length. :)

**Comment by rfjakob** [comment]
Encfs has a limit?

**Comment by charles-dyfis-net** [comment]
From the EncFS man page description for `--extpass`:

> Note: EncFS reads at most 2k of data from the password program, and it removes any trailing newline. Versions before 1.4.x accepted only 64 bytes of text.

**Comment by rfjakob** [comment]
@charles-dyfis-net Done in 6e029a3799816dd6703b2cb573022c7c3fd15c39

**Comment by rfjakob** [comment]
@mhogomchungu I have documented all exit codes that are likely to occour in [CLI_ABI.md](https://github.com/rfjakob/gocryptfs/blob/master/Documentation/CLI_ABI.md).

**Comment by mhogomchungu** [comment]
Thank you,i am already using the one i care about the most[1].

[1] https://github.com/mhogomchungu/sirikali/blob/3cd9d0bf3f562192e1c4c860f2517cadd473f318/src/siritask.cpp#L429
