### ISSUE TITLE
Feature: Add support for LZ4 - Extremely fast compression in real time

### ISSUE THREAD

**Issue by KonoromiHimaries** [rfjakob/gocryptfs#771]
https://github.com/lz4/lz4#benchmarks
https://github.com/pierrec/lz4

**Comment by rfjakob** [comment]
Hi, no, we cannot have compression as this loses random access.

**Comment by jficz** [comment]
@rfjakob random access for reads or for writes? If it's just read, then reverse mode with r/o access should still be doable, right?

**Comment by rfjakob** [comment]
No I don't see how. Files in reverse mode can also be read randomly.
