### ISSUE TITLE
Usability issue: add extra text showing that -fsck is working

### ISSUE THREAD

**Issue by jroovy** [rfjakob/gocryptfs#779]
When using `-fsck`, the command line output looks like this:
```
$ gocryptfs -fsck ENCRYPTED_DIRECTORY
Password:
Decrypting master key
```
However, the user might think it's stuck at decrypting the master key. Adding extra text showing that fsck is working would be nice, something like:
```
$ gocryptfs -fsck ENCRYPTED_DIRECTORY
Password:
Decrypting master key
Checking filesystem...
```

**Comment by rfjakob** [comment]
I agree, thanks for the report! Fixed.
