### ISSUE TITLE
first level gocryptfs.diriv file is always same when init in reverse mode

### ISSUE THREAD

**Issue by F-Hauri** [rfjakob/gocryptfs#786]
Is this a bug or even a security concern?

Let's see:

    $ gocryptfs -q -init -reverse test1 <<<'what a fucking strong pass phrase'
    $ gocryptfs -q -init -reverse test2 <<<"another long'n strong pass phrase"
    $ gocryptfs -q -init -reverse test3 <<<"shortPassword"
    $ gocryptfs -q -reverse test1 <<<'what a fucking strong pass phrase' crypt1
    $ gocryptfs -q -reverse test2 <<<"another long'n strong pass phrase" crypt2
    $ gocryptfs -q -reverse test3 <<<"shortPassword" crypt3
    $ sha1sum crypt?/gocryptfs.diriv
    2c9b6702d05d2de71816666387f6d4ea3c28c9cd crypt1/gocryptfs.diriv
    2c9b6702d05d2de71816666387f6d4ea3c28c9cd crypt2/gocryptfs.diriv
    2c9b6702d05d2de71816666387f6d4ea3c28c9cd crypt3/gocryptfs.diriv

But

    $ mkdir test{4,5,6}
    $ gocryptfs -q -init test4 <<<'what a fucking strong pass phrase'
    $ gocryptfs -q -init test5 <<<'what a fucking strong pass phrase'
    $ gocryptfs -q -init test6 <<<'what a fucking strong pass phrase'
    $ sha1sum test?/gocryptfs.diriv
    f38755738a0be70b6b103f6fdbdb05aaebb3ffe5 test4/gocryptfs.diriv
    e2e64788a6e2f0a4554bc56d9b17e55471766398 test5/gocryptfs.diriv
    206d278a405d3f826da842abdcdd37e475f9e02e test6/gocryptfs.diriv

After doing some more tests;
    [gocrypt-test.sh](https://f-hauri.ch/vrac/gocrypt-test.sh.txt)

I could ensure each *master key* is clearly different!

But I'm not sure about the meaning of *`gocryptfs.diriv`* file,

I wonder if this could significantly reduce required work for breaking the master key!?

**Comment by rfjakob** [comment]
Hi, yes, you are correct, the first level gocryptfs.diriv is always the same.

As seen in https://nuetzlich.net/gocryptfs/reverse_mode_crypto/#derived-ivs , it's computed as

    sha256(path + \0 + DIRIV)

And on the first level, `path = ""`, so we have only

    sha256(\0 + DIRIV)

In bash:

    $ printf "\\0DIRIV" | sha256sum 
    a8f7bac432ddc1cb3dc74e684d6ae48bc71acbd28683297e5e870270be90f248  -

That matches what we see in gocryptfs.diriv:

    $ hexdump -C b/gocryptfs.diriv 
    00000000  a8 f7 ba c4 32 dd c1 cb  3d c7 4e 68 4d 6a e4 8b  |....2...=.NhMj..|
    00000010

**Comment by rfjakob** [comment]
As for your question, no, this is not a problem. The only important thing thing about gocryptfs.diriv (Dir IV = Directory Initialisation Vector) is that you use different values for different directories **within one file system**.
