### ISSUE TITLE
Invalid encrypted names, can't use them on NTFS volumes

### ISSUE THREAD

**Issue by Unixware** [rfjakob/gocryptfs#788]
... as some of the encrypted files have a colon ':' in the midle of their filename so no way to backup (gocryptfs container on network drive) to NTFS volume.

**Comment by rfjakob** [comment]
Hi, colons should be not possible due to the base64 used ( https://www.rfc-editor.org/rfc/rfc4648.html#section-5 ).

Could you show an example?

**Comment by Unixware** [comment]
dang... looks like the NFS was responsible for this, sorry, false alarm.
I bit the bullet and deleted all of those files, as I have backup as well on ext4 volumes.
to give you an idea of that files:

<a href="https://ibb.co/Xb80m29"><img src="https://i.ibb.co/g3VqsjG/fsissue.png" alt="fsissue" border="0"></a>
