### ISSUE TITLE
Portable gocryptfs

### ISSUE THREAD

**Issue by pdroalves** [rfjakob/gocryptfs#79]
I would like to add some files encrypted with gocryptfs to a pendrive and keep a portable installation of gocryptfs to make it easy to decrypt those files in a non-previously set computer.

I couldn't find instructions about it. Is it possible?

**Comment by rfjakob** [comment]
Yes, no problem. Compile using "./build-without-openssl.bash". The
resulting "gocryptfs" binary has no dependencies and runs on any 64-bit
linux computer.

**Comment by gaillard** [comment]
It would be great if stupidgcm was its own pkg that we could use in other projects.

**Comment by rfjakob** [comment]
@gaillard Thinking about it. Just out of interest, what project do you have in mind?

**Comment by gaillard** [comment]
Actually with the pending patch here https://github.com/golang/go/issues/18498 I probably wouldn't end up using it. But if that doesn't go through, the small patch for stupidgcm would be preferable to the heavier spacemonkey's openssl.

**Comment by rfjakob** [comment]
Hmm, given that even spacemonkey-openssl [does not get used much](https://godoc.org/github.com/spacemonkeygo/openssl?importers) I guess stupidgcm would not fare much better. Probably the only user besides gocryptfs will be you, until the ARM64 assembly is merged ;)

I think it makes more sense if you just copy the "stupidgcm" folder into your project. I have just dropped the only dependency it had (a65965783a03645eb427e1958e5b9f9663b18951).

**Comment by rfjakob** [comment]
BTW I created stupidgcm because spacemonkey-openssl added a 0.5-seconds startup delay. I don't know if that has changed by now.

**Comment by gaillard** [comment]
Much appreciated thanks :)
