### ISSUE TITLE
Embedding gocryptfs in a Go webserver

### ISSUE THREAD

**Issue by biorisk** [rfjakob/gocryptfs#791]
I have been using gocryptfs for a few years (and DroidFS on android). Recently, I've thought about integrating the functionality in my open source [file webserver](https://github.com/biorisk/httpfolder). Looking through old issues, my question is identical to  #370, but now several years later. Since importing the gocryptfs package isn't viable, is there a good starting point to copy and paste into another application that wants to remain compatible with future versions of gocryptfs?

**Comment by rfjakob** [comment]
Hi, have you looked at https://github.com/hardcore-sushi/libgocryptfs ?

That's how DroidFS seems to do it.

**Comment by DrDaveD** [comment]
In [Apptainer](https://apptainer.org), which is written in go, we simply [include a gocryptfs binary](https://github.com/apptainer/apptainer/blob/main/INSTALL.md#installing-gocryptfs) in the package and invoke it with "os/exec" functions.

**Comment by biorisk** [comment]
@rfjakob, thanks for the pointer to libgocryptfs! At first glance, it looks like exactly what I need (and has the same motivation of limiting access at an app level rather than a user level). Since this answers my question, I'm closing the issue.
