### ISSUE TITLE
An idea

### ISSUE THREAD

**Issue by ehmo** [rfjakob/gocryptfs#794]
Hi @rfjakob,

I do apologize for reaching out this way. Even after much searching I couldn't find another way to contact you directly.

I was wondering if you would be open to a chat about potential paid consultancy on a project I am working on in the file encryption space. Please reach out at anything @turek.co.

Thank you

**Comment by rfjakob** [comment]
Hi ehmo, thanks for the offer, but I have enough things going on already :)
