### ISSUE TITLE
Unmount before upload to the cloud

### ISSUE THREAD

**Issue by Offerel** [rfjakob/gocryptfs#796]
Is it important to unmount first the plain volume, before i start a upload to the cloud (I'm using Dropbox Uploader: https://github.com/andreafabrizi/Dropbox-Uploader) or is it safe, when i start the upload with a mounted volume?

Reason for asking is: I will create a small backup bash script. In a rough description, i will mount the volume, if thats done, i will rsync my backup files with --delete option to the volume and at the end upload the whole thing to the cloud.

**Comment by rfjakob** [comment]
Safe.
