### ISSUE TITLE
mkdir problem when unionfs on top (permissions)

### ISSUE THREAD

**Issue by diseq** [rfjakob/gocryptfs#8]
Hi, 

let me first thank you for your great work! I'm very impressed what you achieved. :)
i want to report a small bug when creating directories when unionfs-fuse is layered on top.

without unionfs-fuse:
2015/12/09 21:01:26 Dispatch: MKDIR, NodeId: 1. data: {0775 (02)} names: [test3] 6 bytes

with layered unionfs-fuse:
2015/12/09 21:00:12 Dispatch: MKDIR, NodeId: 1. data: {00 (00)} names: [test2] 6 bytes

and unfortunately, the directory cannot be accessed.
i'm not sure if this is a problem of unionfs-fuse or gocryptfs.

**Comment by rfjakob** [comment]
[unionfs](https://github.com/rpodgorny/unionfs-fuse) has an interesting way of creating directories: It first creates it with 000 permissions and afterwards chmods it. That's certainly valid and now supported (commit 78cd97c5e9de221a6cd2ddfcaaa2c1f1f430d264).
