### ISSUE TITLE
Fuse independent

### ISSUE THREAD

**Issue by joeblew99** [rfjakob/gocryptfs#80]
It would be great to use this on mobiles.
Because of the dependency on go-fuse I presume this is not possible ?

**Comment by rfjakob** [comment]
If you want to run it on Android, there is already some info in ticket #65

**Comment by joeblew99** [comment]
#65 required root, so not an option for me.

i think that this is just not the right library to do this.
I need security at rest, and so maybe i will look at the various golang libraries out there that are DBs that can easily run on mobile.

if you happen to have any thought just reply, but am closing this .

**Comment by mirfatif** [comment]
https://github.com/rfjakob/gocryptfs/issues/239#issuecomment-626144226
