### ISSUE TITLE
force_owner not working in reverse mode

### ISSUE THREAD

**Issue by m4rc0d1** [rfjakob/gocryptfs#809]
For a rsync backup, I need to have the reverse-mounted encrypted directory owned by a specific non-privileged user in order to limit access of the backup user.

It seems that adding the -force_owner option while reverse-mounting the plain directory does not have an effect, i.e. all the files in the encrypted dir have the same ownership of the plain files. Is this the expected behavior? The documentation does not specify if the two options are compatible.

My current workaround is to remount the encrypted dir on another mountpoint using bindfs, but I would like to avoid stacking filesystems one over the other if possible.

**Comment by rfjakob** [comment]
Thanks for the report! Fixed now.
