### ISSUE TITLE
chown not working in mounted sub-folder

### ISSUE THREAD

**Issue by Leon-001** [rfjakob/gocryptfs#818]
Hi,
I can not change the owner of a subfolder in the decrypted folder. I have tried this:

```
mkdir .encrypted
mkdir decrypted
gocryptfs -init .encrypted
gocryptfs --allow_other .encrypted/ decrypted
cd decrypted
mkdir mysql
chown mysql: mysql
```
errormessage: "chown: der Eigentümer von 'mysql/' wird geändert: Die Operation ist nicht erlaubt" 
(in english: "operation not permitted")

I have also tried the chmod with "sudo" but that fails with the same error.

./gocryptfs --version gives:
gocryptfs v2.4.0-14-g6fbe61d without_openssl; go-fuse v2.4.0; 2024-01-14 go1.19.8 linux/arm64

uname -a gives:
Linux mx2.fairtragen.de 6.1.0-17-arm64 #1 SMP Debian 6.1.69-1 (2023-12-30) aarch64 GNU/Linux

**Comment by Leon-001** [comment]
When I enter the 4th command 
`gocryptfs --allow_other .encrypted/ decrypted`
it responds with this message (as expected):
The option "-allow_other" is set. Make sure the file permissions protect your data from unwanted access.
Filesystem mounted and ready.

**Comment by rfjakob** [comment]
Hi, gocryptfs needs to run aus root for chmod to work.

In other words, you need to use "sudo gocryptfs ..."

**Comment by Leon-001** [comment]
Ah ok! Thank you!!
