### ISSUE TITLE
Error mounting via fstab under Debian 12.5

### ISSUE THREAD

**Issue by noe-noenoe** [rfjakob/gocryptfs#832]
Dear all,

I have an issue mounting my gocryptfs volume via fstab under Debian 12.5 and I trust that someone can help me:

When I manually mount the gocryptfs volume, everything works fine:

`gocryptfs --passfile=/path/to/password /mnt/cipher/ /mnt/plain/`

But the following entry in /etc/fstab does not work:

`/mnt/cipher /mnt/plain  fuse./usr/local/bin/gocryptfs rw,nofail,auto,x-systemd.idle-timeout=10,x-systemd.automount,allow_other,passfile=/path/to/password 0 0`

Error message when attempting to mount manually is:

`mount: /mnt/plain: wrong fs type, bad option, bad superblock on /mnt/cipher, missing codepage or helper program, or other error.
       dmesg(1) may have more information after failed mount system call.`
         
(gocryptfs is in /usr/local/bin/gocryptfs.)

dmesg shows:
  
`fuse: Unknown parameter 'passfile'`

(If I add quiet to the fstab line, the same with 'quiet'.)

Newly initialising the volume did not help at all.

OS is Debian 12.5. However, when using Ubuntu 22.04.4 LTS, everything works fine. According to https://manpages.debian.org/bookworm/gocryptfs/gocryptfs.1.en.html, it should work under Debian, too.

Any ideas? Thanks in advance!

**Comment by rfjakob** [comment]
By the way, I did not know about `x-systemd.idle-timeout`. Very nice!

**Comment by noe-noenoe** [comment]
Thanks for checking this!

> Debian 12 has gocryptfs 2.3, https://packages.debian.org/bookworm/gocryptfs and probably also a much newer kernel. Can you post your `uname -a`?

Linux [redacted] 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux

Unfortunately, the fstab entry that works on Fedora does not work for me on Debian. I have no clue...

**Comment by caferen** [comment]
I'm having the same problem on Arch. Either with the same entry on `/etc/fstab` or with a `mount` unit.

```
$ uname -a
Linux archlinux 6.8.1-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:23 +0000 x86_64 GNU/Linux
$ gocryptfs --version
gocryptfs v2.4.0; go-fuse [vendored]; 2023-06-15 go1.20.5 linux/amd64
```

**Comment by rfjakob** [comment]
Do you have the command "mount.fuse" installed?

**Comment by caferen** [comment]
Yes. 

```
$ which mount.fuse
/usr/bin/mount.fuse

$ pacman -F mount.fuse
extra/fuse2 2.9.9-4 [installed]
    usr/bin/mount.fuse
```

**Comment by rfjakob** [comment]
On a fresh Debian 12, just installing gocryptfs via `apt install gocryptfs`, and this fstab line:

```
/mnt/cipher /mnt/plain  fuse.gocryptfs nofail,passfile=/mnt/passfile 0 0
```

I get this:

```
# mount -v /mnt/plain
mount: /mnt/plain: wrong fs type, bad option, bad superblock on /mnt/cipher, missing codepage or helper program, or other error.
       dmesg(1) may have more information after failed mount system call.
```

dmesg shows:
```
[24425.600314] fuse: Unknown parameter 'passfile'
```
but this is a red herring!

The actual problem is this:

```
# mount.fuse
-bash: mount.fuse: command not found
```

And this is the fix:

```
# apt install fuse

# mount -v /mnt/plain
passfile: reading from file "/mnt/passfile"
Decrypting master key
Filesystem mounted and ready.
```

**Comment by rfjakob** [comment]
The fix is `apt install fuse`.

**Comment by anrxc** [comment]
For future readers from google:  

On ArchLinux with fuse3 there is no mount.fuse. 

You can do: 

ln -s /usr/bin/mount.fuse3 /usr/local/bin/mount.fuse
