### ISSUE TITLE
avoid shelling out to logger binary

### ISSUE THREAD

**Issue by pmazzini** [rfjakob/gocryptfs#834]
Is there any reason why `gocryptfs` shells out to `logger`[1] instead of using the standard `log/syslog` package?

[1] https://github.com/rfjakob/gocryptfs/blob/master/daemonize.go#L75

**Comment by rfjakob** [comment]
Yes. `log/syslog` does not catch panics.

**Comment by rfjakob** [comment]
Adding a comment explaining that would have been a good idea -_-

**Comment by pmazzini** [comment]
Ok, thanks for the info. This also provides some more context:
https://stackoverflow.com/questions/34772012/capturing-panic-in-golang

**Comment by pmazzini** [comment]
Do you have thoughts on the approach `rclone` is using to redirect `stderr` output and still use `log/syslog`?

**Comment by rfjakob** [comment]
Looks like for rclone, the regular logs will go to syslog but the panics go
somewhere else (into a file somewhere?). I think rclone should switch to
spawning a logger.
