### ISSUE TITLE
[Question] Is using the same config for multiple filesystems a bad idea?

### ISSUE THREAD

**Issue by SimonPilkington** [rfjakob/gocryptfs#835]
My use case is: I want to rsync one of my gocryptfs filesystems to an external server while keeping another completely local. I don't think having different master keys would provide additional security in this case so I tried using the same config for both. I did this by initing the second FS, deleting its config and keeping only the diriv, then telling it to use the first FS's config when mounting.

As far as I can tell, this works. Did I miss something?

EDIT: I forgot to mention, the config is external to both filesystems and stored under $HOME/.config

**Comment by rfjakob** [comment]
Looks good to me. This is equivalent to having two subfolders in one filesystem, which is obviously OK.
