### ISSUE TITLE
if my computer crash and has been hard restart then secound disc not loaded even if i try to run

### ISSUE THREAD

**Issue by KonoromiHimaries** [rfjakob/gocryptfs#838]
this has been doing only if i have mounted partition with gocryptfs
only format with gparted can restore my secound disc

gocryptfs latest
arch endeavor os latest x64

**Comment by rfjakob** [comment]
Hi, what is the error message?

**Comment by KonoromiHimaries** [comment]
![Zrzut ekranu z 2024-04-10 11-24-17](https://github.com/rfjakob/gocryptfs/assets/5884000/4b716163-cf17-4628-9d60-adc60574bce8)

**Comment by KonoromiHimaries** [comment]
this are happens independently of gocryptfs
