### ISSUE TITLE
Decrypt paths?

### ISSUE THREAD

**Issue by lechner** [rfjakob/gocryptfs#84]
Hi, what's the best way to get the unencrypted filename from an encrypted path (from a log or so)? Thank you!

**Comment by rfjakob** [comment]
I added the `-ctlsock` functionality a while back to do that, however, at the moment you can only ENcrypt paths. Details: https://github.com/bit-team/backintime/issues/644#issuecomment-259835183
Also, in the contrib folder there is the `ctlsock-encrypt.bash` example script for how to interact with the control socket.

**Comment by rfjakob** [comment]
For a quick solution you can get the inode number of the decrypted file and use `find -inum` on the encrypted directory. The inode number of encrypted and decrypted files is the same.

**Comment by sam-ka** [comment]
For those who want a slow but concrete solution to this problem on linux, I recommend `find "$2" -inum "$(stat -c '%i' "$1")" `, where `$1` and  `$2`are the encrypted and decrypted roots of the gocryptfs fs (order depends on whether you want to map encrypted paths to decrypted paths or the reverse).

**Comment by rfjakob** [comment]
https://github.com/rfjakob/gocryptfs/blob/master/Documentation/MANPAGE-XRAY.md#-decrypt-paths
