### ISSUE TITLE
REPRODUCIBLE: gocryptfs reverse generating files that gocryptfs can't decrypt?

### ISSUE THREAD

**Issue by DurvalMenezes** [rfjakob/gocryptfs#841]
As per the subject, and here's how to reproduce the problem:

```
mkdir /tmp/gocryptfs_corruption_test
cd !$
export N='===Short_name'; echo $N

mkdir original_data
mkdir original_data/$N
echo Mary Had A Little Lamb > original_data/$N/$N

gocryptfs -init -reverse -deterministic-names original_data
    -> Pick whatever password you want; I used "lO22343%fT" (without quotes)
    -> Take note of the masterkey as we will need it in the last step

mkdir encrypted_data
gocryptfs -reverse -deterministic-names original_data encrypted_data
        -> Enter the same password as above.

mkdir recovered_encrypted_data
cp -rp encrypted_data/. recovered_encrypted_data/.

mkdir recovered_decrypted_data
gocryptfs -deterministic-names -nosyslog -masterkey=stdin recovered_encrypted_data recovered_decrypted_data 
       -> Enter the masterkey  you took note of above.
cat recovered_decrypted_data/\=\=\=Short_name/\=\=\=Short_name
    -> And the result, instead of the beginning of the nunnery song, is an error:
        doRead 3934243: corrupt block #0: cipher: message authentication failed
        doRead 3934243: corrupt block #0: cipher: message authentication failed
        cat: 'recovered_decrypted_data/===Short_name/===Short_name': Input/output error
```

This is on a fully updated Ubuntu 22.04.4 amd64 system using the static gocryptfs v.2.4.0 binary extracted from
https://github.com/rfjakob/gocryptfs/releases/download/v2.4.0/gocryptfs_v2.4.0_linux-static_amd64.tar.gz

This is my very first use of gocryptfs (trying to validate it for my specific use case, which is backing up
encrypted data, and then trying to recover the original data using only the encrypted data plus the masterkey);
So, I may very well be making some kind of stupid mistake, but for the life of me I can't see it -- and will be
doubly grateful if anyone can point it to me.

**Comment by rfjakob** [comment]
Decrypting using the password (i.e. without -masterkey) works normally?

**Comment by DurvalMenezes** [comment]
> Decrypting using the password (i.e. without -masterkey) works normally?
Thanks for the prompt response. Will test momentarily and let you know.

**Comment by DurvalMenezes** [comment]
> Decrypting using the password (i.e. without -masterkey) works normally?

Just tested it. 

In short: YES, IT WORKS! (without `-masterkey` and instead supplying `-config` pointing to a backup of the complete .gocryptfs.reverse.conf file): 

In detail: here's the complete test procedure, changed for this case: 

```
mkdir /tmp/gocryptfs_corruption_test
cd !$
export N='===Short_name'; echo $N
mkdir original_data
mkdir original_data/$N
echo Mary Had A Little Lamb > original_data/$N/$N
gocryptfs -init -reverse -deterministic-names original_data
    -> Pick whatever password you want; I used "lO22343%fT" (without quotes)
    -> This time, no need to take note of the master key as we will be using a copy of the gocryptfs.conf file plus the password entered above.
mkdir encrypted_data
gocryptfs -reverse -deterministic-names original_data encrypted_data
    -> Enter the same password as above.
mkdir recovered_encrypted_data
cp -rp encrypted_data/. recovered_encrypted_data/.
cp original_data/.gocryptfs.reverse.conf original_data_-_DOT.gocryptfs.reverse.conf
mkdir recovered_decrypted_data
gocryptfs -config original_data_-_DOT.gocryptfs.reverse.conf -deterministic-names -nosyslog recovered_encrypted_data recovered_decrypted_data
    -> Enter the same password used above
cat recovered_decrypted_data/\=\=\=Short_name/\=\=\=Short_name
    Mary Had A Little Lamb
    -> The expected result, instead of an error.
```

So right there, that's the workaround for my use case: just stash the complete config file plus its password somewhere safe, instead of just the masterkey so the former can be used in the recovery instead of the latter. Thank you for that. 

OTOH it's much less convenient to safely save the config file as it's a couple of hundred bytes long... eg in a password vault app or similar. So,  if/when you can fix this and get `-masterkey` working, it would be much appreciated.

**Comment by rfjakob** [comment]
Ah, now I see what's going on: you need to pass -aessiv when you mount with
-masterkey.

**Comment by DurvalMenezes** [comment]
> Sorry for the false alarm, and thanks for the clarification. Closing this issue now.

Reopening this issue for just one more observation/suggestion: 

I just noticed that I was technically in accordance with the documentation: for the mount command, along with `masterkey` I did specify every non-standard option I used during `-init`, which in my case was only `-deterministic-names`. 

In other words, I did **not** specify `-aessiv` on the `gocryptfs -init` command; what I *did* specify was `-deterministic-names` which, on `gocryptfs -init`*implies* `-aessiv`, but apparently  does *not* imply it during  the mount command (where I *also* specified it). 

So, I gotta ask: is there any specific reason for `-deterministic-names` *not* implying `-aessiv` during mount? 

If not, may I humbly suggest that you you make it so? Will probably save some other unfortunate person a few hours and some pulled hair... 

TIA!

**Comment by rfjakob** [comment]
-reverse implies -aessiv, https://github.com/rfjakob/gocryptfs/blob/master/Documentation/MANPAGE.md#-reverse

**Comment by rfjakob** [comment]
Emphasized that in https://github.com/rfjakob/gocryptfs/commit/7883d383d842707994b664f4d56ffbe833d3dc52

**Comment by rfjakob** [comment]
BTW this dance

    cp original_data/.gocryptfs.reverse.conf original_data_-_DOT.gocryptfs.reverse.conf

should be unneccessary as `.gocryptfs.reverse.conf` is shown as `gocryptfs.conf` in the encrypted view.
