### ISSUE TITLE
Logger keeps from umounting: target is busy.

### ISSUE THREAD

**Issue by ManuLinares** [rfjakob/gocryptfs#846]
Can't umount because it says target is busy.
Cheked via `ls -l /proc/*/fd` and see that the pidof "logger" is keeping it.

```
 ps axun| grep logg
    1000   29522  0.0  0.0  12260  4900 ?        S    17:02   0:00 logger -t gocryptfs-29507-logger
```

I see this in gocryptfs: https://github.com/rfjakob/gocryptfs/blob/master/daemonize.go#L75

Using log/syslog is standard: https://pkg.go.dev/log/syslog
Handling panics with recover(): https://go.dev/ref/spec#Handling_panics

---

System Archlinux:
go 2:1.22.3-1
gocryptfs 2.4.0-1
linux 6.8.9.arch1-2

**Comment by rfjakob** [comment]
Hi, what does `lsof -p 29522` say?

Gocryptfs uses logger because in-process logging is fundamentally flawed,
but that's a different discussion.

**Comment by ManuLinares** [comment]
Great, than you!
