### ISSUE TITLE
Empty stdin in mkinitcpio hook

### ISSUE THREAD

**Issue by Anuskuss** [rfjakob/gocryptfs#852]
I run `gocryptfs` inside of a `mkinitcpio` hook but it doesn't ask me for the password it just says:
```
Reading Password from stdin
Got empty Password from stdin
```

Using `-extpass` with e.g. `zenity --password` isn't a complete solution because that doesn't work in a terminal (e.g. SSH). It used to work in `encfs` btw.

**Comment by rfjakob** [comment]
This

    Reading Password from stdin

means that gocryptfs is not connected to a terminal. Does not matter too much here, it will just not print the `Password: ` prompt.



The message

    Got empty Password from stdin

and looking at the [code](https://github.com/rfjakob/gocryptfs/blob/f06f27e7bc098e334024c365004f9303e79997d9/internal/readpassword/read.go#L139) means that stdin is connected to /dev/null or it received a single newline.


It works with EncFS you say? Do you have a reproducer?

**Comment by Anuskuss** [comment]
I'm sure it's not related to `mkinitcpio` specifically but I don't know any other case where this happens. The only thing remotely close is runing
```
(gocryptfs /from /to &)
```
which gives you `Got empty Password from stdin`.

**Comment by rfjakob** [comment]
`Got empty Password from stdin` is correct in this case. Check this out, stdin is connected to /dev/null:

```
$ (sleep 1000 &)

$ pgrep sleep
47248

$  ls -l /proc/47248/fd/0
lr-x------. 1 jakob jakob 64 23. Jun 21:00 /proc/47248/fd/0 -> /dev/null
```

**Comment by Anuskuss** [comment]
I've been running `gocryptfs` in a loop because sometimes I mistype the password and I want the command to succeed eventually (basically I replaced `encfs` with `gocryptfs` but maybe I should open a feature request for a `-retry` flag which asks forever) which looks like this:
```bash
while true; do gocryptfs /from /to && break; done
```
which results in the log spam with the two lines above. However just running the command without being in a loop outputs:
```
Reading Password from stdin
Decrypting master key
failed to unlock master key: cipher: message authentication failed
Password incorrect.
```

I've tried to catch it in a another shell by running
```shell
while true; do readlink /proc/$(pidof -s gocryptfs)/fd/0; done
```
but that doesn't do anything.

**Comment by Anuskuss** [comment]
Well I guess this works:
```bash
gocryptfs /from /to </dev/pts/0 >&0 2>/dev/null
```
But it sucks.

**Comment by rfjakob** [comment]
And this "while true" loop runs inside the mkinitcpio hook for the problem
to appear?

**Comment by Anuskuss** [comment]
It doesn't work either way it just results in a slightly different error.

**Comment by rfjakob** [comment]
$ I cannot repro this. I intentionally entered an incorrect password a few times, then this correct one. What shell do you use?

```
while true ; do gocryptfs a b && break ; done

Password: 
Decrypting master key
failed to unlock master key: cipher: message authentication failed
Password incorrect.

Password: 
Decrypting master key
failed to unlock master key: cipher: message authentication failed
Password incorrect.

Password: 
Decrypting master key
failed to unlock master key: cipher: message authentication failed
Password incorrect.

Password: 
Decrypting master key
DetectQuirks: tmpfs detected, no extended attributes except acls will work.
Filesystem mounted and ready.
```

**Comment by rfjakob** [comment]
I can get the log spam you describe by piping garbage (`yes`) to gocryptfs:

```
$ while true ; do yes | gocryptfs a b && break ; done
Reading Password from stdin
Decrypting master key
failed to unlock master key: cipher: message authentication failed
Password incorrect.
Reading Password from stdin
Decrypting master key
failed to unlock master key: cipher: message authentication failed
Password incorrect.
Reading Password from stdin
Decrypting master key
failed to unlock master key: cipher: message authentication failed
Password incorrect.
[...]
```

**Comment by Anuskuss** [comment]
> I cannot repro this.

Running it in a shell is not enough; it has to be inside of a pacman hook (or similar).

I think the "simplest" way to test this would be:
1. Get an [Arch ISO](https://archlinux.org/download) and put it on a flash drive
2. Create a hook in `/etc/pacman.d/hooks/test.hook`
```ini
[Trigger]
Operation=Upgrade
Type=Package
Target=glibc

[Action]
When=PostTransaction
Exec=/usr/bin/bash -c 'while true; do gocryptfs /from /to && break; done'
```
3. `pacman -S glibc`

**Comment by rfjakob** [comment]
I added code that shows where stdin is connected ( https://github.com/rfjakob/gocryptfs/commit/b78e6a1c4cc0d1bbd3581d561773db85ee2e75b7 ). Can you try again and see if it shows something helpful?

But looking at this I think you cannot prompt for input inside hooks: https://bbs.archlinux.org/viewtopic.php?pid=1906273#p1906273

**Comment by Anuskuss** [comment]
```
Choose a password for protecting your files.
Reading Password from stdin (connected to "socket:[56196]")
Got empty Password from stdin
```

> But looking at this I think you cannot prompt for input inside hooks:

There seems to be some truth to that because something like `read r; echo $r` does not work indeed. But how the f does `encfs` get around that then?

**Comment by jficz** [comment]
have you tried leveraging https://www.man7.org/linux/man-pages/man1/systemd-ask-password.1.html ?

**Comment by Anuskuss** [comment]
> have you tried leveraging https://www.man7.org/linux/man-pages/man1/systemd-ask-password.1.html ?

If I do it in the terminal:

```
$ gocryptfs -extpass="systemd-ask-password" /enc /dec
Reading password from extpass program "systemd-ask-password", arguments: []
Failed to query password: Permission denied
extpass program returned an error: exit status 1
```

And if I do it in the hook (it gets stuck):

```
$ sudo sbupdate                                                                

Broadcast message from root@hostname (Fri 2025-01-17 19:27:12 CET):

Password entry required for 'n/a' (PID 12499).
Please enter password with the systemd-tty-ask-password-agent tool.

123456

^C
```
