### ISSUE TITLE
passing options to FUSE

### ISSUE THREAD

**Issue by celesteking** [rfjakob/gocryptfs#861]
Doc says I should use `-ko`, but it doesn't work:

```
$ gocryptfs x y -ko entry_timeout=1800,negative_timeout=300,attr_timeout=300
.....
/usr/bin/fusermount3: unknown option 'entry_timeout=1800'
fs.Mount failed: fusermount exited with code 256

$ man mount.fuse |grep attr_time
       attr_timeout=T
       ac_attr_timeout=T

$ gocryptfs -version
gocryptfs v2.4.0; go-fuse [vendored]; 2024-08-10 go1.22.4 linux/amd64
```

**Comment by celesteking** [comment]
Maybe this issue should be converted to a discussion?

**Comment by rfjakob** [comment]
-ko is for kernel flags as listed in
https://man7.org/linux/man-pages/man8/mount.8.html#FILESYSTEM-INDEPENDENT_MOUNT_OPTIONS

The flags you try to use are foe libfuse and don't work with go-fuse based
filesystems.

Unfortunately, there is no way to change the timeouts from the command line.
