### ISSUE TITLE
Preserve birth date

### ISSUE THREAD

**Issue by Anuskuss** [rfjakob/gocryptfs#865]
I don't know why nobody in Linux land cares about the `btime` but I do. When you move a file to your decrypted directory it loses it's `btime` (Feature Request 1) and it's counterpart in the encrypted directory gets a new one. Wouldn't it be possible to move the file into the encrypted directory and encrypt it in place (Feature Request 2)?

**Comment by rfjakob** [comment]
Looks like even `cp -a` does not preserve btime. Do you know an utility that does?

Unfortunately, "moving" a file between different filesystems is not really a thing. It's copying, then deleting the original.

```
0 jakob@brikett:~/tmp$ touch foo

0 jakob@brikett:~/tmp$ stat foo 
  File: foo
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: 253,1	Inode: 4625804     Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1026/   jakob)   Gid: ( 1026/   jakob)
Context: unconfined_u:object_r:user_tmp_t:s0
Access: 2024-09-08 19:24:50.037500962 +0200
Modify: 2024-09-08 19:24:50.037500962 +0200
Change: 2024-09-08 19:24:50.037500962 +0200
 Birth: 2024-09-08 19:24:50.037500962 +0200

0 jakob@brikett:~/tmp$ cp -a foo foo2

0 jakob@brikett:~/tmp$ stat foo2
  File: foo2
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: 253,1	Inode: 4625805     Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1026/   jakob)   Gid: ( 1026/   jakob)
Context: unconfined_u:object_r:user_tmp_t:s0
Access: 2024-09-08 19:24:50.037500962 +0200
Modify: 2024-09-08 19:24:50.037500962 +0200
Change: 2024-09-08 19:24:56.867527942 +0200
 Birth: 2024-09-08 19:24:56.867527942 +0200
```

**Comment by rfjakob** [comment]
Looks like it is impossible to change `btime`  ( https://unix.stackexchange.com/a/755618 ), sorry.

**Comment by Anuskuss** [comment]
> Unfortunately, "moving" a file between different filesystems is not really a thing.

It's on the same filesystem. `/enc` is my encrpyted directory which is mounted at `/dec` and `/dir` is just a regular directory. Moving the file `/dir/file` into `/dec` will lose the `btime` (that was the first part of my feature request: having the ability to list `btime` which is [supported in FUSE](https://www.phoronix.com/news/Linux-6.6-FUSE)) and has a completely new `btime` when read from `/enc`. This happens because the file lands in `/dec` and gets encrpyted and stored in `/enc/file-enc-name`.
My solution to this is moving `/dir/file` to `/enc/file` (since it's the same filesystem), encrypting and then renaming to `/enc/file-enc-name` (in-place).
