### ISSUE TITLE
-fido2-assert-option flag mentioned in Doc does not exist - Unknown flag output

### ISSUE THREAD

**Issue by vash83a** [rfjakob/gocryptfs#866]
Hello

gocryptfs 2.4.0 linux_static, FIDO 2 Yubikey, Fedora 40

As mentioned in [doc here](https://github.com/rfjakob/gocryptfs/blob/master/Documentation/MANPAGE.md#-fido2-assert-option-option), I tried to init a new vault using this command

`gocryptfs --init --fido2 /dev/device_name --fido2-assert-option uv=true --fido2-assert-option pin=true /home/user/Encrypted\ Folders/fido2test-crypt/`

but it fails giving me this output

`Invalid command line: "gocryptfs" "--init" "--fido2" "/dev/device_name" "--fido2-assert-option" "uv=true" "--fido2-assert-option" "pin=true" "/home/user/Encrypted Folders/fido2test-crypt/": unknown flag: --fido2-assert-option. Try 'gocryptfs -help'.`

Then, I tried to check all available flags typing the following:

`gocryptfs --hh`

actually the output shows no `--fido2-assert-option` flag as follows:

```
[SNIP]
      --f                                                                                                                                                                                         
      --fg                             Stay in the foreground                                                                                                                                     
      --fido2 string                   Protect the masterkey using a FIDO2 token instead of a password                                                                                            
      --force_owner string             uid:gid pair to coerce ownership                                                                                                                           
      --forcedecode                    Obsolete, ignored for compatibility 
[SNIP]
```

I don't understand where the problem is. Has the static binary been compiled without that flag? Is reported string in the [DOC](https://github.com/rfjakob/gocryptfs/blob/master/Documentation/MANPAGE.md#-fido2-assert-option-option) wrong? 
Thank you

**Comment by rfjakob** [comment]
Hi, you need to look at the v2.4.0 version docs:
https://github.com/rfjakob/gocryptfs/blob/v2.4.0/Documentation/MANPAGE.md#-fido2-device_path

**Comment by rfjakob** [comment]
And here's the binary for [latest master](https://github.com/rfjakob/gocryptfs/actions/runs/10684498052), which does include the `-fido2-assert-option` flag: https://github.com/rfjakob/gocryptfs/actions/runs/10684498052
