### ISSUE TITLE
Help on forget password and master key

### ISSUE THREAD

**Issue by galaxy001** [rfjakob/gocryptfs#867]
I can remember the password is not specific designed, should be a few letters and few numbers.

Can I use tools like John the Ripper to try those combinations ?
How to get the hash from `EncryptedKey` and `ScryptObject.Salt` ?

**Comment by rfjakob** [comment]
You can use this:

```
#!/bin/bash

john --incremental --stdout |  while read pass ; do
echo $pass
echo $pass | gocryptfs --quiet myfiles.cipher myfiles.mnt && break
done
```
