### ISSUE TITLE
Building against wolfSSL

### ISSUE THREAD

**Issue by lechner** [rfjakob/gocryptfs#89]
Hi, I ran some tests with wolfSSL crypto. (Performance is similar.) Would you consider a pull request to provide it as an alternative? Thank you!

**Comment by rfjakob** [comment]
Hmm, no, rather not I think.

gocryptfs **optionally** uses OpenSSL for speed. This is because OpenSSL has hand-optimized AES-GCM assembly code for platforms where Go does not have it built-in.

**Comment by rfjakob** [comment]
BTW to see where this comes into play you need a CPU that does *not* have AES instructions.

This is on my box (Pentium G630):
```
$ gocryptfs -speed
AES-GCM-256-OpenSSL 	 176.43 MB/s	(selected in auto mode)
AES-GCM-256-Go      	  46.24 MB/s	
AES-SIV-512-Go      	  34.53 MB/s
```

**Comment by lechner** [comment]
Thank you for your explanation. My patch never ran. :) It's not worth changing unless the AES instructions are missing more often on embedded systems, for which wolfSSL's smaller footprint may be preferred.
