### ISSUE TITLE
Confusing file owner for longname files in reverse mode

### ISSUE THREAD

**Issue by danim7** [rfjakob/gocryptfs#95]
Not sure if this shall be called a bug, or it is just an obscure use-case, but it is somewhat confusing:

1. I have two folders (note that they are owned by root and have 0777 permissions):
```
yo@wtf3-virtual:/media/gocryptfs$ ls -l
total 8
drwxrwxrwx 2 root root 4096 mars  25 18:38 ciphertext
drwxrwxrwx 2 root root 4096 mars  25 18:38 plaintext
```
2. Mount it in reverse mode:
`gocryptfs -reverse  plaintext/ ciphertext/`

3. In the plaintext folder, we have files with short and long filenames
```
yo@wtf3-virtual:/media/gocryptfs$ ls -l plaintext/
total 8
-rw-rw-r-- 1 yo yo 3 mars  25 18:38 12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
-rw-rw-r-- 1 yo yo 3 mars  25 18:37 aa
```

4. In the ciphertext folder, we have the expected files...however, the file owner is a bit confusing, because for the *.name and the gocryptfs.diriv files it doesn't match the owner in the plaintext folder:
```
yo@wtf3-virtual:/media/gocryptfs$ ls -l ciphertext/
total 20
-r-------- 1 yo   yo   413 mars  25 18:36 gocryptfs.conf
-r-------- 1 root root  16 mars  25 18:38 gocryptfs.diriv
-rw-rw-r-- 1 yo   yo    53 mars  25 18:38 gocryptfs.longname.1HKAT_9tvS0womyymfnI-nynl5tJU8YBdk3Q3kPX0IU
-r-------- 1 root root 278 mars  25 18:38 gocryptfs.longname.1HKAT_9tvS0womyymfnI-nynl5tJU8YBdk3Q3kPX0IU.name
-rw-rw-r-- 1 yo   yo    53 mars  25 18:37 nhcZwS0V6sK6--GztikDYQ
```
5. However, even if with the "yo" user it shouldn't be possible, I can successfully read the files owned by root:
```
yo@wtf3-virtual:/media/gocryptfs$ md5sum ciphertext/*
38077a320b8c776d9ebb889049aec647  ciphertext/gocryptfs.conf
c61bd575cfbb88f33838ab94299f828e  ciphertext/gocryptfs.diriv
51ffda0f385b059589c8bfa2a91b8fdb  ciphertext/gocryptfs.longname.1HKAT_9tvS0womyymfnI-nynl5tJU8YBdk3Q3kPX0IU
9fe6790968e4868a3a0facaff3cb591d  ciphertext/gocryptfs.longname.1HKAT_9tvS0womyymfnI-nynl5tJU8YBdk3Q3kPX0IU.name
def3ccf66d1e5ba602e26d0050b5d982  ciphertext/nhcZwS0V6sK6--GztikDYQ
```

After further testing, I figured out that the *.name and gocryptfs.diriv are being assigned the owner of the plaintext folder.

I think it is a bit confusing because:
a) At least for the longname files, I will expect its owner to be the same as the underlying plaintext file.
b) For the gocryptfs.diriv, I think it would be more logical it those files were owned by the same user that launched the gocryptfs process. They are technical files that don't exist in the underlying plaintext folder, and the user interested in reading them is the one who mounted the gocryptfs folder
c) Even if I didn't have the right permissions to read the root files, I could do it. It makes me think there may be a missing check on file permissions somewhere in the code...

The key step to reproduce it is the number 1: to use a plaintext folder owned by a different user than the final user... that could be a rather obscure use-case...

Best regards!

**Comment by rfjakob** [comment]
Merged as https://github.com/rfjakob/gocryptfs/commit/fb1b8ced3843a449f2a85d4ee0a9d426192d82fa , thanks!
