### ISSUE TITLE
Please mention dependancy on  libssl-dev

### ISSUE THREAD

**Issue by nnvn** [rfjakob/gocryptfs#98]
Please mention that you need to do `sudo apt-get install libssl-dev` to do `go get`. Without it, I was getting 
```
# pkg-config --cflags libcrypto
Package libcrypto was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcrypto.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcrypto' found
pkg-config: exit status 1
```

**Comment by rfjakob** [comment]
Ok like this? https://github.com/rfjakob/gocryptfs#compile

**Comment by nnvn** [comment]
Not exactly.

Step 1: apt install libssl-dev
Step 2: go get github.com/rfjakob/gocryptfs

No need to run build.bash

**Comment by rfjakob** [comment]
Yes, it is. Run gocryptfs -version to see why

**Comment by nnvn** [comment]
oh. I see.
